changelog/bug-1608185.md, go.mod, go.sum, workers/generic-worker/main.go, workers/generic-worker/main_test.go, workers/generic-worker/usage.go
Bugzilla Bug: [1608185](https://bugzilla.mozilla.org/show_bug.cgi?id=1608185)
=> Bug 1608185 - wait for protocol initialization

.github/CODEOWNERS, changelog/agNoKBycQ7GTMY2jTrZkMw.md
=> Do not notify service reviewers for go mod changes

changelog/issue-2312.md, ui/src/views/Documentation/index.jsx
=> [docs] Fix docs title formatting

changelog/bug-1588099.md, infrastructure/tooling/src/smoketest/index.js
Bugzilla Bug: [1588099](https://bugzilla.mozilla.org/show_bug.cgi?id=1588099)
Fixes #2318.
=> Bug 1588099 - simplify scope expressions (reland)

.taskcluster.yml, changelog/Y5aYQK5bR7KbF7lVPftbxQ.md, clients/client-go/codegenerator/model/model.go, clients/client-go/http_test.go, clients/client-go/integrationtest/integration_test.go, go.mod, go.sum, internal/jsontest/jsontest.go, internal/scopes/portedtests_test.go, internal/scopes/scopes.go, internal/scopes/scopes_descriptions_test.go, internal/scopes/scopes_test.go, workers/generic-worker/chain_of_trust.go, workers/generic-worker/feature.go, workers/generic-worker/gw-codegen/main.go, workers/generic-worker/livelog.go, workers/generic-worker/main.go, workers/generic-worker/mounts.go, workers/generic-worker/os_groups.go, workers/generic-worker/rdp_windows.go, workers/generic-worker/runasadministrator_windows.go, workers/generic-worker/supersede.go, workers/generic-worker/taskcluster_proxy.go
This fixes some issues that came up in the v25.0.0 release.  See the commit comments for details.
=> Golang release fixes

.taskcluster.yml, dev-docs/README.md, dev-docs/releasing.md, infrastructure/tooling/src/main.js, infrastructure/tooling/src/publish/index.js, infrastructure/tooling/src/publish/tasks.js
Bugzilla Bug: [1615742](https://bugzilla.mozilla.org/show_bug.cgi?id=1615742)
See https://community-tc.services.mozilla.com/tasks/W9Q_W65tTw6s4vjNtRTt5g/runs/0/logs/live/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FW9Q_W65tTw6s4vjNtRTt5g%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log for a successful staging run.
=> Bug 1615742 - support staging releases

changelog/bug-1615762.md, go.mod, go.sum
Bugzilla Bug: [1615762](https://bugzilla.mozilla.org/show_bug.cgi?id=1615762)
=> Bug 1615762 - Specify required version of github.com/tylerb/graceful

changelog/issue-2367.md, go.mod, go.sum
=> Fixed go.mod and go.sum

README.md, workers/README.md
Hotfix for broken `yarn generate` task.
=> Fix yarn generate

changelog/eBgvXvY2RAuQqk5ee6j7vg.md, infrastructure/tooling/src/backup/backup.js, libraries/pulse/src/consumer.js
=> Remove duplicate await

changelog/issue-2377.md, ui/src/utils/constants.js
..in a JSON value
Fixes #2377.
=> Only match dates for update that appear on their own

changelog/bug-1606874.md, services/github/src/handlers.js, services/github/test/handler_test.js, ui/docs/reference/integrations/github/taskcluster-yml-v1.mdx
Before this change, the collaborator check was performed on the owner of
the "head" repo.
Bugzilla Bug: [1606874](https://bugzilla.mozilla.org/show_bug.cgi?id=1606874)
=> Bug 1606874 - check that the person who filed a PR is a collaborator

README.md, workers/README.md, workers/generic-worker/worker_types/README.md
No bug - just deletes an unused directory.
=> No bug - delete unused directory

changelog/tc-github-dev-docs.md, dev-docs/development-process.md
If these docs were here before, I'd set up my app way faster. So adding them!
=> Add docs on how to set up a working github app for development

changelog/issue-2004.md, ui/src/components/TaskDetailsCard/index.jsx
Fixes https://github.com/taskcluster/taskcluster/issues/2004.
=> [UI] Wrap text in task view payload section

changelog/bug-1608185.md, tools/taskcluster-worker-runner/docs/deployment.md, tools/taskcluster-worker-runner/docs/windows-services.md, tools/taskcluster-worker-runner/worker/genericworker/runmethod.go
Bugzilla Bug: [1608185](https://bugzilla.mozilla.org/show_bug.cgi?id=1608185)
=> Bug 1608185 - include --with-worker-runner when running generic-worker

changelog/bug-1618066.md, services/worker-manager/src/provisioner.js, services/worker-manager/test/provisioner_test.js
Bugzilla Bug: [1618066](https://bugzilla.mozilla.org/show_bug.cgi?id=1618066)
=> bug 1618066: fix bug where workerInfo could have NaN values

changelog/TG0cJXDIQTChJ_GlP3a3Kg.md, ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx
This would allow users to go back after changing the index path.
=> [UI] Allow users to go back when changing the index path

changelog/issue-2386.md, ui/src/views/Clients/ViewClients/index.jsx, ui/src/views/Hooks/ListHooks/index.jsx, ui/src/views/Roles/ViewRoles/Roles.jsx
=> [UI] Refresh list after delete

changelog/WARVAcsKSnWHTeFJF18fwQ.md, services/worker-manager/src/api.js
..and sanity-check the 'expires' value returned by each provider.
=> Do not allow expired workers to register

changelog/issue-2441.md, ui/src/components/SchemaTable/index.jsx, ui/src/theme.js
Fixes https://github.com/taskcluster/taskcluster/issues/2441.
=> [UI] Schema viewer nits

changelog/AQveLrgqSHaxFBwtas66vg.md, services/web-server/src/loaders/artifacts.js, services/web-server/test/fixtures/artifact.graphql, services/web-server/test/fixtures/artifacts.graphql, services/web-server/test/fixtures/artifactsCreated.graphql, services/web-server/test/fixtures/latestArtifacts.graphql, services/web-server/test/graphql/artifacts_graphql_test.js, services/web-server/test/graphql/roles_test.js, services/web-server/test/graphql/tasks_graphql_test.js, services/web-server/test/helper.js
Github Bug/Issue: Fixes #???? 
Not sure what issue this should reference. This is just adding more graphql tests
=> Web server/artifacts graphql tests

changelog/Opj3CkB7TlypjZDLKBMXQw.md, infrastructure/tooling/src/generate/generators/go-mod-tidy.js
Since I keep making this mistake :)
=> run 'go mod tidy' in 'yarn generate'

changelog/XuVSu2KWTqakgJB7sSRUJw.md, generated/docs-search.json, generated/docs-table-of-contents.json, ui/docs/reference/workers/generic-worker/support-tiers.mdx, workers/generic-worker/build.sh
As discussed in the weekly meeting.
=> Add generic-worker support tiers to the documentation

infrastructure/tooling/src/meta/checks/node-pg.js, libraries/postgres/README.md
Github Bug/Issue: Fixes #2456
Did I miss any?  Are these too vague?
=> Document security invariants

.github/CODEOWNERS
https://github.com/taskcluster/taskcluster/pull/2469#issuecomment-596109494
=> Add @taskcluster/security-folks to db stuff (from development branch)

changelog/bug-1591476.md, clients/client-go/tcworkermanager/types.go, generated/references.json, services/worker-manager/schemas/v1/config-static.yml, services/worker-manager/schemas/v1/register-worker-response.yml, services/worker-manager/src/api.js, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure.js, services/worker-manager/src/providers/google.js, services/worker-manager/src/providers/static.js, services/worker-manager/src/providers/testing.js, services/worker-manager/test/api_test.js, services/worker-manager/test/provider_aws_test.js, services/worker-manager/test/provider_azure_test.js, services/worker-manager/test/provider_google_test.js, services/worker-manager/test/provider_static_test.js, tools/taskcluster-worker-runner/cfg/providerworkerconfig.go, tools/taskcluster-worker-runner/provider/aws/awsprovider.go, tools/taskcluster-worker-runner/provider/azure/azure.go, tools/taskcluster-worker-runner/provider/azure/azure_test.go, tools/taskcluster-worker-runner/provider/google/google.go, tools/taskcluster-worker-runner/provider/provider/common.go, tools/taskcluster-worker-runner/provider/static/static.go, tools/taskcluster-worker-runner/tc/fakeworkermanager.go
Bugzilla Bug: [1591476](https://bugzilla.mozilla.org/show_bug.cgi?id=1591476)
=> bug 1591476: registerWorker() returns workerConfig

changelog/bug-1618916.md, services/worker-manager/src/providers/azure.js, services/worker-manager/test/provider_azure_test.js, tools/taskcluster-worker-runner/provider/azure/azure.go, tools/taskcluster-worker-runner/provider/azure/azure_test.go, tools/taskcluster-worker-runner/provider/azure/metadata.go, tools/taskcluster-worker-runner/provider/azure/metadata_test.go, ui/docs/reference/core/worker-manager/azure.mdx
Bugzilla Bug: [1618916](https://bugzilla.mozilla.org/show_bug.cgi?id=1618916)
=> bug 1618916: azure w-r and w-m use tags instead of customData for worker information

changelog/bug-1547731.md, services/web-server/src/createContext.js, services/web-server/src/loaders/artifacts.js, services/web-server/src/loaders/auth.js, services/web-server/src/loaders/cachePurges.js, services/web-server/src/loaders/clients.js, services/web-server/src/loaders/github.js, services/web-server/src/loaders/hooks.js, services/web-server/src/loaders/index.js, services/web-server/src/loaders/namespaces.js, services/web-server/src/loaders/notify.js, services/web-server/src/loaders/provisioners.js, services/web-server/src/loaders/roles.js, services/web-server/src/loaders/scopes.js, services/web-server/src/loaders/secrets.js, services/web-server/src/loaders/taskStatuses.js, services/web-server/src/loaders/tasks.js, services/web-server/src/loaders/workerManager.js, services/web-server/src/loaders/workerTypes.js, services/web-server/src/loaders/workers.js, services/web-server/src/main.js, services/web-server/src/monitor.js
Bugzilla Bug: [1547731](https://bugzilla.mozilla.org/show_bug.cgi?id=1547731)
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1547731
=> Bug 1547731 - Add structured logging for web-server requests 

db/src/main.js, dev-docs/development-process.md, infrastructure/tooling/src/dev/index.js, infrastructure/tooling/src/dev/postgres.js, infrastructure/tooling/src/dev/util.js, infrastructure/tooling/src/main.js, package.json, ui/docs/manual/deploying/database.mdx
This has some refactoring of the `yarn dev` commands, too.
Github Bug/Issue: Fixes #2342
=> Support postgres in dev environments

changelog/bug-1621167.md, generated/references.json, libraries/monitor/README.md, services/github/src/api.js, services/github/src/github-auth.js, services/github/src/handlers.js, services/github/src/intree.js, services/github/src/monitor.js, services/github/test/webhook_test.js
Bugzilla Bug: [1621167](https://bugzilla.mozilla.org/show_bug.cgi?id=1621167)
=> Bug 1621167 - improve logging from tc-github

changelog/issue-2503.md, ui/docs/manual/deploying/schema.mdx, ui/docs/manual/design/apis/reference-format.mdx, ui/docs/manual/design/conventions/actions/spec.mdx, ui/docs/reference/core/worker-manager/aws.mdx, ui/docs/reference/core/worker-manager/azure.mdx, ui/docs/reference/core/worker-manager/google.mdx, ui/docs/reference/core/worker-manager/static.mdx, ui/docs/reference/platform/queue/task-schema.mdx, ui/docs/tutorial/monitor-task-status.mdx
=> use precise $id for all SchemaTable components

.taskcluster.yml, workers/generic-worker/gw-decision-task/main.go
I don't think this will work, but let's try it :)
=> add checks route to gw decision-task subtasks

changelog/issue-2498.md, libraries/postgres/src/Database.js, libraries/postgres/test/database_test.js, ui/docs/manual/deploying/database.mdx
Thanks to @edunham for recommending this!
Fixes #2498
=> Check DB user permissions more thoroughly

.github/CODEOWNERS
=> assign worker reviewers when go.mod/go.sum are modified

libraries/entities/src/index.js
Some services look at err.name, and some look at err.code, for the error
messages from Azure entities.  Let's support both.
This will need to be cherry-picked into master once #2515 lands.
=> Set err.name for tc-lib-entities errors.

changelog/b7uSHxw-SJuYmSrstZdD4A.md, dev-docs/best-practices/docs.md
@ajvb asked about names for the various people involved with Taskcluster, and while we have used these informally they were not written down anywhere.  Now they are.
=> document the various audiences for TC

changelog/dev-doc.doc, dev-docs/development-process.md
=> Add instructions on how to publish pulse messages

changelog/bug1621420.md, services/github/src/handlers.js, services/github/test/handler_test.js
Bugzilla Bug: [1621420](https://bugzilla.mozilla.org/show_bug.cgi?id=1621420)
=> Update octokit API call

changelog/issue-2555.md, db/README.md, db/fns.md, db/src/fakes/queue.js, db/test/fns/queue_test.js, db/versions/0006.yml, generated/db-schema.json, libraries/azqueue/test/count_messages_test.js
This accurately reproduces the behavior of the Azure API.
Github Bug/Issue: Fixes #2555
=> Do not count expired messages in queues

changelog/TGufA6yfQR-15deZfkAc9g.md, ui/package.json, ui/src/views/Documentation/Reference/Entry.jsx, ui/yarn.lock
also fixes https://github.com/taskcluster/taskcluster/issues/2442.
=> UI subtle changes (font size, spacing)

changelog/issue-1615.md, ui/package.json, ui/yarn.lock
Fixes https://github.com/taskcluster/taskcluster/issues/1615
=> [UI] CodeEditor placeholder text color

changelog/issue-2522.md, db/src/setup.js, db/test/helper.js, generated/references.json, libraries/entities/test/helper.js, libraries/postgres/src/Database.js, libraries/postgres/test/database_test.js, libraries/postgres/test/helper.js, libraries/testing/src/with-db.js
Cherry picked the first commit from https://github.com/taskcluster/taskcluster/pull/2571. This was already reviewed.
=> Log information about DB and connection pools

changelog/issue-1389.md, ui/src/views/Tasks/TaskIndex/IndexedTask/index.jsx, ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx
Fixes https://github.com/taskcluster/taskcluster/issues/1389.
=> [UI] Add breadcrumbs to index view

changelog/bug-1624602.md, tools/worker-runner/protocol/null.go, tools/worker-runner/protocol/protocol.go, tools/worker-runner/runner/run.go, tools/worker-runner/worker/genericworker/runmethod_windows.go
Bugzilla Bug: [1624602](https://bugzilla.mozilla.org/show_bug.cgi?id=1624602)
This process-management and io stuff is full of subtle bugs :(
=> Bug 1624602 - read all messages from protocol before calling cmd.Wait

ui/docs/manual/deploying/database.mdx
Bugzilla Bug: [1627806](https://bugzilla.mozilla.org/show_bug.cgi?id=1627806)
=> Bug 1627806 - more info on connection counts

changelog/issue-2615.md, ui/src/components/ClientForm/index.jsx, ui/src/components/RoleForm/index.jsx
Fixes https://github.com/taskcluster/taskcluster/issues/2615.
=> [UI] Fix Client/Role view error

changelog/eJGD__3PSYO2KQuRPK2Csg.md, ui/.mocharc.yml, ui/.neutrinorc.js, ui/test/fromNow_test.js, ui/test/isDateWithin_test.js, ui/test/parseTime_test.js, ui/test/slugid_test.js
We use TDD style for all other JS tests in the repo.
=> Switch UI tests to use TDD style

changelog/LXizJp4gSVecRcMuRwosxw.md, libraries/postgres/src/Database.js
Yikes, that was some kind of weird copy/paste error!
=> Roll back on error during db:upgrade/downgrade

changelog/issue-2637.md, dev-docs/development-process.md
=> Update development docs to recommend DB URL

changelog/cHQVmqXORy-4sqFbwREwYw.md, dev-docs/dev-config-example.yml, infrastructure/tooling/src/generate/generators/k8s.js
I messed this up earlier in the week and now it's in two releases :(
=> Don't include procs like write-docs and expire-sentry

dev-docs/best-practices/microservices.md, services/web-server/README.md
Not sure if this is the right place.
Resolves https://github.com/taskcluster/taskcluster/issues/2598.
=> [docs] Add GraphQL docs

infrastructure/tooling/src/importer/monitor.js, infrastructure/tooling/src/importer/operations.js, infrastructure/tooling/src/importer/util.js
* Chunk QueueTaskDependency
* chunk taskIds into 16 evenly-sized chunks
* update the output less often to reduce flickering
@helfi92 do you mind checking my math on the chunks?
=> Tweak importer performance

dev-docs/best-practices/testing.md, package.json, yarn.lock
=> Cleanup - remove azure-entities and azure-blob-storage

ui/package.json, ui/yarn.lock
Worth a try. Not sure if this will fix the cache issue.
=> [UI] Update webpack dependencies

changelog/bug-1548036.md, services/notify/config.yml, services/notify/src/irc.js, services/notify/src/templates/fullscreen/html.pug, services/notify/src/templates/fullscreen/text.pug, services/notify/src/templates/simple/html.pug, services/notify/src/templates/simple/text.pug, tools/jsonschema2go/README.md, ui/docs/reference/core/notify/usage.mdx
Bugzilla Bug: [1548036](https://bugzilla.mozilla.org/show_bug.cgi?id=1548036)
=> [Bug 1548036] Clean-up remaining references to irc.mozilla.org

changelog/bug-1630023.md, libraries/postgres/src/Schema.js, libraries/postgres/src/util.js, libraries/postgres/test/util_test.js
Bugzilla Bug: [1630023](https://bugzilla.mozilla.org/show_bug.cgi?id=1630023)
A few minor fixes I made while working on this bug, that can be merged sooner than the full patch will be ready..
=> Bug 1630023 - minor fixes

ui/src/views/Hooks/ListHooks/index.jsx
Remove unnecessary use of internal state in hooks view.
=> [UI] Hooks view deep search

changelog/HO-88KbETwexWaI0-y1MlA.md, clients/client-web/package.json, clients/client-web/yarn.lock
=> Actually commit versions of web-client deps

changelog/bug-1629168.md, tools/websocktunnel/wsproxy/stopper.go, tools/websocktunnel/wsproxy/wsproxy.go
Bugzilla Bug: [1629168](https://bugzilla.mozilla.org/show_bug.cgi?id=1629168)
=> Bug 1629168 - [websocktunnel] fix race condition in stopping copy ops

changelog/SM0KjiYRS4iY9YwVqCDqRA.md, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure.js, services/worker-manager/src/providers/google.js, ui/docs/reference/core/worker-manager/aws.mdx, ui/docs/reference/core/worker-manager/azure.mdx, ui/docs/reference/core/worker-manager/google.mdx
In #2680 @milescrabill asked me to document this and .. I documented something else.
=> Align docs and comments with reality about instance metadata

changelog/dHuQqCbCTRCb247E7NlM7A.md, libraries/monitor/README.md
=> Fix monitor readme docs

.taskcluster.yml, changelog/bug-1632325.md, infrastructure/tooling/src/build/index.js, infrastructure/tooling/src/build/monoimage.js, infrastructure/tooling/src/main.js, infrastructure/tooling/src/publish/index.js, infrastructure/tooling/src/publish/tasks.js
View results of this at https://community-tc.services.mozilla.com/tasks/AxK8lH_FSSu1kmre3_637g/runs/0#artifacts
Bugzilla Bug: [1632325](https://bugzilla.mozilla.org/show_bug.cgi?id=1632325)
=> [Bug 1632325] Save build/release logs as artifacts

changelog/bug-1627116-1.md, changelog/bug-1627116.md, services/worker-manager/src/providers/aws.js, ui/docs/reference/core/worker-manager/aws.mdx
Bugzilla Bug: [1627116](https://bugzilla.mozilla.org/show_bug.cgi?id=1627116)
=> Bug 1627116 - tag EC2 volumes created for aws-provider workers

ui/src/views/Roles/ViewRoles/index.jsx, ui/src/views/Scopes/ViewScope/index.jsx
* Fixes #2129 
* Use `history.location.search` to store data which we needed
=> [UI] Add deep links for roles and scope views

infrastructure/tooling/src/publish/tasks.js
=> Temporarily disable tc-proxy in release publish

changelog/bug-1629807.md, services/web-server/src/login/strategies/mozilla-auth0.js
This will need to best tested on an instance before merging.
=> Bug 1629807 - Add state token in login

changelog/bug-1633582.md, services/worker-manager/src/providers/google.js, ui/docs/reference/core/worker-manager/google.mdx
Bugzilla Bug: [1633582](https://bugzilla.mozilla.org/show_bug.cgi?id=1633582)
=> Bug 1633582 - Google provider labeling VM disks

infrastructure/tooling/src/publish/tasks.js
Bugzilla Bug: [1633622](https://bugzilla.mozilla.org/show_bug.cgi?id=1633622)
[Staging Release](https://community-tc.services.mozilla.com/tasks/cdzByZUXQEqA-SiVXQFKOw)
=> Bug 1633622 - 'yarn build' before 'npm publish' for tc-client-web

changelog/Ps2qrH6mTFinqSiVTqHdFw.md, libraries/app/src/index.js, package.json, yarn.lock
=> Remove morgan-debug support in lib-app

changelog/fmdVXR7DTiuQMZvHafbM3g.md, tools/jsonschema2go/README.md, tools/websocktunnel/README.md
Signed-off-by: vnzongzna <vnzongzna@gmail.com>
=> Updating godoc reference in jsonschema2go and websocktunnel

infrastructure/docker-images/build-browser-test.sh, infrastructure/docker-images/build-node-and-go.sh, infrastructure/docker-images/build-node-and-pg.sh, infrastructure/docker-images/build-rabbit-test.sh, infrastructure/docker-images/push-all.sh
=> Add a push-all script to push all CI docker images

changelog/bug-1633897.md, ui/src/App/index.jsx
Bugzilla Bug: [1633897](https://bugzilla.mozilla.org/show_bug.cgi?id=1633897)
=> Bug 1633897 - Always use same-origin

changelog/bug-1631829.md, services/worker-manager/src/providers/azure.js
Bugzilla Bug: [1631829](https://bugzilla.mozilla.org/show_bug.cgi?id=1631829)
=> Bug 1631829 - Fix tagging in Azure

workers/docker-worker/test/superseding_test.js
Fixes https://github.com/taskcluster/docker-worker/issues/558.
=> [docker-worker] Fix billingCycleUpdate undefined error

changelog/bug-1561668.md, infrastructure/tooling/src/utils/repo.js, package.json, services/hooks/src/listeners.js, services/web-server/src/PulseEngine/index.js, yarn.lock
Bugzilla Bug: [1561668](https://bugzilla.mozilla.org/show_bug.cgi?id=1561668)
=> Bug 1561668 - use p-synchronize to synchronize async functions

ui/src/views/Hooks/ListHooks/index.jsx
The last bits to resolve https://github.com/taskcluster/taskcluster/issues/2606.
=> [UI] Add empty state for tree view in hooks

changelog/bug-1636163.md, generated/docs-search.json, generated/docs-table-of-contents.json, ui/docs/reference/workers/docker-worker/README.mdx, ui/docs/reference/workers/docker-worker/caches.mdx, ui/docs/reference/workers/docker-worker/environment.mdx, ui/docs/reference/workers/docker-worker/features.mdx, ui/docs/reference/workers/docker-worker/payload.mdx, ui/docs/reference/workers/docker-worker/scopes.mdx
Bugzilla Bug: [1636163](https://bugzilla.mozilla.org/show_bug.cgi?id=1636163)
=> Bug 1636163: Show docker-worker docs on website

changelog/bug-1636165.md, changelog/issue-2788.md, generated/docs-table-of-contents.json, infrastructure/tooling/src/publish/tasks.js, tools/worker-runner/worker/dockerworker/dockerworker.go, tools/worker-runner/worker/dockerworker/dockerworker_test.go, ui/docs/reference/workers/worker-runner/linux-services.mdx, ui/docs/reference/workers/worker-runner/windows-services.mdx, ui/docs/reference/workers/worker-runner/workers.mdx, workers/docker-worker/docs/deployment.md, workers/docker-worker/release.sh, workers/docker-worker/src/bin/worker.js, workers/docker-worker/src/lib/task.js
Bugzilla Bug: [1636165](https://bugzilla.mozilla.org/show_bug.cgi?id=1636165)
(This is based on #2788; I can rebase once that lands)
=> Bug 1636165 - show docker-worker version

changelog/issue-2739.md, infrastructure/tooling/src/publish/tasks.js, tools/taskcluster-proxy/.gitignore, tools/taskcluster-proxy/main.go
=> Issue 2739 - re-enable shipping tc-proxy assets

Dockerfile, changelog/bug-1636189.md, infrastructure/tooling/src/build/monoimage.js, infrastructure/tooling/src/publish/tasks.js, infrastructure/tooling/src/utils/dockerflow.js, infrastructure/tooling/src/utils/index.js, tools/websocktunnel/wsproxy/proxy.go, tools/websocktunnel/wsproxy/proxy_test.go
Bugzilla Bug: [1636189](https://bugzilla.mozilla.org/show_bug.cgi?id=1636189)
In the process, I fixed #2781!
=> Bug 1636189 - Docker-Flow stuff for websocktunnel

changelog/bug-1633582.md, services/worker-manager/src/providers/google.js
Bugzilla Bug: [1633582](https://bugzilla.mozilla.org/show_bug.cgi?id=1633582)
=> bug 1633582 - fix google provider disk tagging

services/worker-manager/src/providers/google.js
Bugzilla Bug: [1633582](https://bugzilla.mozilla.org/show_bug.cgi?id=1633582)
=> bug 1633582 - another fix to google provider disks

README.md, changelog/HKjpNI1AQaSeXayUYHS5Gw.md
=> Remove a no-longer-true line from readme

package.json, yarn.lock
This gets us fixes for
* https://github.com/djmitche/console-taskgraph/issues/15
* https://github.com/djmitche/console-taskgraph/issues/11
=> Upgrade console-taskgraph

changelog/bug-1637982.md, services/queue/src/api.js, services/queue/test/resolvetask_test.js
Bugzilla Bug: [1637982](https://bugzilla.mozilla.org/show_bug.cgi?id=1637982)
This bug has existed since the queue was written!
=> Bug 1637982 - disallow attempts to complete non-running runs

changelog/W6SJ1i9qR6GBU2r-Kqtb0w.md, infrastructure/docker-images/build-node-and-go.sh, tools/jsonschema2go/jsonschema.go, tools/websocktunnel/wsproxy/proxy.go, workers/generic-worker/model.go, workers/generic-worker/occ-workers/main.go
Signed-off-by: vnzongzna <vnzongzna@gmail.com>
=> Fixing all golangci-lint error before update

changelog/issue-1061.md, clients/client-shell/cmds/from-now/from_now.go, clients/client-shell/cmds/root/command.go, clients/client-shell/cmds/root/log.go, clients/client-shell/cmds/signin/signin.go, clients/client-shell/cmds/slugid/slugid.go, clients/client-shell/cmds/task/actors.go, clients/client-shell/cmds/task/fetchers.go, clients/client-shell/cmds/task/task.go, clients/client-shell/cmds/task/utils.go, clients/client-shell/cmds/version/version.go, clients/client-shell/cmds/version/version_test.go
=> adding logger in [client-shell]

changelog/deL4nxnRQY2RM6o3js8wmg.md, services/hooks/src/listeners.js
Bugzilla Bug: [1554201](https://bugzilla.mozilla.org/show_bug.cgi?id=1554201)
This error was fairly easy to reproduce in development, and fairly clear how to handle it.  The switch to debug logging is just following on to a similar change we made in tc-github recently, and might be useful someday :)
=> Bug 1554201 - handle 403 as well as 404 when binding a queue

changelog/issue-2822.md, workers/docker-worker/Vagrantfile
This got Vagrant working for me.
Github Bug/Issue: Fixes #2822
=> Use a libvirt box instead of Virtualbox

changelog/JvB0M6vIQZSGEuSImYTFvQ.md, workers/generic-worker/build.sh
=> Gw build sh log typo

changelog/bug-1639913.md, generated/references.json, services/worker-manager/docs/providers.md, services/worker-manager/src/api.js, services/worker-manager/src/monitor.js, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure.js, services/worker-manager/src/providers/google.js, services/worker-manager/src/providers/provider.js, services/worker-manager/src/providers/static.js
Bugzilla Bug: [1639913](https://bugzilla.mozilla.org/show_bug.cgi?id=1639913)
This is substantially in hopes of figuring out why Windows instances in Azure are getting killed right after startup, but hopefully will provide useful debugging output in the future as well.
=> Bug 1639913 - add logging for providers

changelog/AU7WL2bhSDuSSIRK9gHf-A.md, workers/generic-worker/usage.go, workers/generic-worker/usage_multiuser.go, workers/generic-worker/usage_posix.go, workers/generic-worker/usage_windows.go
Just a generic-worker usage docs fix up.
=> Minor changes to generic-worker usage docs

changelog/KCsPcxKORfymN2HgRlbtwQ.md, workers/docker-worker/src/lib/devices/device_manager.js, workers/docker-worker/src/lib/gc.js, workers/docker-worker/src/lib/runtime.js, workers/docker-worker/src/lib/task.js, workers/docker-worker/src/lib/task_listener.js, workers/docker-worker/src/lib/volume_cache.js, workers/docker-worker/test/integration/file_artifact_test.js
This is to avoid seeing errors of the form `n is not iterable`.
=> [docker-worker] Default to empty object

changelog/dpmqh4-nR3aEb97kZ_7qbg.md, services/worker-manager/src/providers/azure.js
=> Pass monitor to handleOperation

changelog/issue-2912.md, services/web-server/src/graphql/Tasks.graphql, services/web-server/src/loaders/tasks.js, services/web-server/src/resolvers/Tasks.js
First piece of work for https://github.com/taskcluster/taskcluster/issues/2910.
The next piece is to add the UI bits.
=> Add endpoint for listDependentTasks to web-server

changelog/issue-2952.md, services/worker-manager/src/providers/testing.js
=> Fix missed worker-pool entities usage in tests

changelog/bug-1640267.md, workers/docker-worker/test/integration/container_volume_caching_test.js
Bugzilla Bug: [1640267](https://bugzilla.mozilla.org/show_bug.cgi?id=1640267)
=> Bug 1640267 - skip intermittent test 'purge cache during run task'

changelog/issue-2925.md, clients/client-go/tcworkermanager/types.go, generated/references.json, services/worker-manager/schemas/v1/worker-full.yml
=> Include worker state 'stopped' in the worker schema

changelog/issue-2951.md, workers/docker-worker/test/integration/file_artifact_test.js
=> #2951 - skip intermittent test 'file_artifact_test.js'

changelog/issue-2969.md, workers/docker-worker/src/lib/task_listener.js
=> docker-worker: only become idle when claimTasks returns nothing

changelog/bug-1631824.md, generated/references.json, services/worker-manager/schemas/v1/config-azure.yml, services/worker-manager/src/providers/azure.js, services/worker-manager/test/fakes/azure.js, services/worker-manager/test/fakes/schemas/azure-vm.yml, services/worker-manager/test/provider_azure_test.js
Bugzilla Bug: [1631824](https://bugzilla.mozilla.org/show_bug.cgi?id=1631824)
=> bug 1631824 - fix azure-provider to track and delete all of a VM's disks

changelog/b1NVLlk6TuWUU9MOHEmT2w.md, dev-docs/postgres-phase-2-guidelines.md
=> Add dev docs about optimistic concurrency control

changelog/CKF_ES7mRZ2iUtZ9XZ9Yhg.md, workers/generic-worker/aws.go, workers/generic-worker/graceful/graceful.go, workers/generic-worker/graceful/graceful_test.go, workers/generic-worker/main.go, workers/generic-worker/workerrunner.go
This adds support for responding to the `graceful-termination` protocol
message.
=> Bug 1607605 - Support graceful termination in generic-worker

changelog/cNdlqN_xSmKNkMYokAoNwQ.md, workers/docker-worker/src/lib/features/artifacts.js
Report the error message when uploadArtifact fails to better debug failing cases.
=> Include error message when uploadArtifact fails

changelog/issue-3021.md, db/README.md, dev-docs/development-process.md, libraries/postgres/README.md
=> centralize docs for running postgres for testing

changelog/bug-1637302.md, workers/docker-worker/src/lib/features/artifacts.js, workers/docker-worker/src/lib/features/bulk_log.js, workers/docker-worker/src/lib/features/chain_of_trust.js, workers/docker-worker/src/lib/features/docker_save.js, workers/docker-worker/src/lib/task.js, workers/docker-worker/src/lib/upload_to_s3.js, workers/docker-worker/test/integration/file_artifact_test.js, workers/docker-worker/test/upload_to_s3_test.js
Bugzilla Bug: [1637302](https://bugzilla.mozilla.org/show_bug.cgi?id=1637302)
=> Bug 1637302: Compress artifact uploads

changelog/issue-2962.md, db/src/setup.js, generated/docs-search.json, infrastructure/tooling/src/dev/postgres.js, libraries/postgres/README.md, libraries/postgres/src/Database.js, libraries/postgres/src/Keyring.js, libraries/postgres/test/database_test.js, libraries/postgres/test/keyring_test.js, ui/docs/manual/deploying/database.mdx
I believe this is ready to be used! Please put some thought into cases that I haven't covered in tests. I tried to be thorough but have probably missed something.
Github Bug/Issue: Fixes #2962
=> [Issue 2962] Add encryption/decryption to db columns

changelog/issue-3013.md, generated/docs-search.json, services/github/src/constants.js, services/github/src/handlers.js, services/github/test/handler_test.js, ui/docs/reference/integrations/github/checks.mdx
=> For #3013 - Support GitHub annotations

changelog/bug-1638921.md, infrastructure/k8s/templates/taskcluster-auth-cron-purgeExpiredClients.yaml, infrastructure/k8s/templates/taskcluster-github-cron-sync.yaml, infrastructure/k8s/templates/taskcluster-hooks-cron-expires.yaml, infrastructure/k8s/templates/taskcluster-index-cron-expire.yaml, infrastructure/k8s/templates/taskcluster-purge-cache-cron-expireCachePurges.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireArtifacts.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireQueueMessages.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTask.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskDependency.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskGroupMembers.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskGroupSizes.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskGroups.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskRequirement.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireWorkerInfo.yaml, infrastructure/k8s/templates/taskcluster-secrets-cron-expire.yaml, infrastructure/k8s/templates/taskcluster-web-server-cron-cleanup-expire-access-tokens.yaml, infrastructure/k8s/templates/taskcluster-web-server-cron-cleanup-expire-auth-codes.yaml, infrastructure/k8s/templates/taskcluster-web-server-cron-scanner.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-cron-expire-errors.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-cron-expire-worker-pools.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-cron-expire-workers.yaml, infrastructure/tooling/templates/k8s/cron.yaml
Bugzilla Bug: [1638921](https://bugzilla.mozilla.org/show_bug.cgi?id=1638921)
=> Bug 1638921 - ensure crontasks do not run concurrently

changelog/issue-2882.md, services/web-server/src/graphql/WorkerManager.graphql, services/web-server/test/fixtures/workerPool.graphql, services/web-server/test/fixtures/workerPools.graphql, services/web-server/test/graphql/workermanager_test.js, ui/src/components/WMWorkerPoolEditor/index.jsx, ui/src/components/WMWorkerPoolsTable/index.jsx, ui/src/views/WorkerManager/WMEditWorkerPool/index.jsx, ui/src/views/WorkerManager/WMEditWorkerPool/workerPool.graphql, ui/src/views/WorkerManager/WMViewWorkerPools/WMWorkerPools.graphql
Github Bug/Issue: Fixes #2882 
As it says on the tin! Doesn't fix all of the issues in the issue but covers the most helpful ones IMHO
=> Add currentCapacity to ui for workerpools

changelog/bug-1638921-1.md, infrastructure/k8s/templates/taskcluster-auth-cron-purgeExpiredClients.yaml, infrastructure/k8s/templates/taskcluster-github-cron-sync.yaml, infrastructure/k8s/templates/taskcluster-hooks-cron-expires.yaml, infrastructure/k8s/templates/taskcluster-index-cron-expire.yaml, infrastructure/k8s/templates/taskcluster-purge-cache-cron-expireCachePurges.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireArtifacts.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireQueueMessages.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTask.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskDependency.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskGroupMembers.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskGroupSizes.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskGroups.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskRequirement.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireWorkerInfo.yaml, infrastructure/k8s/templates/taskcluster-secrets-cron-expire.yaml, infrastructure/k8s/templates/taskcluster-web-server-cron-cleanup-expire-access-tokens.yaml, infrastructure/k8s/templates/taskcluster-web-server-cron-cleanup-expire-auth-codes.yaml, infrastructure/k8s/templates/taskcluster-web-server-cron-scanner.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-cron-expire-errors.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-cron-expire-worker-pools.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-cron-expire-workers.yaml, infrastructure/tooling/templates/k8s/cron.yaml
Bugzilla Bug: [1638921](https://bugzilla.mozilla.org/show_bug.cgi?id=1638921)
..per @sciurus's good advice
=> Bug 1638921 - restart cron pods on failure, limit jobs duration

changelog/BIoF_9LQQaelZd3CY86Ceg.md, workers/docker-worker/src/bin/worker.js, workers/docker-worker/src/lib/host/test.js, workers/docker-worker/src/lib/host/worker-runner.js, workers/docker-worker/src/lib/runtime.js, workers/docker-worker/src/lib/shutdown_manager.js, workers/docker-worker/test/shutdown_manager_test.js
This was a quick refactor away from #3085.  The first two commits are from that PR, so please consider only the last commit here.
=> Support graceful shutdown in docker-worker

changelog/issue-3067.md, tools/worker-runner/perms/perms_posix.go, tools/worker-runner/perms/perms_test.go, tools/worker-runner/perms/perms_windows.go, tools/worker-runner/run/state.go
=> Write files containing secrets more securely

changelog/issue-3079.md, generated/references.json, services/worker-manager/docs/providers.md, services/worker-manager/schemas/v1/config-static.yml, services/worker-manager/src/api.js, services/worker-manager/test/api_test.js
Sorry this took a bit, I was experimenting with a new editor. Not sure if I'm sold on it yet.
Github Bug/Issue: Fixes #3079
=> Handle terminateAfter in reregister for workers that support it

.taskcluster.yml, changelog/bug-1635455.md, dev-docs/releasing.md, entrypoint, infrastructure/tooling/src/main.js, infrastructure/tooling/src/publish/index.js, infrastructure/tooling/src/publish/tasks.js, infrastructure/tooling/src/release/index.js, infrastructure/tooling/src/release/tasks.js, package.json, taskcluster/ci/release/kind.yml
Bugzilla Bug: [1635455](https://bugzilla.mozilla.org/show_bug.cgi?id=1635455)
=> Bug 1635455: support staging releases

changelog/NafDB1chTA-mY1QknC97xg.md, db/test/versions/0008_test.js, db/test/versions/0009_test.js, db/test/versions/0010_test.js, db/test/versions/0011_test.js, db/test/versions/0012_test.js, db/test/versions/0014_test.js
This should make renumbering verisons a little easier (just renaming
files)
=> Get db version number to test from filename

changelog/PqPHj_OhSYao7G8PDUUZRg.md, dev-docs/postgres-phase-2-guidelines.md, infrastructure/renumber-db-version.js
This is pretty temporary, but hopefully useful!
=> add a version-renumbering script

changelog/bug-1636193.md, infrastructure/tooling/src/utils/dockerflow.js
Bugzilla Bug: [1636193](https://bugzilla.mozilla.org/show_bug.cgi?id=1636193)
=> Bug 1636193 - output a dockerflow-compatible build link

changelog/UF3t1KhMQNSmKA0_bRhK6A.md, db/test/helper.js, dev-docs/postgres-phase-2-guidelines.md
pulled out of #2932
edit: whoops, I failed at `git add -p`.  This has a few more things in it.
=> add a 'toDbVersion' helper, other db testing helpers

changelog/A-YNu_WoRx-WRUxyg4kh9w.md, dev-docs/postgres-phase-2-guidelines.md
Commits were rebased, this fixes links to use the new commit sha.
=> Fix broken postgres phase 2 dev-docs links

dev-docs/postgres-phase-2-guidelines.md
Relates to https://github.com/taskcluster/taskcluster/issues/3131.
=> [docs] Remove mock fcts requirement from pg dev docs

changelog/WjRYbb06SRWsJAWM-NA33A.md, dev-docs/postgres-phase-2-guidelines.md
Based on [a conversation](https://github.com/taskcluster/taskcluster/pull/3134#discussion_r455933294).
=> update advice on etags

workers/docker-worker/package.json, workers/docker-worker/yarn.lock
=> docker-worker deps update

changelog/issue-2887.md, workers/generic-worker/errorreport/errorreport.go, workers/generic-worker/errorreport/errorreport_test.go, workers/generic-worker/main.go, workers/generic-worker/sentry.go, workers/generic-worker/workerrunner.go
=> issue 2887: support error-report message in generic-worker

changelog/bug-1654086.md, services/hooks/src/scheduler.js, services/hooks/test/scheduler_test.js
Bugzilla Bug: [1654086](https://bugzilla.mozilla.org/show_bug.cgi?id=1654086)
=> Bug 1654086 - make hooks more resilient to errors sending notifications

changelog/issue-2928.md, libraries/postgres/README.md, libraries/postgres/src/Database.js, libraries/postgres/test/database_test.js, package.json, yarn.lock
=> [db] Add support for named arguments

libraries/postgres/src/Database.js, libraries/postgres/test/database_test.js
I may have merged without paying attention to CI.
=> Fix CI test

changelog/issue-3285.md, clients/client-go/tcgithub/tcgithub.go, clients/client-py/taskcluster/generated/aio/github.py, clients/client-py/taskcluster/generated/github.py, clients/client-shell/apis/services.go, clients/client/src/apis.js, generated/references.json, services/github/src/api.js
=> Fixes typo

changelog/issue-3185.md, libraries/azqueue/src/index.js, services/notify/src/denier.js, services/queue/src/dependencytracker.js, services/queue/src/main.js, services/web-server/src/login/PostgresSessionStore.js, services/web-server/src/login/strategies/github.js, services/worker-manager/src/api.js
=> rewrite some single-row DB functions to use array destructuring

changelog/issue-3245.md, infrastructure/tooling/src/build/tasks/livelog.js, infrastructure/tooling/src/build/tasks/websocktunnel.js, ui/docs/manual/deploying/websocktunnel.mdx
=> include a leading v in websocktunnel, livelog docker tags

changelog/issue-3301.md, services/github/src/handlers.js, services/github/src/utils.js, services/github/test/utils_test.js
=> Don't ignore errors in throttleRequest

changelog/IkCKMu7GTZiBt35HSrT5_w.md, infrastructure/tooling/src/generate/generators/readme-tocs.js
Fixes an intermittent failure of generation
=> generate READMEs before reading them to make TOCs

changelog/old-docker-config.md, workers/docker-worker/config.yml
=> Remove some unused configuration from docker-worker config.

changelog/docker-manifest-version.md, workers/docker-worker/src/lib/docker/artifact_image.js, workers/docker-worker/test/integration/docker_manifest_test.js
Github Bug/Issue: Fixes #2973.
=> Support docker images generated by newer docker versions.

changelog/dont-compress-dmg-zst.md, changelog/dont-compress-dmg.md, changelog/make-compression-configurable.md, generated/references.json, workers/docker-worker/config.yml, workers/docker-worker/src/lib/features/artifacts.js, workers/docker-worker/test/integration/file_artifact_test.js, workers/docker-worker/test/integration/helper/get.js, workers/docker-worker/test/integration/helper/get_artifact.js, workers/generic-worker/artifacts.go, workers/generic-worker/generated_docker_darwin.go, workers/generic-worker/generated_docker_linux.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/schemas/docker_posix.yml, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml, workers/generic-worker/schemas/simple_posix.yml
Bugzilla Bug: [1637302](https://bugzilla.mozilla.org/show_bug.cgi?id=1637302)
=> [docker-worker] Don't compress `.dmg` files.

changelog/issue-1986-1.md, changelog/issue-1986.md, clients/client-go/tchooks/types.go, generated/references.json, services/hooks/schemas/constants.yml
=> Max length adjust

changelog/per-worker-scopes.md, workers/docker-worker/src/lib/runtime.js, workers/docker-worker/src/lib/task.js, workers/docker-worker/test/integration/device_link_test.js, workers/docker-worker/test/integration/header_footer_logs_test.js, workers/docker-worker/test/testworker.js
Bugzilla Bug: [1623749](https://bugzilla.mozilla.org/show_bug.cgi?id=1623749)
=> [docker-worker] Allow granting device and privileged scopes per-worker-pool.

changelog/disable-features.md, workers/docker-worker/config.yml, workers/docker-worker/src/lib/task.js, workers/docker-worker/test/dockerworker.js, workers/docker-worker/test/integration/features_test.js, workers/docker-worker/test/integration/logging/bulk_log_test.js, workers/docker-worker/test/localworker.js, workers/docker-worker/test/post_task.js, workers/docker-worker/test/testworker.js
Bugzilla Bug: [1623749](https://bugzilla.mozilla.org/show_bug.cgi?id=1623749)
=> [docker-worker] Allow disabling features at the worker level.

changelog/issue-3337.md, services/queue/config.yml, services/queue/src/data.js, services/queue/src/dependencyresolver.js, services/queue/src/dependencytracker.js, services/queue/src/main.js
=> Make dependencyTracker.scheduleTask idempotent, run it in parallel less

.github/CODEOWNERS
One final @taskcluster/services-reviewers review!
=> Simplify codeowners to allow for more round-robin reviewing

changelog/issue-3178.md, clients/client-shell/README.md
=> curl to download binary on mac

changelog/issue-3168.md, generated/references.json, services/worker-manager/schemas/v1/config-aws.yml, services/worker-manager/schemas/v1/config-azure.yml, services/worker-manager/schemas/v1/config-google.yml, services/worker-manager/src/estimator.js, services/worker-manager/src/monitor.js, services/worker-manager/src/providers/aws.js, services/worker-manager/test/api_test.js, services/worker-manager/test/estimator_test.js, services/worker-manager/test/fixtures/schemas/sample-aws-config.json, services/worker-manager/test/fixtures/schemas/sample-aws-worker-pool-full.json, services/worker-manager/test/fixtures/schemas/sample-azure-config.json, services/worker-manager/test/fixtures/schemas/sample-google-config.json, services/worker-manager/test/provider_aws_test.js, services/worker-manager/test/provider_azure_test.js, services/worker-manager/test/provider_google_test.js
=> issue 3168: support scaling ratio in worker-manager

changelog/issue-3334.md, ui/docs/manual/deploying/database.mdx
=> add best practices for DB upgrades

changelog/issue-2910.md, ui/src/components/TaskDetailsCard/index.jsx, ui/src/utils/constants.js, ui/src/views/Tasks/ViewTask/index.jsx, ui/src/views/Tasks/ViewTask/task.graphql
Bugzilla Bug: [1639279](https://bugzilla.mozilla.org/show_bug.cgi?id=1639279)
Github Bug/Issue: Fixes #2910
This doesn't quite fix the above bug/issue, but it's close. I'm struggling to get the graphql bits working correctly -- I'm currently getting this error: ```"Cannot query field \"tasks\" on type \"TasksConnection\"."```.
=> [wip] bug 1639279: add UI for showing dependent tasks

changelog/issue-3344.md, workers/docker-worker/src/lib/task.js
=> Replace use of hasPrefixedScopes in docker-worker with scope expressions

services/worker-manager/test/estimator_test.js
Refs #3372.
No changelog here since this is a temporary, testing-only change.
=> add debug logging for intermittent test

changelog/issue-3355.md, clients/client-go/tcgithubevents/types.go, generated/references.json, services/github/schemas/v1/github-pull-request-message.yml, yarn.lock
=> allow any 'action' for a pull request

changelog/issue-3456.md, services/worker-manager/src/api.js, services/worker-manager/test/api_test.js
Github Bug/Issue: Fixes #3456.
=> Reject invalid workerId/workerGroup identifiers

changelog/bEEhZT-bTH6LSoB_NF1WFg.md, services/hooks/src/scheduler.js, services/hooks/test/scheduler_test.js
This fixes a failure in v36.0.0.
=> Fix calls to hook scheduling

changelog/issue-3464.md, services/queue/src/data.js, services/queue/test/claimwork_test.js, services/queue/test/createtask_test.js, services/queue/test/deadline_test.js, services/queue/test/dependency_test.js, services/queue/test/expiretask_test.js, services/queue/test/helper.js, services/queue/test/resolvetask_test.js, services/queue/test/retry_test.js, services/queue/test/taskgroup_test.js
=> Format timestamps correctly in task status

changelog/bug-1563191.md, workers/generic-worker/main.go, workers/generic-worker/payload_test.go
Bugzilla Bug: [1563191](https://bugzilla.mozilla.org/show_bug.cgi?id=1563191)
=> Bug 1563191 - include required json schema in task log if payload non-conformant

infrastructure/tooling/src/generate/generators/yarn-minify.js, yarn.lock
=> Upgrade @hapi/hoek

changelog/issue-3346.md, services/worker-manager/src/providers/azure.js, services/worker-manager/test/provider_azure_test.js
Github Bug/Issue: Fixes #3346
In progress, not ready for review yet.
=> Issue 3346 - no longer call fetchVmInfo to determine provisioningState

changelog/issue-3347.md, generated/references.json, services/worker-manager/schemas/v1/config-azure.yml, services/worker-manager/src/providers/azure.js, services/worker-manager/test/provider_azure_test.js
=> #3347 - optionally ignore failed provisioning states

changelog/issue-3058.md, services/worker-manager/src/providers/azure.js, services/worker-manager/test/provider_azure_test.js
See the comments on the individual commits here.
Github Bug/Issue: Fixes #3058
=> [azure provider] factor out provisioning/deprovisioning resources into functions, handle status better

changelog/issue-3501.md, services/worker-manager/src/main.js, services/worker-manager/test/expiration_test.js
=> Correctly configure the worker-manager expireErrors job

.yarnrc, changelog/WUqtDO0rTryiWxQqODoGkw.md, package.json, ui/package.json, workers/docker-worker/package.json
=> renovate/yarn 1.x

changelog/issue-3503.md, services/auth/test/helper.js
=> run mock auth tests without azure creds

changelog/issue-3543.md, ui/package.json, ui/src/components/Shell/index.jsx, ui/yarn.lock
=> use new docker-exec-websocket-client to avoid server dependencies

changelog/issue-3495.md, ui/package.json, ui/src/components/SchemaTable/index.jsx, ui/yarn.lock
=> Upgrade schema viewer to show full descriptions

changelog/issue-3287.md, dev-docs/best-practices/db.md
This was mostly taken from our postgres phase 2 migration guidelines.
Closes #3287.
=> Add BP to DB document

package.json, yarn.lock
=> Upgrade pg to 8.x

package.json, yarn.lock
Reverts taskcluster/taskcluster#3572
See #3588.
=> Revert "Upgrade pg to 8.x"

changelog/issue-3598.md, libraries/postgres/src/Database.js
=> Issue 3598 - fix db collation check

changelog/issue-3525.md, workers/docker-worker/src/lib/features/chain_of_trust.js
=> Do not try to update CoT hashes when a task is aborted

changelog/PuHrN7CeT7agfhJ5byJO9w.md, db/README.md
Just found that a link was broken on that README as I was reading up with the intention of tackling #3538 .
=> Fix link to fns.md in db/README.md

changelog/issue-3591.md, services/web-server/src/login/User.js, services/web-server/test/login_strategies_github_test.js, services/web-server/test/login_strategies_mozilla_auth0_test.js
=> Add anonymous scope in web-server

changelog/issue-3679.md, tools/taskcluster-proxy/README.md
=> minor updates to tc-proxy README

changelog/Z6X5UswwTSi82HeDK3i5HA.md, services/auth/src/static-scopes.json, services/web-server/scopes.yml
A follow up on https://github.com/taskcluster/taskcluster/commit/e895ea7eaa91e329521dc870e2068b7eb094d205.
=> Add assume:anonymous to web-server scopes

changelog/issue-3662.md, taskcluster/ci/release/kind.yml, ui/docs/reference/core/notify/README.mdx, ui/docs/reference/core/notify/usage.mdx, ui/docs/reference/integrations/github/taskcluster-yml-v1.mdx
This is a followup I forgot to ask for in #3662. @ricky26 offered to do it but I had the time and needed something simple to get my mind back on track again anyway!
@ricky26 I think it will force us to get a review from an admin as well but I'm going to rely on your review here to be the final say on if these docs are correct!
=> Add some docs for new notify routes

changelog/issue-3767.md, clients/client-py/setup.py, clients/client-py/tox.ini
Github Bug/Issue: Fixes #3767.
=> don't use aiohttp==3.7.0

changelog/issue-3791.md, clients/client-shell/config/init.go
=> Fix incorrect checks for presence of credentials in shell client

changelog/MC82jTRcTTeM9DLV1W98Zw.md, ui/docs/reference/workers/generic-worker/installing.mdx
Thanks to @bhearsum for bringing this up.
=> fix links from g-w installing doc

changelog/issue-3502.md, services/auth/src/scoperesolver.js
This is the result of @djmitche and I pairing on this issue. He's providing a summary of why these
changes are needed in the issue itself.
Github Bug/Issue: Fixes #3502
=> Fix occasional issue in `authenticateHawk` return values

changelog/issue-3793.md, services/web-server/src/loaders/artifacts.js, services/web-server/src/loaders/tasks.js, services/web-server/test/helper.js
=> Update web-server artifact support to work in a private deployment

changelog/issue-3738.md, infrastructure/tooling/src/generate/generators/k8s.js
=> set up k8s/templates once, instead of for every service

changelog/ZdTx8PtwSXePP6NmvZut0Q.md, workers/docker-worker/release.sh
After this, I think we can release 38.0.1.
=> fix docker-worker's release.sh

changelog/bug-3759.md, libraries/postgres/src/Database.js, libraries/postgres/test/database_test.js
=> Ensure that access and schema checks occur at the end of every run

changelog/N_DWnCdBSPyMjyptKYIEfg.md, services/auth/src/static-scopes.json, services/github/scopes.yml
Addresses https://sentry.prod.mozaws.net/operations/taskcluster-cloudops-stage/issues/9908731/?referrer=alert_email
=> Add queue:list-task-group:* for tc-github

changelog/issue-3731.md, ui/src/components/AuthConsent/index.jsx, ui/src/theme.js, ui/src/views/Documentation/Reference/Entry.jsx
=> rename ExpansionPanel to Accordion

changelog/issue-3834.md, clients/client-go/creds_test.go, clients/client-go/tcauth/auth_examples_test.go, clients/client-py/test/test_async.py, clients/client-py/test/test_client.py, clients/client-web/test/Auth_test.js, clients/client/test/creds_test.js, workers/generic-worker/tcproxy/tcproxy_test.go
=> update integration tests to expect anonymous role

changelog/FF4-j6aSQXe1vel4PSfeIA.md, workers/generic-worker/tcproxy/tcproxy_test.go
Test failure log message fix from #3835.
=> Fix TestTcProxy test failure message

changelog/issue-3839.md, services/web-server/src/loaders/artifacts.js, services/web-server/src/loaders/tasks.js, services/web-server/src/utils/maybeSignedUrl.js, ui/src/components/ErrorPanel/index.jsx, ui/src/components/TaskRunsCard/index.jsx
Github Bug/Issue: Fixes #3839
This at least *changes* how #3831 behaves, so perhaps the fix for that issue should be based on this one.
=> Fix "e.artifacts is null" and improve UI error handling

changelog/U8vidxdsRei06FdottNeTg.md, services/github/src/main.js, services/github/test/github-auth.js
=> Undo one mistaken octokit update

changelog/issue-3851.md, ui/src/components/SiteSpecific/index.jsx, ui/src/utils/siteSpecific.jsx, ui/src/views/Quickstart/index.jsx
=> Fix up the QuickStart view

changelog/issue-3831.md, services/web-server/src/loaders/artifacts.js, services/web-server/src/loaders/tasks.js, services/web-server/src/utils/maybeSignedUrl.js, ui/src/views/Tasks/TaskLog/index.jsx
There are two commits here -- the first fixes my error in #3844, and the second fixes #3831.
I tested this fix on both Firefox and Chome.
Github Bug/Issue: Fixes #3831
=> Work around a history bug in parsing URLs

changelog/issue-3884.md, services/web-server/src/login/scanner.js, services/web-server/src/login/strategies/test.js, services/web-server/test/scanner_test.js
=> Allow third-party clients to have assume:anonymous

changelog/issue-3906.md, services/github/src/api.js, services/github/src/handlers.js, services/github/test/github-auth.js, services/github/test/handler_test.js
=> Fix github issue commenting

changelog/issue-3832.md, package.json, services/github/src/github-auth.js, services/github/src/main.js, services/github/test/github-auth_test.js, yarn.lock
Don't land this quite yet, I want to try it in my dev first.
Feel free to review though!
Github Bug/Issue: Fixes #3832
=> use github's own retry plugins

changelog/issue-3808.md, services/worker-manager/src/providers/azure.js
Github Bug/Issue: Fixes #3808 
I have separated the try-catch. Now IP, NIC, and Vm have their separate try-catch. the description of the error message is not complete.
=> Error message change of IP, NIC, and VM in azure.js

services/object/src/backends/index.js, services/object/test/backends_test.js
=> Add the promised tests for backendMap

changelog/issue-3881.md, clients/client-go/tcobject/tcobject.go, clients/client-web/src/clients/Object.js, clients/client/src/apis.js, generated/references.json, services/object/src/api.js
=> Include projectId in the upload scope

clients/client-go/tcobject/tcobject.go, clients/client-go/tcobject/types.go, clients/client-py/taskcluster/generated/aio/object.py, clients/client-py/taskcluster/generated/object.py, clients/client-shell/apis/services.go, clients/client-web/src/clients/Object.js, clients/client/src/apis.js, generated/docs-table-of-contents.json, generated/references.json, services/object/schemas/v1/get-object-http.yml, services/object/src/api.js, services/object/src/backends/base.js, services/object/src/backends/test.js, services/object/test/api_test.js, services/object/test/helper.js, ui/docs/reference/platform/object/upload-download-methods.mdx
..and fix a few other minor inconsistencies in the API endpoint.
This was some preparatory work I did for #3931, and I thought I'd put it up for review while I work on the rest of that issue.
=> Implement method negotiation in the downloadObject API endpoint

changelog/issue-3637.md, services/github/src/handlers.js, services/github/test/handler_test.js
This probably isn't my dream fix for all of this but I think we need to get a quick fix in and then start building a bigger update
Github Bug/Issue: Fixes #3637
=> Avoid spamming comments from tc-gh

changelog/issue-3719.md, clients/client-go/tcobject/types.go, clients/client-py/taskcluster/generated/aio/object.py, clients/client-py/taskcluster/generated/object.py, clients/client-shell/apis/services.go, clients/client/src/apis.js, generated/docs-search.json, generated/docs-table-of-contents.json, generated/references.json, services/object/package.json, services/object/schemas/v1/upload-object-request.yml, services/object/src/api.js, services/object/src/backends/aws.js, services/object/src/backends/base.js, services/object/src/backends/index.js, services/object/src/backends/test.js, services/object/test/api_test.js, services/object/test/backends/aws_test.js, services/object/test/helper/aws.js, services/object/test/helper/index.js, services/object/test/helper/simple-download.js, services/object/test/helper/temporary-upload.js, services/queue/test/helper.js, ui/docs/manual/deploying/object-service.mdx, ui/docs/reference/platform/object/aws-backend.mdx, ui/docs/reference/platform/object/download-methods.mdx, ui/docs/reference/platform/object/simple-downloads.mdx
Github Bug/Issue: Fixes #3719, Fixes #3932.
This also implements a testing framework that can help ensure that all
backends behave the same way (which isn't so hard yet, since they do so
little!) -- that's #3932.
And it fills out the temporary upload mechanism so that it, y'know, actually uploads something :)
=> Implement a basic AWS object storage backend

changelog/Dq5lqjEMSaG6R9BHXnQxjA.md, infrastructure/tooling/src/meta/checks/depcheck.js, package.json
I spotted this unmet peer dependency.  Something else was pulling in the package, so nothing failed -- but we should be explicit.
=> add peer dependency on @octokit/core

changelog/issue-3986.md, generated/references.json, infrastructure/k8s/values.schema.json, services/object/config.yml, services/object/src/backends/index.js
=> Make object.backends,backendMap configs optional

changelog/issue-3999.md, libraries/postgres/src/Database.js, libraries/postgres/test/database_test.js, package.json, services/worker-manager/src/api.js, yarn.lock
=> fix handling of named parameters to db functions

libraries/api/src/middleware/auth.js
=> grammar correction: double 'and' in exception

changelog/issue-4061.md, package.json, yarn.lock
See https://github.com/taskcluster/taskcluster/issues/4054
Github Bug/Issue: Fixes #4061
=> Downgrade sift

changelog/issue-3892.md, ui/docs/manual/deploying/github.mdx
=> Add documentation for github.webhook_secret

changelog/PgiDACCRTtWuyANsgKZXJQ.md, package.json, services/github/src/github-auth.js, ui/yarn.lock, yarn.lock
Quickest fix we can think of to get this out of the way
=> Remove github octokit throttling until we understand why it is doing what it is doing

changelog/issue-4056.md, tools/taskcluster-proxy/routes.go, tools/taskcluster-proxy/routes_test.go
=> tc-proxy should not follow redirects

changelog/issue-4057.md, clients/client-go/http.go, clients/client-go/http_test.go, clients/client-py/taskcluster/utils.py, clients/client-py/test/test_utils.py, clients/client-shell/apis/provider.go, clients/client-shell/apis/provider_test.go, clients/client-web/src/fetch.js, clients/client/src/client.js, clients/client/test/client_test.js
=> Do not follow redirects in clients.

changelog/issue-3888.md, generated/references.json, services/worker-manager/schemas/v1/worker-lifecycle.yml
...with the correct value for "30 days"
Github Bug/Issue: Fixes #3888
=> Fix max reregistrationTimeout

changelog/issue-2875.md, workers/docker-worker/src/monitor/logger.js, workers/docker-worker/src/task.js, workers/docker-worker/src/util/validate_schema.js
=> safer use of Object.keys

changelog/issue-3466.md, services/queue/src/api.js, services/queue/test/canceltask_test.js
=> Improve cancelTask idempotency

changelog/issue-3665.md, libraries/app/src/index.js, services/auth/test/helper.js, taskcluster/ci/service/kind.yml
=> Add debugging for EADDRINUSE errors

changelog/issue-4125.md, services/worker-manager/src/api.js
=> Elide reregister payload from logs

changelog/issue-3894.md, libraries/monitor/README.md, libraries/monitor/src/plugins/sentry.js, libraries/postgres/src/Database.js
Brian, any chance I could use your dev env to test this somehow?
Github Bug/Issue: Fixes #3894
=> Add Sentry fingerprints for postgres errors

changelog/issue-3751.md, services/auth/src/api.js, services/auth/test/client_test.js
=> Handle conflicts when creating clients

changelog/issue-1064.md, clients/client-shell/apis/provider.go, clients/client-shell/apis/provider_test.go, clients/client-shell/cmds/root/command.go
=> client-shell: handle API errors better

changelog/issue-4072.md, clients/client-shell/cmds/config/config.go
=> Fix parsing of authorizedScopes in client-shell config

changelog/issue-3758.md, clients/client-shell/apis/provider.go
=> client-shell: Display a warning if input is expected on stdin

changelog/D2RWdSbNRfS-GDRufHMmhg.md, infrastructure/tooling/src/release/tasks.js
A more permanent fix for 0c7084821e69f25c344bfa9628074de656ec6fcb
/cc @petemoore
=> do not add unnecessary quotes in yarn release

changelog/issue-4226.md, entrypoint, infrastructure/tooling/src/main.js, infrastructure/tooling/src/minify/index.js, infrastructure/tooling/src/minify/tasks.js, package.json
=> remove minification from yarn generate, and run it via 'yarn minify'

changelog/issue-4110.md, ui/package.json, ui/src/App/index.jsx, ui/src/components/Dashboard/index.jsx, ui/src/components/Landing/index.jsx, ui/src/styleguide/ThemeWrapper.jsx, ui/yarn.lock
=> Fix React error boundaries to not crash browsers

changelog/issue-4238.md, services/auth/src/static-scopes.json, services/index/scopes.yml
=> Issue 4238 - Allow index service to view tasks always

changelog/issue-4240.md, services/web-server/src/entities/Task.js, services/web-server/src/graphql/Tasks.graphql, ui/src/components/TaskDetailsCard/index.jsx, ui/src/views/Tasks/TaskDefinition/index.jsx, ui/src/views/Tasks/TaskDefinition/task.graphql, ui/src/views/Tasks/routes.js
=> Display task definitions within the UI

changelog/issue-4248.md, clients/client-go/tcqueue/types.go, generated/references.json, services/queue/schemas/v1/list-artifacts-response.yml, services/queue/test/artifact_test.js
=> Add link to the storageTypes for listArtifacts

changelog/bug-1562993.md, go.mod, go.sum, workers/generic-worker/main.go, workers/generic-worker/main_test.go
Bugzilla Bug: [1562993](https://bugzilla.mozilla.org/show_bug.cgi?id=1562993)
=> Bug 1562993 - generic-worker: only log first error encountered in task log

changelog/issue-4275.md, ui/docs/manual/deploying/workers.mdx
=> mention azure cred expiration in docs

.gitattributes, .github/CODEOWNERS, changelog/issue-4295.md, infrastructure/tooling/src/changelog/index.js
=> ignore generated rust files

changelog/issue-4296.md, clients/client-rust/src/client.rs
=> rust client: document where  should appear instead of panicing

changelog/issue-3868.md, services/web-server/src/login/PostgresSessionStore.js, services/web-server/test/session_store_test.js
Fixes #3868 
Hi @djmitche, sorry for the delay in getting back with this really short fix! 
How does this look?
I am afraid I will trouble you a little bit more!
I've made the change but I'm not 100% sure how to check if it's working! Could you please help me with that?
Thank you!
=> fix: web-server should check session when fetching

changelog/issue-4279.md, libraries/testing/README.md, libraries/testing/src/with-db.js, services/web-server/test/session_store_test.js
=> Add `helper.withDbClient` in tc-lib-testing

changelog/issue-4336.md, tools/worker-runner/errorreport/errorreport.go, tools/worker-runner/errorreport/errorreport_test.go
This has likely never worked!
Github Bug/Issue: Fixes #4336
=> Fix error reporting from worker-runner

changelog/issue-4256.md, clients/client-web/package.json, clients/client-web/yarn.lock, ui/package.json, ui/yarn.lock, yarn.lock
Github Bug/Issue: Fixes #4256
Previous dependabot PRs:
* PR #4352 - karma-webpack update (which may require an update to webpack 5)
* PR #4253 - karma update
=> Update to Karma 6.1.0

changelog/alKSd9LHRcyRzV0gHOEjuA.md, services/web-server/src/resolvers/CachePurges.js
Let's land this before releasing 41.
=> Fix call to purgeCache.purgeCache in web-server to use workerPoolId

changelog/issue-4273.md, clients/client-go/tcobject/tcobject.go, clients/client-go/tcobject/types.go, clients/client-py/taskcluster/generated/aio/object.py, clients/client-py/taskcluster/generated/object.py, clients/client-rust/src/generated/object.rs, clients/client-shell/apis/services.go, clients/client-web/src/clients/Object.js, clients/client/src/apis.js, generated/references.json, services/object/schemas/v1/finish-upload-request.yml, services/object/src/api.js, services/object/test/api_test.js, services/object/test/middleware/cdn_test.js
Github Bug/Issue: Fixes #4273
Still WIP pending landing of #4334
=> Add an object.finishUpload method

changelog/issue-4411.md, clients/client-go/tcqueue/types.go, generated/references.json, services/queue/schemas/v1/post-artifact-request.yml, services/queue/src/artifacts.js
=> Allow specifying a content-type for link artifacts

changelog/issue-4417.md, clients/client-go/tchooks/types.go, generated/references.json, services/hooks/schemas/constants.yml, services/hooks/schemas/v1/task-status.yml, services/hooks/src/taskcreator.js
=> Fix triggerHook response schema to include taskQueueId

changelog/aXcfkSZZRMWYlfEArj8_jA.md, clients/client-go/tcobject/types.go, generated/references.json, services/object/schemas/v1/create-upload-request.yml, services/object/test/api_test.js
Came across this testing #4422.
=> fix typo in createUpload schema, add test

changelog/issue-4455.md, clients/client/package.json, clients/client/src/client.js, clients/client/yarn.lock
Github Bug/Issue: Fixes #4455
If this is green on the first try, I will mark its changelog leve down to `patch`.
Note that there are a few scattered uses of superagent remaining in the codebase.  I'm not going to push my luck by rewriting those in this PR.
=> replace superagent with got in taskcluster-client

changelog/issue-4050.md, workers/docker-worker/src/features/bulk_log.js, workers/docker-worker/src/features/local_live_log.js, workers/docker-worker/test/integration/container_startup_test.js, workers/generic-worker/artifacts.go, workers/generic-worker/helper_broken_on_docker_test.go, workers/generic-worker/livelog.go, workers/generic-worker/mocktc/queue.go
=> Workers: create a LinkArtifact from live.log to live_backing.log

changelog/amcA9BpCStuTXcduDsdFwA.md, clients/client-py/setup.py
=> require aiohttp >= 3.7.4

changelog/IuNWJ07pRtiW4b1faDHL8w.md, clients/client-rust/Cargo.toml, clients/client-rust/src/client.rs
=> Upgrade reqwest and Tokio to latest major versions

changelog/issue-4502.md, services/github/src/handlers.js, services/github/test/data/yml/invalid-task.json, services/github/test/handler_test.js
=> Wrap more of tc-gh handler in try/catch

changelog/issue-4470.md, services/web-server/src/graphql/Tasks.graphql, services/web-server/test/fixtures/createTask.graphql, ui/src/utils/gqlToApi.js, ui/src/views/Tasks/ViewTask/index.jsx, ui/src/views/Tasks/createTask.graphql
=> Fix 400 errors when creating / retriggering tasks

yarn.lock
=> upgrade xmldom

changelog/issue-4420.md, services/object/src/api.js, services/object/src/backends/index.js, services/object/test/api_test.js, services/object/test/backends/aws_test.js, services/object/test/backends/google_test.js, services/object/test/helper/index.js, services/object/test/helper/simple-download.js
=> Fail with 400 when an object's backend is not found

.github/workflows/codeql.yml, changelog/issue-4523.md
I found this by clicking the "set up CodeQL" option and copy-pasting.
Github Bug/Issue: Fixes #4523
=> Update the codeql workflow to the latest version

changelog/YI0fRsNoQkS6jc80hjggWg.md, ui/docs/manual/deploying/queue-config.mdx
=> Bucket names are not URLs

changelog/epek3TMRRLm6yZGNJpf9_Q.md, clients/client-go/tcobject/tcobject.go, clients/client-py/taskcluster/generated/aio/object.py, clients/client-py/taskcluster/generated/object.py, clients/client-rust/src/generated/object.rs, clients/client-shell/apis/services.go, clients/client-web/src/clients/Object.js, clients/client/src/apis.js, generated/references.json, services/object/src/api.js, ui/docs/reference/platform/object/download-methods.mdx
I figure we should say this somewhere :)
=> Objects are immutable

changelog/issue-4592.md, services/object/test/helper/data-inline-upload.js, services/object/test/helper/put-url-upload.js
Bugzilla Bug: [1523226](https://bugzilla.mozilla.org/show_bug.cgi?id=1523226)
Github Bug/Issue: Fixes #4592
=> verify that zero-length objects work

changelog/drZjMzcgRzGB9FsnrN6o5g.md, clients/client-go/README.md, clients/client-go/codegenerator/model/api.go, clients/client-go/codegenerator/model/exchange.go, clients/client-go/tcauthevents/tcauthevents.go, clients/client-go/tcgithubevents/tcgithubevents.go, clients/client-go/tchooksevents/tchooksevents.go, clients/client-go/tcnotifyevents/tcnotifyevents.go, clients/client-go/tcpurgecacheevents/tcpurgecacheevents.go, clients/client-go/tcqueueevents/tcqueueevents.go, clients/client-go/tcworkermanagerevents/tcworkermanagerevents.go, generated/references.json, infrastructure/tooling/src/release/tasks.js, tools/jsonschema2go/README.md, tools/jsonschema2go/jsonschema.go, ui/docs/reference/workers/websocktunnel.mdx, workers/generic-worker/README.md, workers/generic-worker/generated_docker_darwin.go, workers/generic-worker/generated_docker_linux.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/schemas/docker_posix.yml, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml, workers/generic-worker/schemas/simple_posix.yml
I hadn't realised we had even more references, this should be all of them, hopefully!
=> General cleanup for godoc.org -> pkg.go.dev

changelog/issue-4587.md, clients/client-go/tcqueue/tcqueue.go, clients/client-py/taskcluster/generated/aio/queue.py, clients/client-py/taskcluster/generated/queue.py, clients/client-rust/src/generated/queue.rs, clients/client-shell/apis/services.go, clients/client-web/src/clients/Queue.js, clients/client/src/apis.js, generated/references.json, services/queue/src/api.js, services/queue/test/reruntask_test.js
..and add some tests to verify the new docs are accurate.
Github Bug/Issue: Fixes #4587
=> Update documentation for queue.rerunTask

.eslintrc.yml, infrastructure/tooling/src/dev/postgres.js
In an effort with Dustin, I'm working on deploying Taskcluster and we try to fix all issues we encounter (or document) along the way. Some of this is tracked in issue 4631.
=> Update postgres.sql to work for new deployments

changelog/issue-4655.md, clients/client/src/client.js, services/auth/src/static-scopes.json, services/built-in-workers/scopes.yml, services/built-in-workers/src/TaskQueue.js, services/built-in-workers/test/helper.js
=> Use task credentials in built-in-workers

.all-contributorsrc, README.md
=> Add @MasterWayZ for work on infra and bug reporting

changelog/issue-2393.md, ui/src/views/Roles/ViewRoles/Roles.jsx
Github Bug/Issue: Fixes #2393 for Roles page
=> Roles list update after deleting a role

changelog/issue-4705.md, db/fns.md, infrastructure/tooling/src/utils/db.js, libraries/postgres/src/Schema.js
=> Include version where a function is last defined in generated db/fns.md

changelog/issue-4715.md, services/worker-manager/src/providers/azure.js, services/worker-manager/test/provider_azure_test.js
Github Bug/Issue: Fixes #4715 
Reviewers: please review the first commit individually, as that's the one I'll backport to the v39.1.1 branch running in firefox-ci.  The refactor passes tests, but is higher-risk and I won't backport it.
=> Always deprovision STOPPING azure workers

changelog/issue-4722.md, ui/src/components/ReferenceLinks/index.jsx
Fixes #4722 
hey @djmitche! what do you think about this fix? :) 
thanks!
=> Fix: 'Reference Links' box links are incorrect in README

changelog/issue-4739.md, dev-docs/dev-deployment.md
=> Update reverse proxy example to avoid weird authentication errors caused by default apache config

changelog/issue-4741.md, dev-docs/creating-a-worker-ami.md
Wrote this from as best as I could remember, looking at all the files I've edited and the process I went through.
Github Bug/Issue: Fixes #4741
=> Add documentation on how to create AWS backed workers

changelog/bug-1442024.md, generated/docs-search.json, package.json, services/object/src/backends/aws.js, services/object/test/backends/aws_test.js, services/object/test/backends/google_test.js, services/object/test/helper/data-inline-upload.js, services/object/test/helper/put-url-upload.js, ui/docs/reference/platform/object/simple-downloads.mdx
Bugzilla Bug: [1442024](https://bugzilla.mozilla.org/show_bug.cgi?id=1442024)
=> Serve HTML documents as attachments

changelog/issue-4631.md, dev-docs/dev-deployment.md
Addresses a few minor points in #4631.
=> Minor updates to dev docs

changelog/issue-4765.md, infrastructure/tooling/src/build/tasks/client-shell.js, tools/livelog/build.sh, tools/taskcluster-proxy/build.sh, tools/taskcluster-proxy/dockerbuild.sh, tools/worker-runner/build.sh, ui/docs/reference/workers/generic-worker/support-tiers.mdx, workers/generic-worker/build.sh, workers/generic-worker/clean-builds.sh
=> Issue 4765 - native darwin/arm64 release binaries

changelog/bug-1631824.md, generated/references.json, services/worker-manager/schemas/v1/config-azure.yml, services/worker-manager/src/providers/azure/index.js, services/worker-manager/test/fakes/schemas/azure-vm.yml, services/worker-manager/test/provider_azure_test.js, ui/docs/manual/deploying/workers.mdx
..to allow their deletion during deprovisioning
I'm going to test this out in my dev environment.
Bugzilla Bug: [1631824](https://bugzilla.mozilla.org/show_bug.cgi?id=1631824)
=> [azure-provider] Generate names for dataDisks

changelog/issue-4764.md, clients/client-py/taskcluster/aio/download.py, clients/client-py/taskcluster/download.py, clients/client-py/taskcluster/exceptions.py, clients/client-py/test/aio/test_upload_download.py, clients/client-py/test/test_upload_download.py
=> Add `downloadArtifact*` to the Python client

changelog/issue-4757.md, infrastructure/tooling/src/dev/aws.js, infrastructure/tooling/src/dev/common.js, infrastructure/tooling/src/dev/helm.js, infrastructure/tooling/src/dev/rabbit.js, infrastructure/tooling/src/dev/taskcluster.js, services/object/src/backends/aws.js
=> Fix some small bugs in dev:init

changelog/issue-4714.md, clients/client-go/tcobject/upload.go, clients/client-py/taskcluster/aio/upload.py, clients/client-rust/upload/src/lib.rs, clients/client/src/upload.js
=> Send hashes for uploaded objects

changelog/issue-4606.md, internal/mocktc/queue.go, internal/mocktc/tc/services.go, workers/generic-worker/artifacts_multiuser_test.go, workers/generic-worker/helper_broken_on_docker_test.go, workers/generic-worker/main_broken_on_docker_test.go, workers/generic-worker/mounts.go, workers/generic-worker/mounts_test.go
=> Support downloading object artifacts in generic-worker

clients/client-py/README.md
=> add docs for client-py's download functionality

changelog/issue-4882.md, libraries/pulse/src/client.js, libraries/pulse/test/client_test.js
=> Pass servername to amqplib.connect

changelog/issue-4895.md, clients/client-go/tcobject/upload.go, clients/client-py/README.md, clients/client-py/taskcluster/aio/upload.py, clients/client-rust/integration_tests/tests/upload_download.rs, clients/client-rust/upload/src/lib.rs, clients/client/README.md, clients/client/src/upload.js
=> Allow/require passing uploadId to upload helpers

changelog/bug-1712924.md, services/web-server/src/utils/login.js, services/web-server/src/views/callback.ejs, ui/src/auth/UserSession.js
Bugzilla Bug: [1712924](https://bugzilla.mozilla.org/show_bug.cgi?id=1712924)
=> [Bug 1712924] Encode postmessage content to avoid issues

changelog/PR5ssmFDTpC0p3UvMYcCVQ.md, dev-docs/principles.md
This is what came to mind, but this is a good time to add more bullet points if you think of anything..
=> Update principles in dev-docs

changelog/issue-4896.md, services/queue/src/artifacts.js, services/queue/test/helper.js
=> Fix `queue.getArtifact` return for object artifacts

workers/generic-worker/main_test.go, workers/generic-worker/mounts_test.go
Just some minor lint fixes that https://code.visualstudio.com/ suggested.
=> Lint fixes (generic-worker)

changelog/bug-1131975.md, clients/client-shell/cmds/validate-json/validate.go, clients/client-shell/cmds/validate-json/validate_test.go, clients/client-shell/subtree_imports.go
Signed-off-by: vnzongzna <vnzongzna@gmail.com>
Bugzilla Bug: [1131975](https://bugzilla.mozilla.org/show_bug.cgi?id=1131975)
=> Add validate-json command in client-shell

yarn.lock
=> Commit changes yarn wants to make to main

changelog/issue-2749.md, ui/package.json, ui/src/views/Hooks/ListHooks/index.jsx, ui/yarn.lock
=> issue2749 - change migrate to material-ui/treeview

changelog/issue4926.md, ui/docs/reference/workers/generic-worker/support-tiers.mdx, workers/generic-worker/build.sh
Bugzilla Bug: [1714200](https://bugzilla.mozilla.org/show_bug.cgi?id=1714200)
Github Bug/Issue: Fixes #4926
=> [Bug 1714200] add generic-worker-simple darwin arm64 build

changelog/IPK2S6uoRcy6XlExQJNvaQ.md, changelog/fnMGPBjuRFyDOTgSQUPDNw.md, changelog/issue-4947.md
Github Bug/Issue: Fixes https://github.com/taskcluster/taskcluster/issues/4947#issuecomment-908614772
=> dev-docs update

changelog/issue-4242.md, ui/src/components/HookForm/index.jsx, ui/src/components/IndexedEntry/index.jsx, ui/src/components/JsonDisplay/index.jsx, ui/src/components/TaskActionForm/index.jsx, ui/src/components/TaskDetailsCard/index.jsx, ui/src/components/WMErrorsTable/index.jsx, ui/src/views/PulseMessages/index.jsx, ui/src/views/Tasks/TaskDefinition/index.jsx
=> issue4242 - added the displayable json/yaml element

changelog/issue-4939.md, clients/client-web/README.md, dev-docs/dev-deployment.md, services/auth/README.md, services/built-in-workers/README.md, services/notify/README.md, services/object/README.md, services/purge-cache/README.md, services/queue/README.md, services/secrets/README.md, tools/worker-runner/worker/dockerworker/dockerworker.go, tools/worker-runner/worker/dummy/dummy.go, tools/worker-runner/worker/genericworker/genericworker.go, tools/worker-runner/worker/worker.go, ui/docs/manual/deploying/README.mdx, ui/docs/reference/workers/worker-runner/workers.mdx
Github Bug/Issue: Fixes #4939 
Fixed the three first points of the issue as asked.
=> Fix doc [#4939]

changelog/issue-4962.md, ui/src/components/RolesTable/index.jsx
=> [FIX] Style for RolesTable item link

changelog/issue-5011.md, tools/worker-runner/provider/static/static.go, tools/worker-runner/provider/static/static_test.go, tools/worker-runner/registration/registration.go, tools/worker-runner/registration/registration_test.go, tools/worker-runner/runner/run_test.go, ui/docs/reference/workers/worker-runner/providers.mdx
=> Give useful error messages for expired creds, cacheOverRestarts+static provider

changelog/issue-5106.md, clients/client-rust/client/src/client.rs, yarn.lock
Github Bug/Issue: #5016
This just adds debug info.  Assuming I can make this fail on the PR, I shouldn't need to merge this.
=> add debug info to client::tests::test_simple_request_with_perm_creds

changelog/issue-4614.md, clients/client-py/README.md, clients/client-py/release.sh, clients/client-py/setup.py, clients/client-py/taskcluster/aio/asyncclient.py, clients/client-py/taskcluster/aio/asyncutils.py, clients/client-py/taskcluster/aio/download.py, clients/client-py/taskcluster/aio/upload.py, clients/client-py/taskcluster/client.py, clients/client-py/taskcluster/download.py, clients/client-py/taskcluster/upload.py, clients/client-py/taskcluster/utils.py, clients/client-py/test/test_client.py, clients/client-py/test/test_imports.py, clients/client-py/tox.ini, taskcluster/ci/client/kind.yml, ui/docs/manual/using/api.mdx
Github Bug/Issue: Fixes #4614 
Always fun to delete some code :)
=> Drop support for Python-2.7 in the client.

.github/dependabot.yml, .github/workflows/dependabot-automerge.yml
* Change Dependabot schedule from `daily` to `monthly`
* Automerge semver-patch version upgrades via GitHub Actions Workflow (thanks @grahamalama!)
=> Additional Dependabot Config

changelog/issue-5153.md, clients/client-shell/cmds/signin/signin.go
=> For #5153 - Fix CLI Signin Success Page

changelog/UNcKF5bhS8y0TVOyCkRW-w.md, ui/.neutrinorc.js, ui/src/components/Dashboard/SidebarListItem.jsx, ui/src/components/DiffTextArea/index.jsx, ui/src/components/DocSearch/index.jsx, ui/src/components/Markdown/index.jsx, ui/src/components/MarkdownTextArea/MuiMarkdownTextArea.jsx, ui/src/components/MarkdownTextArea/index.jsx, ui/src/components/PageTitle/index.jsx, ui/src/components/Search/index.jsx, ui/src/components/SiteSpecific/index.jsx, ui/src/components/TaskRunsCard/index.jsx, ui/src/theme.js, ui/src/utils/constants.js, ui/src/views/Clients/ViewClient/index.jsx, ui/src/views/Documentation/components/Warning/index.jsx, ui/src/views/Tasks/TaskGroup/index.jsx, ui/test/e2e/cypress/integration/01-Login.js, ui/yarn.lock
Ran the e2e cypress tests locally with success as well!
```
➜  e2e git:(matt-boris/yarnUpgradeUI) yarn test
yarn run v1.22.10
$ cypress run
====================================================================================================
(Run Starting)
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Cypress:        9.4.1                                                                          │
│ Browser:        Electron 94 (headless)                                                         │
│ Node Version:   v16.14.0 (/Users/mboris/.nvm/versions/node/v16.14.0/bin/node)                  │
│ Specs:          1 found (01-Login.js)                                                          │
│ Experiments:    experimentalStudio=true …
```
=> yarn upgrade in ui

changelog/issue-4940.md, infrastructure/references/nginx.conf, libraries/app/src/index.js, ui/web-ui-nginx-site.conf
Github Bug/Issue: Fixes #4940.
Minor task to prepare for addressing #4597.
=> For #4940 - Set content type for heartbeat endpoints

changelog/YGDzBnEUR9-Hxl9SjnKx5g.md, go.mod, go.sum, internal/mocktc/auth.go, tools/websocktunnel/client/client_test.go, tools/websocktunnel/util/util.go, tools/websocktunnel/wsproxy/proxy.go, tools/websocktunnel/wsproxy/proxy_test.go
Github Bug/Issue: Fixes https://github.com/taskcluster/taskcluster/security/dependabot/19
I followed [this guide](https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md).
=> For dependabot alert 19

Dockerfile, changelog/issue-5193.md, taskcluster/ci/ui/kind.yml, ui/.neutrinorc.js, ui/yarn.lock
Inconsistent npm dependencies
Github Bug/Issue: Fixes #5193
=> Fix for #5193: incosistent UI deps

changelog/XFKHGROXRYuV2-oayfJfnQ.md, ui/jest.setup.js, ui/src/components/AuthConsent/index.test.jsx, ui/src/components/TaskDetailsCard/index.test.jsx
=> Set fixed date on testing to avoid snapshot changes

changelog/issue-5235.md, infrastructure/k8s/templates/ingress.yaml, services/web-server/procs.yml
For https://github.com/taskcluster/taskcluster/issues/5235.
=> Add web-server ingress for dockerflow endpoints

changelog/QzZL33Y1SZa5JUMZ5ZiVYQ.md, dev-docs/upgrading.md
This is just off the top of my head, improvements are likely needed and are welcome.
=> Add upgrade documentation

changelog/issue-5269.md, tools/worker-runner/registration/registration.go, tools/worker-runner/util/nonmonotonic.go, tools/worker-runner/util/nonmonotonic_test.go
Github Bug/Issue: Fixes #5269
See the issue -- I'm not sure this is worth fixing?
=> Renew worker creds on time, even after hibernation

changelog/issue-5277.md, ui/src/views/Hooks/ListHooks/__snapshots__/index.test.jsx.snap, ui/src/views/Hooks/ListHooks/index.jsx, ui/src/views/Hooks/ListHooks/index.test.jsx
"Cannot access property length of undefined" prevented real message from
being shown for unauthenticated users.
Fixes #5277
=> fix(ui): JS error blocked real error

.github/workflows/dependabot-automerge.yml, changelog/Cel8kZBTTZaPwE4y_wsBGg.md
Now using https://github.com/ahmadnassri/action-dependabot-auto-merge as previous code kept erroring out on enabling auto-merge.
=> Update dependabot auto merge gh action

changelog/issue-5003.md, services/worker-manager/src/provisioner.js, services/worker-manager/test/fakes/aws.js, services/worker-manager/test/fakes/azure.js, services/worker-manager/test/provisioner_test.js
Force provisioner loop to exit in case of timeouts
Github Bug/Issue: Fixes #5003
=> Worker-manager exit when timeouts lead to stuck process

changelog/issue-5217.md, services/github/src/constants.js, services/github/src/handlers.js, services/github/test/handler_test.js
Github checks UI link for logs https://github.com/taskcluster/taskcluster/issues/5217
=> feat(github): get to logs quicker through GitHub checks UI

changelog/MzfRpH7EQFibZok7N4WoMQ.md, workers/generic-worker/multiuser_windows_test.go, workers/generic-worker/testdata/mouse_and_screen_resolution.py
Attempt to fix current test failures in Windows Server 2012 R2 CI for generic-worker.
=> Fix broken tests on win2012r2 CI

changelog/N3fQy9ZuTx2jk0GOAJBiMA.md, generated/docs-table-of-contents.json, ui/docs/reference/core/worker-manager/exchanges.mdx
=> Document exchanges for worker-manager

changelog/VlOMXTv0QuuFshzoZGN7vQ.md, services/web-server/src/graphql/WorkerManager.graphql, services/web-server/test/fixtures/workerPool.graphql, services/web-server/test/fixtures/workerPools.graphql, services/web-server/test/graphql/workermanager_test.js, ui/src/views/WorkerManager/WMEditWorkerPool/workerPool.graphql, ui/src/views/WorkerManager/WMViewWorkerPools/WMWorkerPools.graphql
GraphQL was missing schema for the new columns returned by the API.
=> fix(graphql): update schema for new counts/capacities per state

changelog/DUJSNfxWTXSu82W0ff7zmA.md, ui/src/components/TaskDetailsCard/index.jsx
It was broken due to wrong object destructuring
=> Fix filtering of dependent tasks

changelog/issue-3163.md, generated/references.json, services/worker-manager/src/monitor.js, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure/index.js, services/worker-manager/src/providers/google.js, services/worker-manager/src/providers/provider.js, services/worker-manager/src/provisioner.js, services/worker-manager/test/provider_test.js, services/worker-manager/test/provisioner_test.js
* include total number of workers seen for a provider
* add duration for a single worker pool provisioning loop
Related to #3163
=> Worker manager extra stats

changelog/Ahqd3qjBRrWuwWcFKv4YeA.md, clients/client-go/tcqueue/types.go, generated/references.json, services/queue/schemas/v1/list-workers-response.yml, services/queue/schemas/v1/worker-response.yml, ui/src/views/Provisioners/ViewWorkers/workers.graphql
> Update `ViewWorkers` query to get `lastDateActive`. Update some schemas too.
Related to the work done in https://github.com/taskcluster/taskcluster/pull/5370 and https://github.com/taskcluster/taskcluster/pull/5365.
=> fix(graphql): update GraphQL query and schemas

changelog/OtK90DxYQVGckmpIOsv8ng.md, services/queue/src/api.js
=> fix(queue): Added null check for lastDateActive

changelog/issue-5348.md, changelog/issue-5362.md, changelog/issue-5373.md, ui/.neutrinorc.js, ui/README.md, ui/src/components/TaskRunsCard/index.jsx, ui/src/components/TaskRunsCard/index.test.jsx, ui/src/components/TaskRunsCard/sort.js, ui/src/components/TaskRunsCard/sort.test.js
* fix copy URL functionality for some artifacts (#5348)
* allow to run local UI against remote Taskcluster instance (#5373)
* put log files on top of the list (#5362)
Closes bugs: #5348 #5373 #5362
=> UI artifacts list improvements

changelog/bug-1613593.md, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure/index.js, services/worker-manager/src/providers/google.js
Bugzilla Bug: [1613593](https://bugzilla.mozilla.org/show_bug.cgi?id=1613593)
Include additional information when worker provision fails. Worker vm id and launch configuration should help to identify issues faster
=> Extra information about failed provisioning

changelog/issue-5393.md, generated/references.json, infrastructure/k8s/values.schema.json, services/queue/config.yml
Fixes https://github.com/taskcluster/taskcluster/issues/5393.
@Eijebong thanks for being our deployment tester and finding this!
=> fix(helm): make `worker_info_update_frequency` optional

changelog/issue-5336.md, ui/src/components/Log/__snapshots__/index.test.jsx.snap, ui/src/components/Log/index.jsx, ui/src/components/Log/index.test.jsx
Avoid scrolling to bottom when link contain line references
Fixes #5336
=> Fix log autoscroll behaviour

changelog/OkfSZygbTaqaS9_Q_jbYoQ.md, workers/generic-worker/build.sh
Build was broken because of incorrectly placed comment
=> Fix command

changelog/bug-1767244.md, clients/client-web/package.json, clients/client-web/yarn.lock, clients/client/package.json, clients/client/yarn.lock, package.json, yarn.lock
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1767244
=> build(deps): upgrade `hawk` to v9.0.1

changelog/issue-4999.md, package.json, services/worker-manager/src/main.js, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure/index.js, services/worker-manager/src/providers/cloudapi.js, services/worker-manager/src/providers/google.js, services/worker-manager/test/cloudapi_test.js, yarn.lock
Add timeout to all cloud api calls to avoid stuck processes.
Problem described in https://github.com/taskcluster/taskcluster/issues/4999#issuecomment-1118659890 
Github Issue:  #4999
=> feat(#4999): Worker manager cloud call timeout

changelog/issue-5179.md, clients/client-shell/cmds/group/actors.go, ui/src/components/ConnectionDataTable/index.jsx, ui/src/components/RolesTable/index.jsx, ui/src/components/SecretsTable/index.jsx
* Reduce number of elements rendered (almost 2x less)
Fixes #5179
=> Roles view improvements

changelog/issue-5361.md, ui/src/components/WMWorkerPoolEditor/index.jsx, ui/src/components/WorkersTable/index.jsx
Addresses #5361.
> Link Worker State Buttons on Worker Pool Details View to a filtered view of workers in that state.
=> feat(ui): link to filtered workers view

clients/client-web/package.json, clients/client-web/yarn.lock, clients/client/yarn.lock, package.json, yarn.lock
Combined multiple dependabot PRs with:
```
pmac add 5473 5472 5471 5470 5468 5466
```
=> build(deps): upgrade multiple dependabot dependencies (minors and patches)

changelog/issue-5506.md, services/github/src/api.js
=> Log debug information for incoming github webhooks

changelog/Y9UzMzbJTlWja1JxdGd7nQ.md, cloudbuild.yaml
> Added a `cloudbuild.yaml` file for the Google Cloud Build trigger on the `main` branch.
=> feat(build): add cloudbuild config for gcp trigger

changelog/bug-1633440.md, infrastructure/k8s/templates/taskcluster-github-cron-sync.yaml, infrastructure/k8s/templates/taskcluster-index-cron-expire.yaml, infrastructure/k8s/templates/taskcluster-object-cron-expire.yaml, infrastructure/k8s/templates/taskcluster-purge-cache-cron-expireCachePurges.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireArtifacts.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTask.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskDependency.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskGroups.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireWorkerInfo.yaml, infrastructure/k8s/templates/taskcluster-web-server-cron-scanner.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-cron-expire-worker-pools.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-cron-expire-workers.yaml, services/github/procs.yml, services/index/procs.yml, services/object/procs.yml, services/purge-cache/procs.yml, services/queue/procs.yml, services/web-server/procs.yml, services/worker-manager/procs.yml, ui/docs/manual/deploying/monitoring.mdx
Fixes bug [1633440](https://bugzilla.mozilla.org/show_bug.cgi?id=1633440)
=> chore(k8s): Spread cron times to avoid CPU spikes and increased db loads

.yarnrc, changelog/VXM5bBIdR9qXHR46xSl-eg.md, package.json, ui/package.json, workers/docker-worker/package.json, yarn.lock
Upgrades to latest version of stable `yarn`.
From v1.22.10 &#8594; v1.22.19.
I ran `yarn policies set-version` to download the latest stable release. `yarn` docs [here](https://classic.yarnpkg.com/en/docs/cli/policies/).
=> chore: upgrade to latest stable version of yarn

changelog/issue-5577.md, docker-compose.yml, infrastructure/tooling/src/generate/generators/docker-compose.js, ui/.neutrinorc.js, ui/docs/manual/deploying/ui.mdx, ui/src/utils/constants.js, ui/src/utils/validateTaskPayloadSchemas.js, ui/src/utils/validateTaskPayloadSchemas.test.js, ui/src/views/Tasks/CreateTask/index.jsx
* Docker compose provides correct defaults in task view.
* Adds functionality to validate task payload in UI.
* "Reset editor" takes currently selected schema in consideration and produces valid paylaod
Task schema validation is done on the UI only and with the help of the following schemas:
* [task schema](https://docs.taskcluster.net/docs/reference/platform/queue/task-schema)
* worker type, selected by user:
* [docker worker payload](https://docs.taskcluster.net/docs/reference/workers/docker-worker/payload)
* [generic worker simple posix](https://docs.taskcluster.net/docs/reference/workers/generic-worker/simple-posix-payload)
* [generic worker multiuser posix](https://docs.taskcluster.net/docs/reference/workers/generic-worker/multiuser-posix-payload)
* [generic worker multiuser …
=> Validate task payload before creation

infrastructure/docker-images/build-browser-test.sh, infrastructure/docker-images/build-ci-image.sh, infrastructure/docker-images/build-rabbit-test.sh, infrastructure/docker-images/build-worker-ci.sh, infrastructure/docker-images/push-all.sh, infrastructure/docker-images/worker-ci/Dockerfile, infrastructure/tooling/src/build/tasks/livelog.js, infrastructure/tooling/src/build/tasks/monoimage.js, infrastructure/tooling/src/build/tasks/release.js, infrastructure/tooling/src/build/tasks/taskcluster-proxy.js, infrastructure/tooling/src/build/tasks/websocktunnel.js
=> Issue 5560 - multiarch docker builds

package.json, ui/package.json, ui/yarn.lock, workers/docker-worker/package.json, workers/docker-worker/yarn.lock, yarn.lock
Upgrades multiple deps by combining multiple PRs using `pmac` tool:
```bash
pmac add 5631 5629 5627 5626 5622 5614 5609 5604
```
=> build(deps): multiple dependency upgrades, some security

changelog/issue-5616.md, generated/references.json, services/github/schemas/v1/taskcluster-github-config.v1.yml, services/github/src/handlers/job.js, services/github/src/handlers/policies.js, services/github/src/tc-yaml.js, services/github/test/data/configs/taskcluster.push_pull_release.v1.yml, services/github/test/data/yml/valid-yaml-v1.json, services/github/test/handler_test.js, services/github/test/tc-yaml_test.js, ui/docs/reference/integrations/github/taskcluster-yml-v1.mdx
This PR implements [RFC 175](https://github.com/taskcluster/taskcluster-rfcs/blob/main/rfcs/0175-restricted-pull-requests.md)
=> Create a new 'public_restricted' pullRequestPolicy

changelog/UXL6xkWaSLSxQ1DoRmMkVQ.md, services/github/src/utils.js, services/github/test/utils_test.js
Reduces the noise in then output
=> feat(github): Trim shell control sequences from logs sent to github

changelog/OhVD4bHyTqKfNaF5kZpgkg.md, clients/client-web/package.json, clients/client-web/yarn.lock, clients/client/yarn.lock, go.mod, go.sum, package.json, yarn.lock
> Upgrade many deps with the following command:
`pmac add 5692 5691 5690 5689 5688 5687`
This also addresses some of the recent high vulnerabilities found [here](https://github.com/taskcluster/taskcluster/security/dependabot).
=> build(deps): dep upgrades w/PMAC

changelog/issue-5737.md, ui/src/views/Tasks/TaskGroup/__snapshots__/index.test.jsx.snap, ui/src/views/Tasks/TaskGroup/index.jsx, ui/src/views/Tasks/TaskGroup/index.test.jsx
=> Persist task group filter in URL

changelog/issue-5737.md, ui/src/views/Tasks/TaskGroup/index.jsx
=> Improves props handling for search query for TaskGroup page

.taskcluster.yml, changelog/B2emgkP8TzGMfzssvqYEeA.md
Using https://github.com/mozilla-mobile/android-components/commit/6bd8e999946eca39d3925e41a8166da6ccdd6901 as a reference
=> Update base_ref evaluation

.gitignore
This appears to be created by tests..
=> ignore workers/generic-worker/downloads

changelog/issue-5779.md, services/github/src/handlers/status.js
=> fix(github): set default runId for gh handler

changelog/bug-1803745.md, generated/references.json, workers/docker-worker/config.yml, workers/generic-worker/artifacts.go, workers/generic-worker/generated_docker_darwin.go, workers/generic-worker/generated_docker_linux.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/schemas/docker_posix.yml, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml, workers/generic-worker/schemas/simple_posix.yml
Bugzilla Bug: [1803745](https://bugzilla.mozilla.org/show_bug.cgi?id=1803745)
=> Add ".deb" to the exclusion list for artifact compression

changelog/issue-5844.md, services/worker-manager/src/api.js
Required to debug some unknown workers that are trying to register unsuccessfully.  #5844
=> feat(w-m): Log extra information on failed worker registration

changelog/issue-5851.md, services/github/src/api.js
Adds extra handling for the 422 error and also uses standard error handling.
Throwing errors inside api handlers seems to be not catched by middlewares and results in timeouts
Fixes #5851
=> Better github service error reporting

changelog/issue-5844.md, services/worker-manager/src/api.js, services/worker-manager/src/util.js, services/worker-manager/test/util_test.js
Remove some undesired information from logs
=> Filter logged debug information for registerWorker calls

changelog/TSbcwXCARD-mfpMY3Dh3dw.md, clients/client-go/tcobject/tcobject.go, clients/client-py/taskcluster/generated/aio/object.py, clients/client-py/taskcluster/generated/object.py, clients/client-rust/client/src/generated/object.rs, clients/client-shell/apis/services.go, clients/client-web/src/clients/Object.js, clients/client/src/apis.js, generated/references.json, services/object/src/api.js, services/object/test/api_test.js
Documenting what we wondered about in today's community meeting.
=> Update docs regarding finishUpload and object hashes, +test

.github/dependabot.yml, changelog/Zt8zhtHVQFuTmpLvzaKb8A.md
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#rebase-strategy
=> chore: disable auto rebase on dependabot PRs

Dockerfile, changelog/BCfZcjB1Qr2Qk23eSC6q_A.md, package.json
=> Better handling of preinstall script inside docker

.dockerignore, changelog/O1OoXd6YRrqVeJ6MRr44gQ.md
It was added by accident in #5926
=> Add .git to .dockerignore

changelog/B7UU7b3fQqmg_fBqBuW_WQ.md, generated/references.json, workers/docker-worker/schemas/v1/payload.yml, workers/docker-worker/test/integration/invalid_payload_schema_test.js
Fixed the exit code statuses so they are now integer too.
=> Docker worker exit code statuses now integer

clients/client-rust/client/src/client.rs, clients/client-rust/client/src/credentials.rs, clients/client-rust/upload/src/lib.rs
=> Upgrade to base64 0.21.0

.taskcluster.yml, changelog/KZHMVHzFQpC7Wh5y7SEmaA.md
Suggested keeping this change separate from Pete's work https://github.com/taskcluster/taskcluster/pull/6066#discussion_r1107477154
=> bump taskgraph decision image

changelog/Dvjux1eIT3qKUYOG7a7Ntg.md, dev-docs/development-process.md
Provide up-to date instructions for hacking on the UI
=> Update local development instructions for the UI

changelog/bug-1590886.md, services/github/src/handlers/deprecatedStatus.js, services/github/src/handlers/index.js, services/github/test/handler_test.js
Fixes Bugzilla Bug: [1590886](https://bugzilla.mozilla.org/show_bug.cgi?id=1590886)
=> Statuses API set back status to pending when task was restarted

changelog/issue-6208.md
A follow up fix to the changelog from #6209.
=> Fix changelog

changelog/issue-6216.md, tools/livelog/build.sh, tools/taskcluster-proxy/build.sh, tools/taskcluster-proxy/dockerbuild.sh, tools/worker-runner/build.sh, tools/worker-runner/perms/perms_posix.go, tools/worker-runner/perms/perms_posix_test.go, tools/worker-runner/worker/genericworker/runmethod_posix.go
=> Freebsd updates

changelog/LDAqHZpTSGyBwOIamw2wDw.md, generated/references.json, workers/docker-worker/schemas/v1/payload.yml
Bringing up to date with d2g https://github.com/taskcluster/d2g/pull/15/files#diff-d590677e2076793b24dbf7179d592c57076c015df2fd3657b6b470299483ad2b
=> chore: add defaults to dw payload

changelog/XwAbQR8rTA-5_3VSbwwfFQ.md, generated/docs-search.json, generated/docs-table-of-contents.json, infrastructure/tooling/src/generate/generators/docs-tocs.js, ui/.neutrinorc.js, ui/docs/changelog.mdx, ui/package.json, ui/src/components/Dashboard/index.jsx, ui/src/utils/constants.js, ui/src/views/Documentation/Changelog/index.jsx, ui/yarn.lock
Adding changelog entry to the docs.
It is linked from the sidebar.
Includes filters 🎉
=> Add changelog viewer in documentation

changelog/CUeO1krWS2Kp8nPNMICphQ.md, ui/src/views/Documentation/Changelog/index.jsx
=> feat(ui): Slightly improved changelog titles

changelog/Wy4ufN5lT7KS8Db2OJoSAw.md, ui/src/components/Dashboard/index.jsx, ui/src/views/TcYamlDebug/index.jsx
=> Allow sharing debug tool with yaml url

changelog/S4_1HGPEQcmMeQiYUUqsGw.md, ui/src/views/TcYamlDebug/index.jsx, ui/src/views/TcYamlDebug/test-payload.js
=> Fix undefined in task counts

changelog/YDRepDPgQ5e2w0ncJOpvVA.md, services/github/src/utils.js
=> feat(github): Better ANSI escape code regexp

CHANGELOG.md
Points to correct issue number.
=> [skip ci] Update CHANGELOG.md

changelog/XhNs2JPLSV-vC2_s9xEe5g.md, workers/generic-worker/artifacts_test.go, workers/generic-worker/helper_test.go
Seeing if I can cause the HTTP 500 errors in Community too...
=> fix accept-encoding issues after gcp migration

changelog/aRbeyY13Rfm9GQkNDh2fzw.md, taskcluster/src/transforms/__init__.py
Pardon the branch name.. I was initially thinking I'd be able to easily edit the task priority of the gw decision task. I'll tackle this in a different PR.
=> chore: additional cleanup from PR #6339

changelog/fLlpV11uTfWanQyIWmIThA.md, go.mod, go.sum, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/dw_features_tests.yml, tools/d2g/d2gtest/testdata/testcases/no_artifacts_test.yml
Similar to how it was done in https://github.com/taskcluster/taskcluster/pull/6385, I've included it in `d2g` now as @petemoore suggested [here](https://github.com/taskcluster/taskcluster/pull/6385#issuecomment-1630356729).
=> fix: update d2g to retry on exit 125

changelog/I3HcVYPjTd2lQczy1fc-Fw.md, services/web-server/src/graphql/Hooks.graphql, services/web-server/src/resolvers/Hooks.js, ui/src/components/HooksListTable/index.jsx, ui/src/utils/prop-types.js, ui/src/views/Hooks/ListHooks/hooks.graphql, ui/src/views/Hooks/ListHooks/index.jsx
Last fire and task state are shown, as well as schedule/binding details
=> Refactor Hooks page do display extra info.

changelog/Hj8UAm3LSKClWjTXC0ojiQ.md, workers/generic-worker/build.sh, workers/generic-worker/gdm3/gdm3.go, workers/generic-worker/gdm3/gdm3_freebsd.go, workers/generic-worker/gdm3/gdm3_nonfreebsd.go, workers/generic-worker/gotestcover.sh, workers/generic-worker/helper_posix_test.go, workers/generic-worker/loopback_video_linux_test.go, workers/generic-worker/multiuser_posix.go, workers/generic-worker/runtime/runtime_darwin.go, workers/generic-worker/runtime/runtime_freebsd.go, workers/generic-worker/runtime/runtime_linux.go, workers/generic-worker/runtime/runtime_other.go, workers/generic-worker/testdata/run-after-user.sh
In the process of implementing osGroups for posix, I realised that we should either drop support for FreeBSD, or start testing it, like we test the other platforms.
I started by manually setting up a FreeBSD worker in AWS, and am iterating through fixing bugs in this PR. Eventually I hope to add a FreeBSD image set to community-tc-config (mozilla/community-tc-config#612).
=> Fix freebsd

changelog/issue-5961.md
Pretty trivial change log fix.
=> Touch up change log for issue #5961

changelog/issue-6442.md, clients/client-py/taskcluster/client.py
=> Python lint fixes

changelog/issue-6414.md, tools/websocktunnel/client/client_test.go
Fixes #6414
Introduced in 057a6db3781cd5057831b3fb7033a55528f45825.
=> Issue 6414: fix intermittent TestExponentialBackoffFailure

changelog/issue-6482.md, clients/client-go/tcqueue/types.go, clients/client-go/tcqueueevents/types.go, clients/client-go/tcworkermanager/types.go, generated/references.json, services/queue/schemas/v1/task-metadata.yml, services/queue/test/createtask_test.js, services/worker-manager/schemas/v1/task.yml
Follow-up PR to https://github.com/taskcluster/taskcluster/pull/6482.
=> Add test for git ssh source urls

changelog/issue-6269.md, generated/references.json, tools/d2g/genericworker/generated_types.go, workers/generic-worker/README.md, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/gwconfig/config.go, workers/generic-worker/helper_test.go, workers/generic-worker/main.go, workers/generic-worker/payload_test.go, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml, workers/generic-worker/schemas/simple_posix.yml, workers/generic-worker/usage.go
Some tinkering around #6269 to unblock https://github.com/mozilla/firefox-translations-training/issues/153
=> feat(g-w): Allow the maximum on the maxRunTime property to be configured

changelog/issue-6484.md, dev-docs/development-process.md, generated/references.json, tools/d2g/dockerworker/generated_types.go, tools/d2g/genericworker/generated_types.go, workers/docker-worker/schemas/v1/payload.yml, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml, workers/generic-worker/schemas/simple_posix.yml
=> Fix typos in documentation

.github/dependabot.yml, changelog/deeeqiWvSdW-Os-Mz0MWNA.md
Got this error: https://github.com/taskcluster/taskcluster/pull/6504/checks?check_run_id=16427616541
=> Fix dependabot config schema

changelog/eh3jyK_FSMWR2U7RIs-M8w.md, ui/docs/manual/deploying/github.mdx
thanks @Eijebong for pointing out
=> Add missing event from github documentation

changelog/issue-6516.md, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/indexeddockerimage.go
=> Issue 6516: Use first listed tag in indexed docker images

changelog/bqAgweRhRoic9ZgDd_OpTQ.md, generic-worker.Dockerfile, infrastructure/docker-images/worker-ci/Dockerfile, infrastructure/tooling/src/build/tasks/livelog.js, infrastructure/tooling/src/build/tasks/taskcluster-proxy.js, services/github/test/data/configs/taskcluster.branchlimited.v0.yml, services/github/test/data/configs/taskcluster.branchlimited.v1.yml, services/github/test/data/configs/taskcluster.exclude-error.yml, services/github/test/data/configs/taskcluster.exclude.yml, services/github/test/data/configs/taskcluster.non-github.v0.yml, services/github/test/data/configs/taskcluster.non-github.v1.yml, services/github/test/data/configs/taskcluster.pull_with_exclude.yml, services/github/test/data/configs/taskcluster.push_pull_release.v0.yml, services/github/test/data/configs/taskcluster.push_pull_release.v1.yml, services/github/test/data/configs/taskcluster.release_single.v0.yml, services/github/test/data/configs/taskcluster.release_single.v1.yml, services/github/test/data/configs/taskcluster.single.v0.yml, services/github/test/data/configs/taskcluster.single.v1.yml, services/github/test/data/configs/taskcluster.star.yml, services/github/test/data/configs/taskcluster.tag.branchlimited.v0.yml, services/github/test/data/configs/taskcluster.tag.branchlimited.v1.yml, services/github/test/data/configs/taskcluster.tag_single.v0.yml, services/github/test/data/configs/taskcluster.tag_single.v1.yml, services/web-server/README.md, taskcluster/ci/release/kind.yml, ui/docs/manual/tasks/README.mdx, workers/docker-worker/test/fixtures/create_images.js
>Updates ubuntu image versions to `jammy`.
=> chore: standardize ubuntu versions to jammy

changelog/issue-6564.md, docker-compose.yml, docker/nginx-ui-local-dev-only.conf, docker/nginx.conf, infrastructure/tooling/src/generate/generators/docker-compose.js
Removing startup dependency on `s3` proxy service running. 
Hiding CSP headers for local compose env
Fixes: #6564
=> Fixes local UI running issues

changelog/N5t-xXxxTHiPhF0OcPoYXA.md, clients/client/package.json, infrastructure/tooling/src/generate/generators/node-version.js
This file was not being updated and its node version requirement was extremely outdated.
=> build(deps): update `clients/client/package.json` node version on generate

changelog/issue-6471.md, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/dw_features_tests.yml, tools/d2g/d2gtest/testdata/testcases/no_artifacts_test.yml, tools/worker-runner/worker/genericworker/genericworker.go
Fixes #6471.
>Worker Runner now sets the `TASKCLUSTER_WORKER_LOCATION` variable for Generic Worker.
=> fix(worker-runner): set the `TASKCLUSTER_WORKER_LOCATION` variable for generic worker

changelog/issue-6592.md, generated/references.json, tools/d2g/genericworker/generated_types.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml, workers/generic-worker/schemas/simple_posix.yml
=> Issue 6592: Generic Worker requires unique items in osGroups array of task payload

changelog/issue-6590.md, workers/generic-worker/helper_posix_test.go, workers/generic-worker/os_groups_multiuser.go, workers/generic-worker/os_groups_multiuser_darwin.go, workers/generic-worker/os_groups_multiuser_freebsd.go, workers/generic-worker/os_groups_multiuser_linux.go, workers/generic-worker/os_groups_multiuser_posix.go
=> Generic Worker: fix osGroups feature on Linux

changelog/Ga_faejSSnGtrlSJyDrxQA.md, ui/src/components/IndexedEntry/index.jsx, ui/src/components/JsonDisplay/index.jsx, ui/src/components/TaskDetailsCard/__snapshots__/index.test.jsx.snap, ui/src/components/TaskDetailsCard/index.jsx, ui/src/views/Tasks/TaskDefinition/index.jsx
>UI: Task Definitions and Payloads now display in YAML by default for readability.
=> chore(ui): switch default payload view to yaml

changelog/issue-6644.md, generated/references.json, libraries/api/src/index.js, libraries/app/src/index.js, services/web-server/src/servers/createApp.js, services/web-server/test/server_test.js
And refactor `loadVersion` to be defined in single place
Fixes #6644
=> Fix version endpoint

changelog/aKKl-NuXSmykoGTGQsaQ9Q.md, services/hooks/test/api_test.js, services/web-server/src/graphql/Hooks.graphql, services/web-server/src/resolvers/Hooks.js, services/web-server/test/fixtures/createHook.graphql, services/web-server/test/fixtures/hook.graphql, services/web-server/test/fixtures/hookLastFires.graphql, services/web-server/test/fixtures/hooks.graphql, services/web-server/test/graphql/hooks_test.js, services/web-server/test/helper.js
Fixes: `Enum "HookTaskState" cannot represent value: "unknown"`
=>  Fix "unknown" graphql state error

changelog/bug-1859323.md, workers/generic-worker/helper_test.go, workers/generic-worker/main.go, workers/generic-worker/multiuser.go, workers/generic-worker/multiuser_posix.go, workers/generic-worker/multiuser_windows.go
Addresses [bug 1859323 comment 10](https://bugzilla.mozilla.org/show_bug.cgi?id=1859323#c10).
=> Bug 1859323: report full path of all "state" files in Generic Worker logs

changelog/issue-4998.md, clients/client-py/taskcluster/aio/asyncclient.py, clients/client-py/taskcluster/client.py, clients/client-py/test/test_client.py
=> fix(client-py): Don't raise exception on 300 status code

changelog/issue-6688.md, ui/src/components/HooksListTable/index.jsx
=> feat(ui): add last-fire-time to hooks list table

changelog/QFSA-q-2QOO9tK3TRJusbQ.md, tools/d2g/README.md, workers/generic-worker/payload_linux.go
=> Update d2g docs and link to d2g cli docs from generic-worker task logs

changelog/bug-1874568.md, services/web-server/src/login/clients/PersonAPI.js, services/web-server/src/login/strategies/mozilla-auth0.js, services/web-server/test/login_strategies_mozilla_auth0_test.js
After making pods run for longer than 24h issue with token expiry was uncovered. Auth0 returned token that would expire in 24h but due to the bug in code, check never considered those as expired (off by 1000 times error)
Bug #1874568
=> feat(web): Fixes auth0 token fetching

changelog/issue-6775.md, ui/src/views/Provisioners/ClaimedTasks/index.jsx, ui/src/views/Provisioners/PendingTasks/index.jsx
Components were missing to show errors
Fixes #6775
=> Show errors in Pending/Claimed pages

changelog/issue-6235.md, infrastructure/tooling/src/dev/aws.js, libraries/monitor/README.md, libraries/monitor/src/monitor.js, libraries/monitor/test/monitor_test.js, package.json, services/auth/src/aws.js, services/auth/test/s3_test.js, services/notify/package.json, services/notify/src/main.js, services/notify/src/notifier.js, services/notify/test/helper.js, services/object/src/backends/aws.js, services/object/test/backends/aws_test.js, services/object/test/backends/google_test.js, services/object/test/helper/geturl-download.js, services/object/test/helper/simple-download.js, services/queue/src/artifacts.js, services/queue/src/bucket.js, services/queue/src/utils.js, services/queue/test/artifact_test.js, services/queue/test/bucket_test.js, services/queue/test/expireartifacts_test.js, services/queue/test/helper.js, services/worker-manager/src/providers/aws.js, services/worker-manager/test/fakes/aws.js, services/worker-manager/test/fakes/fake.js, workers/docker-worker/src/monitor/monitor.js, yarn.lock
Fixes #6235.
>Migrates to aws sdk v3.
=> chore: migrate to aws sdk v3

changelog/CjMR4wenTIWgTSOILgroyQ.md, workers/generic-worker/README.md, workers/generic-worker/fileutil/fileutil.go, workers/generic-worker/main.go, workers/generic-worker/mounts.go, workers/generic-worker/mounts_multiuser.go, workers/generic-worker/mounts_multiuser_test.go, workers/generic-worker/mounts_simple.go, workers/generic-worker/mounts_simple_test.go, workers/generic-worker/mounts_test.go, workers/generic-worker/multiuser_test.go, workers/generic-worker/usage.go
>Generic Worker: adds `unarchive` subcommand to the `generic-worker` binary.
=> feat(generic-worker): add `unarchive` subcommand

changelog/issue-6789.md, workers/generic-worker/d2g_test.go, workers/generic-worker/main.go, workers/generic-worker/model.go, workers/generic-worker/taskcluster_proxy.go
Fixes #6789
This PR comprises two commits. The first adds a test, which should hopefully cause the CI to fail. The second provides a fix, which should hopefully cause the CI to pass!
=> Fix Issue 6789

changelog/Pi5gxBGyS0aajYrTXeQRCA.md, ui/docs/tutorial/hello-world.mdx, ui/src/components/TaskDetailsCard/__snapshots__/index.test.jsx.snap, ui/src/components/TaskDetailsCard/index.test.jsx, ui/src/components/TaskRunsCard/index.test.jsx, ui/src/utils/constants.js
Should reduce overall resource consumption. Defaults matter! 😆 
(not sure why there are several copies of the same text)
=> The Task Creator now defaults to a task that only takes 1 minute

changelog/issue-6793.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml
=> Issue #6793: d2g: upload artifacts after maxRunTime is exceeded

changelog/issue-6798.md, workers/generic-worker/chain_of_trust.go, workers/generic-worker/d2g_multiuser_test.go, workers/generic-worker/main.go, workers/generic-worker/model.go, workers/generic-worker/taskcluster_proxy.go
Fixes #6798
First commit is a test, which should fail, to demonstrate the issue.
Second commit is a fix, which should hopefully pass the CI!
=> Fix issue 6798

changelog/HFgbx-vLT5OFRAXhZMVkig.md, tools/worker-runner/perms/perms_windows.go
Should've been addressed in https://github.com/taskcluster/taskcluster/pull/6828.
=> fix(worker-runner): remove shadowing

changelog/issue-6852.md, tools/websocktunnel/client/client_test.go
=> Issue 6852 - increase max retry count in TestExponentialBackoffFailure

changelog/issue-6836-1.md, infrastructure/k8s/templates/taskcluster-web-server-deployment-web.yaml, infrastructure/tooling/src/smoketest/checks/ping.js, package.json, services/web-server/procs.yml, services/web-server/src/main.js, services/web-server/src/servers/createApp.js, ui/package.json, ui/yarn.lock, yarn.lock
=> Graphql additions

changelog/issue-6890.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/dw_features_tests.yml, tools/d2g/d2gtest/testdata/testcases/env_escaping_test.yml, tools/d2g/d2gtest/testdata/testcases/no_artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml
=> Issue 6890: D2G: pass --privileged to all generated podman run commands

changelog/D37mnxb6RxWBdf-48EcjAA.md, ui/docs/reference/workers/generic-worker/installing.mdx
Updated macOS installation documentation after a working session with @matt-boris
=> Updated macOS documentation

changelog/issue-5967.md, generated/references.json, workers/generic-worker/d2g_test.go, workers/generic-worker/generated_insecure_darwin.go, workers/generic-worker/generated_insecure_freebsd.go, workers/generic-worker/generated_insecure_linux.go, workers/generic-worker/schemas/insecure_posix.yml
>Allows Docker Worker payloads to be used on the `insecure` Generic Worker engine, translated by `d2g`.
=> feat(generic-worker): `insecure` engine accepts docker worker payloads

changelog/issue-7059.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml
=> D2G includes libvirtd osGroup for KVM enabled task payloads

changelog/issue-7082.md, go.mod, go.sum, tools/d2g/d2g.go, tools/d2g/d2gtest/d2g_test.go, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml, tools/d2g/dockerimageartifact.go, tools/d2g/dockerimagename.go, tools/d2g/indexeddockerimage.go, tools/d2g/nameddockerimage.go
Fixes #7082
Tested in https://community-tc.services.mozilla.com/tasks/aEp39hd-QYKzs1mFFwvRKQ
=> D2G: use docker (instead of podman) for privileged tasks

changelog/issue-7126.md, tools/d2g/d2g.go, tools/d2g/d2gtest/d2g_test.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/dw_features_tests.yml, tools/d2g/d2gtest/testdata/testcases/env_escaping_test.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml
=> Revert #6891 and #6929

changelog/YsqougpvRtqJssPfQgjSJA.md, generated/docs-table-of-contents.json, ui/docs/manual/task-execution/definitions.mdx
I probably got one or more things wrong here. All suggestions and improvements welcome.
=> Add brief definitions of task queue and worker terminology.

changelog/issue-7129.md, services/worker-manager/src/providers/provider.js, services/worker-manager/test/provider_test.js
=> feat(w-m): avoid sending duplicate email errors

changelog/BQAVL-5yRPG57g6uDkMmHw.md, workers/generic-worker/runtime/runtime_linux.go
=> Remove ineffective and inaccurate build constraint

changelog/issue-7218.md, workers/generic-worker/multiuser.go, workers/generic-worker/runtime/runtime_darwin.go, workers/generic-worker/runtime/runtime_other.go, workers/generic-worker/runtime/runtime_windows.go
=> Generic Worker waits for expected task user to login rather than any user

.github/workflows/browserslist.yml, .github/workflows/codeql.yml, .github/workflows/dependabot-automerge.yml, .github/workflows/staticcheck.yml, changelog/OICNZSrRQmaqUIZbU87IPA.md
As suggested in https://wiki.mozilla.org/GitHub/Repository_Security/GitHub_Workflows_%26_Actions#GitHub_Workflows_and_Actions.
=> fix(gha): secure gha workflows

changelog/issue-5669-2.md, services/github/src/handlers/status.js, services/github/src/handlers/utils.js
Fixes #5669 
Fix artifact url generation
Fix artifact fetch due to missing permission issues
Hide headers in checkrun for absent values
=> fix(github) Fix artifact fetch due to permission issue

changelog/issue-7255.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/dw_features_tests.yml, tools/d2g/d2gtest/testdata/testcases/env_escaping_test.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml, tools/d2g/d2gtest/testdata/testcases/no_artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml
=> D2G: pass --init to docker run / podman run command

changelog/WVz0_Zx1SLepFUpZ-ABhlQ.md, docker/generic-worker-config.json, generic-worker.Dockerfile, workers/entrypoint.sh, workers/generic-worker/host/host_insecure_posix.go, workers/generic-worker/host/host_multiuser_posix.go, workers/generic-worker/kc/kc.go, workers/generic-worker/multiuser_posix.go
=> Docker Compose: Use Generic Worker Multiuser Engine

changelog/issue-6923.md, clients/client-test/package.json, clients/client-test/yarn.lock, clients/client/package.json, clients/client/test/upload_download_test.js, clients/client/yarn.lock
Fixes #6923.
Opened because of this comment https://github.com/nock/nock/issues/2595#issuecomment-2391538222.
=> fix(tests): don't skip client tests due to nock issue

changelog/issue-7320.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml, workers/generic-worker/tcproxy/tcproxy.go
>Reverts PR #7324. Taskcluster Proxy will now only listen on 127.0.0.1.
=> Revert PR #7324

changelog/issue-3823.md, services/web-server/config.yml, services/web-server/src/main.js, services/web-server/src/servers/createSubscriptionServer.js, services/web-server/src/servers/credentials.js, services/web-server/src/servers/decryptToken.js, services/web-server/test/graphql/artifacts_graphql_test.js, services/web-server/test/graphql/tasks_graphql_test.js, services/web-server/test/helper.js, ui/docs/manual/deploying/anonymous-role.mdx, ui/src/App/index.jsx
=> Add authentication to websockets

changelog/issue-3823.md
Follow-up for the https://github.com/taskcluster/taskcluster/pull/7377
=> Update changelog entry to include new scope information

changelog/issue-4086.md, services/queue/src/artifacts.js
=> fix(queue): Add expiration check for artifacts

changelog/WaGaBzv_SRixwWYDRB9m0w.md, services/web-server/src/servers/createApp.js, services/web-server/test/graphql/validation_test.js, services/web-server/test/helper.js, services/web-server/test/server_test.js, services/web-server/test/third_party_test.js
`req.logout` was missing required callback argument
=> feat(web): Fix missing callback to req.logout

changelog/e4YfPtqLQjO6YOaZ5f53Zw.md, workers/generic-worker/runtime/runtime_linux.go
Minor cleanup:
* formatting fix (spaces -> tabs)
* added trailing `:` in sed find expression, to ensure username matches an _entire_ username entry in `/etc/subuid`
=> Follow on from #7428 (cleanup)

changelog/HhkHHCfgQrSneakt0ArgxQ.md, workers/generic-worker/d2g_test.go
https://github.com/taskcluster/community-tc-config/pull/901 will also be needed.
Uses tests from https://github.com/taskcluster/taskcluster/blob/main/workers/docker-worker/test/integration/device_link_test.js
=> chore: add d2g device generic worker tests

changelog/issue-7475.md, services/hooks/src/api.js, services/hooks/test/api_test.js, ui/docs/reference/core/hooks/firing-hooks.mdx
Bugzilla Bug: [1935142](https://bugzilla.mozilla.org/show_bug.cgi?id=1935142)
Github Issue: Fixes #7475
=> [Bug 1935142] Include URL query parameters in trigger hook API endpoints

changelog/RfmEwupoTIadTLHkRx46MA.md, clients/client-shell/cmds/d2g/d2g.go, tools/d2g/d2g.go, tools/d2g/d2gtest/d2g_test.go, tools/d2g/d2gtest/testdata/testcases/container_engine_test.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/dw_features_tests.yml, tools/d2g/d2gtest/testdata/testcases/env_escaping_test.yml, tools/d2g/d2gtest/testdata/testcases/no_artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml, workers/generic-worker/insecure.go, workers/generic-worker/interactive.go, workers/generic-worker/interactive/interactive.go, workers/generic-worker/interactive/interactive_test.go, workers/generic-worker/model.go, workers/generic-worker/multiuser_posix.go, workers/generic-worker/payload_linux.go
https://github.com/user-attachments/assets/6aef095a-8588-44c8-8810-2a9e82095dc7
=> Drop users in task containers when using d2g with the interactive feature

CHANGELOG.md, changelog/C2GjKFOUSrCbpHTozUToHA.md
=> Fix changelog PR link 5727 -> 7527

changelog/QXzmWD50R4-boaH7MpoUXg.md, clients/client-go/tcworkermanager/tcworkermanager.go, clients/client-go/tcworkermanager/types.go, clients/client-py/taskcluster/generated/aio/workermanager.py, clients/client-py/taskcluster/generated/workermanager.py, clients/client-rust/client/src/generated/workermanager.rs, clients/client-shell/apis/services.go, clients/client-web/src/clients/WorkerManager.js, clients/client/src/apis.js, generated/references.json, services/web-server/src/loaders/workerManager.js, services/web-server/test/helper.js, services/worker-manager/schemas/v1/worker-pool-full.yml, services/worker-manager/schemas/v1/worker-pool-list-stats.yml, services/worker-manager/src/api.js, services/worker-manager/src/data.js, services/worker-manager/test/api_test.js, ui/src/views/WorkerManager/WMViewWorkerPools/WMWorkerPools.graphql
Fixes UI showing 0 for worker pool stats
=> feat(w-m): Introduce separate stats endpoint for workers stats

changelog/issue-7427.md, workers/generic-worker/chain_of_trust.go, workers/generic-worker/feature.go, workers/generic-worker/fileutil/fileutil.go, workers/generic-worker/interactive.go, workers/generic-worker/livelog.go, workers/generic-worker/loopback_audio_linux.go, workers/generic-worker/loopback_video_linux.go, workers/generic-worker/main.go, workers/generic-worker/mounts.go, workers/generic-worker/os_groups.go, workers/generic-worker/rdp_windows.go, workers/generic-worker/run_task_as_current_user.go, workers/generic-worker/runasadministrator_windows.go, workers/generic-worker/taskcluster_proxy.go
The write to disk occurs after each task that uses the mounts feature.
Fixes #7427.
=> Routinely write file-caches.json and directory-caches.json to disk

changelog/O_T64JpoSey4NKOs6FVojg.md, workers/generic-worker/d2g_multiuser_test.go, workers/generic-worker/d2g_test.go, workers/generic-worker/helper_insecure_test.go, workers/generic-worker/helper_multiuser_test.go
Would've caught https://github.com/taskcluster/taskcluster/issues/7568 before it was released, but adding for additional coverage!
=> chore(tests): add tc-proxy d2g test with refreshing creds

changelog/issue-7603.md, ui/src/views/Provisioners/ClaimedTasks/index.jsx, ui/src/views/Provisioners/PendingTasks/index.jsx, ui/src/views/WorkerManager/WMLaunchConfigs/LaunchConfigDetails.jsx, ui/src/views/WorkerManager/WMLaunchConfigs/index.jsx, ui/src/views/WorkerManager/WMViewWorkers/index.jsx
Not all dates were shown in UTC
Fixes #7603
=> Fix date representation in UI 

changelog/A_K0AWj_S--QETrODMypFA.md, workers/generic-worker/artifacts/s3.go
Will help in giving additional insight for #7623.
cc @bhearsum
=> chore(generic-worker): add artifact upload worker logs

changelog/KcfaqDzQS-y4IfnQ5h8q_w.md, services/web-server/src/main.js, services/web-server/src/servers/createApp.js, services/web-server/test/server_test.js, ui/src/views/ThirdPartyLogin/index.jsx
Improves error handling and fixes some issues with 3rd party login
=> feat(ui): Fix third-party login issue, improve error handling

changelog/issue-7474.md, changelog/issue-7686.md, ui/src/components/SpeedDial/index.jsx, ui/src/utils/gqlToApi.js, ui/src/utils/gqlToApi.test.js
* feat(ui): Fix retrigger issue with undrescores in priority
* feat(ui): Fix hamburger menu closing too quickly
Fixes #7686 
Fixes #7474
=> Several UI fixes

changelog/WvoGodJdQDGuNxOQlEVn5w.md, changelog/issue-7707.md, generated/docs-search.json, generated/docs-table-of-contents.json, generated/references.json, infrastructure/k8s/templates/podmonitoring.yaml, infrastructure/k8s/values.schema.json, infrastructure/tooling/src/generate/generators/k8s.js, infrastructure/tooling/src/generate/generators/monitoring.js, infrastructure/tooling/templates/k8s/podmonitoring.yaml, libraries/monitor/src/monitormanager.js, libraries/monitor/src/plugins/prometheus.js, libraries/monitor/test/prometheus_test.js, services/queue/src/monitor.js, ui/docs/manual/deploying/monitoring.mdx, ui/docs/manual/design/metrics/README.mdx, ui/docs/reference/platform/queue/README.mdx, ui/docs/reference/platform/queue/metrics.mdx, ui/src/components/ReferenceLinks/index.jsx, ui/src/views/Documentation/Reference/Entry.jsx, ui/src/views/Documentation/Reference/MetricsReference.jsx
Typo in resource definition and updated changelog description
Adds documentation sections for metrics
Fixes: #7706
=> Fixes for prometheus deployment and documentation

changelog/issue-7771.md, ui/src/components/TaskGroupProgress/__snapshots__/index.test.jsx.snap, ui/src/components/TaskGroupProgress/index.jsx, ui/src/components/TaskGroupProgress/index.test.jsx
Fixes #7771 
I can't produce features faster than @Eijebong creates new issues 🤣
=> feat(ui): Fixes Task Group error introduced in fast-memoize refactoring

changelog/GQ8_LsDZTaWciea5--qlZw.md, tools/websocktunnel/util/util.go
Hit [this linting issue](https://github.com/taskcluster/taskcluster/runs/44240899798) while working on something unrelated.
=> Fix lint issue

changelog/issue-7356.md, workers/generic-worker/build.sh, workers/generic-worker/insecure.go, workers/generic-worker/insecure_darwin_test.go, workers/generic-worker/insecure_linux.go, workers/generic-worker/main.go, workers/generic-worker/mounts_feature.go, workers/generic-worker/multiuser.go, workers/generic-worker/multiuser_darwin.go, workers/generic-worker/multiuser_darwin_test.go, workers/generic-worker/multiuser_freebsd.go, workers/generic-worker/multiuser_linux.go, workers/generic-worker/multiuser_posix.go, workers/generic-worker/multiuser_windows.go, workers/generic-worker/plat_darwin_test.go, workers/generic-worker/process/multiuser_darwin.go, workers/generic-worker/process/multiuser_windows.go, workers/generic-worker/process/other.go, workers/generic-worker/process/posix.go, workers/generic-worker/process/process.go, workers/generic-worker/usage.go, workers/generic-worker/usage_insecure.go, workers/generic-worker/usage_multiuser_darwin.go, workers/generic-worker/usage_multiuser_freebsd.go, workers/generic-worker/usage_multiuser_linux.go, workers/generic-worker/usage_posix.go, workers/generic-worker/usage_windows.go
=> Generic Worker multiuser macOS: delegate process execution to launch agent

changelog/issue-6951.md, ui/src/components/SpeedDial/index.jsx, ui/src/views/Tasks/ViewTask/index.jsx
* Changes state management for Task View page to avoid using "stale" actions when task changes
* Update Speed Dial (menu) to close when navigating away 
Fixes #6951
=> UI: Fix state for task view page

changelog/YPJZgGYnTOqdbmuToi2ijg.md, ui/package.json, ui/src/components/Dashboard/DocsSidebarList.jsx, ui/src/components/DenylistTable/index.jsx, ui/src/components/TaskGroupProgress/index.jsx, ui/src/components/TaskGroupTable/index.jsx, ui/src/utils/task.js, ui/src/utils/titleCase.js, ui/src/utils/upperSnakeCase.js, ui/src/views/Documentation/Reference/Entry.jsx, ui/src/views/Documentation/index.jsx, ui/yarn.lock
Will be able to close https://github.com/taskcluster/taskcluster/pull/7189 after this lands.
=> chore: remove `lower-case` and `upper-case` deps

.gitignore, changelog/issue-7849.md, workers/generic-worker/d2g_feature.go, workers/generic-worker/garbagecollector.go, workers/generic-worker/helper_test.go
Fixes #7849.
>Generic Worker (D2G): caches loaded docker images.
=> feat(d2g): cache loaded docker images

changelog/IQ1LQIucR8a_7Tg1JTrmXA.md, cloudbuild.yaml
Used the following documentation https://cloud.google.com/sql/docs/sqlserver/connect-build
=> fix(cloudbuild): use private worker pool to access db 

changelog/bug-1990389.md, workers/generic-worker/d2g_feature.go
Bugzilla Bug: [1990389](https://bugzilla.mozilla.org/show_bug.cgi?id=1990389)
>D2G: add stderr logging if any docker commands fail within the task feature.
=> fix(d2g): add stderr logging in feature
