changelog/issue-4036.md, services/object/src/main.js
This had just been copy/pasted from another service.
Github Bug/Issue: Fixes #4036.
=> Remove check for azure-compatibility crypto config

generated/docs-search.json, services/object/src/middleware/cdn.js, services/object/src/middleware/index.js, services/object/test/api_test.js, services/object/test/helper/index.js, services/object/test/middleware/cdn_test.js, services/object/test/middleware_test.js, ui/docs/manual/deploying/object-service.mdx
This is *super* basic!  I can imagine we might eventually want to be able to "filter" more precisely.  Like, maybe we want to use a CDN for only some projects, or different object names on different projects.  Maybe we should find a way to generalize the backendMap functionality into a kind of filtering expression that could be used here, too.
I can also imagine that some CDNs might need something more complex than just "append the object name here".  Maybe we'll want some kind of regexp / replace functionality.
In any case, I think this is good for now but I'm happy to be told otherwise.
Github Bug/Issue: Fixes #3951
=> Add "cdn" middleware to the object service.

changelog/YpDp67kpSfKLguKjO-lQ-Q.md, clients/client-go/tcobject/types.go, generated/references.json, services/object/schemas/v1/download-method-simple.yml, services/object/src/middleware/test.js, services/object/test/api_test.js, services/object/test/middleware_test.js
The schema included a `details` object, which is not necessary for this
method and was not what the backends returned.
=> Fix schema for the simple download method

changelog/issue-4059.md, services/github/src/handlers.js, services/github/test/handler_test.js
Github Bug/Issue: Fixes #4059
This changes `requestArtifact` to use `buildSignedUrl` so that it works properly without the anonymous role and also fixes some of the error body being omitted.
=> Fix GitHub service producing errors without the anonymous role

changelog/UlUctg1LRiSo2wfHvffTMw.md, services/github/src/handlers.js
This makes the error messages related to the metadata artefacts for GitHub checks more specific and easier to track down.
=> Improve GitHub checks artifact error messages

package.json
I assume this will need further tweaking.  I'm not sure automerging will work with our current GitHub settings (in particular, I think renovate can't merge with pending reviews, so we may need to solve that).  And I'm not sure this is the right way to express this in renovate config anyway.  Hopefully the addition of `_comment` doesn't cause errors and helps understanding the intent.
Github Bug/Issue: Fixes #4011
=> enable auto-merge for top-level packages

changelog/issue-4074.md, package.json, services/github/src/github-auth.js, yarn.lock
Github Bug/Issue: Fixes #4074 and Fixes #4054 
Still going to test this in my dev but this is their recommended way of doing things now. In particular in [their README](https://github.com/octokit/auth-app.js#implementation-details) they say
> When creating a JSON Web Token, it sets the "issued at time" (iat) to 30s in the past as we have seen people running situations where the GitHub API claimed the iat would be in future. It turned out the clocks on the different machine were not in sync.
Which sounds a lot like what we're seeing here. I'm honestly surprised we got away with this for so long. We could fix it directly ourselves but I figure this is a nicer long-term fix.
=> Use github's own jwt auth stuff instead of ours

changelog/issue-4012.md, infrastructure/tooling/src/changelog/index.js, infrastructure/tooling/src/utils/git.js
Result:
---
▶ [patch] [#4059](https://github.com/taskcluster/taskcluster/issues/4059)
Fixed an issue fetching GitHub metadata when using a Taskcluster instance without the anonymous role.
This presented as unexpected 'Failed to get your artifact.' errors.
▶ [minor] [#4006](https://github.com/taskcluster/taskcluster/issues/4006)
The `takscluster-client-web` library is no longer installable from a `<script>` tag.
Instead, it should be incorporated into the build process of the consuming application, like any other library.
▶ [patch] 
Improved error messages related to fetching artifacts for GitHub checks.
▶ [patch] [#4061](https://github.com/taskcluster/taskcluster/issues/4061)
This version fixes an issue with the "actions" button not appearing for task groups.
▶ [patch] …
=> include renovate package updates in changelog

clients/client-web/package.json, clients/client-web/yarn.lock, ui/yarn.lock
Spotted this after a warning from `yarn`.
=> remove redundant hawk requirement in devDependencies

changelog/FuHmLyHZS--UbHLntDvDRw.md, clients/client-py/taskcluster/utils.py, clients/client-py/tox.ini, taskcluster/ci/client/kind.yml
This replaces `base64.encodestring` which was [deprecated in 3.1 and removed in 3.9](https://bugs.python.org/issue39351). This is the only change I had to make to run `tc-admin` with Python 3.9.
=> Use `base64.encodebytes` in Python 3.

changelog/BBFlJRFnRuyYVf-i9Ukg-g.md, infrastructure/tooling/src/changelog/index.js
CI runs use shallow clones, within which the latest release tag may not
be available, so generation of the renovate updates doesn't work.  We
don't need them in that context, so just skip it.  It's also distracting
in `yarn changelog:show`, so omitted there.
This showed up in #4109.
=> Omit renovate information from changelogs except in release

changelog/issue-3940.md, clients/client-go/tcobject/tcobject.go, clients/client-py/taskcluster/generated/aio/object.py, clients/client-py/taskcluster/generated/object.py, clients/client-shell/apis/services.go, clients/client-web/src/clients/Object.js, clients/client/src/apis.js, generated/references.json, services/object/src/api.js, services/object/src/backends/aws.js, services/object/src/backends/base.js, services/object/src/backends/test.js, services/object/src/middleware/base.js, services/object/src/middleware/cdn.js, services/object/src/middleware/index.js, services/object/src/middleware/test.js, services/object/test/api_test.js, services/object/test/helper/simple-download.js, services/object/test/middleware_test.js
Silent changelog just because this is an "unreleased" service. I can add a real one if that's not a good assumption.
Github Bug/Issue: Fixes #3940
=> Update object service enpoint names to be more descriptive

changelog/A4XwOeGIT8eVqiGOQP-yeQ.md, services/worker-manager/src/provisioner.js
I suspect this was introduced when refactoring a `providers.forEach(..)` into a `for` loop.  It caused an issue for me in my dev env.
=> continue to look at other worker pools after one has an invalid providerId

changelog/NOQU5PRYRqm7B93a5wiiPw.md, clients/client-web/README.md, clients/client-web/src/Client.js, clients/client-web/test/buildUrl_test.js
This is broken out from #4111.  I think this will need to land first and be released so that the `ui/` directory can require `taskcluster-client-web` from the package registry, rather than using the local copy.
=> support signing URLs synchronously when not using credentialAgent

changelog/issue-3739.md, ui/docs/manual/deploying/ui.mdx, ui/docs/manual/using/task-notifications.mdx, ui/docs/reference/core/notify/usage.mdx, ui/src/components/SiteSpecific/index.jsx
This should help users find the bots.
Note that the github bot is already adequately documented with SiteSpecific -- there's no need for users to know its github username.
Github Bug/Issue: Fixes #3739.
=> add site-specific details for notify

changelog/issue-3718.md, generated/docs-search.json, services/object/src/backends/aws.js, services/object/test/backends/google_test.js, services/object/test/helper/google.js, services/object/test/helper/index.js, ui/docs/manual/deploying/object-service.mdx, ui/docs/reference/platform/object/aws-backend.mdx
Github Bug/Issue: Fixes #3718 
I've successfully configured a GCS bucket and uploaded and downloaded objects to it using the AWS client.
I spent some time with @helfi92 trying to get tests to work but haven't yet been successful, so some guidance here would be helpful.
Just as when using a real AWS S3 backend with the object service, an access key ID and a secret access key are both needed. However, additionally, the endpoint URI is required as configuration, and needs to be set to `https://storage.googleapis.com`. More information is available at https://cloud.google.com/storage/docs/interoperability.
Under the `pmoore-dev` project of our gcloud account, I was able to create a bucket `pmoore-potatoes`, create an HMAC and service account, and configure my local s3 client to use them, and …
=> Add a GCS backend based on the AWS backend

changelog/issue-4125-1.md, services/worker-manager/src/api.js, services/worker-manager/test/api_test.js
This should make this field interpreted correctly. I hope to never multiply or divide a time
by 1000 again. This whole bit of w-m could use a re-work at some point.
Github Bug/Issue: Fixes #4125
=> Fix reregistrationTimeout

changelog/issue-3983.md, services/web-server/src/graphql/Tasks.graphql, services/web-server/src/resolvers/Tasks.js, ui/src/components/TaskDetailsCard/index.jsx, ui/src/utils/labels.js
This introduces a new DependentTask type that may have a null status and
metadata, and adjusts the UI to handle that case.
Github Bug/Issue: Fixes #3983
=> UI: Handle dependencies that have expired

changelog/issue-2721.md, tools/taskcluster-proxy/main.go, tools/taskcluster-proxy/routes.go, tools/taskcluster-proxy/routes_test.go
=> tc-proxy: avoid using ServeMux, as it mangles URLs

changelog/issue-2398.md, ui/docs/reference/core/hooks/README.mdx, ui/docs/reference/core/index/README.mdx, ui/docs/reference/core/notify/README.mdx, ui/docs/reference/core/purge-cache/README.mdx, ui/docs/reference/core/secrets/README.mdx, ui/docs/reference/core/web-server/README.mdx, ui/docs/reference/core/worker-manager/README.mdx, ui/docs/reference/integrations/github/README.mdx, ui/docs/reference/platform/auth/README.mdx, ui/docs/reference/platform/object/README.mdx, ui/docs/reference/platform/queue/README.mdx, ui/docs/reference/workers/built-in-workers/README.mdx, ui/src/components/ReferenceLinks/index.jsx
This should make the API specs, etc. a bit more discoverable.
Github Bug/Issue: Fixes #2398
=> Include a card with links to reference docs

changelog/issue-4209.md, package.json
We depend on upstream docker images that lag the official Node releases.
=> Wait 7 days before proposing node upgrades

changelog/issue-4239.md, ui/src/components/HookForm/index.jsx, ui/src/components/SecretForm/index.jsx, ui/src/components/TaskActionForm/index.jsx, ui/src/views/Quickstart/index.jsx, ui/src/views/Tasks/CreateTask/index.jsx, ui/src/views/Tasks/TaskGroup/index.jsx, ui/src/views/Tasks/ViewTask/index.jsx, ui/src/views/Tasks/submitTaskAction.js
🤦🏽 
I think Webpack didn't because safeLoad and safeDump are still *deifned*, they are just functions that throw an error.  Typescript would hopefully have caught this?
Github Bug/Issue: Fixes #4239
=> fix yaml.safe{Load,Dump} in ui

tools/taskcluster-proxy/dockerbuild.sh
This arch is no longer supported by Golang
=> Drop support for a darwin/386 taskcluster-proxy image

dev-docs/best-practices/changelog.md
For example, https://github.com/taskcluster/taskcluster/releases/tag/v40.0.0 should have had
> [MAJOR] #3578
> The queue service now uses taskQueueId internally instead of the pair provisionerId/workerType for tasks.
> This involves an online database migration that scans each row in the `queue_tasks` table and thus might take considerable time for a production deployment.  A well-equipped database can scan about 600 rows per second.
=> long migrations should be flagged as major

changelog/issue-3580.md, clients/client-go/tcqueue/types.go, clients/client-go/tcqueueevents/types.go, generated/references.json, services/queue/schemas/v1/create-task-request.yml, services/queue/schemas/v1/list-taskqueues-response.yml, services/queue/schemas/v1/list-workertypes-response.yml, services/queue/schemas/v1/pending-tasks-response.yml, services/queue/schemas/v1/task-status.yml, services/queue/schemas/v1/task.yml, services/queue/schemas/v1/taskqueue-response.yml, services/queue/schemas/v1/worker-response.yml, services/queue/schemas/v1/workertype-response.yml, services/queue/src/api.js, services/queue/src/data.js, services/queue/src/utils.js, services/queue/test/artifact_test.js, services/queue/test/canceltask_test.js, services/queue/test/claimtask_test.js, services/queue/test/createtask_test.js, services/queue/test/deadline_test.js, services/queue/test/dependency_test.js, services/queue/test/expiretask_test.js, services/queue/test/gettask_test.js, services/queue/test/querytasks_test.js, services/queue/test/reruntask_test.js, services/queue/test/resolvetask_test.js, services/queue/test/retry_test.js, services/queue/test/taskgroup_test.js
Github Bug/Issue: Fixes #3580
I'm not completely sure of all the places that taskQueueId should appear alongside the old identifiers.
I'm guessing that other than what I've done so far I should add it to task statuses as well?
=> Allow taskQueueId in task definitions

changelog/Q1047xsrS2KoRLzwSE5bkw.md, libraries/monitor/src/plugins/sentry.js, package.json, ui/package.json, ui/src/App/index.jsx, ui/yarn.lock, workers/docker-worker/package.json, workers/docker-worker/src/monitor/plugins/sentry.js, workers/docker-worker/yarn.lock, yarn.lock
This extends Dependabot PR #4282 to [explicitly disable](https://docs.sentry.io/platforms/javascript/configuration/releases/#release-health) the new [session tracking feature](https://docs.sentry.io/product/releases/health/). If desired, I can instead apply this commit to the original PR, now or when the expected minor release 6.0.2 is applied.
=> Sentry no session tracker

changelog/epN9o-WkS4a2zI9R9OxYbA.md, clients/client-go/tcqueue/types.go, clients/client-go/tcqueueevents/types.go, generated/references.json, services/queue/schemas/v1/artifact-created-message.yml, services/queue/schemas/v1/list-artifacts-response.yml, services/queue/schemas/v1/post-artifact-request.yml
This value is used by the UI to select an icon, and that purpose is just
fine.  But it is redundant to the content-type of the actual data in the
artifact, and it's important to be clear about which value is
authoritative.
I had previously marked this value as deprecated, but that's not quite right.
=> Doc that the artifact.contentType is informational

changelog/issue-4298.md, clients/client-rust/Cargo.toml, infrastructure/tooling/src/build/index.js, infrastructure/tooling/src/build/tasks/release.js, infrastructure/tooling/src/utils/crates.js, infrastructure/tooling/src/utils/index.js, taskcluster/ci/release/kind.yml, taskcluster/src/transforms/__init__.py
Github Bug/Issue: Fixes #4298
There's no good way to stage the upload part, unfortunately.  As-is, it does a dry run without building the crate, which amounts to not much more than exercising the JS code that calls `cargo publish`.
See https://docs.rs/taskcluster/40.0.3/taskcluster/ for the docs :)
=> Publish rust client

changelog/issue-4276.md, clients/client-go/tcworkermanager/tcworkermanager.go, clients/client-py/taskcluster/generated/aio/workermanager.py, clients/client-py/taskcluster/generated/workermanager.py, clients/client-rust/src/generated/workermanager.rs, clients/client-shell/apis/services.go, clients/client/src/apis.js, generated/references.json, services/worker-manager/docs/providers.md, services/worker-manager/src/api.js, services/worker-manager/src/main.js, services/worker-manager/src/providers/google.js, services/worker-manager/src/providers/index.js, services/worker-manager/src/providers/provider.js, services/worker-manager/src/providers/testing.js, services/worker-manager/src/provisioner.js, services/worker-manager/src/worker-scanner.js, services/worker-manager/test/provider_google_test.js, services/worker-manager/test/providers_test.js, services/worker-manager/test/provisioner_test.js
This allows the failure of one provider, or a provider backend such as a
cloud provider, from causing the entire process to fail a startup.
Github Bug/Issue: Fixes #4276
=> Track whether a provider is set up correctly

changelog/KAP_TpnwQEupodrRoTjqwA.md, workers/docker-worker/test/garbage_collection_test.js
This starts the 1-second timer *before* creating the container, so that
the timer will always measure more time than the container's expiration.
https://community-tc.services.mozilla.com/tasks/PuHyD99MQlG1dJZo3WshOw/runs/0/logs/public/logs/live.log
=> Fix timing for a docker-worker test

changelog/UweKfAv0Q6iDvhuDhosUlA.md, clients/client-go/tcobject/tcobject.go, clients/client-py/taskcluster/generated/aio/object.py, clients/client-py/taskcluster/generated/object.py, clients/client-rust/src/generated/object.rs, clients/client-shell/apis/services.go, clients/client-web/src/clients/Object.js, clients/client/src/apis.js, generated/references.json, services/object/src/api.js, services/object/src/backends/aws.js, services/object/src/backends/base.js, services/object/src/backends/test.js, services/object/src/middleware/base.js, services/object/src/middleware/index.js, services/object/src/middleware/test.js, services/object/test/api_test.js, services/object/test/helper/simple-download.js, services/object/test/middleware_test.js, ui/docs/reference/platform/object/download-methods.mdx
This name matches the `createUpload` method (#4334) a little better, and doesn't sound like a "get" method.
=> Rename object.fetchObjectMetadata to object.startDownload

changelog/AMi2KrwySg-5L-avlo0CXQ.md, services/web-server/README.md
This points devs to the existing development docs.
Plus a few other edits, removing other usually-unnecessary and
probably-not-helpful content.
=> Update docs on running web-server locally

changelog/WtoPEfpQR_eS8iaOo3pZRg.md, tools/worker-runner/cfg/workerconfig.go
This should silence a CodeQL warning that appeared out of nowhere today.
=> guard against integer overflow

changelog/issue-3789.md, services/purge-cache/src/api.js, services/purge-cache/test/purgecache_test.js
fixes #3789
@djmitche do you think this needs a changelog?
Also, does it look ok?
=> fix: allPurgeRequests returns a continuationToken when there's nothing left

changelog/issue-4340.md, workers/generic-worker/main.go
=> [generic-worker] Do not fail if tasks-resolved-count.txt is empty

changelog/issue-4388.md, clients/client-py/release.sh
I pushed a fixed 41.0.0 release to pypi manually.
Github Bug/Issue: Fixes #4388
=> include setuptools_rust for pypi cryptography project

changelog/issue-4274.md, clients/client-go/tcobject/types.go, generated/references.json, services/object/schemas/v1/create-upload-request.yml, services/object/schemas/v1/create-upload-response.yml, services/object/schemas/v1/upload-method-put-url.yml, services/object/src/backends/aws.js, services/object/test/backends/aws_test.js, services/object/test/backends/google_test.js, services/object/test/helper/data-inline-upload.js, services/object/test/helper/index.js, services/object/test/helper/put-url-upload.js, ui/docs/reference/platform/object/upload-methods.mdx
This is the bicycle of upload methods: not fast, but it will always
work.
Github Bug/Issue: Fixes #4274
=> Add a putUrl upload method, supported in AWS and Google

changelog/issue-4346.md, clients/client-rust/src/client.rs
This should help with the intermittency.
Github Bug/Issue: Fixes #4346
=> Increase ts_skew for client-rs test

changelog/issue-4417.md, clients/client-go/tchooks/types.go, generated/references.json, services/hooks/schemas/constants.yml, services/hooks/schemas/v1/task-status.yml, services/hooks/src/taskcreator.js, services/queue/schemas/v1/task-status.yml
A few other options turned out to be difficult or impossible:
* `$ref` between services' schemas aren't allowed (and changing this would be hard)
* Just copying `task-status.yml` from `services/queue` to `services/hooks` does not work since it uses `$ref` to pull in lots of other queue schemas
* Switching the `triggerHook` response body to just `{type: "object", additionalProperties: true, description: "This is the response from queue.createTask.."}` would change the Golang API incompatibly, requiring a major version bump and potentially doing more harm than a bugfix should.
* Setting `additionalProperties: true` but keeping all of the defined properties also changes the Golang API incompatibly (replacing the whole thing with `json.RawMessage`.
Github Bug/Issue: Fixes #4417
=> Allow projectId in hooks.triggerHook

changelog/Up1Pcx-6SdeGj-NOjCSVVw.md, libraries/validate/src/index.js, libraries/validate/test/validate_test.js, services/object/src/backends/aws.js, services/object/test/helper/data-inline-upload.js, services/object/test/helper/index.js, services/object/test/helper/put-url-upload.js
I discovered that the AWS backend's `putUrl` impl was returning data in the wrong format.  The fix is one-line, but this also adds some tests to avoid this in the future.
=> Check upload return values

package.json
Docker-worker requires taskcluster-client, and the UI requires
taskcluster-client-web.  In neither case can we make the build process
work correctly linking to those within the monorepo, so we import them
from the registry, and rely on renovate to bump them.  But, that bumping
doesn't need to happen on every minor version -- just major versions.
(refs #4433)
=> Disable minor and patch updates of the TC clients

changelog/issue-4444.md, clients/client-go/tcobject/types.go, generated/references.json, services/object/schemas/v1/upload-method-put-url.yml, services/object/src/backends/aws.js
If this header is omitted, AWS responds with a 501 error, which is not
very helpful.  Although some clients do automatically set this header,
not all do, so this commit chooses to err on the side of including a
possibly-duplicative header instead of omitting it.
Github Bug/Issue: Fixes #4444
=> Include 'Content-Length' in putUrl headers for AWS

changelog/NXTIXhw6RlSrbdRh-zDaGA.md, services/object/src/backends/aws.js, services/object/test/helper/data-inline-upload.js, services/object/test/helper/put-url-upload.js
The missing `await` meant that the schema verification wasn't actually verifying.
I have now checked that it actually fails when the value does not match the schema.  I had done so in the last PR as well, but before factoring out the `helper.assertSatisfiesSchema` function.
=> Fix the putUrl response body, where headers must be strings

changelog/SDee64D8SxCBdpFAoid7SQ.md, services/built-in-workers/src/TaskQueue.js, services/built-in-workers/src/main.js
I added this while debugging an issue that turned out to be something completely different, but this is still useful: with level=DEBUG, it means that this service will log things periodically, confirming it's alive.
=> Add some debug-level logging to built-in-workers

package.json
=> Add got to special imports because `link:` doesn't install it

changelog/YD2eFNQKSDyzU8ngS3vmng.md, taskcluster/ci/client/kind.yml, test/client-library-secrets.py
This adds credentials from a secret for all client-library tasks.  This will be necessary for the upload/download functionality.
=> read client-library secrets into env vars for all client-library tasks

changelog/issue-4502.md, services/github/src/tc-yaml.js, services/github/test/data/configs/taskcluster.external-dep.v1.yml, services/github/test/intree_test.js
Handle the case where .taskcluster.yml specifies a dependency on a task
not defined in that file.
Github Bug/Issue: Fixes #4502
=> Handle external dependencies in .taskcluster.yml

changelog/issue-3779.md, workers/generic-worker/simple_docker.go
Github Bug/Issue: Fixes #3779 
Note, in the code it looks as if the directory is created when it does not exist. I wonder if the failure to create the directory in #3779 was due to the user not having write permission for the parent folder?
=> Issue 3779 - generic-worker: reasonable default for simple and docker engines tasksDir

changelog/eVBfVTX-Rimj_U4C4Ik9SA.md, services/object/test/helper/index.js
This fixes a bug I introduced yesterday that caused failures in the condition where there are no AWS/GCP credentials available.
=> balance load.{save,restore} in obj-service tests

changelog/issue-4423.md, clients/client/README.md, clients/client/package.json, clients/client/src/client.js, clients/client/src/download.js, clients/client/src/index.js, clients/client/src/retry.js, clients/client/src/upload.js, clients/client/test/client_test.js, clients/client/test/creds_test.js, clients/client/test/helper.js, clients/client/test/retry_test.js, clients/client/test/upload_download_test.js, clients/client/yarn.lock, taskcluster/ci/client/kind.yml
This works against a "real" deployment (mine) but won't work against the current deployment, so left as a draft.
This API is good for now, but I can imagine cases where we will need more sophisticated support, such as for parallel uploads and downloads.  The `streamFactory` means that we can only read or write sequentially.  We can address that when we support such a thing!
Github Bug/Issue: Fixes #4423
=> [client-js] Add upload/download functionality

changelog/PMBzq5oKTVOV6usMDCeJ_g.md, clients/client-go/README.md, clients/client-go/codegenerator/model/model.go
Originated from https://github.com/taskcluster/taskcluster/pull/4493#discussion_r600833582
=> Move http://godoc.org links to https://pkg.go.dev and include version in path

changelog/issue-4561.md, services/github/src/handlers.js, services/github/test/handler_test.js
If the the repo has no `taskcluster.yml`, create a pseudo object for `defaultBranchYml` containing the necessary entries needed by the following collaborator checks. The Policy is set to `collaborators_quiet` since the issue comment created by `collaborators` does not reflect this case.
Bugzilla Bug: [1564512](https://bugzilla.mozilla.org/show_bug.cgi?id=1564512)
Github Bug/Issue: Fixes #3927
=> Bug 1564512 - service/github: Do not ignore if no .taskcluster.yml in default branch

changelog/issue-4610.md, services/object/src/backends/aws.js, ui/docs/reference/platform/object/upload-methods.mdx
There's room for some nuance here -- if this header *isn't* set, then a backend might support other content-encodings.  But, which?  For example, GCS only supports `gzip`.  Instead of trying to address that here, let's leave the `putUrl` method simple, and always require `identity`.  The more advanced, cloud-specific upload methods can be more specific.
Github Bug/Issue: Fixes #4610
=> Require content-encoding: identity for putUrl uploads.

changelog/CxWEWKD_Rx6GXxX-vqDtWQ.md, workers/generic-worker/gw-decision-task/tasks.yml
The single mac worker we have is by far the slowest worker, and its
slowness causes delays to merging PRs, especially Renovate PRs.  This
will cut its load by 50% and hopefully allow it to keep up.
=> Disable testing the simple engine on macos

changelog/bug-1701255.md, ui/docs/manual/deploying/workers.mdx
Bugzilla Bug: [1701255](https://bugzilla.mozilla.org/show_bug.cgi?id=1701255)
=> Add a warning about service accounts for gcp workers

.dockerignore, changelog/OfHN0QMdR1OlhOS81xevrA.md
This saves a good 7GB on my system!
=> Do not include Rust's build directory in Docker context

taskcluster/ci/docker-worker/kind.yml
..in docker-worker tests only
This is pretty silly, but should get us back to passing tests while AWS sorts itself out.
Github Bug/Issue: Refs #4673
=> Hard-code the CloudFront host to use for artifacts

changelog/issue-4691.md, workers/generic-worker/README.md, workers/generic-worker/gwconfig/config.go, workers/generic-worker/helper_test.go, workers/generic-worker/livelog.go, workers/generic-worker/main.go, workers/generic-worker/usage.go
Github Bug/Issue: Fixes #4691 
Not sure if it's appropriate to use a unit test for this. I've updated the existing ones to use the config field for setting the ports they use, so in some means it is tested.
If this isn't appropriate, give me a shout. :smile:
=> Allow generic-worker livelog ports to be configured

changelog/issue-4646.md, libraries/pulse/src/publisher.js
We came across this in #4631, and I think that's not the first time I've been left puzzling about this.  It's really the only reason that a process would *hang* on startup and not crash.  I think this bit of logging should at least make that hang visible.
Github Bug/Issue: Fixes #4646
=> Log rather noisily when pulse blocks startup

ui/yarn.lock
Fixes a dependabot alert (-- one that's not especially critical).
=> Upgrade an old, indirect highlight.js dep

changelog/Re2MUtpfTGqwz0sZgbkqHg.md, clients/client-py/README.md
I found this, which looks like a mistake, while having a quick look at the python client docs (as I was having a look at maybe working on #4698).
=> Fix function names in client-py's readme

changelog/issue-3948.md, package.json, services/object/src/api.js, services/object/src/backends/aws.js, services/object/src/backends/base.js, services/object/test/backends/aws_test.js, services/object/test/backends/google_test.js, services/object/test/helper/put-url-upload.js, ui/docs/manual/deploying/object-service.mdx, yarn.lock
This automatically tags objects with the ProjectId, and allows deployers to add other custom tags on a per-backend basis.
Github Bug/Issue: Fixes #3948
=> Support tagging S3 objects

changelog/issue-4623.md, clients/client-go/tcobject/upload.go
I can't reproduce this error, so for the moment we'll make all upload operations behave the same way and not retry on 400's.
Github Bug/Issue: Fixes #4623
=> remove special-case in go for retrying 400s on upload

changelog/issue-4698.md, clients/client-py/taskcluster/aio/asyncutils.py, clients/client-py/taskcluster/aio/download.py, clients/client-py/taskcluster/aio/upload.py, clients/client-py/taskcluster/download.py, clients/client-py/taskcluster/upload.py, clients/client-py/test/aio/test_upload_download.py, clients/client-py/test/aio/test_upload_download_real.py, clients/client-py/test/test_upload_download.py, clients/client-py/test/test_upload_download_real.py
Github Bug/Issue: Fixes #4698 
I've started by doing the upload part; I'm hoping to get feedback of whether this looks right, as doing the download part is almost the same.
This would probably benefit from more thorough tests to be confident that it does what it has to.
=> Call the async versions of upload and download from their sync versions in python client

changelog/issue-4744.md, services/worker-manager/src/providers/azure.js, services/worker-manager/test/provider_azure_test.js
Microsoft has changed the content-type of the cert to
`application/x-x509-ca-cert`, and superagent (contrary to its docs)
buffers that as text, decoding with utf-8 and replacing lots of bytes
with U+BFBD, irrecoverably scrambling the binary content.  Got, as is
its habit, just does the right thing.
Github Bug/Issue: Fixes #4744
=> Switch from superagent to got for fetching certs

changelog/b8nrp5qFTiqJqIE6Rkd8CA.md, infrastructure/k8s/values.yaml, services/object/procs.yml
I missed this in #4746.  It's not marked major because it won't actually cause anything that's already working to fail -- it will just create a new k8s deployment that fails.
=> Default k8s replicas for the object service to 1

package.json
This change causes renovate to match any path containing package.json
and enable automerge.  We had previously wanted to avoid this, since
`ui/` and `workers/docker-worker` are poorly tested, but in practice
we're merging those anyway.  And in fact, the build process for `ui/`
ends up catching most issues with things like Babel, so tihs has done
quite well.
This should further reduce the team's required toill.
=> Automerge in all package.json's

changelog/issue-4807.md, libraries/monitor/src/monitor.js, libraries/monitor/test/monitor_test.js, package.json, yarn.lock
This avoids issues with errors that have helpful details like an HTTP
request attached.  In practice, most error logging contains only
top-level strings, so this should not be a problem.
Github Bug/Issue: Fixes #4807
=> Serialize errors for logging more succinctly

changelog/bug-1711921.md, workers/docker-worker/src/features/artifacts.js
Bugzilla Bug: [1711921](https://bugzilla.mozilla.org/show_bug.cgi?id=1711921)
=> Bug 1711921 - remove superfluous `/` in docker-worker artifact names

changelog/issue-4890.md, clients/client-rust/client/src/client.rs, clients/client-rust/integration_tests/tests/against_real_deployment.rs
=> send content-length: 0 for empty-bodied requests

changelog/bug-1711612.md, services/queue/src/artifacts.js, services/queue/test/artifact_test.js
The existing `ok = ok && ..` was completely bogus.  When in doubt,
factor into a function and test it within an inch of its life.
Github Bug/Issue: Fixes #1711612
=> Bug 1711612 - fix queue.createArtifact's idempotency

changelog/issue-4889.md, clients/client-rust/client/src/credentials.rs
This is useful since API methods often pass credentials around.
Github Bug/Issue: Fixes #4889
=> Support serializing / deserializing creds in rust client

changelog/issue-4934.md, infrastructure/tooling/src/dev/rabbit.js
When running ``yarn dev:init``, place the RabbitMQ admin management origin (like ``https://rabbitmq.hostname.com``) at the key ``meta.rabbitAdminManagementOrigin``, rather than at the root key ``rabbitAdminManagementOrigin``. This avoids a schema validation failure when later running ``yarn dev:apply``.
If a user has already run ``yarn dev:init`` successfully, then they will need to manually update ``dev-config.yml``.
Fixes #4934, at least for future devs.
=> Move RabbitMQ management URL in dev-config.yml

changelog/bNGK5OD7RqyIBnEpkgeamA.md, infrastructure/tooling/src/dev/postgres.js
When running `yarn dev:init`, drop any existing postgres user accounts before (re-)creating them.
=> Recreate postgres users in `yarn dev:init`

changelog/issue-4946.md, ui/src/views/Hooks/ListHooks/index.jsx
Github Bug/Issue: Fixes #4946 
Follow-on work from PR #4921, which switched to the built-in material-ui/treeview, but always detected that there were no hook defined. 
Screenshot of /hooks page with this PR, against community-tc API:
=> Fix check for "no hooks defined" on /hooks

changelog/issue-4944.md, clients/client-py/taskcluster/aio/asyncclient.py
This appears to be a copy of this line [1] from the synchronous python
`client.py`. However, in that file, `retry` is an integer tracking which
attempt number we're on [2].
In the `asyncclient`, `retry` is a function [3], and does not format
into a %d. We likely didn't catch this because python logging doesn't
format % strings format % strings unless the log level includes the log
message to output. Because this is in a `log.debug` call and we probably
don't run with debug logging enabled, we haven't caught this issue.
We can rename `retry`, or import it under a different name, or track the
attempt under a different variable name and log that. Removing the
logging line seemed like the most expedient fix.
[1] https://github.com/taskcluster/taskcluster/blob/797867c78082986e0814639b505c5b00eb …
=> [client-py] remove asyncclient retry debug log

changelog/BfpJ0vR7SNOFBAEU37elaw.md
The release for 44.2.0 failed when uploading the monoimage. Adding a note for the changelog.
=> Add note for 44.2.1

changelog/aaOoe-xeS9WD-D1jdIwv2A.md, ui/docs/manual/deploying/README.mdx
Saw this when responding in https://bugzilla.mozilla.org/show_bug.cgi?id=1724628#c8
=> Fix two broken links in docs

changelog/Gu3PcueMRSizrNAjNxE--g.md, infrastructure/tooling/src/generate/generators/monitoring.js, ui/docs/manual/deploying/monitoring.mdx
* Display the generated monitoring hints table, rather than comment it out
* Fix a typo
This is the first commit from #4941 (thanks @imbstack!)
=> Fix monitoring hints table

.all-contributorsrc, changelog/Ff23bT42QaGQD-Q8LoF5nA.md
Assuming I'm not entirely incompetent, this should add @leplatrem as staff and change @imbstack and @djmitche to staff alumni...
=> Fix "People of Taskcluster page"

changelog/bug-1635730.md, workers/generic-worker/runtime/runtime_darwin.go
Bugzilla Bug: [1635730](https://bugzilla.mozilla.org/show_bug.cgi?id=1635730)
Note, this should be tested on a real macOS worker. It may be that the root user won't have permission to do this cleanup, so the code won't fail if the delete fails, it will simply report the failure.
=> Bug 1635730 - clean up /private/var/folders on macOS multiuser

changelog/issue-4999.md, generated/references.json, services/worker-manager/src/monitor.js, services/worker-manager/src/providers/azure/index.js
Add ``workerPoolId``, ``providerId``, and ``workerId`` to ``registration-error-warning`` context, logged from the Azure provider's ``register()`` function in worker-manager.
Add ``workerState`` to the warning context when the ``state`` is not ``REQUESTED``, to help diagnose registration with an unexpected state.
Github Bug/Issue: #4999 (helps diagnose, doesn't yet fix)
=> Expand Azure register warning context

changelog/issue-5021.md, clients/client-py/taskcluster/helper.py
As discussed on the matrix `taskcluster` channel we should also be able to send bytes.
Closes #5022
=> [client-py] for `upload_artifact` let `contet` be `bytes` or `str`.

changelog/AJArSGy7RO--XMAKDZoduQ.md, clients/client-rust/Cargo.lock
This is an immediate fix to the broken state that `yarn release` left the repo in. Issue #5028 separately needs to be fixed to prevent this happening in future releases too, but this PR does not fix that.
=> Fix rust client version number (caused by #5028)

changelog/bRGHs0kbQ5ijt2Sec0Mr_A.md, workers/docker-worker/release.sh
Release 44.3.0 failed due to an issue with the docker image node:14.17.5.
This is a workaround for that issue, until it has been resolved upstream.
See the [failed release task](https://community-tc.services.mozilla.com/tasks/bVGir4inRTiglqpaIN0lPA/runs/0/logs/public/logs/live.log#L904) (around line 904).
=> Temp fix - use curl `--insecure` with docker image node:14.17.5

infrastructure/tooling/src/release/tasks.js
Github Bug/Issue: Fixes #5028
This substitutes the version numbers in Cargo.lock, as well,  And it updates taskcluster-integration-tests, even though that's not published, just for consistently.
=> update TC versions in Cargo.lock, too

changelog/JteOOaxXQCGmRHxCcOTSjw.md, ui/src/views/Tasks/ViewTask/pageArtifacts.graphql
11769844ce2b0cd66b3c2fe8a62192a376160da0 changed the call to this query
to `artifactsConnection` instead of `connection` but didn't change this
query accordingly.
Github Bug/Issue: Fixes #5045
=> Fix artifacts pagination

.taskcluster.yml, changelog/issue-5070.md, taskcluster/src/job.py, taskcluster/src/loader/__init__.py, taskcluster/src/target_tasks.py, taskcluster/src/transforms/__init__.py
Use the latest version of the [taskgraph code](https://hg.mozilla.org/ci/taskgraph) and the [mozillareleases/taskgraph images](https://hub.docker.com/r/mozillareleases/taskgraph/tags):
* taskgraph cb3ae27 - commited 2022-01-19
* mozillareleases/taskgraph e035c4bb - pushed 2021-07-19
Additionally:
* Specify pip3 to ensure the Python 3 version runs.
* Update `taskcluster/src` to Python 3
Fixes #5070
=> Bump taskgraph code and image

changelog/XxH2bNQ-TcuEpA4qOxk07w.md, ui/src/views/Quickstart/index.jsx
* Visit https://community-tc.services.mozilla.com/quickstart
* Select/De-select any of the checkbox options show
* Observe label becomes nearly unreadable due to styling change
* Label does not change style anymore when checkboxes are clicked
=> Fix styling of label on GitHub Quickstart Page

changelog/bdp4Ifc0SGe81snujuhMrQ.md, ui/package.json, ui/yarn.lock, workers/docker-worker/package.json, workers/docker-worker/test/integration/interactive_test.js, workers/docker-worker/yarn.lock
Update `docker-exec-websocket-client` and `docker-exec-websocket-server`. These should work under Node v14, and are required for Node v16. They fix an issue when the `docker exec` command is reading and writing data
to the container.
This is part of PR #5095. The tests are failing under Node 16.13.2, and I'm curious if they also fail under the current Node 14.17.5.
=> Update to docker-exec-websocket-* 3.0.0

changelog/AXUb6drpSAu7hthCd0Lumw.md, clients/client-web/yarn.lock, clients/client/yarn.lock, ui/yarn.lock, workers/docker-worker/yarn.lock, yarn.lock
It appears some package upgrades were only changed in the `package.json` file and not also updated in the `yarn.lock` file, which is what's used by dependabot for scanning. I ran `yarn upgrade` on all of our `yarn.lock` files aside from the one in the `/ui` directory (will handle in another PR due to breaking changes).
This should help us clean up some open dependabot alerts.
=> Run yarn upgrade

Dockerfile, changelog/bC1vCkgnREWrPpkpqu-dgA.md, infrastructure/references/nginx.conf, infrastructure/references/references.sh, ui/web-ui-nginx-site.conf
Updated nginx user config location due to node LTS upgrade changing paths from `/etc/nginx/conf.d/default.conf` to `/etc/nginx/http.d/default.conf`.
Also, added `__heartbeat__` config back to `nginx.conf` to continue to serve 200s until work in https://github.com/taskcluster/taskcluster/issues/4597 is complete.
Previous image (`node:14.17.5-alpine`) used alpine v3.11.11, while new image (`node:16.14.0-alpine`) uses alpine v3.15.0.
In [alpine v3.14.0](https://alpinelinux.org/posts/Alpine-3.14.0-released.html), you'll see this changelog:
> NGINX package changed the default directory for the vhost configs from /etc/nginx/conf.d to /etc/nginx/http.d
More info [here](https://gitlab.alpinelinux.org/alpine/aports/-/commit/383ba9c0a200ed1f4b11d7db74207526ad90bbe3).
=> Update nginx config path

changelog/SVPvge_iRTORSeHNGxP0Cw.md, ui/src/components/TaskDetailsCard/index.test.jsx
There's an `X days ago` in there that would break all the time
otherwise.
=> Fix UI tests by mocking the date in the TaskDetailsCard snapshot test

changelog/issue-5027.md, ui/src/components/SecretsTable/index.jsx
=> Make the whole row clickable in the secrets table

changelog/issue-5181.md, ui/.neutrinorc.js, ui/src/components/ClientsTable/index.jsx, ui/src/components/ConnectionDataTable/index.jsx, ui/src/components/RolesTable/index.jsx, ui/src/components/SecretsTable/index.jsx, ui/src/components/TaskDetailsCard/index.jsx, ui/src/components/TaskRunsCard/index.jsx, ui/src/components/WMWorkerPoolsTable/index.jsx
Resolves #5181
There's a performance issue with the tables itself, which makes filtering slower. Will be addressed in #5179
=> Add Copy URL  button for artifacts, rows filtering in tables

changelog/issue-5247.md, ui/src/components/ConnectionDataTable/index.jsx
Pagination not shown when table doesn't have next and previous pages.
Filter is shown when there are more than 10 items in a table.
Fixes #5247 #5246
=> fix(ui): Pagination and filters shown conditionally

.pre-commit-config.yaml, README.md, changelog/Or0UB2kBRAOKTG4-toN6zw.md
Also, skip the `taskcluster_yml` hook on ci because it appears outgoing traffic is blocked and it cannot reach the schema to do validations.
=> Add pre-commit badge

CHANGELOG.md, changelog/ScVIcRDORtCC1NdlPyhsQQ.md, infrastructure/tooling/src/changelog/index.js
https://github.com/taskcluster/taskcluster/commit/09391656a8e448071121b9226318903c22807315 fails pre-commit ci checks because of whitespace created in the changelog. This removes that from happening again.
=> Fix changelog generation to not include whitespace

changelog/FmCD7dK1QHu5JV-IfSdRBw.md, workers/docker-worker/src/upload_to_s3.js
That function called was not an `async` one so awaiting had no effect.
If anyone used that function and was unlucky, they would end up with an
empty tmp file instead of one containing the string.
=> Fix usage of `temporary.writeFile` in docker worker

changelog/issue-4999.md, generated/references.json, services/worker-manager/src/monitor.js, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure/index.js, services/worker-manager/src/providers/google.js
Required to debug #4999 where worker is being terminated before/during
it is being started.
=> feat(worker-manager): Azure provider logs extra information

changelog/cjZPYS4KS96R3Fqpupq6Lg.md, clients/client/package.json, clients/client/yarn.lock, package.json, ui/package.json, ui/yarn.lock, workers/docker-worker/package.json, workers/docker-worker/yarn.lock, yarn.lock
> Upgrade to latest `mocha` version to address https://github.com/taskcluster/taskcluster/security/dependabot/70, https://github.com/taskcluster/taskcluster/security/dependabot/71, and https://github.com/taskcluster/taskcluster/security/dependabot/72.
=> security(deps): upgrade `mocha` for security vulns

changelog/issue-5282.md, ui/src/auth/UserSession.js, ui/src/auth/UserSession.test.js, ui/src/utils/base64.js, ui/src/utils/base64.test.js
Using Github as oauth provider encodes user profile using base64 encoding,
which, if contains unicode characters, is not decoded properly by `atob()`.
Fixes Bug #5282
=> feat(auth): Proper handling of unicode in profile

changelog/D7QydcVbRfKTuGMWyaWo5A.md, clients/client-web/yarn.lock, ui/test/e2e/yarn.lock, ui/yarn.lock, yarn.lock
> Upgrade to latest `minimist` version to address https://github.com/taskcluster/taskcluster/security/dependabot/73.
=> security(deps): upgrade `minimist` for high vuln

changelog/issue-4987.md, services/worker-manager/src/providers/azure/index.js, services/worker-manager/test/fakes/schemas/azure-nic.yml, services/worker-manager/test/provider_azure_test.js
Azure cannot launch VM without attached network interface. Public IP should be still optional.
Unless it's needed for RDP
=> Azure provision NIC always

changelog/issue-4366-1.md, services/web-server/src/graphql/Workers.graphql, ui/src/components/WorkersTable/index.jsx
Addresses UI part of #4366.
note: as more and more columns are added to this table, I feel like the UX is worse and worse, as horizontal scrolling is then needed. We may need to address this as more columns will be added from https://github.com/taskcluster/taskcluster/issues/3060.
=> feat(ui): show last active in queue workers view

changelog/PDAjqa-dSv69kv9lf36SvA.md, infrastructure/tooling/src/build/tasks/client-shell.js, taskcluster/ci/release/kind.yml
> `go get` no longer builds or installs packages in module-aware mode, so replacing with `go install`.
I tested this using `yarn staging-release` https://github.com/taskcluster/staging-releases/runs/6131472369
=> fix(release): use `go install` with go1.18

changelog/issue-5364.md, services/github/src/api.js, services/github/test/api_test.js
The `/repository/<owner>/<repo>/<branch>/latest` endpoint relies on the
Github `statuses` API to retrieve the link to the task group of a
commit. But for some reason most repositories I've tested, seem to
return an empty list of statuses for this API, rending the latest
endpoint useless. Practically speaking, this means the badge links for
most projects are busted.
This PR tweaks the endpoint to use the Github `checks` API to build the URL
instead. Unfortunately this API does not contain the task group id
anywhere, so linking to the task group is not possible. Instead, this
links to the run id of the check in question.
Fixes #5364
=> fix(github): use checks API to fulfill latest endpoint

changelog/issue-4999.md, services/worker-manager/README.md, services/worker-manager/src/providers/azure/index.js, services/worker-manager/test/provider_azure_test.js
Further improve worker manager Azure provisioning. 
Till now, Azure was the only provider that was not actually doing any cloud api calls in the `provisioner` loop, and only created worker record in `REQUESTED` state, that was later picked by `workerScannerAzure`.
This sometimes can take 10-20 minutes, and, considering overall provisioning slowness, it often ends with worker being terminated, as they fail to start within given time (`terminateAfter`) (Leading to errors seen in #4999)
Related to #4999
=> feat(worker-manager): Immediate worker provisioning for Azure

changelog/issue-5395.md, services/github/src/api.js, services/github/test/api_test.js
I had implemented this endpoint under the assumption that the
`findTCChecks` function was calling Github's `check-suites` API, when in
fact it was using the `check-runs` API.
Since check-runs points to individual tasks, I grab the run with the
smallest id, which should correlate to the Decision task. Even if it
doesn't, it's not a big deal as all tasks are easily accessible on the
side.
Fixes #5395
=> Fix the `latest` endpoint in the Github service when using checks

changelog/V0_EcwTuQ9WhJwllOcK9xg.md, infrastructure/tooling/src/release/tasks.js, workers/generic-worker/build.cmd, workers/generic-worker/build.sh, workers/generic-worker/main.go, workers/generic-worker/main_test.go
Some minor cleanup in generic-worker (mostly related to migration of project into monorepo).
=> Some further cleanup from generic-worker move to monorepo

.gitignore, changelog/cS1OSo2wRuSyqtrFaM7V-w.md, taskcluster/ci/docker-worker/kind.yml, taskcluster/ci/lint/kind.yml, taskcluster/src/transforms/__init__.py, taskcluster/test/params/main-repo-pull-request.yml, taskcluster/test/params/main-repo-push.yml
> `docker-worker-chunk-{1,2,3,4,5}` tasks would non-deterministically fail during releases due to them depending on the `release-publish` task passing successfully before they run. This will be fixed by setting a dependency on `release-publish` in the `docker-worker-chunk-{1,2,3,4,5}` tasks. For now, on releases, two task groups are created, making it impossible to define a dependency on `release-publish` in the `docker-worker-chunk-{1,2,3,4,5}` tasks. Once we combine the two task groups to one, on release, this dependency can be set to fix the issue.
=> fix(release): prepare `docker-worker-chunk` for `release-publish` dependency

changelog/f6AHYFu-T2WrY1g4RYvvaA.md, services/queue/src/data.js
> Add null check to `lastDateActive` in queue workers serialize() func.
Got this sentry issue when releasing to FxCI: https://sentry.prod.mozaws.net/operations/taskcluster-firefox-ci/issues/19477419/
=> fix(queue): add null check to `lastDateActive` in queue workers `serialize()` func

changelog/issue-4366.md, services/web-server/src/graphql/Workers.graphql, ui/src/components/WorkerDetailsCard/index.jsx, ui/src/views/Provisioners/ViewWorker/worker.graphql
Related to https://github.com/taskcluster/taskcluster/issues/4366
Added last date active to the worker detail view as well - https://firefox-ci-tc.services.mozilla.com/provisioners/gecko-t/worker-types/win10-64-2004/workers/centralus/vm-a0k3byryqdmvkezxamergb0rdop81rzwkrt.
=> feat(ui): display last date active in the worker detail view

changelog/issue-2776.md, ui/src/components/WorkerTable/index.jsx
Addresses https://github.com/taskcluster/taskcluster/issues/2776.
> Show worker tasks from most recent to least recent. Also, link the `taskId` field to the task page.
=> feat(ui): improvements to provisioners ViewWorker

changelog/issue-5433.md, ui/src/components/ConnectionDataTable/index.jsx, ui/src/components/DataTable/index.jsx, ui/src/components/WorkersTable/index.jsx
Addresses https://github.com/taskcluster/taskcluster/issues/5433.
> Show workers from last recently active. Also, removed the deprecated prop `onChangePage` and replaced with `onPageChange`.
=> feat(ui): improvements to provisioners ViewWorkers

changelog/issue-3490.md, services/worker-manager/src/providers/azure/index.js, services/worker-manager/test/provider_azure_test.js
Simplify azure `scanCleanup` method, only check pools with errors, instead of iterating through all and doing extra db call for each worker pool.
Closes #3490
=> Iterate only pools with errors

changelog/issue-5459.md, infrastructure/tooling/src/utils/command.js, infrastructure/tooling/src/utils/docker.js
Addresses https://github.com/taskcluster/taskcluster/issues/5459.
> Add exponential backoff retries to the `dockerPush` function to help alleviate intermittent failures in the `release-publish` task.
=> feat(release): add exponential backoff retries to `dockerPush` function used in `release-publish` task

changelog/WEXGTNjNQYaDFU7YuJjiDQ.md, clients/client-go/tcworkermanager/types.go, generated/references.json, services/worker-manager/schemas/v1/list-workers-response.yml, services/worker-manager/schemas/v1/worker-response.yml
Fixes this error:
```
"Output schema validation error: 
Schema Validation Failed!
Rejecting Schema: https://stage.taskcluster.nonprod.cloudops.mozgcp.net/schemas/worker-manager/v1/list-workers-response.json#
Errors:
* data/workers/0 should have required property 'state'
* data/workers/0 should have required property 'capacity'
* data/workers/0 should have required property 'providerId'"
```
> Fix output schema validation error when calling `workerManager.listWorkers()` and `workerManager.getWorker()` methods by not requiring additional worker manager fields.
=> fix(schema): don't require additional wm fields

changelog/DDq2rs66QBeeC0BvCTZZ8g.md, services/web-server/src/graphql/Workers.graphql
> Fix `GRAPHQL_VALIDATION_FAILED` error on ViewWorker query.
```
{
"errors": [
{
"message": "Cannot query field \"workerPoolId\" on type \"Worker\". Did you mean \"workerId\" or \"workerGroup\"?",
"locations": [{ "line": 16, "column": 5 }],
"extensions": { "code": "GRAPHQL_VALIDATION_FAILED" }
}
]
}
```
=> fix(graphql): add `workerPoolId` field to `Worker`

changelog/DJkOOynvQVSVLNN5jOj3xg.md, clients/client-go/tcworkermanager/types.go, generated/references.json, services/web-server/src/graphql/Workers.graphql, services/worker-manager/schemas/v1/list-workers-response.yml, services/worker-manager/schemas/v1/worker-full.yml, services/worker-manager/schemas/v1/worker-response.yml, services/worker-manager/src/api.js, services/worker-manager/src/data.js, ui/src/utils/labels.js, ui/src/views/Provisioners/ViewWorker/worker.graphql, ui/src/views/Provisioners/ViewWorkers/workers.graphql
Addresses PR comments from @petemoore on #5491.
> Don't allow additional properties in `worker-response.yml` schema. Updated descriptions in `worker-response.yml` and `list-workers-response.yml` schemas to explain some default values that may occur in the case where the queue knows about the worker, but worker manager does not. Also, updated the GraphQL queries to extract additional needed data.
=> fix(schema, graphql): use explicit values when a worker is not known by worker manager, add better descriptions, update graphql queries

changelog/PayJ3gOCRH-_zaEHb7QOtw.md, services/web-server/src/loaders/workers.js
> Fix this error (`Function listWorkers takes options: continuationToken, limit, quarantined, workerState but was given isQuarantined`) while filtering workers based on quaratine status.
=> fix(ui): filter by quarantine status param fix

changelog/Ot8d0idDQ5-8wEglwamz_g.md, clients/client-go/tcworkermanager/types.go, generated/references.json, services/web-server/src/graphql/Workers.graphql, services/worker-manager/schemas/v1/list-workers-response.yml, services/worker-manager/schemas/v1/worker-response.yml, services/worker-manager/src/api.js, services/worker-manager/src/data.js, ui/src/utils/labels.js
> This fixes the default worker state of a worker not known by worker manager to be `standalone` as opposed to `unmanaged` to be consistent with the rest of the project. This issue was first brought up in v44.16.0
Thanks @djmitche for pointing this out to us!
=> fix: use `standalone` over `unmanaged`

changelog/VbwHlWIoRiSpUjyjwY025g.md, services/worker-manager/src/provisioner.js
> This patch adds a new field to be logged out on a failed provision call. This field will be used to measure the provisioning failed count.
=> feat(logs): make provision failed log searchable

changelog/OTS0C0L3Sumu_0ZiHkKDLg.md, ui/src/components/WorkersTable/index.jsx
Left a tiny chunk of unreachable code in https://github.com/taskcluster/taskcluster/pull/5505. This removes it. It's not needed anymore because a terminate button is not even visible due to the `enableTerminate()` check. https://github.com/taskcluster/taskcluster/blob/eaa8a1c8672b27bc60a1c46e558bae1efbafa7fb/ui/src/components/WorkersTable/index.jsx#L329
=> chore: clean up unreachable code

changelog/issue-5503.md, services/github/src/handlers/index.js, services/github/src/handlers/rerun.js, services/github/test/handler_test.js
Fixes #5503
To be able to use `re-run` events, github project must be set up properly.
Github handler will assume `repo:github.com:/$org/$repo:pull-request` role when calling `queue.rerunTask()`
This means this role needs to be defined, and it should include necessary scopes to make that call:  
https://github.com/taskcluster/taskcluster/blob/cc0c17e2601075ad328ae5d2af2ce2edcf71d266/services/queue/src/api.js#L761-L767
=> Add missing rerun scope for github handler.

changelog/WFqYtmKPQfuMVMkhEKU9ug.md, services/worker-manager/src/api.js, services/worker-manager/src/data.js, services/worker-manager/test/api_test.js
> This patch returns up the `quarantineUntil` field in the `workerManager.getWorker` and `workerManager.listWorkers` methods. This issue was first noticed in v44.15.0.
=> fix: always return `quarantineUntil` field in worker manager X queue methods

changelog/issue-5319.md, libraries/api/src/middleware/logging.js, libraries/iterate/src/index.js, libraries/monitor/src/monitor.js, libraries/monitor/src/timekeeper.js, services/auth/test/scoperesolver_test.js, workers/docker-worker/src/features/artifacts.js, workers/docker-worker/src/monitor/monitor.js, workers/docker-worker/src/monitor/timekeeper.js
Addresses https://github.com/taskcluster/taskcluster/issues/5319.
> This patch migrates the legacy, `process.hrtime([time])` to the new, `process.hrtime.bigint()`.
See [Node Docs](https://nodejs.org/docs/latest-v16.x/api/process.html#processhrtimetime) for more information.
=> fix: migrate to `process.hrtime.bigint()`

changelog/issue-5391.md, services/github/src/handlers/status.js, services/github/src/handlers/taskDefined.js, services/github/test/handler_test.js
Skip github checks if github build is unkown.
This happens in periodic and manual hooks that are doing some periodic operations on github repo.
Those operations are not initiated by github, so there is no new build/check suite created for those events.
Fixes #5391
=> feat(github): Avoid TypeErrors for cron tasks

.gitignore, changelog/RL_V3EpeSC-YafwwUKM7HA.md
If I've understood correctly from [here](https://github.com/taskcluster/taskcluster/blob/main/dev-docs/development-process.md#development-and-debugging-using-docker-compose), we should never commit a `docker-compose-override.yml` file to the repository, so this should help avoid that we do. I believe this filename is fixed (or at least the default), so that it is unlikely you would override settings with a filename of a different name. If that isn't the case, maybe this PR isn't useful and we can close it.
Thanks!
=> Add docker-compose-override.yml to .gitignore

changelog/ZKSl9L0dQMKI1pu5VUaMlQ.md, ui/src/components/SignInDialog/CredentialsDialog.jsx
It doesn't much sense to have what is essentially a password be
displayed in plain text.
This also makes it so a password manager would recognize the form as a
login form and is able to automatically fill it.
=> Change the access token input to be a password field

changelog/HItnC6sATOGBZnB41eiffw.md, clients/client-go/tchooks/types.go, generated/references.json, services/hooks/schemas/v1/create-hook-request.yml, services/hooks/schemas/v1/hook-definition.yml, ui/docs/reference/core/hooks/firing-hooks.mdx, ui/docs/reference/core/notify/usage.mdx, ui/src/components/HookForm/index.jsx
The previous link is dead and following the repo trail brings us here
https://github.com/json-e/json-e with documentation at
https://json-e.js.org/
=> Change references to taskcluster.github.io for JSON-e documentation

changelog/TY9RHwsbTDC4afWvLixzoQ.md, docker/nginx.conf, infrastructure/tooling/src/generate/generators/docker-compose.js
The issue here is that `proxy_pass http://something` will always try to
resolves `something` as soon as nginx starts. By using an intermediate
variable, we force nginx to resolve it later at runtime [1].
Because the `github-web` container exits without any extra config, it
would becomes unresolvable DNS wise and prevent nginx from starting.
Same with other containers if they took too long to start up.
1: https://forum.nginx.org/read.php?2,215830,215832#msg-215832
=> Fix docker compose sometimes not starting up the ingress container

changelog/issue-5553.md, cloudbuild.yaml, dev-docs/dev-deployment.md, infrastructure/tooling/src/generate/generators/node-version.js
Fixes #5553.
> This change adds continuous deployment support to the `cloudbuild.yaml` file so that each change to `main` results in a new deployment to [`https://dev.alpha.taskcluster-dev.net/`](https://dev.alpha.taskcluster-dev.net/).
=> feat(cd): use cloudbuild for CD to a dev env

changelog/csJB1kjqSw6D0SDWxeSrWg.md, clients/client-shell/README.md
This PR adds homebrew installation instructions to the docs for the `taskcluster` cli.
[Rendered view](https://github.com/taskcluster/taskcluster/blob/79cce9987c4e4326a1337cd6a8c23c3c87fb0b91/clients/client-shell/README.md#taskcluster-client-for-shell)
=> chore(docs): add brew installation docs

changelog/W83WYfXqReGqudzT57c-zg.md, cloudbuild.yaml
Cloudbuild improvements:
* using #5613 ingress nginx support to replace hardcoded ingress.yml
* Adding intermediate deployment image for faster deployments - will be built first time and then reused in later builds.
* Switching to higher CPU machines for faster builds (suggested by google cloud)
=> Remove hardcoded ingress, use latest ingress nginx support.

changelog/QYv_97qTRVO61yND4sGtqQ.md, infrastructure/k8s/templates/ingress.yaml, infrastructure/tooling/src/generate/generators/k8s.js, services/web-server/procs.yml
Google load balancer uses Url Maps, and having wildcard in path is mandatory to match all sub-paths.
Default k8s ingress and nginx-ingress do not use wildcard in paths, so it should be removed.
Tested on dev
=> Remove duplicate ingress paths

changelog/a3HEtQUpR8egkMA6HkXf3Q.md, cloudbuild.yaml
> This patch makes it so that a `yarn smoketest` on our dev environment is run after a successful deploy.
=> feat(cd): run `yarn smoketest` after deploy to dev

changelog/Xs1ReEpFQ0qsbwZfapWt6Q.md, changelog/f0LQ1YkwQNGEq8F6z1UuJg.md, changelog/issue-5046.md, docker-compose.yml, infrastructure/tooling/src/generate/generators/docker-compose.js, services/web-server/src/graphql/Tasks.graphql, services/web-server/src/resolvers/Tasks.js, ui/.neutrinorc.js, ui/src/components/PulseBindings/index.jsx, ui/src/utils/constants.js, ui/src/utils/exchangesList.js, ui/src/utils/exchangesList.test.js, ui/src/views/PulseMessages/index.jsx, ui/src/views/Tasks/ViewTask/index.jsx, ui/src/views/Tasks/ViewTask/taskSubscription.graphql
* UI: Task page: subscribe to task real-time updates to display latest status and run information
* UI: Task page: automatically show latest run after triggering "Rerun" 
* Docker compose: only run `standalone` generic worker on start, `static` can be run with `COMPOSE_PROFILES=workers`
* UI: Pulse messages: autocomplete known exchanges + submit on enter
This should help quickly subscribe to known exchanges without thinking  long for the correct format of the exchange name. It only fetches exchange names of the taskcluster services
Github Bug/Issue: Fixes #5046
=> UI: reload task on updates, show recent run on rerun

changelog/E4bduEqrT_yEseRzgmPIYw.md, cloudbuild.yaml
Problem with using ":latest" is that deployment configuration doesn't change, so the pods are not being restarted
=> cloudbuild: Use commit SHA instead of latest to trigger redeployment

.all-contributorsrc, changelog/issue-5295.md, ui/src/components/TaskGroupTable/index.jsx
Fix incomplete background colour change when hovering over a row at the group task page.
Issue was causing the background colour to change only for half the row when hovering over a row at the group task page, which was causing confusion  for users with wider screens as to what row is being hovered. 
Github Bug/Issue: Fixes #5295
=> Fix hover bug

changelog/issue-5653.md, services/github/src/handlers/status.js, services/github/src/handlers/taskDefined.js
Since 44.19.1 release github service started tracking additional task state changes, and this resulted in a race condition between "taskDefined" and "status" handlers where both of them would create new check run at the same time. Wrong check run would later get all status updates, while Github UI will be showing a different check run which didn't receive all the updates.
Fixes #5653 
Description of the issue:
task status handler was doing roughly this:
1. get `checkRun` from db
2. do several calls to queue to fetch several artifacts (this may take couple of seconds!)
3. create new `checkRun` if it didn't exist yet
And in the same time `taskDefined` would be creating initial check run when task was initially defined.
So depending on luck and network latency there might be several …
=> Fix github checks updates

changelog/issue-5217.md, services/github/src/constants.js, services/github/src/handlers/status.js, services/github/test/handler_test.js
Addresses #5217.
> This patch gets a tail of the last 250 lines of the `live.log` file and provides it in the GitHub checks view without having to visit the Taskcluster UI.
=> feat(github): provide log tail in gh checks ui

changelog/fo9GU7tCSi6RnqqWH_GHqQ.md, cloudbuild.yaml
This PR makes it so that old GCP CloudBuild images are cleaned up after a successful deploy.
=> fix(build): clean up old cloudbuild images

changelog/H42TyvckS0qTGG5vL07qHw.md, cloudbuild.yaml, services/github/src/handlers/index.js, services/github/src/handlers/status.js, services/github/test/handler_test.js
Pending happens at the same time as taskDefined so it is enough for taskDefined to take the initiative and create the check run 
Otherwise they create two check runs on the github side and store outdated records in the db
According to the [exchanges doc](https://firefox-ci-tc.services.mozilla.com/docs/reference/platform/queue/exchanges#taskDefined) both `taskDefined` and `taskPending` happens at the same time, so to avoid it, only `taskDefined` is being used
=> Remove pending from the status listeners

changelog/bnW-iDD1R0-0D7rBUNF0Zw.md, ui/src/components/HookForm/index.jsx, ui/src/components/PulseBindings/index.jsx, ui/src/views/Hooks/ViewHook/index.jsx
PulseBindings component was expecting non-empty autocompletion list.
That was only passed on the Pulse Exchanges page but not on the Hooks Create/Edit page, which resulted in error message
=> fix(ui): Hooks create page fix

changelog/issue-5663.md, infrastructure/tooling/src/utils/docker.js
Fixes #5663.
> This patch upgrades to the new, v2 Docker Hub APIs.
v1 APIs were deprecated as of September 5, 2022 - see [here](https://www.docker.com/blog/docker-hub-v1-api-deprecation/) for more info.
=> fix(release): upgrade to v2 Dockerhub API

changelog/issue-5666.md, clients/client-go/http.go, clients/client-go/http_test.go
Github Bug/Issue: Fixes #5666 
Note, the `main.ClaimWork()` function returns `main.TaskRun(nil)` in [both of the following cases](https://github.com/taskcluster/taskcluster/blob/826df87beab373476f6cb793846cd2343f27b36a/workers/generic-worker/main.go#L541-L549):
* when [`func (queue *Queue) ClaimWork(taskQueueId string, payload *ClaimWorkRequest) (*ClaimWorkResponse, error)`](https://pkg.go.dev/github.com/taskcluster/taskcluster/v44@v44.20.4/clients/client-go/tcqueue#Queue.ClaimWork) returns an `error`
* when there are no tasks to run (when the Queue has no tasks for the worker to execute)
Therefore, a Queue service outage is equivalent to the Queue returning no tasks to execute, from the workers' perspective. The worker may exit if there is an idle timeout configured, for example, but now …
=> Issue 5666: do not dereference nil pointer

changelog/issue-4534.md, clients/client-shell/cmds/completions/completions.go
In addition to bash completions, add completions for fish, powershell, and zsh.
The [default Cobra completion command](https://pkg.go.dev/github.com/spf13/cobra#CompletionOptions) is still in place though. It can probably be removed in a separate (breaking?) update if necessary.
Github Bug/Issue: Fixes #4534
=> Add completions for other shells

changelog/IHQLaOuaRza29g6XB87x-A.md, netlify.toml
We would serve docs.taskcluster.net from netlify deployment, and it should forward all to `/docs`
=> Add redirect to /docs/ for netlify deployment

changelog/d-w-seccomp.md, generated/references.json, workers/docker-worker/config.yml, workers/docker-worker/schemas/v1/payload.yml, workers/docker-worker/src/task.js, workers/docker-worker/test/integration/disable_seccomp_containers_test.js
This is required to run `rr` inside a container, as described here: [Docker (rr wiki)](https://github.com/mozilla/rr/wiki/Docker)
This was previously opened as https://github.com/taskcluster/docker-worker/pull/532, but stalled during testing.
=>  Add a capability disableSeccomp to disable seccomp system call filter.

changelog/ND-XyXVjQwimxc4dCTtQ1A.md, ui/docs/manual/deploying/github.mdx
I noticed that the strings mentioned in the deployment docs don't quite match up with what exists in Github when creating a new app. It's not too hard to figure out which options are *meant* to be set, but figured it would be better if the docs mentioned the exact permission strings visible in the Github interface.
=> docs: update Github deployment docs for new Github interface

changelog/Ocr2-xk7S36i1Xb_AUtjRA.md, package.json, yarn.lock
This reverts commit e2015f35330a4b059d1bccf55c871df2af77bfbb.
=> Revert "build(deps): bump matrix-js-sdk from 15.6.0 to 20.0.2 (from PR #5692)"

changelog/issue-5728.md, services/github/src/handlers/status.js, services/github/src/queue-lock.js, services/github/test/queue-lock_test.js
Logs show that few github handlers might error or hang without releasing own lock. `maxLockTimeMs` for QueueLock will ensure that handlers do not run beyond given time, and forces their lock to be released. This will allow next waiting handlers to start work.
=> Add auto-release to github status handlers

changelog/C0wbR7wOQ8WP3HThfO44Yw.md, taskcluster/ci/docker-worker/kind.yml
The `disableSeccomp` capability feature was removed from Docker Worker in #5800 after being deemed [superfluous](https://github.com/taskcluster/taskcluster/pull/5800#issuecomment-1330766821). This removes its use from the Docker Worker CI tests too.
=> Remove discontinued and unneeded disableSeccomp capability from dw-ci

changelog/JpzzjXzuTkqyZ_ekVL8EjA.md, workers/generic-worker/gw-decision-task/tasks.yml
I hadn't spotted that my changes in PR #5782 were not enough to implement issue #5781. This is a follow-on that should hopefully put the issue to bed.
This time I'll also check the output of the affected CI tasks to make sure that the intended changes are effective before merging! (whoops)
=> Issue 5781 part 2: specify package(s) name when calling go test to suppress stdout/stderr in passing tests

changelog/issue-5804-2.md, ui/src/components/ErrorPanel/index.jsx, ui/src/components/TaskGroupStats/index.jsx
Fixes in this PR:
* Extend ErrorPanel component to display errors that look like json serialized API response error.  In hooks last fires it was showing empty red panel.
* Task group stats adds safe min width for the graph, so group with few tasks wouldn't have really wide bars on it. Looks better
=> feat(ui): Fix empty error message for hook last fire

dev-docs/development-process.md
Docker-compose is awesome!  Very easy to set up.  This just fixes a 404 link in the docs.
=> fix URL for docker-compose-plugin

changelog/DehbA-CwSziOtiWg2rFZkg.md, clients/client-py/tox.ini
Python tests were failing [py38](https://github.com/taskcluster/taskcluster/pull/5854/checks?check_run_id=9995796033)
According to [documentation](https://tox.wiki/en/4.0.3/config.html) external tools needs to be whitelisted
=> Fix python client tests

changelog/issue-5851.md, services/github/src/api.js, services/github/test/api_test.js
This fixes scenario when check run was not found for a given branch or installation didn't exist.
Fixes #5851
=> github: Return correct status code for the latest status

changelog/QE-LV6FARYKtvKcdj7tmFQ.md, taskcluster/ci/config.yml, taskcluster/ci/generic-worker/kind.yml, workers/generic-worker/gw-decision-task/tasks.yml
> This patch switches running CI tasks on generic-worker-windows2012r2 worker pool to the new, windows 2022 worker pool.
=> chore(ci): Upgrade CI images to use windows2022

changelog/QE-LV6FARYKtvKcdj7tmFQ.md, changelog/fJpkNU2fTIC0nHl0LxjIRg.md, taskcluster/ci/config.yml, taskcluster/ci/generic-worker/kind.yml, workers/generic-worker/gw-decision-task/tasks.yml
> This patch switches running CI tasks on generic-worker-windows2012r2 worker pool to the new, windows 2022 worker pool.
> Use updated gw-ci-macos-10-14 worker pool.
=> chore(ci): use updated worker pools

changelog/issue-4624.md, clients/client-go/tcobject/download.go, clients/client-go/tcobject/hashes.go, clients/client-go/tcobject/hashingreadseeker_test.go, clients/client-go/tcobject/hashingwriteseeker.go, clients/client-go/tcobject/hashingwriteseeker_test.go, clients/client-go/tcobject/upload.go, clients/client-go/tcobject/upload_download_test.go, clients/client-go/tcqueue/download_test.go, clients/client-py/setup.py, clients/client-py/taskcluster/aio/download.py, clients/client-py/taskcluster/exceptions.py, clients/client-py/test/aio/test_upload_download.py, clients/client-py/test/test_upload_download.py, clients/client-rust/Cargo.lock, clients/client-rust/download/Cargo.toml, clients/client-rust/download/src/artifact.rs, clients/client-rust/download/src/geturl.rs, clients/client-rust/download/src/hashing.rs, clients/client-rust/download/src/lib.rs, clients/client-rust/download/src/object.rs, clients/client-rust/download/src/test_helpers.rs, clients/client/src/download.js, clients/client/src/hashstream.js, clients/client/src/upload.js, clients/client/test/upload_download_test.js, internal/mocktc/object.go
In fact, the clients no longer use simple downloads, meaning that all downloads performed via a client will verify hashes on the downloaded content.
Github Bug/Issue: Fixes #4624
=> Support getUrl downloads in clients

changelog/QXcPePhQRKm2s1stITCfWQ.md, workers/generic-worker/build.sh
Version numbers were hidden inside `workers/generic-worker/build.sh` script so would never get auto-updated. These versions are only for CI lint checks so don't affect release bits of generic-worker, only the lint checks. This keeps them on latest, which is probably a safer bet them pinning them to a version which quickly could outdated without us noticing.
Additionally run the linter against all generic-worker engines, not just multiuser engine. Also reinstated `goimports -w` which was temporarily suppressed.
=> Go lint updates

.github/dependabot.yml, changelog/OFix2WquQtu17rXkCGqbZA.md, clients/client-rust/Cargo.lock
I also ran a `cargo update` to avoid all the dependabot PRs to come after this lands.
=> Update dependabot.yml to include rust client and e2e ui tests

.gitignore, .goreleaser.yaml, changelog/FtfvrZ_XTgiXV-Dh-U0BEg.md, infrastructure/tooling/src/build/tasks/client-shell.js
This fixes https://github.com/taskcluster/homebrew-tap/issues/2.
> This patch makes it so the taskcluster shell client (cli) is built with `goreleaser`.
>
> `goreleaser` also will automatically keep our [homebrew-tap](https://github.com/taskcluster/homebrew-tap/blob/main/Formula/taskcluster.rb) formula up-to-date during the release process.
>
> GitHub releases will now also contain zipped Windows executables of this cli supporting both amd64 and arm64. arm64 binaries for linux have been added as well.
>
> The darwin and linux binaries are now tarballs.
Followed https://goreleaser.com/customization/homebrew/ as well as many of their other docs.
This tool is incredibly powerful. We can use it to publish to chocolatey and snap, for example. I think all of our go builds could be migrated over …
=> feat(cli): build taskcluster cli with goreleaser

.github/dependabot.yml, changelog/dyG9QgtwTLevqu-z-B4BfA.md
No longer monitor deps for docker worker.
=> dependabot: remove docker worker config

.github/workflows/dependabot-automerge.yml, changelog/Jn-33Ge2SpWIS2UEI2V_fw.md
> This patch updates the GitHub Dependabot auto-merge workflow to use the recommended solution for approving/auto-merging minor and patch Dependabot PRs.
>
> [GitHub Documentation Link](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request)
=> fix(workflows): Dependabot automerge workflow updated to align with GitHub's suggested method

.github/workflows/dependabot-automerge.yml, changelog/ThGmvxI_T4SfsEIugoMRJw.md
This makes it so the steps in the workflow use the taskcluster-bot PAT to approve and merge these PRs, instead of the github-actions user that's used by default.
=> fix(workflow): use TC bot gh token to automerge

changelog/P0y1fNy1QyGmCr69tnBdyA.md, infrastructure/tooling/src/changelog/index.js
This will fix it so that `meta-changelog-pr` tasks in `client-rust` and `taskgraph` dependency upgrades won't fail like they are in https://github.com/taskcluster/taskcluster/pull/5904 and https://github.com/taskcluster/taskcluster/pull/5908.
=> fix(changelog): don't require changelog on dep upgrades

changelog/NsOxgW4BRIS6YFPo4Zl1Ng.md, package.json, yarn.lock
>Upgrade some major version dependency bumps using `pmac` tool:
>
>`pmac add 5748 5811 5902 5903`
If you look into each of the 4 PRs I've combined (#5748 #5811 #5902 #5903), you'll see my comment as to why it should be fine to merge (typically just dropped support for old versions of Node.js).
=> build(deps): major version bumps using `pmac` tool

Dockerfile, changelog/VmYrW6fORn-_YIdldfu4gA.md
Cloudbuild starting [failing](https://github.com/taskcluster/taskcluster/runs/10259231223) after https://github.com/taskcluster/taskcluster/pull/5920 landed.
Adding in [this flag](https://classic.yarnpkg.com/en/docs/cli/install#yarn-install---ignore-scripts-) will skip the new, `preinstall` script.
Example of it running with and without the flag:
```bash
➜  taskcluster git:(main) yarn                 
yarn install v1.22.19
$ cd clients/client && yarn --frozen-lockfile
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.06s.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
✨  Done in 1.92s.
➜ …
```
=> fix(cloudbuild): add `--ignore-scripts` flag to yarn install to skip preinstall

changelog/Rm385PxBThimb_W5zJt3ag.md, test/go-lint.sh
Simple update to lint tests to make sure all generic-worker engines are linted, not just multiuser engine.
=> Lint all the generic-worker engines, not just multiuser

.taskcluster.yml, changelog/issue-4950.md
This file is auto-generated by taskgraph but is not configured and is not used in taskcluster repository. It relies on the hooks that should be created by third-party tools on every change of .taskcluster.yml.
Fixes #4950
=> Prevent actions.json from being uploaded to artifacts.

.dockerignore, Dockerfile, changelog/P7Ks2AE_SSGiOju6vezbzg.md
* tidy-up `.dockerignore` file to add few more entries that don't belong in resulting monoimage
* install dependencies for `clients/client` to match the expected behavior from other workflows
* fixes issue with `rm -rf` that used bash expansion which doesn't work since RUN doesn't use bash
=> Improve monoimage by removing unnecessary files and fixing RUN commands

changelog/issue-5518.md, services/github/src/api.js, services/github/src/constants.js, services/github/src/handlers/job.js, services/github/src/tc-yaml.js, services/github/test/intree_test.js, services/github/test/tc-yaml_test.js, ui/docs/reference/integrations/github/taskcluster-yml-v0.mdx, ui/docs/reference/integrations/github/taskcluster-yml-v1.mdx
This adds new variable 'action' for release payload that includes type of the release: [github docs](https://docs.github.com/developers/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=released#release)
In case of `prereleased` action `<>:pre-release` role would be assumed instead of `<>:release`.
Fixes #5518
This is possibly a breaking change if some repositories relied on different workflows?
=>  Assume different role for pre-release event.

.dockerignore, Dockerfile, changelog/THAtLb7vRvSlEg4wcg5EWw.md, infrastructure/tooling/src/build/tasks/client-shell.js
Some of the docker images rely on the presence of .git folder during release
=> Exclude .git from dockerignore

changelog/dvL-x41MQkyo1qq8x8VI4g.md, infrastructure/tooling/src/build/tasks/monoimage.js
yarn used cache folder in /usr/local which stored extra ~500mb of cached deps
=> Remove yarn cache after installing all packages

changelog/GiqjO4i_Q-aVD-EcTkIeUA.md, taskcluster/ci/generic-worker/kind.yml, workers/generic-worker/gw-decision-task/tasks.yml
>Upgrade `git` to latest version to address the security vulnerabilities affecting versions 2.39 and older.
>
>[Announcement on GitHub](https://github.blog/2023-01-17-git-security-vulnerabilities-announced-2/)
=> build(deps): upgrade git to latest version

changelog/issue-6014.md, generated/references.json, workers/docker-worker/schemas/v1/payload.yml
Spotted this issue when looking at docker-worker to generic-worker conversion mechanics. I have a nasty feeling I saw this once before, and there was tasks in the wild that were setting env vars to bools or ints unintentionally - I think this is reasonable, and will probably never reach production fxci since we are not intending on deploying updated docker-workers in fxci from now on. If tasks do break though, they should be very easy to fix.
Fixes #6014.
=> Ensure docker worker env var values are strings

changelog/issue-6021.md, generated/references.json, workers/docker-worker/schemas/v1/payload.yml
=> Issue 6021: tighten docker-worker payload to enforce cache is string to string mapping

changelog/dPeI-3ufTsq51tIXcflv6A.md, generated/references.json, workers/docker-worker/schemas/v1/payload.yml, workers/docker-worker/test/validate_schema_test.js
See #6020 for context.
No functional impact anticipated.
This is useful for the d2g project where docker worker payload is mapped to native go types. The type was changed from `number` to `integer` in the json schema, but since the property `multipleOf` was already set to `1`, it was already effectively validated as an integer, even if the type was "looser".
=> Docker worker json schema payload has been tweaked for cleaner go code generation.

changelog/VvP2TgMtQ5Sjk-HEI4gjjg.md, workers/generic-worker/process/docker.go
This is plaguing our CI at the moment, and all CI runs are currently failing due to this issue. The issue is that generic-worker docker engine was running tasks under `ubuntu:latest` using podman, but since ubuntu:latest was updated 21 hours ago, we are getting the error:
```
unsupported docker v2s2 media type: application/vnd.oci.image.manifest.v1+json
```
The "fix" here is to freeze the ubuntu version to the previous working version. We intend to drop support for the docker engine at some point, or replace it internally with the new d2g translation layer, therefore freezing this version, for something that isn't used in any production system, should be fine.
=> Fix for 'unsupported docker v2s2 media type: application/vnd.oci.image.manifest.v1+json'

changelog/NOLxL81nRA2pG_84dr_KSQ.md, clients/client-shell/cmds/validate-json/validate_test.go
Issue originally stemmed from https://github.com/taskcluster/taskcluster/pull/6019. Interesting how the tests didn't fail then...
=> fix(cli): fix broken cli test

.taskcluster.yml, changelog/TotHjZ6OTS6wbCFSoKtoNA.md
Seeing if I can switch our own docker-worker CI decision task to generic-worker, using d2g tool...
Let's see how many attempts this takes, at the same time I've tried to reformat the output a little bit to make it easier to read, and due to all the encodings inside encodings, this may take a few attempts to get right...
=> Move taskcluster CI decision task to generic-worker

.taskcluster.yml
It occurred to me it that for environment variables which are only used by programs in the (podman) container and not by commands on the host, that it is an unnecessarily complication and overhead to set these env vars in the host process too. In other words, this:
```yaml
env:
ENV_VAR: "<VALUE>"
....
command:
....
podman -e "ENV_VAR=$${ENV_VAR}"
....
```
simplifies to:
```yaml
command:
....
podman -e "ENV_VAR=<VALUE>"
....
```
=> Simplify decision task: set env vars only in container, not in host process

changelog/issue-1753249.md, ui/.gitignore, ui/src/components/TaskDetailsCard/__snapshots__/index.test.jsx.snap, ui/src/components/TaskDetailsCard/index.jsx
Bugzilla Bug: [1753249](https://bugzilla.mozilla.org/show_bug.cgi?id=1753249)
=> Bugzilla 1753249 task id clickable field

db/fns.md, db/versions/0028.yml, generated/db-schema.json
It looks like this got here through a revert in #3243.
=> Document db fn is_task_group_active

changelog/YHDKOgBXSZ-t6gQX9OvHbg.md, go.mod, go.sum, tools/jsonschema2go/jsonschema.go, workers/generic-worker/gw-codegen/main.go, workers/generic-worker/gw-decision-task/main.go, workers/generic-worker/yamltojson/main.go
The package `github.com/ghodss/yaml` is no longer actively maintained. See discussion in https://github.com/ghodss/yaml/issues/75 and https://github.com/ghodss/yaml/issues/80. [`sigs.k8s.io/yaml`](https://github.com/kubernetes-sigs/yaml) is a permanent fork of `github.com/ghodss/yaml`.
The notable change is that `github.com/ghodss/yaml` uses `gopkg.in/yaml.v2 v2.2.2`, but `sigs.k8s.io/yaml` uses `gopkg.in/yaml.v2 v2.4.0`. Changes can be seen here [v2.2.2...v2.4.0](https://github.com/go-yaml/yaml/compare/v2.2.2...v2.4.0), mostly bug fixes.
=> Replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

changelog/Kd63czIOSqmtb38S_OmW_g.md, infrastructure/tooling/src/build/tasks/monoimage.js, infrastructure/tooling/src/utils/docker.js
We found during releases that check registry tag failed with 503 for some unknown reason:
```
HTTPError: Response code 503 (Service Unavailable) (while executing task Build Taskcluster Devel Docker Image)
at Request.<anonymous> (/task_167707000275458/taskcluster/node_modules/got/dist/source/as-promise/index.js:118:42)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
code: 'ERR_NON_2XX_3XX_RESPONSE',
timings: {
start: 1677070518700,
socket: 1677070518701,
lookup: 1677070518701,
connect: 1677070518763,
secureConnect: 1677070518826,
upload: 1677070518826,
response: 1677070518900,
end: 1677070518901,
error: undefined,
abort: undefined,
phases: {
wait: 1,
dns: 0,
tcp: 62,
tls: 63,
request: 0,
firstByte: 74,
download: 1,
total: 201
}
}
}
```
This fix does only …
=> Wrap error handling for release checks

changelog/issue-6067.md, generated/references.json, services/worker-manager/src/estimator.js, services/worker-manager/src/monitor.js, services/worker-manager/src/provisioner.js, services/worker-manager/test/estimator_test.js, services/worker-manager/test/provisioner_test.js
Stopping workers require multiple calls for Azure to deprovision. When Workers that fail to start immediately due to the configuration or cloud availability error, go into stopping mode. Next provisioner loop doesn't count those against total capacity and keeps spawning them. This leads to the situations where stopping capacity grows significantly over short period of time and blocks scanning loop.
Fixes #6067
=> Worker manager considers stoppingCapacity in estimator

changelog/MTgMbz1CQNixwcs5AnOyEQ.md, clients/client-go/README.md, clients/client-go/codegenerator/model/types.go, clients/client-go/tcauth/types.go, clients/client-go/tcgithub/types.go, clients/client-go/tchooks/types.go, clients/client-go/tcobject/download.go, clients/client-go/tcobject/types.go, clients/client-go/tcobject/upload.go, clients/client-go/tcworkermanager/types.go, internal/mocktc/object.go, test/go-lint.sh, tools/jsonschema2go/jsonschema.go, workers/generic-worker/artifacts_multiuser_test.go, workers/generic-worker/chain_of_trust.go, workers/generic-worker/generated_docker_darwin.go, workers/generic-worker/generated_docker_linux.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/runasadministrator_windows.go, workers/generic-worker/runasadministrator_windows_test.go, workers/generic-worker/taskcluster_proxy.go, workers/generic-worker/taskcluster_proxy_broken_on_docker_test.go
>Go code now maps the jsonschema boolean type to `*bool` rather than `bool` in order to differentiate between an unspecified value and `false`.
=> Use `*bool` instead of `bool` in jsonschema in go

changelog/SJ8XbCO5RE6EPQLrqgmn-g.md, ui/src/components/StatusDashboard/StatsFetcher.jsx, ui/src/components/StatusDashboard/index.jsx, ui/src/components/StatusDashboard/summarizeWorkerPools.js, ui/src/components/StatusDashboard/summarizeWorkerPools.test.js
Few updates to the dashboard:
* `stoppingCapacity` is being displayed, since worker manager uses it during provisioning
* Values are being grouped by provisioning and general stats
* worker manager stats are being refreshed every 30s
* visual animations when values change
=> Dashboard displays stopping capacity, values autoreloaded.

changelog/issue-6124.md, ui/src/views/Tasks/TaskGroup/index.jsx
This error wasn't showing up on community-tc because we don’t use `actions.json` artifact.. but on fxci it is being used, so when it is not empty, graphql loader is trying to filter those actions with broken filter (filter that might be working with old library, but is not with the new one)
Fixes #6124
=> fix(ui): Fix graphql filter query for TaskGroup

changelog/bug-1590886.md, services/github/src/handlers/deprecatedStatus.js, services/github/test/handler_test.js
Patching https://github.com/taskcluster/taskcluster/pull/6129 that was released in 48.2.0
Since new event was added to that handler, it was invoked too often and resulted in unnecessary status api updates.
When task starts running  it is only worth updating status if whole build was already fail/success. 
Initial `pending` state is handled by a different handler, so safe to skip it here
=> feat(github): Skip updating statuses when task is running

changelog/bug-1824937-0.md, workers/docker-worker/src/util/artifact_download.js
If the connection to download the docker image hangs for whatever reason, we could wait indefinitely, and because the maxRunTime timer isn't set up by that point, we'd only stop when hitting the task's deadline and failing to reclaim it.
Instead, time out the connection if it stays idle for 60 seconds, so we can properly retry the download.
Bugzilla Bug: [1824937](https://bugzilla.mozilla.org/show_bug.cgi?id=1824937)
=> docker-worker: set a timeout when downloading artifact

changelog/ATiAPN9YTSa2nWrYeK0ugA.md, workers/generic-worker/gw-decision-task/tasks.yml
>Builds and tests generic worker (multiuser) on macOS Ventura 13 on new, arm64 machines.
=> ci: build/test gw (multiuser) on macOS 13 on arm64

changelog/Trjdzsg9Sbyt4rHD-N-aBw.md, clients/client-py/setup.py, clients/client-py/tox.ini, services/github/test/data/configs/taskcluster.dependencies.v1.yml, services/github/test/intree_test.js, taskcluster/ci/client/kind.yml, taskcluster/ci/lint/kind.yml
Python 3.6 is no longer a [supported version](https://devguide.python.org/versions/#supported-versions). This also adds python 3.10 and 3.11 support.
>Remove python 3.6 support as it's past its end-of-life date.
>
>Add python 3.10 and python 3.11 support.
=> refactor!: drop support for python 3.6

changelog/NkBUdjnRQ3GpKq1bG41CbA.md, docker-compose.yml, docker/nginx.conf, infrastructure/tooling/src/generate/generators/docker-compose.js, infrastructure/tooling/src/utils/repo.js
* `s3_init_buckets:` doesn't remove and create buckets if they exist.
* added multi-line yaml for docker-compose files for readability 
* `nginx.conf` fixed bucket urls to support POST operations on a bucket. Trailing slash was not matched on `"POST /public-bucket?delete"` action
First one was very annoying to debug anything on cron job level, as those services depend on `s3_init_buckets` which removed all contents before service starts, thus making it hard to tell if deletion through API really works or was it this startup script :)
=> docker-compose several improvements

changelog/HwVqACuzTlGplHg8EfGEkA.md, taskcluster/ci/docker-worker/kind.yml
The past handful of new version commits fail the CI due to the docker worker chunk tasks relying on the new livelog version being published. These are the error codes that return in these cases. Would be nice to have a ✅ next to each commit to `main`...
=> chore(ci): retry docker worker chunk tasks

changelog/issue-5773.md, ui/src/components/UserMenu/UserMenuButton.jsx, ui/src/components/UserMenu/UserMenuList.jsx, ui/src/utils/getPictureFromUser.js, ui/src/utils/getPictureFromUser.test.js, ui/src/utils/username.js, ui/src/utils/username.test.js, ui/src/views/Dashboard/index.jsx, ui/src/views/Profile/index.jsx
In some rear scenarios #5773 `user.profile` or `user` objects became `undefined` or `null`. 
Although the root cause of this issue remains unclear and cannot be reproduced, enhancing the UI's resilience can prevent pages from crashing when such instances occur
Fixes #5773
=> Fix profile name handling in UI

changelog/ead5aXzMSNWdGmLGD9nU0Q.md, workers/generic-worker/main.go, workers/generic-worker/model.go, workers/generic-worker/mounts.go, workers/generic-worker/purge_caches_test.go
https://github.com/taskcluster/taskcluster/pull/6148 incorrectly would purge _all_ caches on the worker. This patch makes it so only caches related to the task run get purged. I ensured that the new test that I added fails on the `main` branch.
>Generic worker feature `task.Payload.OnExitStatus.PurgeCaches` now only purges caches related to the task, instead of all caches on the worker.
=> fix(generic-worker): only purge task caches

changelog/bug-1590886.md, services/github/src/handlers/deprecatedStatus.js, services/github/src/handlers/index.js, services/github/test/handler_test.js
Before it was only listening to `taskRunning` and it took some time to switch github state after rerun, as it takes time to get scheduled and start running
Bugzilla Bug: [1590886](https://bugzilla.mozilla.org/show_bug.cgi?id=1590886)
=> Set status back to pending as soon as task restarts

changelog/issue-6185.md, clients/client-go/tcqueue/types.go, generated/references.json, services/queue/schemas/v1/quarantine-worker-request.yml
Reason field was marked as optional, but validation required min length 1
Fixes #6185
=> Fix quarantine worker payload schema

changelog/issue-6058.md, workers/generic-worker/process/multiuser_windows.go
Bugzilla Bug: [1815711](https://bugzilla.mozilla.org/show_bug.cgi?id=1815711)
This is a partial fix for #6058. It should workaround the issue for the specific case raised, but will not work if custom `osGroups` entries are specified in the task payload.
=> Only grant SID Winsta Access when refreshing access token

changelog/issue-6186.md, services/worker-manager/config.yml, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure/index.js, services/worker-manager/src/providers/google.js, services/worker-manager/src/worker-scanner.js, services/worker-manager/test/provider_aws_test.js, services/worker-manager/test/provider_azure_test.js, services/worker-manager/test/provider_google_test.js
This is an attempt to reduce the amount of workers that are being stopped even after they were registered and started claiming work. In some conditions, especially for Azure workers, scan loops can take 10-20 minutes. And since all records are being fetched in memory once, it may happen that worker record was updated. We simply reload the record before finally removing worker.
Fixes #6186 
I'm only 99% confident this is the main cause why normally working workers are being removed, because `update_worker_2` function is actually checking `etag` of the record when doing an update, so it's not clear how it can overwrite something that was already updated. But maybe not all updates are being handled with try/catch or are not being logged. 
From the investigation into 2k of killed workers, 85% …
=> Extra check before worker is terminated on terminateAfter time exceeded.

changelog/BR8hGDKyQh-21RNB_u0t8w.md, generated/references.json, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/simple_posix.yml
Copy/paste from the docker worker schema that I forgot to update :)
=> chore(schema): fix copy/paste error in generic worker schema

changelog/issue-6208.md, workers/generic-worker/helper_test.go, workers/generic-worker/interactive.go, workers/generic-worker/interactive_test.go
Fixes https://github.com/taskcluster/taskcluster/issues/6208.
>Return a malformed payload error if `task.payload.features.interactive` is enabled, while the `enableInteractive` worker config is false.
=> fix(generic-worker): return error if worker config not set for interactive

changelog/J-Yz6b4tRtSddILhruvtkA.md, tools/jsonschema2go/jsonschema2go/cli.go
This adds some optional arguments to the jsonschema2go cli for:
* outputting nested structs
* outputting default struct tags
This is needed by d2g. In that project, the docker worker payload schema has some features which are `true` by default (such as `payload.features.bulkLog`). In order for an absent value to be interpreted as `true` rather than `false`, the default will need to be specified in the generated go type as a default struct tag.
=> Add options for jsonschema2go cli for nested structs and defaults

changelog/Weif8TmwSvyp-dxVV4Ns0Q.md, generic-worker.Dockerfile
This is a fix for the release process that was discovered in the following staging release: https://github.com/taskcluster/staging-releases/tree/staging-release/v50.0.0
=> Fix build of generic-worker docker image for dev deployments

changelog/issue-5621.md, services/auth/src/static-scopes.json, services/github/scopes.yml, services/github/src/handlers/index.js, services/github/test/handler_test.js
This is a followup on #5621 to give extra scopes for github client, as it currently cannot cancel own task groups. 
Github client will get following scopes:
- `queue:seal-task-group:taskcluster-github/*`
- `queue:cancel-task-group:taskcluster-github/*`
When some repository is using different `schedulerId` then corresponding `repo:github.com/` role should be updated to have adjusted roles (to make github client capable of stopping previous builds)
=> Allow github client to seal and cancel task groups

changelog/IRI3DiqKST2KvPcZvMmjtA.md, workers/generic-worker/process/process.go
Without docker engine, this build constraint is no longer necessary.
=> Remove unneeded build constraint

changelog/Z0bho1tfSzCbOXmaShDFFg.md, clients/client-web/test/Auth_test.js
Resolves https://github.com/taskcluster/taskcluster/security/code-scanning/312
=> Update client-web test to avoid using env variables in regexp

changelog/AX4UCxG0RqGeqDU4poPqwQ.md, ui/src/utils/constants.js
This is no longer a valid schema to validate against in the create task view on the UI.
=> chore: remove docker engine reference

changelog/JzuKhYjZTTy3hvABhImD9Q.md, docker-compose.dev.yml, infrastructure/tooling/src/generate/generators/docker-compose.js
The changelog is necessary to be able to compile
`ui/src/views/Documentation/Changelog/index.jsx` and needs to be at the root of the app.
=> Mount the changelog in the UI container in dev mode

changelog/IBhqsY4ZR1qLSobQrzU4tQ.md, clients/client-go/tcgithub/types.go, clients/client-go/tcobject/types.go, tools/jsonschema2go/text/text.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/mounts.go
The jsonschema2go tool now considers `SHA` and `KVM` to be words that should be
capitalised when generating go type names.
As a consequence, the taskcluster go client is backwardly incomaptible with the
previous release, since the `tcgithub.Build` struct member `Sha` has been
renamed to `SHA`.
=> jsonschema2go: Add SHA, KVM as initialisms

changelog/issue-6245.md, generated/references.json, internal/mocktc/factory.go, internal/mocktc/index.go, internal/mocktc/indexprovider.go, internal/mocktc/mocktc.go, internal/mocktc/tc/factory.go, internal/mocktc/tc/services.go, workers/generic-worker/garbagecollector.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/mounts.go, workers/generic-worker/mounts_multiuser.go, workers/generic-worker/mounts_simple.go, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml, workers/generic-worker/schemas/simple_posix.yml
=> Issue 6245: generic-worker: support mounting indexed content

changelog/JSKb0tL-RparNBUHNdVf0A.md, workers/generic-worker/mounts.go
Both Artifact Content and the new Indexed Content type contain an "artifact" property. Indexed Content was incorrectly being unmarshaled into ArtifactContent, since the presence of "artifact" was assumed (in the past) to mean that the content was Artifact Content. I've changed the check so that a "taskId" property implies Artifact Content (the only type which contains this property), and "namespace" continues to imply Indexed Content (also unique to this type). I've also added a comment to highlight that when making changes to this switch statement, extreme care needs to be taken to check that previous conditions still hold.
I will add tests for this, but in the meantime, here is an emergency fix.
Currently not used in production.
=> Fix: generic-worker: indexed content now unmarshaled into IndexedContent go type

changelog/issue-6247.md, services/auth/src/static-scopes.json, services/worker-manager/scopes.yml, services/worker-manager/src/api.js, services/worker-manager/src/main.js, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure/index.js, services/worker-manager/src/providers/google.js, services/worker-manager/src/providers/index.js, services/worker-manager/src/providers/provider.js, services/worker-manager/src/providers/static.js, services/worker-manager/src/providers/testing.js, services/worker-manager/test/api_test.js, services/worker-manager/test/helper.js, services/worker-manager/test/provider_aws_test.js, services/worker-manager/test/provider_azure_test.js, services/worker-manager/test/provider_google_test.js, services/worker-manager/test/provider_static_test.js
This patch should theoretically lower the number of `claim-expired` exceptions when `queue` service serves tasks to the workers that were requested to be removed. 
Queue service already checks quarantine field to avoid giving tasks to such workers, so this approach doesn't make any changes to the queue itself, only uses existing functionality
It will not solve all race conditions, as `claimWork` is waiting for up to 20s on each call, so worker could be already making this call, when instance would be removed by worker-runner.
Fixes #6247
=> Quarantine worker on removeWorker

changelog/issue-6227.md, infrastructure/tooling/src/build/tasks/generic-worker.js
=> Issue 6277 - stop releasing Generic Worker simple engine binaries

changelog/issue-5807.md, services/github/src/utils.js, services/github/test/utils_test.js
Some sequences (sgr0) where not parsed and appeared raw in github logs that we attach to check runs. Later that output was being likely incorrectly hashed which causes checksum mismatches for the github events.
this possibly fixes #5807
=> feat(github): Fix ans2txt parsing of sequence codes

changelog/issue-5006.md, workers/generic-worker/runtime/runtime_darwin.go
If Generic Worker under macOS (multiuser engine) can't determine logged in console user, dump output of `last` command to worker logs.
This adds troubleshooting information for Issue #5006 but does not contain a fix for it.
=> Issue 5006 - add troubleshooting information

changelog/Dfv-PelkQBKeV3RzGheTcw.md, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/gw-codegen/main.go, workers/generic-worker/main.go, workers/generic-worker/payload_test.go
The rename is for three reasons:
1) In general it is useful when generating go types via jsonschema2go, to also generate a method which contains the jsonschema which was used to generate the methods, since any code that uses the generated code will invariably want to unmarshal data into the generated go types from a JSON data source that conforms to the schema it used to generate the go types. However, it will typically want to validate that the input data conforms to the schema, before it unmarshals it into the generated go types. Therefore this is a generally useful feature for any user of jsonschema2go.
2) Now the function name is capitalised, thus exported, which means that the generated code can live in a different package to the code that calls it. It also means it will appear in …
=> gw-codegen: rename taskPayloadSchema -> JSONSchema

.taskcluster.yml, changelog/eKrFAszJQ0aX0oR4-P7QvA.md
I happened to notice that a decision task was resolved as successful, even though it failed (unfortunately I've lost the reference to the task/github check) and it was because the exit code was from the `rm artifacts/actions.json` command rather than the `~/.local/bin/taskgraph decision` command.
The fix is to make sure `bash` runs with the `-e` option.
=> Fix: fail task if decision task fails

changelog/SH9GLDhmS86nZh2mY3JzTw.md, taskcluster/ci/config.yml, taskcluster/ci/generic-worker/kind.yml
We have two distinct types of worker pools in proj-taskcluster:
* proj-taskcluster/gw-ci-\<platform\> (privileged - tasks run as root/LocalSystem)
* proj-taskcluster/gw-\<platform\> (regular - tasks run as regular task users)
The first type is intended for generic-worker CI, which when testing generic worker, needs to be able to create OS users on-the-fly.
The second type is for regular tasks that don't require the additional privileges. The generic-worker decision task and worker runner tests don't require these privileges, so in this PR I am moving them to the regular (less privileged) worker pools.
=> Don't run generic-worker decision task and worker runner tests as root user

changelog/issue-6280.md, clients/client-rust/upload/src/factory.rs
This is due to a tokio bug where `try_clone` does not wait for pending operations to finish.
I wasn't able to reproduce after making this fix.
Github Bug/Issue: Fixes #6280
=> Fix an intermittent test failure in client-rust

changelog/Ts4yf7zsS7Wjjo0rwDJViw.md, infrastructure/tooling/src/build/tasks/generic-worker.js
>This essentially reverts the change in [#6279](https://github.com/taskcluster/taskcluster/pull/6279).
>
>We learned from RelOps that the simple engine is useful for running generic worker inside a VM and inside of docker containers.
@aerickson thanks for bringing this to our attention 👍🏻
=> feat(release): build and publish the generic worker simple engine binary

changelog/dZvtWFeQSKO9cn3iVU3GhA.md, go.mod, go.sum, ui/src/components/Shell/index.jsx, workers/generic-worker/interactive.go, workers/generic-worker/interactive/interactive.go, workers/generic-worker/interactive/interactive_test.go, workers/generic-worker/interactive/interactivejob.go, workers/generic-worker/interactive_test.go
Instead of sending commands line by line and reading responses the same way, present the pty to the client through a websocket. This allows for interactive applications to run as well as displaying things as they would be in a normal terminal emulator. This includes support for resizing which means the PTY will adjust to the window size of the user.
This changes how interactive commands work on a fundamental level. Instead of running one command that everyone attaches to, this spawns one command per connection. That means that a command is spawned when a websocket opens instead of when the task starts running.
To be able to handle resizing, we need to distinguish resize requests coming from the client. Since we only have one websocket, we use the first byte of every message to distinguish …
=> Rework the interactive feature for generic worker

changelog/issue-6247.md, services/auth/src/static-scopes.json, services/worker-manager/scopes.yml, services/worker-manager/src/api.js, services/worker-manager/src/main.js, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure/index.js, services/worker-manager/src/providers/google.js, services/worker-manager/src/providers/index.js, services/worker-manager/src/providers/provider.js, services/worker-manager/src/providers/static.js, services/worker-manager/src/providers/testing.js, services/worker-manager/test/api_test.js, services/worker-manager/test/helper.js, services/worker-manager/test/provider_aws_test.js, services/worker-manager/test/provider_azure_test.js, services/worker-manager/test/provider_google_test.js, services/worker-manager/test/provider_static_test.js
Reverts taskcluster/taskcluster#6267
it is a temporary (experimental) fix in attempt to reduce `claim-expired` exceptions. 
It was released with `51.1.0`.
If it doesn't give us the desire effect and amount of `claim-expired` wouldn't go down, we should revert this pull request https://github.com/taskcluster/taskcluster/pull/6267 
Upd:
Evidence suggests that there was no significant impact on the `claim-expired` exceptions number, so no need to keep that longer in codebase
=> Revert "Quarantine worker on removeWorker"

changelog/L3z8Vpo3TxyOP00mQ1oRvg.md, infrastructure/tooling/src/changelog/index.js
Example changelog of this last working https://github.com/taskcluster/taskcluster/blob/main/CHANGELOG.md#automated-package-updates
=> fix(changelog): correctly filter for dependabot/renovate updates

changelog/issue-6237.md, workers/generic-worker/main.go
Fixes #6237.
>This patch fixes the case where a generic worker won't upload its log on a malformed payload error. This has been broken since v48.2.0 from PR [#6107](https://github.com/taskcluster/taskcluster/pull/6107).
=> fix(generic-worker): set defaults before validating payload

changelog/JJPL-qvEQaalv3ZidxyoWw.md, clients/client-py/Makefile, clients/client-py/setup.py, clients/client-py/tox.ini, docker/tc-admin/Dockerfile, services/github/test/data/configs/taskcluster.dependencies.v1.yml, services/github/test/intree_test.js, taskcluster/ci/client/kind.yml
>Remove python 3.7 support as it's hit the EoL date, 2023-06-27.
>
>More info on the python 3.7 release schedule can be found [here](https://peps.python.org/pep-0537/).
=> refactor!: drop support for python 3.7

changelog/MXt8cGWOTfyVFTCtxhdHhA.md, docker/tc-admin/Dockerfile
Moved dockerfile to `tc-admin` where it should have been since start
https://github.com/taskcluster/tc-admin/pull/232
Tc-admin update broke local dev env, as `tc-admin:3.2.0` was published manually ~year ago.
=> Moved dockerfile to tc-admin repository

changelog/c2yKFTwySzu3DTvhI6Zo4w.md, docker/nginx.conf, infrastructure/tooling/src/generate/generators/docker-compose.js, ui/src/views/SwitchEntryPoint/index.jsx
Wanted to fix #6330 but couldn't reproduce it.
* Fixes duplicate CORS headers issue
* Fix UI redirect where `/docs?version=x` redirect was not preserving query parameters
=> Fix duplicate CORS header issues

changelog/JIdME6vOQiq7Yr6nXJf4EQ.md, clients/client-shell/README.md, clients/client-shell/cmds/d2g/d2g.go, clients/client-shell/subtree_imports.go
>This change adds the `d2g` subcommand to the `taskcluster` cli.
>
>It can be used to translate a Docker Worker payload to a Generic Worker payload.
>Both the input and output are JSON. You can either pass the input as a file or pipe it in to the command.
>
>View help with:
>
>```shell
>taskcluster d2g -h
>```
>
>Example usages:
>
>```shell
>taskcluster d2g -f /path/to/input.json
>```
>
>_OR_
>
>```shell
>taskcluster d2g --file /path/to/input.json
>```
>
>_OR_
>
>```shell
>cat /path/to/input.json | taskcluster d2g
>```
>
>_OR_
>
>```shell
>echo '{"image": "ubuntu", "command": ["bash", "-c", "echo hello world"], "maxRunTime": 300}' | taskcluster d2g
>```
=> feat(cli): integrate `d2g` into taskcluster cli

changelog/issue-6330.md, ui/src/utils/ajv.js, ui/src/utils/exchangesList.js, ui/src/utils/exchangesList.test.js, ui/src/utils/validateTaskPayloadSchemas.js, ui/src/views/TcYamlDebug/index.jsx
This happened on the production build only as whole code was living in the shared scope. 
Multiple pages were adding same schema twice which caused an exception to be thrown in console. 
To avoid this, we only load those schemas once.
Also refactored lib-url usage across pages
Fixes #6330
=> Load schemas once

changelog/PcHmdF8uQ6ef6GxEusgNQw.md, ui/src/utils/ajv.js, ui/src/utils/ajv.test.js, ui/src/utils/validateTaskPayloadSchemas.js, ui/src/views/TcYamlDebug/index.jsx
Previously same schema was used on two different pages/components and there were errors if both pages would be loaded, saying that schema was already loading.
This refactoring adds single `loadServiceSchema()` function that loads resource once and adds it to `ajv` once to avoid those issues.
=> UI: Refactor service schema loading and validation

clients/client-web/package.json, clients/client-web/yarn.lock
Identical to #6291 but this description does not include those magical words that prevent the CI from running. I won't mention what they are here...
=> build(deps-dev): bump karma from 6.4.1 to 6.4.2 in /clients/client-web

changelog/Poh6dB8NQ5S_-IAOgyYoew.md, taskcluster/ci/generic-worker/kind.yml
As per `go help install`:
> If the arguments have version suffixes (like @latest or @v1.0.0), "go install"
> builds packages in module-aware mode, ignoring the go.mod file in the current
> directory or any parent directory, if there is one. This is useful for
> installing executables without affecting the dependencies of the main module.
By adding `@latest` to go install commands, we should ensure that installing dev tools (such as goimports) will not modify `go.mod` and `go.sum` files.
By continuing to check that running `go mod tidy` does not alter the contents of `go.mod` or `go.sum`, we also ensure that these files are consistent with the go code.
=> Align `go mod tidy` usage with current go semantics

changelog/AD0QORFPR-KxRAyAVxT9fg.md, ui/src/components/HooksListTable/index.jsx
Extra schedule/exchanges displayed as Badge with Tooltips
And fixes `+n` logic
=> Hooks page improvements:

changelog/issue-6395.md, docker-compose.yml, infrastructure/tooling/src/generate/generators/docker-compose.js
Pinned `minio/minio`, `minio/mc` images to avoid having breaking changes in future.
Rabbitmq version was also upgraded.
Fixes #6395
=> Fixes local docker-compose environment for public artifacts

changelog/issue-6395-1.md, docker-compose.yml, docker/generic-worker-config.json, infrastructure/tooling/src/generate/generators/docker-compose.js, workers/generic-worker/README.md, workers/generic-worker/expose/local.go, workers/generic-worker/expose/local_test.go, workers/generic-worker/gwconfig/config.go, workers/generic-worker/main.go, workers/generic-worker/usage.go
By default it will remain `0` and so port would be allocated dynamically.
But for local development environment where generic-worker runs inside the container, and `livelog` binary is executed within same container, assigning ports dynamically would make it hard to expose it using static `docker-compose.yml` file. 
This way we provide predefined port that will be used to expose livelog, which then could be accessed on the host and in the UI.
generic worker config may look like this:
```json
"publicIP": "127.0.0.1",
"livelogPortBase": 60000,
"livelogExposePort": 59999
```
This means it would run `livelog` with `60000`, `60001` ports, and read port would be exposed on `59999` port, which will be used for the reference artifact, and would make it accessible in the UI.
Fixes #6395
=> Livelog working in local dev env

changelog/issue-5967.md, clients/client-go/codegenerator/model/api.go, clients/client-go/tcauth/types.go, clients/client-go/tchooks/types.go, clients/client-go/tchooksevents/types.go, clients/client-go/tcobject/types.go, clients/client-go/tcqueue/types.go, generated/references.json, taskcluster/ci/go/kind.yml, tools/d2g/d2g.go, tools/d2g/d2gtest/d2g_test.go, tools/d2g/genericworker/generated_types.go, tools/jsonschema2go/jsonschema.go, ui/docs/reference/workers/generic-worker/README.mdx, workers/generic-worker/d2g_test.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/helper_test.go, workers/generic-worker/main.go, workers/generic-worker/payload_darwin.go, workers/generic-worker/payload_freebsd.go, workers/generic-worker/payload_linux.go, workers/generic-worker/payload_windows.go, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml, workers/generic-worker/schemas/simple_posix.yml
Fixes #5967.
>This change integrates the `d2g` tool into Generic Worker so that it can accept a valid, Docker Worker payload.
=> feat(generic-worker): integrate `d2g` to interpret docker worker payloads

changelog/issue-6405.md, services/queue/src/utils.js, services/queue/test/expireartifacts_test.js, services/queue/test/helper.js
GCS throws `NoSuchKey` errors when artifact is not found during deletion, whereas S3 would always say 204.
Added separate tests for GCS-like S3 implementation with no `deleteObjects` support and different `deleteObject` behaviour
Fixes #6405
=> Handle GCS expire artifacts errors

changelog/issue-6420.md, workers/generic-worker/main.go
Fixes #6420.
>Fixes generic worker issue where artifacts were no longer being uploaded.
Introduced in https://github.com/taskcluster/taskcluster/pull/6355.
=> fix(generic-worker): set default payload fields

changelog/VJk2Ow6nQXKOZVg-HbA3ZQ.md, infrastructure/tooling/src/changelog/index.js
Though, the previous arguments technically worked on a local machine, it seems like the regex filtering doesn't work when running the `child_process.execFile()` function (what is used to call `git log ...`).
=> fix(changelog): correctly filter on git log author

infrastructure/tooling/src/changelog/index.js
I shouldn't have changed the formatting in https://github.com/taskcluster/taskcluster/pull/6431/files#diff-cadf460b1bafdecb8698d80a7010dbfdd292ed039b1c0c1570a3c3c34e7e1612R122, it was literally putting `'` around each line item update.
=> fix(changelog): small formatting fix [skip ci]

changelog/YwSnRwj5QSO-5EIvR50r5A.md, workers/generic-worker/main.go
>Adds a task log letting the user know their Docker Worker payload is being converted to a Generic Worker payload using d2g.
=> chore(generic-worker): extra d2g log

changelog/issue-6405.md, generated/references.json, services/queue/src/main.js, services/queue/src/monitor.js, services/queue/src/utils.js, services/queue/test/expireartifacts_test.js
Instead, debug level is used and total errors count is added to the resulting log message.
This is because GCS throws errors unlike AWS when deleted object is missing, which results in millions of reported objects (which were removed manually before migration)
follow up on #6405
=> Expire artifacts don't report errors on each missing object

changelog/OjoTb8YJSOKqGJaeMM-gKQ.md, ui/docs/manual/using/namespaces.mdx
Some doc fixes.
Note, we should probably auto generate this doc based on the `project-admin:*` role, since they easily get out of sync with each other. However, it is specific to community-tc, and is a convention rather than a requirement, so that might not be so straightforward. I also noticed that role has some non-project scopes in there, which doesn't seem right, but I will look at that in a separate PR (presumably configured in community-tc-config repo, so a PR for that repo instead).
=> Parameterized role doc fixes

changelog/Ql7JTgMMTYq6vzHdD1CncQ.md, workers/generic-worker/interactive/interactive_test.go, workers/generic-worker/interactive_test.go
I added that when fixing test failures in
dca2377bc8a27cdc6e4ee928a95058b7f53ca528 and
i6026a3fa263175550cda877a6d7b9123301becc7 in the hope that it would make tests fail faster instead of deadlocking should something go wrong with my patch.
Turns out it added a new kind of intermittent test failure because the interactive process could exit before we finish, signal it, close the server-side websocket before the test is done reading from it.
=> Don't force the interactive process to exit

changelog/issue-6438.md, ui/src/views/Tasks/ViewTask/index.jsx
Fixes https://github.com/taskcluster/taskcluster/issues/6438.
>`dependencies` are no longer removed from the task definition when you `Edit` or `Retrigger` a task.
=> fix(ui): don't remove task dependencies on edit/retrigger

changelog/issue-5995.md, generated/references.json, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/genericworker/generated_types.go, workers/generic-worker/README.md, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/gwconfig/config.go, workers/generic-worker/loopback_audio_darwin.go, workers/generic-worker/loopback_audio_darwin_test.go, workers/generic-worker/loopback_audio_freebsd.go, workers/generic-worker/loopback_audio_freebsd_test.go, workers/generic-worker/loopback_audio_linux.go, workers/generic-worker/loopback_audio_linux_test.go, workers/generic-worker/loopback_audio_posix.go, workers/generic-worker/main.go, workers/generic-worker/multiuser_posix.go, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/simple_posix.yml, workers/generic-worker/simple.go, workers/generic-worker/usage.go
Fixes #5995.
>Generic Worker: Adds `task.payload.feature.loopbackAudio` for loopback audio device support on Linux.
>
>The `snd-aloop` kernel module must be installed on the host system for this feature to work, although it does not _need_ to be loaded. Generic Worker loads the module with `modprobe` and generates the virtual audio device with a `snd-aloop` command. Under the multiuser engine, it also manages file ownership of the device with `chown` to ensure that only tasks with suitable scopes have read/write access to the virtual device.
>
>For tasks that enable the feature, the virtual audio device will be found at `/dev/snd`. Devices inside that directory will take the form `/dev/snd/controlC<DEVICE_NUMBER>`, `/dev/snd/pcmC<DEVICE_NUMBER>D0c`, `/dev/snd/pcmC<DEVICE_NUMBER>D0p`, …
=> feat(generic-worker): add loopbackAudio support

changelog/U4SFSYxkTWW283bMcwZdbg.md, workers/generic-worker/payload_linux.go
>Generic Worker: If a Docker Worker payload is received, the resulting, d2g-translated Generic Worker payload will be logged out to the user.
=> feat(generic-worker): log out d2g translated payload

changelog/issue-6513.md, infrastructure/tooling/src/release/tasks.js, taskcluster/ci/generic-worker/kind.yml
The CI file for generic-worker was moved in https://github.com/taskcluster/taskcluster/commit/13c21c268bfc62726064ece7740b7ad92d70e21b
but the release script wasn't updated to accomodate that. One of the
command needs the version to match the current release and was
automatically updated by the release script. After the path change, that
version fell out of sync leading to CI failures because some linker
argument was wrong and it wasn't setting the `revision` parameter.
Github Bug/Issue: Fixes #6513
=> Also change the version in generic worker CI files on release

.github/dependabot.yml, changelog/OdCDYxRzSsaA8ACNx6LeDw.md
I felt like `build(deps-dev): bump the deps-dev group in /clients/client with 1 update` sounded a little strange for a PR title, so dropped the `-dev` part so it'll read, `build(deps-dev): bump the deps group in /clients/client with 1 update` in future PRs.
=> Rename dependabot groups

changelog/A3EkBRJlRkSxwkS-Ke50BA.md, tools/d2g/d2g.go
Fixes: https://github.com/taskcluster/taskcluster/security/code-scanning/318
Note, this updated implementation is marginally less efficient, but removes the warning, which is kind of bogus, since practically I don't think it would be possible to hit the limits with a real payload, as the payload would have to be so big, I suspect some other limit would prevent such a task being created anyway.
=> Fix code-scanning #318: possible overflow

changelog/QdL_EujxRpqk_Q5V_eKAfA.md, go.mod, workers/generic-worker/gw-codegen/main.go
This is just a trivial simplification, I don't know why I used the more complicated form originally, quite bizarre.
=> no-op: simplify string replacement expression in gw-codegen

changelog/issue-6521.md, workers/generic-worker/d2g_test.go, workers/generic-worker/main.go, workers/generic-worker/payload_linux.go
This is a follow on from [#6491](https://github.com/taskcluster/taskcluster/pull/6491#pullrequestreview-1602787612) to include full task definition when showing the output of the internal d2g conversion process.
=> d2g: log full task definition rather than just task payload

changelog/issue-6534.md, infrastructure/k8s/templates/taskcluster-auth-cron-purgeExpiredClients.yaml, infrastructure/k8s/templates/taskcluster-github-cron-sync.yaml, infrastructure/k8s/templates/taskcluster-hooks-cron-expires.yaml, infrastructure/k8s/templates/taskcluster-index-cron-expire.yaml, infrastructure/k8s/templates/taskcluster-object-cron-expire.yaml, infrastructure/k8s/templates/taskcluster-purge-cache-cron-expireCachePurges.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireArtifacts.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireQueueMessages.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTask.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskDependency.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireTaskGroups.yaml, infrastructure/k8s/templates/taskcluster-queue-cron-expireWorkerInfo.yaml, infrastructure/k8s/templates/taskcluster-secrets-cron-expire.yaml, infrastructure/k8s/templates/taskcluster-web-server-cron-cleanup-expire-access-tokens.yaml, infrastructure/k8s/templates/taskcluster-web-server-cron-cleanup-expire-auth-codes.yaml, infrastructure/k8s/templates/taskcluster-web-server-cron-scanner.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-cron-expire-errors.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-cron-expire-worker-pools.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-cron-expire-workers.yaml, infrastructure/tooling/templates/k8s/cron.yaml
This is also preventing production clusters from being upgraded to 1.25
Fixes #6534
=> Upgrade CronJobs to use latest batch/v1 api

changelog/IqAgAVXDQyWlJus1Tgdp4A.md, dev-docs/development-process.md, docker/cleanup-images.sh
I realised that we do releases very often, and each new release bring new image version. 
Over time they pile up and may take 10gb+ of disk space on local development machine.
This is only for the images that are referenced in `docker-compose.yml`
=> Provide a script to remove all unused taskcluster images locally

changelog/issue-5514.md, db/README.md, db/test-setup.sh, dev-docs/dev-deployment.md, dev-docs/development-process.md, docker-compose.yml, infrastructure/docker-images/build-ci-image.sh, infrastructure/tooling/src/generate/generators/docker-compose.js, libraries/azqueue/test/slow_test.js, libraries/postgres/README.md, libraries/postgres/src/Database.js, libraries/postgres/src/constants.js, taskcluster/src/transforms/__init__.py, ui/docs/manual/deploying/database.mdx
Fixes https://github.com/taskcluster/taskcluster/issues/5514.
Note, once this lands, we will upgrade our dev cluster's db to pg15 and ensure things are working. From there, we'll do community tc, then let SREs know about the ending support of v11. At that time, it might be best for them to make a copy of the pg11 db, and perform the upgrade to v15, just to see what the expected downtime might be while running the upgrade on Firefox CI.
>Adds support for postgres version 15.
>
>Note: if you want to migrate your local dev db to pg15, you'll need to either erase the existing db with `docker volume rm taskcluster_db-data` before you migrate, or, if you'd prefer to keep your local dev data, you'll need to manually dump the db contents and then import them into the upgraded db.
>
>Support for …
=> chore(db): allow for pg v15

changelog/issue-6540.md, workers/generic-worker/mounts.go, workers/generic-worker/mounts_test.go
=> Generic Worker: fix nil pointer dereference in Evict(*TaskMount)

changelog/issue-6543.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/dw_features_tests.yml, tools/d2g/d2gtest/testdata/testcases/no_artifacts_test.yml
Fixes https://github.com/taskcluster/taskcluster/issues/6543. Thanks for the suggestion @jschwartzentruber!
>Generic Worker: d2g no longer passes the environment variable values to the `podman run` command. Instead, just the variable name is passed as `-e VAR` which tells podman to take the value from the host. This will tidy up the run command and will help with any escaping issues users may have been having.
=> fix(d2g): only pass env var name

changelog/issue-6488.md, workers/generic-worker/artifacts.go
=> Issue 6488 - Generic Worker no longer panics on IO errors while scanning file system for artifacts

changelog/issue-6470.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml
=> Issue 6470: D2G now properly escapes artifact path in podman cp commands

changelog/Y3Q62wgKQpGVDp06fZF5xg.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/dockerimageartifact.go, tools/d2g/dockerimagename.go, tools/d2g/indexeddockerimage.go, tools/d2g/nameddockerimage.go
>D2G now takes advantage of Generic Worker Indexed Artifacts, introduced in Generic Worker 51.0.0. D2G translates Indexed Docker Images into Generic Worker mounted Indexed Artifacts. Previously, D2G generated commands to query the taskcluster Index and fetch the docker image.
>With this improvement, docker images are now cached on workers, docker image dependencies between tasks are declarative (and thus inspectable), and generated Generic Worker task payloads are simpler and easier to understand.
=> feat(d2g): use gw indexed artifact type

changelog/issue-6569.md, services/hooks/src/api.js
Fixes https://github.com/taskcluster/taskcluster/issues/6569.
>This patch updates the regex for the `hookGroupId` and `hookId` params for the hooks API to allow for up to 1000 characters.
cc @ahal
=> fix(hooks): allow for 1000 characters in `hookGroupId` and `hookId`

.goreleaser.yaml, changelog/issue-6571.md, infrastructure/tooling/src/build/tasks/client-shell.js
Fixes #6571. View issue to see deprecation notices.
This also pins `goreleaser` to the latest version that worked on our most recent release, v1.20.0.
=> fix(release): replace deprecated goreleaser config

changelog/djZWGa-3S2O7AJWcR_aKfA.md, workers/generic-worker/artifacts.go, workers/generic-worker/artifacts/artifacts.go, workers/generic-worker/artifacts/error.go, workers/generic-worker/artifacts/link.go, workers/generic-worker/artifacts/object.go, workers/generic-worker/artifacts/redirect.go, workers/generic-worker/artifacts/s3.go
System commands such as copy (Windows) or cp (Linux/macOS/FreeBSD) provide useful output when commands fail. Elsewhere we have been using system commands for such things, let's do this for copying files too.
This is part 1, which separates out the optional gzip compression from the file copy, in preparation for using the system copy command in future.
=> Generic Worker: Use system copy command for better logging

changelog/cBmAFvklRfu3hYByRUiRGA.md, generated/references.json, tools/d2g/genericworker/generated_types.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/generated_simple_darwin.go, workers/generic-worker/generated_simple_freebsd.go, workers/generic-worker/generated_simple_linux.go, workers/generic-worker/purge_caches_test.go, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml, workers/generic-worker/schemas/simple_posix.yml
I was trying to abuse the caching system to download a binary that I was developing on another machine to run in a task. Took me by surprise that it didn't allow automatically purging the cache when the command succeeded. As far as I can tell, docker-worker did not have such a limit and I don't see why there should be one anyway.
=> Allow specifying `0` as a value for `onExitStatus.purgeCaches`

changelog/issue-6621.md, taskcluster/ci/generic-worker/kind.yml, taskcluster/ci/meta/kind.yml, taskcluster/src/transforms/__init__.py
Fixes #6621.
This only applied to the go tasks, as they'd fail if there was a lint error.
=> chore(ci): add deps to help not waste resources

.env, changelog/RxEk8HJ3QDKaVsXGGYga1w.md, docker-compose.dev.yml, docker-compose.yml, docker/cleanup-images.sh, infrastructure/tooling/src/generate/generators/docker-compose.js, infrastructure/tooling/src/release/tasks.js
Version tags were changed after each release which resulted in all compose files being changed. 
This introduces unnecessary changes in history.
This will keep changing versions in `.env` file and `docker-compose*` files would reference it using `image: ${IMAGE}` format, as `docker` by default reads variables from `.env` file
=> feat(docker): Move image names into .env file

changelog/G8Sjop3gSmqQSIC3xgPbuQ.md, clients/client-go/tchooks/types.go, generated/references.json, services/hooks/.babelrc, services/hooks/schemas/v1/list-lastFires-response.yml, services/hooks/src/api.js, services/hooks/test/api_test.js
This [hook](https://firefox-ci-tc.services.mozilla.com/hooks/project-releng/cron-task-mozilla-central%2Fship-geckoview) has tasks that expire after 7d, so no longer available. Displaying `"unscheduled"` as its state might not be accurate, as they were scheduled at that time.
=> Hook service display 'unknown' state when task doesn't exist anymore

changelog/Akx0pTXSTUuwG6T9qqHxBA.md, workers/docker-worker/src/task.js
It turns out seeing `[object Object]` in the task log isn't too helpful.
This is untested, and rather academic as we're not deploying updated docker-workers, but maybe it's trivial enough that it's still worth it?
=> docker-worker: stringify scope expressions in error message

changelog/issue-6472.md, tools/d2g/d2g.go, tools/d2g/d2gtest/d2g_test.go, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml, workers/generic-worker/payload_linux.go
Fixes https://github.com/taskcluster/taskcluster/issues/6472.
>D2G: Add the `kvm` OS group to the Generic Worker payload if the KVM device is enabled in the Docker Worker payload.
Keeping in WIP for now until we can get a working test to prove we need the task user added to these groups.
=> fix(d2g): add `kvm` OS group for KVM feature

changelog/issue-6634.md, services/queue/src/workclaimer.js, services/queue/test/hintpoller_test.js, services/queue/test/workclaimer_test.js
In some rare conditions, `queue.claimWork` was throwing `500` errors.
This happened because of the changes introduced in recent [queue internals refactoring](https://github.com/taskcluster/taskcluster/commit/3cdec1d6a1c92201cecc5da244f21f05ea67d357#diff-07d1f6e8072664349e5c609273873df2ca0904b88f917517eec8ba91e4ec6a26 )
Adding tests for `HintPoller` and `WorkerClaimer` and making sure destroyed hint poller doesn't interfere with other calls
Fixes #6634
=> Fix `claimWork` returning `500`

Dockerfile, changelog/issue-6636-1.md
This should've been removed in #6646.
Found this issue in https://github.com/taskcluster/taskcluster/runs/18228850091.
>Fix Dockerfile from PR #6646. The `.yarn` directory does not exist anymore, so it shouldn't be copied.
=> fix: remove .yarn COPY commands

changelog/issue-6656.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/env_escaping_test.yml
Fixes https://github.com/taskcluster/taskcluster/issues/6656.
>D2G now shell escapes environment variable key names in case they contain spaces or special characters that would previously mess up the `podman run...` command.
=> fix(d2g): shell escape env var names

changelog/bug-1855653.md, clients/client-go/tcqueue/types.go, generated/references.json, services/queue/schemas/v1/post-artifact-request.yml, tools/d2g/d2gtest/testdata/testcases/env_escaping_test.yml, ui/docs/reference/workers/generic-worker/installing.mdx, workers/generic-worker/README.md, workers/generic-worker/artifacts.go, workers/generic-worker/artifacts/artifacts.go, workers/generic-worker/artifacts/error.go, workers/generic-worker/artifacts/link.go, workers/generic-worker/artifacts/object.go, workers/generic-worker/artifacts/redirect.go, workers/generic-worker/artifacts/s3.go, workers/generic-worker/artifacts_multiuser.go, workers/generic-worker/artifacts_multiuser_test.go, workers/generic-worker/artifacts_simple.go, workers/generic-worker/artifacts_test.go, workers/generic-worker/chain_of_trust.go, workers/generic-worker/fileutil/fileutil.go, workers/generic-worker/helper_multiuser_test.go, workers/generic-worker/helper_simple_test.go, workers/generic-worker/helper_test.go, workers/generic-worker/main.go, workers/generic-worker/process/multiuser_posix.go, workers/generic-worker/process/multiuser_windows.go, workers/generic-worker/rdp_windows.go, workers/generic-worker/usage.go
Fixes Bugzilla Bug 1855653.
>Generic Worker: The `generic-worker` binary _must be_ readable and executable by the task user. If it's not, artifact uploads _will fail_.
>
>Generic Worker: Add `copy-to-temp-file` subcommand to `generic-worker` to copy a file (`--copy-file`) to a temporary file.
=> feat(generic-worker): add `copy-to-temp-file` subcommand

changelog/cNPiQAqZTEeqDmtRcz-kKQ.md, ui/docs/reference/workers/generic-worker/installing.mdx, workers/generic-worker/artifacts.go, workers/generic-worker/artifacts_multiuser.go, workers/generic-worker/artifacts_simple.go, workers/generic-worker/fileutil/fileutil_posix.go, workers/generic-worker/fileutil/fileutil_windows.go, workers/generic-worker/main.go, workers/generic-worker/multiuser_test.go, workers/generic-worker/process/multiuser_windows.go, workers/generic-worker/runtime/runtime.go, workers/generic-worker/runtime_multiuser.go, workers/generic-worker/runtime_simple.go
As a follow-up to https://github.com/taskcluster/taskcluster/pull/6673, this change will check to ensure that the generic-worker binary is readable and executable by the task user. If not, the worker will exit with exit code 69, internal error.
>Generic Worker: Adds validation that the task user is able to read and execute the generic-worker binary on startup of the worker. If the task user is not able to read and execute the binary, the worker will exit with exit code 69, internal error.
=> fix(generic-worker): validate the task user can read/execute the generic-worker binary

changelog/issue-6701.md, workers/generic-worker/runtime_simple.go
Fixes #6701.
>Generic Worker: Fixes `permission denied` error while checking if `generic-worker` binary is executable by the task user for simple engine.
=> fix(generic-worker): fix gwVersion check on simple engine

changelog/issue-5514.md, db/README.md, dev-docs/best-practices/db.md, dev-docs/dev-deployment.md, dev-docs/development-process.md, libraries/postgres/README.md, libraries/postgres/src/Database.js, ui/docs/manual/deploying/database.mdx
Related to #5514. Now that we've upgraded all of our deployments' pg databases to v15, we can drop v11.
>Removes postgres v11 support.
=> chore(db)!: remove pg11 support

changelog/issue-6739.md, workers/generic-worker/README.md, workers/generic-worker/usage.go
Fixes https://github.com/taskcluster/taskcluster/issues/6739.
>Generic Worker: Updates `--help` text to include missing exit codes (76, 79, and 80).
=> chore(generic-worker): update help text

changelog/issue-6641.md, services/worker-manager/src/estimator.js, services/worker-manager/test/estimator_test.js
The estimator subtracts stopping workers from the desired capacity, but they're not actually useful capacity.  So we now also count them as part of the desired capacity, to make sure not to exceed maxCapacity while not otherwise preventing the spawning of new workers.
Github Bug/Issue: Fixes #6641
=> worker-manager: take stopping instances into account for desired capacity

changelog/issue-6759.md, infrastructure/k8s/templates/taskcluster-auth-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-built-in-workers-deployment-server.yaml, infrastructure/k8s/templates/taskcluster-github-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-github-deployment-worker.yaml, infrastructure/k8s/templates/taskcluster-hooks-deployment-listeners.yaml, infrastructure/k8s/templates/taskcluster-hooks-deployment-scheduler.yaml, infrastructure/k8s/templates/taskcluster-hooks-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-index-deployment-handlers.yaml, infrastructure/k8s/templates/taskcluster-index-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-notify-deployment-handler.yaml, infrastructure/k8s/templates/taskcluster-notify-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-object-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-purge-cache-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-queue-deployment-claimResolver.yaml, infrastructure/k8s/templates/taskcluster-queue-deployment-deadlineResolver.yaml, infrastructure/k8s/templates/taskcluster-queue-deployment-dependencyResolver.yaml, infrastructure/k8s/templates/taskcluster-queue-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-references-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-secrets-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-ui-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-web-server-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-deployment-provisioner.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-deployment-workerscanner-azure.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-deployment-workerscanner.yaml, infrastructure/tooling/templates/k8s/deployment.yaml, libraries/app/src/index.js
This changes container lifecycle in kubernetes, therefor a major version.
- web containers no longer killed daily and will be running as long as process responds to `livenessProbe`. (There are no indications that containers leak memory or use large amounts of CPU when running longer than few days)
- non-web containers keep the old logic, but will be terminated after 5 days instead (experiment to see if this can be removed or better not)
- tweaks `initialDelaySeconds` for readiness probe, as `3` was too short and caused too many errors to be logged.
- additionally listens to `SIGINT`
- grace termination period increased to `120s` (k8s will not kill stopping pod for so long)
- `lifecycle.preStop` sleep timeout reduced to `10s` because this happens before container's process receives …
=> Kubernetes config improvements

changelog/issue-6762.md, taskcluster/src/transforms/__init__.py, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/dw_features_tests.yml, tools/d2g/d2gtest/testdata/testcases/env_escaping_test.yml, tools/d2g/d2gtest/testdata/testcases/no_artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml
Fixes https://github.com/taskcluster/taskcluster/issues/6762.
>Generic Worker: Tasks internally translated by D2G will add exit code 128 to the retry exit status array for retrying on an intermittent docker image pull issue.
=> fix(d2g): auto retry on exit code 128

changelog/websocktunnel-dev.md, tools/websocktunnel/.gitignore, tools/websocktunnel/Dockerfile, tools/websocktunnel/README.md, tools/websocktunnel/cmd/wst-client/main.go, tools/websocktunnel/start-dev.sh
I managed to get a local websocktunnel and generic worker talking to each other with these instructions. (I used the firefox ci staging taskcluster deployment for the core services - hence the necessary hacks around auth.)
=> websocktunnel local dev improvements

changelog/issue-6779.md, workers/generic-worker/interactive/interactivejob.go
=> Issue #6779 - generic-worker (interactive feature): fix data race of cmd.ProcessState

changelog/issue-6785.md, workers/generic-worker/README.md, workers/generic-worker/chain_of_trust.go, workers/generic-worker/chain_of_trust_test.go, workers/generic-worker/main.go, workers/generic-worker/multiuser.go, workers/generic-worker/simple.go, workers/generic-worker/usage.go, workers/generic-worker/usage_multiuser.go, workers/generic-worker/usage_simple.go
=> Generic Worker: exit with exit code 82 if chain of trust key missing

changelog/Tvnvy_n2T5SCY2pHwdYHVA.md, workers/generic-worker/mounts.go, workers/generic-worker/mounts_test.go
>Generic Worker now copies archives to the task user's directory before unarchiving.
=> fix(generic-worker): copy archive to task user dir before unarchiving

changelog/issue-6801.md, clients/client-go/tcnotify/tcnotify.go, clients/client-py/taskcluster/generated/aio/notify.py, clients/client-py/taskcluster/generated/notify.py, clients/client-rust/client/src/generated/notify.rs, clients/client-shell/apis/services.go, clients/client-web/src/clients/Notify.js, clients/client/src/apis.js, generated/references.json, libraries/pulse/src/publisher.js, services/notify/src/api.js, services/notify/src/notifier.js, services/notify/test/notifier_test.js
Sending multiple messages to the same channel would fail if it contained same `text` but different `blocks` or `attachments` because they were considered to be duplicate.
This also introduces `204` status code to give clients information that this particular call did not result in actual sending of the message, as it was detected to be duplicate.
Fixes #6801
=> Slack notification fix

changelog/beo_hKEkRr25Ph8pVPtaew.md, tools/worker-runner/provider/azure/azure.go, tools/worker-runner/provider/google/google.go
>Worker Runner now checks for termination notice when starting the Google provider.
>
>When Worker Runner runs, the instance may already be scheduled to be shutdown. So on Google provider startup, we now check for this case.
>
>This functionality mimics what's already in place for AWS.
>
>This change also decreases the time Worker Runner checks to see if the instance is scheduled to be shutdown from 30 seconds to 15 seconds on the Google and Azure providers, as they each have a 30 second notice before a hard-shutdown Google: https://cloud.google.com/compute/docs/instances/spot#preemption-process Azure: https://learn.microsoft.com/en-us/azure/virtual-machines/spot-vms.
=> fix(worker-runner): check for Google spot instance termination on provider startup

.github/workflows/codeql.yml, changelog/TLgA6zOvTbOdLlQpFuUUAw.md
Fixes this https://github.com/taskcluster/taskcluster/security/code-scanning/tools/CodeQL/status/configurations/actions-FZTWS5DIOVRC653POJVWM3DPO5ZS6Y3PMRSXC3BOPFWWY/405aa96584f48822b00d6c0830c4a80093f1384ddb9dbab00cd29577f4fc4f1e.
=> chore: fix CodeQL autobuild for go

changelog/issue-6820.md, ui/src/components/ClientScopesTable/index.jsx, ui/src/components/RoleScopesTable/index.jsx
Fixes roles and clients view, which were not filtered properly:
Fixes #6820
=> feat(ui): Fixes role/clients filtering in the UI

changelog/SVcOpPCVQ3OUmfcb69qt7A.md, clients/client-go/README.md, clients/client-go/codegenerator/model/model.go
AMQP API links were in HTTP section, HTTP API links were in AMQP section 😬
Introduced in #2666.
=> Go client doc fix

changelog/ZFQORwwvQTeyGaX83Csyag.md, clients/client-go/codegenerator/model/model.go, clients/client-go/tcauth/tcauth.go, clients/client-go/tcauthevents/tcauthevents.go, clients/client-go/tcgithub/tcgithub.go, clients/client-go/tcgithubevents/tcgithubevents.go, clients/client-go/tchooks/tchooks.go, clients/client-go/tchooksevents/tchooksevents.go, clients/client-go/tcindex/tcindex.go, clients/client-go/tcnotify/tcnotify.go, clients/client-go/tcnotifyevents/tcnotifyevents.go, clients/client-go/tcobject/tcobject.go, clients/client-go/tcpurgecache/tcpurgecache.go, clients/client-go/tcqueue/tcqueue.go, clients/client-go/tcqueueevents/tcqueueevents.go, clients/client-go/tcsecrets/tcsecrets.go, clients/client-go/tcworkermanager/tcworkermanager.go, clients/client-go/tcworkermanagerevents/tcworkermanagerevents.go
This line break was removed in #2666 but was intentionally included so that the comment about auto-generation is a code comment, not a package comment. It has no value for users to see this comment in the generated go docs. They simply wish to know how to use the package, and do not care that the docs are auto-generated. Developers care, because they need to know they should not be making manual changes to the file, which is why it is included as a code comment, and should not be part of the go docs.
=> Go client doc fix - some more fallout from #2666

changelog/S9g9IeHnRVGoyV0E1TTK6g.md, infrastructure/k8s/templates/taskcluster-auth-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-built-in-workers-deployment-server.yaml, infrastructure/k8s/templates/taskcluster-github-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-github-deployment-worker.yaml, infrastructure/k8s/templates/taskcluster-hooks-deployment-listeners.yaml, infrastructure/k8s/templates/taskcluster-hooks-deployment-scheduler.yaml, infrastructure/k8s/templates/taskcluster-hooks-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-index-deployment-handlers.yaml, infrastructure/k8s/templates/taskcluster-index-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-notify-deployment-handler.yaml, infrastructure/k8s/templates/taskcluster-notify-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-object-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-purge-cache-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-queue-deployment-claimResolver.yaml, infrastructure/k8s/templates/taskcluster-queue-deployment-deadlineResolver.yaml, infrastructure/k8s/templates/taskcluster-queue-deployment-dependencyResolver.yaml, infrastructure/k8s/templates/taskcluster-queue-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-references-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-secrets-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-ui-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-web-server-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-deployment-provisioner.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-deployment-workerscanner-azure.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-deployment-workerscanner.yaml, infrastructure/tooling/templates/k8s/deployment.yaml
This combination has proven to be efficient for kubernetes which reduces significantly all (or most of) 502s
Those numbers were applied on the cluster directly during experimentation period, and this is simply to have them configured in the code
=> feat(k8s): Add sufficient timeouts and delays for 502 issue

changelog/issue-6795.md, ui/src/views/Tasks/TaskLog/index.jsx
To avoid seeing link expired errors we  need to refresh it
Fixes #6795 
Fixes #5033
=> Refreshes raw log url before opening it

changelog/issue-6848.md, ui/src/components/Shell/index.jsx, workers/generic-worker/interactive/interactivejob.go
There's 2 parts to this. First, the worker was using a `TextMessage` for websockets which would assume the message was valid UTF-8. This ended up being the main issue, it would just close the websocket when it saw invalid UTF-8.
The second part was the DECODER (which wasn't used in version 2 of interactive sessions until now), which was spamming the console with errors when it received invalid UTF-8.
Fixing both of those allows one to see invalid UTF-8 output in their interactive sessions.
I kept backwards compatibility with generic-worker which are still sending `TextMessage` messages by checking that the received data is a string and kept the old behavior in that case.
Fixes #6848
=> Don't close the websocket when invalid UTF-8 is output by an interactive session

changelog/issue-6850.md, workers/generic-worker/multiuser_posix.go, workers/generic-worker/simple.go
The `TERM` environment variable is used to indicate the capabilities of the current terminal emulator. Applications use it to know whether they can use some features or not. An example of that is tmux which looks for the `clear` capability which is missing from the default `TERM` assigned by bash (`dumb`).
Thankfully this was fairly easy as `hterm` is a supported terminal.
Github Bug/Issue: Fixes #6850
=> Add a proper `TERM` environment variable to interactive sessions

changelog/d_PriigFRCas7ER_z3UwpA.md, ui/src/components/Shell/index.jsx
It looks like this is broken on first load, due to the second `resize` call, as well as on resize (onTerminalResize and DockerExecClient.resize's arg order doesn't match).
There's an initial `this.client.resize.apply` call which is correct...and seems like it doesn't need to exist...but this is working fine so it seems best not to try to remove it.
=> Fix docker worker shell UI to set row/cols properly

changelog/issue-6864.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml
=> Issue 6864: D2G: pass --privileged to podman run when passing --device=/dev/shm

changelog/AuLw2QSJTYishObr92Sz7A.md, services/web-server/src/main.js, services/web-server/test/graphql/validation_test.js, services/web-server/test/helper.js
Since validationRules property was misplaced before, it didn't do anything, so this problem wasn't caught. After it complained about hooksGroup query validation complexity. As that query includes lists and queries external entities with additional queries, complexity rises to ~4000.
=> Fix validation error for hooks page

changelog/issue-6881.md, services/worker-manager/src/providers/google.js, services/worker-manager/test/provider_google_test.js, ui/docs/reference/core/worker-manager/google.mdx
Fixes #6881
Note, `zone` is a [required](https://github.com/taskcluster/taskcluster/blob/d34967f798d91ec794bcec4556682e1f932fda55/services/worker-manager/schemas/v1/config-google.yml#L94) property in launch config, so no risk that only `region` is specified in worker pool definition. This is different to AWS, where `region` [is specified](https://github.com/taskcluster/taskcluster/blob/4c9c284a8afda18ec3e163a8be198450128a3ef0/services/worker-manager/schemas/v1/config-aws.yml#L66), but `availabilityZone` is not.
=> Issue 6881: google cloud workers workerGroup set to zone rather than region

changelog/Ap0wKwVAT-CSQUTGw7gOtw.md, workers/generic-worker/interactive.go
>Generic Worker: fixed incorrect log line when an Interactive Task fails due to the worker pool config not being set.
=> fix(generic-worker): fix malformed payload log when enabling interactive task

changelog/XqmVDnNSQeaUj-43ZuK1Sw.md, workers/generic-worker/artifacts.go, workers/generic-worker/multiuser_windows.go, workers/generic-worker/simple_test.go
>Generic Worker now utilizes `filepath.WalkDir` instead of `filepath.Walk`.
>
>`filepath.WalkDir` was introduced in go1.16 and is more performant and efficient over `filepath.Walk`.
>
>This _may_ help with race conditions during artifact uploads, where a file was initially seen, but then became unavailable at upload time.
From https://pkg.go.dev/path/filepath#Walk:
>Walk is less efficient than [WalkDir](https://pkg.go.dev/path/filepath#WalkDir), introduced in Go 1.16, which avoids calling os.Lstat on every visited file or directory.
=> chore(generic-worker): use `filepath.WalkDir`

.github/dependabot.yml, changelog/D6MDNkAhSZ6PE5MPGJPp3Q.md
This'll help make it more clear _which_ dependencies are being upgraded. vs what we have now, it's a little unclear https://github.com/taskcluster/taskcluster/releases/tag/v61.0.0.
=> chore(dependabot): rename update groups

changelog/SpXAnuHoR-eCCnQRLNqCGQ.md, clients/client-test/package.json, clients/client-test/yarn.lock, clients/client/package.json, clients/client/src/apis.js, clients/client/src/client.js, clients/client/src/download.js, clients/client/src/hashstream.js, clients/client/src/index.js, clients/client/src/parsetime.js, clients/client/src/retry.js, clients/client/src/upload.js, clients/client/src/utils.js, clients/client/test/client_test.js, clients/client/test/credinfo_test.js, clients/client/test/creds_test.js, clients/client/test/helper.js, clients/client/test/upload_download_test.js, clients/client/test/utils_test.js, clients/client/yarn.lock, infrastructure/tooling/src/generate/generators/tc-client.js, package.json, services/worker-manager/src/providers/azure/index.js, yarn.lock
Having CJS only was blocking some of the dependency upgrades which switched to ESM only distributions
`stream-buffers` was removed since it was only used in tests and could be rewritten using Readable/Writable streams from stdlib
=> Client-node rewritten to ESModules

changelog/N39Wr4udTH-1jL1N6rTggw.md, ui/src/views/Tasks/submitTaskAction.js
This is in support of making actions like "Cancel All" work on task groups that have been created by an Action Task (see https://github.com/mozilla/firefox-translations-training/issues/250).
In an ideal world I'd like to understanding how `task.decisionTask` fits into things a bit more, and see if it could be removed...but that's more work than I'm willing to put in at the moment. I think this is a fairly safe fix to take in the meantime.
=> Ensure 'taskGroup' is always defined when fetching scopes for submitting an action task

changelog/C7wI7jeHQHe41TMMOOrVYA.md, generated/references.json, tools/d2g/dockerworker/generated_types.go, tools/d2g/genericworker/generated_types.go, workers/docker-worker/schemas/v1/payload.yml, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/schemas/multiuser_posix.yml
We added support for configurable maxRunTime in generic worker in https://github.com/taskcluster/taskcluster/pull/6465. We're now converting our existing docker-worker tasks over to d2g/generic-worker, some of which require a higher maxRunTime than generic-worker's docker-worker schema allows for. I believe this patch will fix that.
I did notice that there's also the same limit in https://github.com/taskcluster/taskcluster/blob/main/workers/docker-worker/schemas/v1/payload.yml, but seeing as docker-worker is deprecated, I don't think it's worthwhile to make any changes there.
(And for completeness: the docker worker maxRunTime was _reduced_ in https://github.com/taskcluster/taskcluster/pull/6019/files, but the version we're running allows for the old `604800` limit, which is how we have …
=> Remove maxRunTime limitations for d2g payloads

changelog/issue-6802.md, tools/worker-runner/provider/google/google.go, tools/worker-runner/provider/google/google_test.go
Fixes #6802.
>Worker Runner no longer polls the metadata service for the Google provider. Instead, we've added `?wait_for_change=true` to the endpoint to perform a hanging GET request that'll return as soon as the metadata has changed and the VM has been preempted.
=> fix(worker-runner): use a hanging GET for GCP spot termination detection

.github/workflows/dependabot-automerge.yml, changelog/JWSqSOBOSo693R2Nm6wJDg.md
Gets rid of these warnings https://github.com/taskcluster/taskcluster/actions/runs/8509082081
>Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: dependabot/fetch-metadata@v1.6.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> chore: upgrade fetch-metadata action to remove node v16 usage

changelog/issue-6946.md, services/worker-manager/src/providers/google.js, services/worker-manager/test/fakes/schemas/google-instance.yml, services/worker-manager/test/provider_google_test.js
Likely schema got changed, or it was not placed correctly intially.
[instances.insert](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert) say that disk labels should be placed inside `disks[].initializeParams.labels`
Fixes #6946
=> feat(w-m): place disk labels inside `initializeParams`

changelog/issue-6958.md, services/worker-manager/src/providers/google.js, services/worker-manager/test/fakes/schemas/google-instance.yml, services/worker-manager/test/provider_google_test.js
Fixes https://github.com/taskcluster/taskcluster/issues/6958.
>Worker Manager now only applies GCP disk labels to `PERSISTENT` disk types.
>
>This fixes an issue in v64.2.2 where `initializeParams.labels` was being set on all disk types and caused GCP to error on local SSDs (`SCRATCH` type disks).
=> fix(w-m): only apply `initializeParams.labels` to `PERSISTENT` disks on GCP

changelog/issue-6900.md, tools/worker-runner/provider/azure/azure.go, workers/generic-worker/README.md, workers/generic-worker/usage.go
Fixes https://github.com/taskcluster/taskcluster/issues/6900.
>Worker Runner on Azure no longer sends a `graceful-termination` message if the scheduled event type is `Freeze`. It will continue to send the message for all other event types: `Reboot`, `Redeploy`, `Preempt`, and `Terminate`.
=> fix(worker-runner azure): don't gracefully terminate on `Freeze` event

changelog/issue-6972.md, go.mod, go.sum, internal/mocktc/mocks3/mocks3.go, workers/generic-worker/artifacts.go, workers/generic-worker/artifacts/s3.go, workers/generic-worker/artifacts_insecure.go, workers/generic-worker/artifacts_multiuser.go, workers/generic-worker/chain_of_trust.go, workers/generic-worker/main.go, workers/generic-worker/model.go
Should help with and/or fix #6972.
>Generic Worker now uploads task payload artifacts in parallel to decrease graceful termination time in the event of a spot termination.
>
>The `insecure` engine no longer performs a file copy command as the task user before the artifact upload process happens to help speed up the process.
>
>Generic Worker (posix only) now tries to put an exclusive file lock on artifacts before upload to prevent the file from being written to by any other process. This is done in lieu of copying the file to a temporary location which was achieving the same thing. If putting the lock on the file fails, Generic Worker will fallback to copying the file.
=> fix(generic-worker): upload artifacts in parallel to speed up graceful shutdowns

changelog/issue-6983.md, services/worker-manager/src/providers/aws.js, services/worker-manager/test/fakes/aws.js, services/worker-manager/test/provider_aws_test.js
Error code can be sent as both "code" and "Code", better to check both
Fixes #6983
=> feat(worker-manager): Fixes error code detection in AWS checkWorker

changelog/issue-6987.md, workers/generic-worker/main.go
Fixes #6987.
>Generic Worker now checks if a graceful termination was requested from worker runner _before_ calling `queue.claimWork()`.
>
>This helps fix a race condition where a preemption occurs right after Generic Worker starts up, but before the graceful termination handler to abort the task has been initialized.
=> fix(generic-worker): check for graceful termination before claiming work

changelog/issue-6761.md, services/github/src/handlers/index.js, services/github/test/handler_test.js
This can happen when decision task of a previous run failed
Fixes #6984
=> Ignore missing task groups on auto-cancel

changelog/fjesG933Q0GogV5uMABoOQ.md, go.mod, infrastructure/tooling/src/generate/generators/go-version.js
As suggested in https://github.com/github/codeql/issues/15647 to fix the below issue:
=> chore: use full go version in go.mod

changelog/bug-1768667.md, ui/src/components/IndexTaskNamespaceTable/index.jsx, ui/src/components/IndexedEntry/index.jsx, ui/src/views/Tasks/TaskIndex/IndexedTask/artifacts.graphql, ui/src/views/Tasks/TaskIndex/IndexedTask/index.jsx, ui/src/views/Tasks/TaskIndex/IndexedTask/taskGroupRedirect.jsx, ui/src/views/Tasks/TaskIndex/routes.js
1. Adds link to the Task Group from the indexed namespaces view: 
2. Displays Task Group link from inside the indexed task view:
3. Introduces a link that will redirect to the task group view in the UI by using indexed namespace and indexed tasks as parameters:
`/tasks/index/indexed.namespace/indexedtask/task-group`
Bugzilla Bug: [1768667](https://bugzilla.mozilla.org/show_bug.cgi?id=1768667)
=> feat(ui): Add Task Group link from the indexed tasks

changelog/EdA3XVyRQlGVGNjJlRW6yw.md, workers/generic-worker/multiuser_posix.go
Github Bug/Issue: Fixes #6979
Spent the entire day looking at this to see if there is a comfortable way to generate the env vars that would be set in the gnome desktop environment and pass them to Generic Worker, but after a full day of trying (and with the help of @Eijebong) decided this was the most sensible solution. We had some successes with systemd-run but it all got very complicated, and only set 3 or 4 env vars compared to what would be seen in a full graphical session, so this seemed like the most pragmatic solution.
It isn't ideal having Generic Worker care about desktop settings, but it also isn't currently trivial for a task to launch a desktop session of its own, so this seems like a reasonable compromise.
=> Issue 6979 - Explicitly set XDG_RUNTIME_DIR in Linux/Multiuser

changelog/issue-6117.md, services/web-server/src/graphql/WorkerManager.graphql, services/web-server/src/loaders/workerManager.js, services/web-server/src/resolvers/WorkerManager.js, services/worker-manager/src/data.js, ui/src/components/WorkerDetailsCard/index.jsx, ui/src/views/Provisioners/ViewWorker/index.jsx, ui/src/views/Provisioners/ViewWorker/worker.graphql, ui/src/views/WorkerManager/WMViewWorkers/index.jsx
When only worker-manager data is available, page no longer shows error and gives 404, but displays available info
=> feat(ui): Worker Manager shows worker page properly when queue data is missing

changelog/E0xwqIBzTh-KsBPNQO-c1w.md, workers/generic-worker/multiuser_darwin.go, workers/generic-worker/multiuser_freebsd.go, workers/generic-worker/multiuser_linux.go, workers/generic-worker/multiuser_posix.go
=> Generic Worker multiuser engine on macOS/Linux/FreeBSD: fix tasksDir default

changelog/HdnVbhnoRYGzKYzoDlyksg.md, ui/src/views/Provisioners/ViewWorker/index.jsx, ui/src/views/Provisioners/ViewWorkers/index.jsx, ui/src/views/Provisioners/ViewWorkers/workers.graphql
Small addition to #7015 - always displaying w-m info when available, so views are merged 
Workers view includes a button when given provisionerId/workerType has corresponding workerPool associated with it
=> feat(ui): Display both queue and w-m info when available

changelog/issue-6117-1.md, ui/src/components/WMWorkerPoolEditor/index.jsx, ui/src/components/WorkersNavbar/index.jsx, ui/src/views/Provisioners/ClaimedTasks/claimedTasks.graphql, ui/src/views/Provisioners/ClaimedTasks/index.jsx, ui/src/views/Provisioners/PendingTasks/index.jsx, ui/src/views/Provisioners/PendingTasks/pendingTasks.graphql, ui/src/views/Provisioners/ViewWorkers/index.jsx, ui/src/views/WorkerManager/WMEditWorkerPool/index.jsx, ui/src/views/WorkerManager/WMViewWorkers/index.jsx
This is a refactoring of navigation components.
Worker manager pages and worker pages use same component
=> feat(ui): Using consistent UI navigation across worker pages

changelog/O9vA5V01RcKpfVE04-jc8w.md, taskcluster/config.yml, taskcluster/kinds/generic-worker/kind.yml
Switching over to Azure (from AWS) now that https://github.com/taskcluster/community-tc-config/issues/630 is complete.
Fixes https://github.com/taskcluster/community-tc-config/issues/732.
=> chore: switch to azure worker pools

changelog/issue-7025.md, ui/src/components/WMWorkerPoolEditor/index.jsx, ui/src/components/WorkersNavbar/index.jsx, ui/src/views/WorkerManager/WMEditWorkerPool/index.jsx, ui/src/views/WorkerManager/WMViewErrors/index.jsx
1. Fixes issue introduced in previous release where worker pool info was requested with graphql query.
One of the parameters was passed as `encodeURIComponent(workerPoolId)` which becomes string `"undefined"` when its value is `undefined`
2. Adds "Errors" link to the workers/worker-manager navigation bar for consistency and easier navigation between related pages
Fixes #7025
=> feat(ui): Fixes broken "Create Worker Pool" page

changelog/DJWkVnx1QnCXp6E1yLgKlg.md, ui/src/views/Provisioners/ViewWorker/index.jsx
Since we might have queue only view, worker-manager only view, both views or none, we only want to show errors, when there were zero records found for both queue and worker-manager
=> feat(ui): Show errors only when no worker info exists

changelog/issue-6567.md, dev-docs/development-process.md, infrastructure/tooling/src/generate/generators/db-schema-dump.js
This adds `pg_dump` in development process documentation and fixes some of the problems around `yarn generate`.
Generate command expects database to be running so that its schema could be checked with the help of `pg_dump`. 
Sometimes it might result in local `pg_dump` version being different from postgres's server version, in such case `pg_dump` throws an error. 
Sometimes you might not have `pg_dump` installed at all.
Plus local development environment is being built around `docker compose` which always run the required version of `postgres` db.
This fix is trivial and will first run native `pg_dump` and in case of any error will attempt to run it with `docker compose`. If both fail, the generation process will also fail.
Fixes #6567
Fixes #6079
=> pg_dump used inside docker if versions mismatch

changelog/V3z_1AjJTOeFS6wU-kzxYA.md, infrastructure/tooling/src/generate/generators/db-schema-dump.js, infrastructure/tooling/src/utils/command.js
Previous error handling wasn't sufficient as missing binary would be a fatal error and docker compose wouldn't even run.
New approach detects first if executable exists.
It also prefers to run pg_dump from the same docker container that db is running in. If there are any docker processes with postgres running, generator will execute pg_dump inside that container.
Also instead of only checking `docker compose`, it should also run if postgres is run as a  standalone container, as mentioned in docs.
=> Fix pg_dump usage in yarn generate

changelog/coke9jDbTnSkucqYxJXSTg.md, taskcluster/config.yml, taskcluster/kinds/generic-worker/kind.yml
See https://github.com/taskcluster/community-tc-config/pull/740 for context.
=> Azure CI worker pools no longer have -azure suffix

changelog/Ke9Borz8TjuPzMIJu_X9TA.md, workers/generic-worker/loopback_audio_darwin.go, workers/generic-worker/loopback_audio_darwin_test.go, workers/generic-worker/loopback_audio_freebsd.go, workers/generic-worker/loopback_audio_freebsd_test.go, workers/generic-worker/loopback_audio_linux.go, workers/generic-worker/loopback_audio_linux_test.go, workers/generic-worker/loopback_video_darwin.go, workers/generic-worker/loopback_video_darwin_test.go, workers/generic-worker/loopback_video_freebsd.go, workers/generic-worker/loopback_video_freebsd_test.go, workers/generic-worker/loopback_video_linux.go, workers/generic-worker/loopback_video_linux_test.go, workers/generic-worker/payload_darwin.go, workers/generic-worker/payload_freebsd.go, workers/generic-worker/payload_linux.go, workers/generic-worker/payload_windows.go
Looks like some unnecessary build constraints slipped in. Go already applies a platform build constraint if the platform is specified in the filename.
=> Remove explit build constraints that are already implied by filename

changelog/ajz5NZzdQrS0XJd3QNy24g.md, workers/generic-worker/tcproxy/tcproxy_test.go
Should fix intermittent failures like https://github.com/taskcluster/taskcluster/runs/25857314796 ...
Fixes #7049
=> Use unique port for tcproxy test to fix conflicts

changelog/Myg7o2toQHmLeZ3QCOGwug.md, clients/client-go/tcnotifyevents/tcnotifyevents.go, clients/client-py/taskcluster/generated/aio/notifyevents.py, clients/client-py/taskcluster/generated/notifyevents.py, clients/client-web/src/clients/NotifyEvents.js, clients/client/src/apis.js, generated/references.json, services/notify/src/exchanges.js
The notify service supports sending notifications out through a pulse exchange. Tasks can make use of this via routes like:
notify.pulse.some.custom.topic.on-resolved
However, the notify service currently does not use `some.custom.topic` in the routing key it emits. This results in *all* messages using the same routing key, which ends up being `primary._`.
This defeats the purpose of using the notify service's pulse exchange, as consumers need to manually sift through *all* messages sent out over this exchange.
=> fix(notify): Ensure pulse routes use custom topics from routing key

changelog/YrTfUOV0SKiBQXopdCv9aA.md, infrastructure/tooling/src/generate/generators/db-schema-dump.js
If postgres was started without the compose, it might have random name. Better to filter by image name
=> `yarn generate` uses any postgres container to run pg_dump

changelog/issue-7080.md, services/github/src/handlers/index.js, services/github/test/handler_test.js
Previously incorrect property was checked for an error code, which resulted in same error being sent to github comments
Fixes #7080
=> feat(github): Fixes 404 handling when task group doesn't exist

changelog/issue-7076.md, tools/worker-runner/provider/aws/metadata.go, tools/worker-runner/provider/aws/metadata_test.go
=> Worker Runner: Use IMDSv2 in EC2 instead of IMDSv1

changelog/issue-7083.md, libraries/api/src/pagination.js, libraries/api/test/pagination_test.js
Used hashids library throws an error if decoded token contains invalid characters. API in such case would throw `500 InternalServerError` error. However, this should be a client error - `400 InvalidInput`.
Fixes #7083
=> API graceful query handling for pagination

changelog/issue-7095.md, workers/generic-worker/build.sh
=> Avoid pulling in go module github.com/taskcluster/taskcluster@latest (v24.3.1+incompatible)

.taskcluster.yml, changelog/H0Ct7_leTvejnaMekiKJOw.md, taskcluster/config.yml, taskcluster/kinds/client/kind.yml, taskcluster/kinds/db/kind.yml, taskcluster/kinds/generic-worker/kind.yml, taskcluster/kinds/go/kind.yml, taskcluster/kinds/library/kind.yml, taskcluster/kinds/lint/kind.yml, taskcluster/kinds/meta/kind.yml, taskcluster/kinds/service/kind.yml, taskcluster/kinds/ui/kind.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml
This migrates the taskcluster CI workloads from Ubuntu 22.04 to Ubuntu 24.04.
=> Migrate CI from Ubuntu 22.04 to Ubuntu 24.04 worker pools

changelog/issue-7120.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/env_escaping_test.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml, tools/d2g/d2gtest/testdata/testcases/no_artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml
These seem to be the key ones in the cases that I've had issues. I also looked at:
- Removing CPU limits - but after a reread of the docs, it looks like that only applies when multiple containers are competing for resources, which is something that rarely happens in practice, and there's no way to "disable" them (you need to set limits and shares for each container, which d2g can't do intelligently)>
- Setting shm size. I didn't change this in the end because there's no way to make it unlimited, and unless we have a reason to believe it needs to be increased, it may as well stay as the default.
Github Bug/Issue: Fixes #7120
=> fix(d2g): disable memory, pid, or ulimits in d2g (fixes #7120)

changelog/issue-7085.md, clients/client-go/tcworkermanagerevents/types.go, generated/references.json, services/worker-manager/schemas/v1/pulse-worker-message.yml, services/worker-manager/schemas/v1/pulse-worker-pool-error-message.yml, services/worker-manager/schemas/v1/pulse-worker-removed-message.yml, services/worker-manager/src/providers/provider.js, services/worker-manager/test/api_test.js
So far payloads didn't contain time information inside, so if someone would to process events async, not in real-time, it would be impossible to know when a particular event happened.
This is an addition to #7085
=> Add timestamp field to the worker related events

changelog/cfqLHDjdTS-KgnhzdwG7kQ.md, workers/generic-worker/process/multiuser_posix.go
Spotted that we were calling `user.Lookup(username)` twice unnecessarily...
=> Code simplification: no need to call user.Lookup(username) twice

changelog/issue-7073.md, clients/client-shell/cmds/version/version.go, tools/livelog/main.go, tools/taskcluster-proxy/main.go, tools/websocktunnel/cmd/websocktunnel/main.go, tools/worker-runner/cmd/start-worker/main.go, workers/generic-worker/README.md, workers/generic-worker/main.go, workers/generic-worker/usage.go
CLI tools and generic-worker now returns short-version string if executed with `--short-version` argument:
- `generic-worker --short-version`
- `livelog --short-version`
- `websocktunnel --short-version`
- `start-worker --short-version`
- `taskcluster version --short-version`
Fixes #7073
=> feat(cli): Add an option to output short-version only for all cli tools

changelog/issue-7073.md, workers/generic-worker/logging.go
=> Generic Worker log to stderr, not stdout

changelog/bug-1907075.md, services/web-server/src/servers/createApp.js, services/web-server/test/graphql/validation_test.js
Instead of sending 500 always, we return appropriate code from the error or 413 
Bugzilla Bug: [1907075](https://bugzilla.mozilla.org/show_bug.cgi?id=1907075)
=> web server returns correct error code instead of 500

changelog/PUMDkmd0RlmEMQJWef3qVQ.md, workers/generic-worker/runtime/runtime_linux.go
`adduser/deluser` are debian specific wrappers around `useradd/userdel` and friends. By changing to `useradd/userdel`, we allow workers to be deployed on non debian derivative distributions. Tested on archlinux.
Flag mapping for useradd:
`--disabled-password`: Disables password prompting and disables the password for the user. `useradd` does that by default.
`--gecos ""`: This sets the GECOS flag for the user to "". Maps to `chfn -f ${username}`
`--debug`: Makes adduser output what commands it runs. Irrelevant here.
`--home ${homedir}`: Creates the home directory at `${homedir}`. `-m` Creates the user home directory and `-d ${homedir}` defines it as being `${homedir}`.
Flag mapping for userdel:
`--remove-home`: This removes the user's home directory when deleting the user. Maps to `-r` …
=> Change `adduser/deluser` usage to `useradd/userdel`

changelog/PUMDkmd0RlmEMQJWef3qVQ.md, workers/generic-worker/runtime/runtime_linux.go
The latter doesn't exist on Debian based distributions.
Github Bug/Issue: Fixes #7168
=> fix: look for `chfn` in `/usr/bin` instead of `/usr/sbin`

changelog/issue-7128-1.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml
This patch maps uids and gids from the host system into containers that run with Podman, which helps to avoid permission issues within the container on mounted volumes.
=> fix: map uid/gid of user running podman into useful uids/gids in podman containers

changelog/issue-7167.md, tools/worker-runner/provider/aws/awsprovider.go
Change the polling period for EC2 spot instance interruption notices to 5 seconds, as recommended by [AWS documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-instance-termination-notices.html).
Github Bug/Issue: Fixes #7167
=> Poll more frequently for EC2 spot interruption

changelog/issue-7202.md, services/github/src/fake-payloads.js, services/github/test/api_test.js
In some payloads `branch` value was not properly escaped which resulted in invalid json
Fixes #7202
=> Fixes taskcluster.yml rendering for some payloads

changelog/issue-7172.md, ui/src/components/StatusDashboard/summarizeWorkerPoolsStats.js, ui/src/components/StatusDashboard/summarizeWorkerPoolsStats.test.js
In minified version of `Object.values(obj?.prop)` it got compiled into `void 0` if property doesn't exist which results in `Object.values(undefined)` and "Can't convert undefined to object" error
Fixes #7172
=> Better handling of defaults and undefined

changelog/issue-6304.md, services/github/src/utils.js, services/github/test/utils_test.js
Fixes #6304.
>GitHub service no longer skips CI based on PR description. It will only skip CI based on the PR title or the commit message, [as GitHub does](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/skipping-workflow-runs).
=> fix(github): only skip CI on commit message and PR title

changelog/ZyFDOEbmRjWmSyg85kKemA.md, workers/generic-worker/loopback_audio_darwin_test.go, workers/generic-worker/loopback_audio_freebsd_test.go, workers/generic-worker/loopback_audio_linux_test.go
Unfortunately we had to move Generic Worker Ubuntu workloads to AWS from GCP while our images are broken in GCP.
This (temporarily) disables the loopback audio tests, which don't run in AWS, since audio loopback is currently not working there.
When we move workloads back to Google Cloud, we should be able to safely revert this commit.
=> Disable audio loopback tests in generic-worker while audio-loopback broken in AWS

changelog/A5ondlA9T8KDsa60w5noNA.md, workers/generic-worker/loopback_audio_darwin_test.go, workers/generic-worker/loopback_audio_freebsd_test.go, workers/generic-worker/loopback_audio_linux_test.go
These tests were disabled in #7230 due to a temporary problem with workers in GCP. Since that issue has been resolved the tests can be re-enabled.
Note, CI will initially fail, because workers are still running in AWS. However, once https://github.com/taskcluster/community-tc-config/pull/808 has been applied, the workers should be running in GCP again, the failing CI tasks can be rerun, and then everything should be working again.
=> Generic Worker: restore snd-aloop CI tests

changelog/issue-7233.md, services/queue/src/bucket.js, services/queue/test/bucket_test.js
=> queue: uri-encode artifact names in CDN urls

yarn.lock
On main branch, the yarn.lock seems to be bad with incorrect checksums. I've run a `yarn install` and `yarn generate` and here are the updated checksums.
=> Fix checksums

changelog/VEBr6SyJRo62vORtESdAWw.md, clients/client-rust/Cargo.lock, clients/client-rust/client/Cargo.toml, clients/client-rust/download/Cargo.toml, clients/client-rust/integration_tests/Cargo.toml, clients/client-rust/upload/Cargo.toml
This is a "major" change because it requires a major version bump for
the rust client as some dependencies (`reqwest`) is exposed through the
public API.
=> Update rust dependencies

changelog/issue-5669-1.md, services/auth/src/static-scopes.json, services/github/scopes.yml
For the #5669 we forgot to include necessary scopes
After this feature was merged https://github.com/taskcluster/taskcluster/pull/7208 we noticed we forgot to include one more scope 
https://github.com/taskcluster/tc-dev-integration-test/commit/643820fe0576909515c72f6c40d4990d36837812#comments
=> feat(github): allow fetching artifacts from queue

changelog/issue-7257.md, generated/references.json, services/worker-manager/schemas/v1/config-azure.yml, services/worker-manager/src/providers/azure/index.js, services/worker-manager/test/provider_azure_test.js
in #4987 it was decided to skip public IP provisioning for generic-worker since it wasn't used
However, having public IP might still be useful for debug purposes. Worker pool configuration allows `workerManager.publicIP=true` to override that logic
Fixes #7257
=> Allow provision of public IP for g-w in Azure

changelog/issue-7263.md, services/github/src/handlers/status.js, services/github/test/handler_test.js, ui/src/views/Tasks/TaskArtifactRedirect/index.jsx, ui/src/views/Tasks/routes.js
UI adds new artifact redirect route:
`/tasks/QPXuvAhvThmoieABhZ1c_g/runs/0/public/parameters.yml`
would fetch signed url for artifact and do redirect
=> feat(github): Improve checks output, add artifact redirect handling

changelog/issue-7269.md, libraries/app/src/index.js
"Possible EventEmitter memory leak detected" was happening because many tests run at once and server tries to add termination handler every time
Fixes #7269
=> Fix tests warning

changelog/issue-7151.md, ui/src/components/StatusLabel/index.jsx
Regression from #7158 
Since we fetch dependencies differently, their status was not upper-cased which didn't let the component to pick right color
=> feat(ui): Fix missing status colors in task view

changelog/Lm5qHBgeSb-IihhTTSVA3Q.md, workers/generic-worker/multiuser.go
This is useful groundwork for #4595. It just moves a section of code into its own function.
=> Refactor: move code into own function

changelog/issue-7278.md, generated/docs-search.json, ui/docs/reference/workers/docker-worker/capabilities.mdx
Fixes #7278.
>Adds `containerEngine` docs in `Capabilities` section of Docker Worker docs.
=> fix(docs): add `containerEngine` docker worker docs

changelog/issue-7235.md, workers/generic-worker/os_groups_multiuser_test.go, workers/generic-worker/os_groups_multiuser_windows.go, workers/generic-worker/runtime/runtime_windows.go
Fixes https://github.com/taskcluster/taskcluster/issues/7235.
>Generic Worker (windows): Removes calls to `wmic` (being [deprecated](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/wmi-command-line-wmic-utility-deprecation-next-steps/ba-p/4039242)) and `net` in favor of a more modern approach using PowerShell cmdlets.
>
>The `powershell` executable is required to be in the path.
=> fix(generic-worker)!: remove `wmic` and `net` calls on windows

changelog/issue-7222.md, tools/worker-runner/util/oom_linux.go
Fixes https://github.com/taskcluster/taskcluster/issues/7222.
>Worker Runner: Replaces deprecated `/proc/<pid>/oom_adj` with `/proc/<pid>/oom_score_adj`.
=> fix(worker-runner): replace deprecated oom adjuster

changelog/a2Z3cBueQ22fD0s4BGC7bQ.md, services/auth/src/api.js, services/auth/test/role_test.js
`hashids.decode` throw an error when input contains unexpected characters. 
This wraps the handling and responds 400 to the client instead of 500
=> feat(auth): Fix error handling in continuation token

changelog/issue-7052.md, services/worker-manager/src/estimator.js, services/worker-manager/test/estimator_test.js
provisioner and estimator are operating with partially stale information
Fixes #7052
=> feat(w-m): Handling edge-case in estimation

changelog/issue-7305.md, workers/generic-worker/insecure.go, workers/generic-worker/main.go, workers/generic-worker/multiuser.go
=> Generic Worker task log headers and sentry reports include key worker config settings

changelog/issue-7307.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml
Fixes #7307.
>Generic Worker (D2G): Pass devices through to the `docker run ...` command using `--device` instead of a volume mount.
=> fix(d2g): use `--device` instead of volume mounts

changelog/SmfnwIYeTx-ovzAwJulBaQ.md, db/fns.md, infrastructure/tooling/src/utils/db.js
In working on #7286, I had a hard time finding all of the DB functions in one place. This adds them hidden behind `<details>` elements.
[Results](https://github.com/djmitche/taskcluster/blob/dumpfns/db/fns.md)
=> Include function definitions in documentation

changelog/R2HFCq_uQE64uf2VIN3uYQ.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml, tools/d2g/dockerimageartifact.go, tools/d2g/dockerimagename.go, tools/d2g/indexeddockerimage.go, tools/d2g/nameddockerimage.go
>D2G: No longer specify file mount format on image if compressed with gzip, bzip2, xz, or zstd when using docker. Generic Worker will now no longer decompress these files before running `docker load`. Docs [here](https://docs.docker.com/reference/cli/docker/image/load/).
A small optimization I found while looking into https://github.com/taskcluster/taskcluster/issues/7254.
=> fix(d2g): don't decompress certain image extensions before docker load

changelog/issue-7309.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/container_engine_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/dw_features_tests.yml, tools/d2g/d2gtest/testdata/testcases/env_escaping_test.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml, tools/d2g/d2gtest/testdata/testcases/no_artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml
Fixes #7309.
>D2G: No longer pass `--init` to the `docker run ...` command. This was breaking docker image build tasks that Taskgraph creates. To kill the running docker container, we now pass `-s KILL` to the `timeout` command.
=> fix(d2g): use `KILL` signal on `timeout` command instead of `--init`

changelog/issue-6858.md, clients/client-shell/cmds/d2g/d2g.go, tools/d2g/d2g.go, workers/generic-worker/d2g_test.go, workers/generic-worker/helper_test.go, workers/generic-worker/payload_linux.go
Fixes #6858. First commit adds new tests that will fail as we have things today, second commit is the implementation that'll fix this test and implement the fix to the issue.
>D2G: Translated payload or task definition will no longer contain the default `expires` string for artifacts, `"0001-01-01T00:00:00.000Z"`.
=> fix(d2g): remove default artifact expires timestamp on translated payload

changelog/issue-7286.md, generated/docs-search.json, ui/docs/reference/platform/queue/run-life-cycle.svg, ui/docs/reference/platform/queue/task-life-cycle.mdx
Task states are derived from run states. This updates the docs to reflect this, and to include a diagram of run states. It also cautions against relying on absence of edges in the task state diagram.
This came up at a community meeting last week (and in particular the "Warning"), where I promised to update the docs accordingly.
=> Improve docs for run/task states

changelog/issue-7320.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml, workers/generic-worker/tcproxy/tcproxy.go
Github Bug/Issue: Fixes #7320, fixes #6797
=> generic-worker, d2g: let containers talk to the tc proxy without sharing the host network namespace

changelog/issue-7322.md, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure/index.js, services/worker-manager/src/providers/google.js, services/worker-manager/test/provider_aws_test.js, services/worker-manager/test/provider_google_test.js
Fixes #7322.
>Worker Manager: AWS and GCP workers now transition into stopping state on call to `removeWorker`.
=> fix(w-m): transition aws/gcp workers to stopping on `removeWorker` call

changelog/issue-7327.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml
Fixes #7327.
>D2G: Don't provide `--privileged` flag for dind and host shared memory use. Only using now as a one-to-one mapping to Docker Worker's privileged payload flag.
=> fix(d2g): one-to-one mapping for `--privileged` flag

changelog/Og8mVokkRQm4KhmGt2gpGA.md, clients/client-rust/upload/src/lib.rs
Without this, the rust client would silently fail when uploading an artifact if the PUT request would return a 4/5xx.
=> Return an error when the rust client fails to upload an artifact

changelog/IvW12q6QRjSbGotMqDkFXQ.md, clients/client-rust/upload/src/lib.rs
When the object service gives us a PUT URL, it also gives a list of headers to add to the call. That list might contain a content-length. Before this change, the library would always add its own content-length header which would result in a header list like this:
```
{
"content-length": "421",
"content-length": "421",
"content-encoding": "identity",
"content-type": "application/octet-stream",
}
```
which in turn would result in the upstream object storage returning a 400.
Unfortunately, reqwest doesn't allow insights into the current header map of the request builder so we have to build the entire thing ourselves, hence the size of this change.
It's also worth noting that the header map is case insensitive so we don't have to worry about casing ourselves.
=> Don't duplicate content-length in PUT request to upstream object storage

changelog/issue-7340.md, tools/d2g/d2g.go
Fixes #7340.
>D2G: Use unique task container names to avoid container naming conflicts.
cc @jschwartzentruber
=> fix(d2g): use unique task container names

changelog/fady1OgaQ1ulcxtyDR4fuQ.md, clients/client-shell/cmds/d2g/d2g.go, internal/scopes/scopes.go, tools/d2g/d2g.go, tools/d2g/d2gtest/d2g_test.go, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml, workers/generic-worker/d2g_multiuser_test.go, workers/generic-worker/d2g_test.go, workers/generic-worker/loopback_audio_darwin_test.go, workers/generic-worker/loopback_audio_freebsd_test.go, workers/generic-worker/loopback_audio_linux_test.go, workers/generic-worker/loopback_video_darwin_test.go, workers/generic-worker/loopback_video_freebsd_test.go, workers/generic-worker/loopback_video_linux_test.go, workers/generic-worker/payload_linux.go, workers/generic-worker/sentry.go
>D2G: Renamed methods `Convert()` --> `ConvertPayload()` and `Scopes()` --> `ConvertScopes()`.
>
>D2G: `ConvertScopes()` checks that the provided docker worker payload is valid with the supplied scopes. Generic Worker will now resolve a docker worker task as `exception/malformed-payload` if any required docker worker scopes are missing for its payload.
=> feat(d2g)!: added scope/payload validation

changelog/Nf0wHHyBR52vH0-l7oaJ0Q.md, tools/d2g/d2g.go
Builds on top of https://github.com/taskcluster/taskcluster/pull/7343.
>D2G: `ConvertScopes()` additionally checks scopes for `loopbackAudio` and `loopbackVideo`.
=> fix(d2g): add scope check validations for loopback audio/video

changelog/a8d1VKbnTpGqX_T6TduJew.md, tools/d2g/d2g.go
Cleanup from https://github.com/taskcluster/taskcluster/pull/7343.
>D2G: `ConvertScopes()` checks all scopes at once so users would see all missing scopes in one run.
=> fix(d2g): perform all scope validations once

changelog/issue-7386.md, ui/src/views/Provisioners/ClaimedTasks/index.jsx, ui/src/views/Provisioners/PendingTasks/index.jsx
Not all task queues have worker pools associated,
pending and claimed tasks list should still work
Fixes #7386
=> Fix graphql error for claimed/pending

changelog/issue-7128-2.md, workers/generic-worker/README.md, workers/generic-worker/d2g_multiuser_test.go, workers/generic-worker/mounts.go, workers/generic-worker/mounts_insecure.go, workers/generic-worker/mounts_insecure_test.go, workers/generic-worker/mounts_multiuser.go, workers/generic-worker/mounts_multiuser_test.go, workers/generic-worker/mounts_test.go, workers/generic-worker/multiuser_linux.go, workers/generic-worker/multiuser_posix.go, workers/generic-worker/multiuser_windows.go, workers/generic-worker/runtime/runtime.go, workers/generic-worker/usage.go
UPDATE: This is the third, and hopefully last part, of the fix for #7128.
The complete fix includes:
* #7170
* #7144
* #7149 (this PR)
=> fix(generic-worker)!: only chown writable directory cache files owned by previous task user to new task user

changelog/issue-7404.md, workers/generic-worker/mounts.go, workers/generic-worker/mounts_insecure.go, workers/generic-worker/mounts_insecure_test.go, workers/generic-worker/mounts_multiuser.go, workers/generic-worker/mounts_multiuser_test.go, workers/generic-worker/mounts_test.go, workers/generic-worker/multiuser_linux.go, workers/generic-worker/multiuser_posix.go, workers/generic-worker/multiuser_windows.go, workers/generic-worker/runtime/runtime.go
Reverts #7149 due to #7404.
>Generic Worker: Reverting 61b985dd009210a204da3bb354eab2037d132bef due to issue #7404 with cache permissions.
=> fix(generic-worker): revert PR #7149

changelog/TLW2aOmER_-7eM2Um6TfEQ.md, workers/generic-worker/README.md, workers/generic-worker/gwconfig/config_linux.go, workers/generic-worker/gwconfig/config_other.go, workers/generic-worker/gwconfig/config_windows.go, workers/generic-worker/main.go, workers/generic-worker/payload_linux.go, workers/generic-worker/payload_test.go, workers/generic-worker/usage.go, workers/generic-worker/usage_linux.go, workers/generic-worker/usage_other.go, workers/generic-worker/usage_windows.go
>Generic Worker: adds `disableNativePayloads` (default: `false`) worker config option (`linux` only) to require all task payloads to be Docker Worker payloads. If this option is set to `true`, the task log will no longer contain the translated task definition and the warning about using Docker Worker payloads.
>
>Tasks submitted with native payloads will be resolved as `exception/malformed-payload`.
>
>Generic Worker: adds `d2gConfig.logTranslation` (default: `true`) worker config to control whether the D2G-translated task definition is logged to the task logs.
=> feat(d2g): disable native payloads

changelog/dyIkQZPYS16nYjzjJEZyxw.md, infrastructure/tooling/src/generate/generators/generic-worker.js
Fixes an issue with `yarn generate` causing a diff from what's on `main`. This was due to generic worker config splitting out into linux-specific config, apart from posix.
=> fix(generate): generic worker readme generation fixed to linux amd64

changelog/issue-7404.md, workers/generic-worker/mounts.go, workers/generic-worker/mounts_insecure.go, workers/generic-worker/mounts_insecure_test.go, workers/generic-worker/mounts_multiuser.go, workers/generic-worker/mounts_multiuser_test.go, workers/generic-worker/mounts_test.go, workers/generic-worker/multiuser_linux.go, workers/generic-worker/multiuser_posix.go, workers/generic-worker/multiuser_windows.go, workers/generic-worker/runtime/runtime.go, workers/generic-worker/runtime/runtime_linux.go
Force all task users to share the same subuid map
This fixes the cache issues we've been having with podman with #7149
applied.
The core idea here is that on podman, caches permissions for UIDs
(outside of 1000) are mapped to the user subuid range on the host. So UID 0 becomes
100000, 1 becomes 100001 and so on. When remounting the cache in the
next container, the reverse operation happens to get the right UID in
the container, 100000 on the host becomes 0 in the container.
However, by default, users do not share subuid ranges, `adduser` will
always use a new subuid range (100000 for the first user, +64k for the
second and so on). Which means that the mapping wouldn't work on the
second job and the cache would just get mounted as `nobody:nogroup`.
This commit changes the user creation so …
=> Fix worker caches with d2g

changelog/RretABTnSM6y7D-IgcBNbA.md, workers/generic-worker/mounts.go, workers/generic-worker/mounts_insecure.go, workers/generic-worker/mounts_multiuser.go, workers/generic-worker/mounts_test.go
Fixes an issue that was brought up with the initial commit in https://github.com/taskcluster/taskcluster/pull/7428. I'm not sure why this code was pulled out.
>Generic Worker: fixes permissions issues with ReadOnlyDirectory mounts.
=> fix(generic-worker): give task user access to readonly mounts

changelog/VujHkx4yTsCmExAvFY_ZKQ.md, cloudbuild.yaml
I've migrated our Container Registry usage over to Artifact Registry and found this small cleanup we can add now that I've added a cleanup policy to our Artifact Registry repository:
Fixes https://github.com/taskcluster/taskcluster/issues/6916.
=> chore: remove delete old image step in gcp cloudbuild

changelog/U77J9G-tSsKxYnI_MrbvVg.md, db/src/main.js, infrastructure/tooling/src/dev/index.js
Seen in the `Deploy` stage of a recent cloudbuild log:
```bash
(node:570) [DEP0059] DeprecationWarning: The `util.log API is deprecated. Please use console.log() with a custom formatter or a third-party logger instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
=> chore: clean up deprecated `util.log()` usage

changelog/issue-7443.md, generated/references.json, services/worker-manager/schemas/v1/worker-lifecycle.yml, services/worker-manager/test/api_test.js
Default claim timeout constant is set to 20 min.
Former value of minimum for queueInactivityTimeout was incorrectly set to 1min which conflicted with workers being killed while working on tasks.
Fixes #7443
=> feat(w-m): Increase queueInactivityTimeout min to 1200

changelog/dxMKwlKpRNyo1GnU2pstkg.md, generated/references.json, services/worker-manager/src/monitor.js, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure/index.js, services/worker-manager/src/providers/cloudapi.js, services/worker-manager/src/providers/google.js, services/worker-manager/test/cloudapi_test.js
Logging cloud api call metrics for provisioner and scanner. 
This includes min/max/median values and breakdown by status.
Attempt to understand how (in)effective cloud provider calls are
=> Log cloud api call metrics for scanner and provisioner

changelog/QV0lt44lRRGrvqdCFIBv-A.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml
Before this commit, when a docker container had a volume declared that wasn't explicitly mounted by the task, it would leak it as it would create an anonymous docker volume for every single one. This changes the `rm` command to remove those anonymous volumes.
Note that the unnamed task container path used `docker run --rm` which takes care of those anonymous volumes on its own.
=> Fix d2g container deletion to not leak anonymous volumes

changelog/issue-7218.md, workers/generic-worker/gdm3/gdm3.go, workers/generic-worker/gdm3/gdm3_test.go, workers/generic-worker/runtime/runtime_darwin.go, workers/generic-worker/runtime/runtime_other.go, workers/generic-worker/runtime/runtime_windows.go
Fixes https://github.com/taskcluster/taskcluster/issues/7218.
>Generic Worker: Unset cached interactive username when we unexpectedly receive a non-task username.
>
>This will fix errors like: `interactive username gdm does not match task user task_173764785573833`.
=> fix(generic-worker): unset unexpected cached username

changelog/issue-7463.md, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/container_engine_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/dw_features_tests.yml, tools/d2g/d2gtest/testdata/testcases/env_escaping_test.yml, tools/d2g/d2gtest/testdata/testcases/no_artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml, tools/d2g/dockerimagename.go, tools/d2g/nameddockerimage.go
Fixes #7463.
>D2G: Pull docker image as initial command to ensure latest image version is used during task execution.
=> fix(d2g): pull latest docker image tag

changelog/issue-7465.md, services/worker-manager/src/api.js, services/worker-manager/test/api_test.js
Before it would return `500` if worker with the same `workerId` already existed
Related to #7465 issue
=> feat(w-m): createWorker correctly handles unique key errors

changelog/issue-7464.md, services/worker-manager/src/providers/static.js, services/worker-manager/test/provider_static_test.js
Instead of caching workerConfig inside worker.providerData at create time, static workers would always receive "fresh" workerPool's workerConfig at register time.
Fixes #7464
=> feat(w-m): Static workers use pool's workerConfig

changelog/issue-7475.md, services/hooks/src/api.js, services/hooks/test/api_test.js, ui/docs/reference/core/hooks/firing-hooks.mdx
Reverts taskcluster/taskcluster#7476
Unfortunately I forgot about the query validation step, so no arbitrary parameters would be passed, if there is no validation defined. 
I'm reverting this until a better plan comes up with Phabricator team how those values are delivered
cc @La0
=> Revert "[Bug 1935142] Include URL query parameters in trigger hook API endpoints"

changelog/b7yn_DkbSAeqXnmIGB3wNA.md, taskcluster/config.yml, taskcluster/kinds/generic-worker/kind.yml
Uses new pool https://github.com/taskcluster/community-tc-config/pull/909. No longer version-specific naming.
=> chore: use generic macos pool

changelog/issue-7462.md, workers/generic-worker/garbagecollector.go
Fixes #7462.
>Generic Worker (D2G): prune docker images during garbage collection, if needed.
=> fix(generic-worker): prune docker images during garbage collection

changelog/emD8TJ-xRkCksGQW9uhA7A.md, clients/client-shell/cmds/group/actors.go
The way filters work for this command is that for each task in the returned list from taskcluster, it checks if the status of the task is contained in the flags. A completed task in taskcluster has its status set to `completed` [1], not `complete` so the previous flag always returned an empty list.
[1]: https://github.com/taskcluster/taskcluster/blob/107b4228071ed9b949e0281f72ae177336e9c776/services/queue/schemas/v1/task-status.yml#L37
=> Fix the `completed` flag for `taskcluster group list`

changelog/issue-7517.md, workers/generic-worker/gwconfig/config_insecure.go, workers/generic-worker/gwconfig/config_multiuser.go, workers/generic-worker/main.go
Fixes #7517.
>Generic Worker: fixes `fork/exec` issue on headless, multiuser engine introduced in v81.0.0.
=> fix(generic-worker): fix `fork/exec` issue on headless, multiuser engine

.taskcluster.yml, changelog/Mdm-zSfjSgSnorb9peDNMg.md, taskcluster/config.yml, taskcluster/kinds/generic-worker/kind.yml, taskcluster/requirements.in, taskcluster/requirements.txt
Due to https://github.com/taskcluster/community-tc-config/pull/917 (which I've already applied so that this PR's CI will work)
~~Need https://github.com/taskcluster/taskgraph/pull/644 to land and a new version of Taskgraph to be released first.~~
=> chore(ci): use new `*-gui` pools

changelog/issue-7521.md, workers/generic-worker/multiuser_linux_test.go, workers/generic-worker/multiuser_windows.go, workers/generic-worker/run_task_as_current_user.go, workers/generic-worker/run_task_as_current_user_posix.go
Fixes #7521.
>Generic Worker: fixes an issue introduced in v81.0.0 where `TASK_USER_CREDENTIALS` env var wasn't written to the task's environment if `task.payload.features.runTaskAsCurrentUser` was enabled.
=> fix(generic-worker): properly configure env vars when running as current user

changelog/WYasEGVwS6mc4brujKnaYw.md, taskcluster/kinds/release/kind.yml
Was removed from the worker config here https://github.com/taskcluster/community-tc-config/commit/b84b8e2ac98b3fab1ab72d31a06d76a75b8ff301#diff-23fc71490cc090eec860515efc9788fad76e67b9559b9420316af4a48ef23713L39 and we now need to use the task feature.
=> fix(release): run as current user

changelog/issue-5727.md, workers/generic-worker/chain_of_trust.go, workers/generic-worker/chain_of_trust_test.go, workers/generic-worker/testdata/chain-of-trust-additional-data.json
Fixes #7527
First commit provides a test demonstrating the issue. The second commit will provide a fix.
=> Generic Worker (fix): merging of Chain of Trust additional data with common ancestors

changelog/issue-7532.md, workers/generic-worker/mounts_multiuser.go, workers/generic-worker/multiuser_posix.go, workers/generic-worker/multiuser_windows.go
Fixes #7532.
>Generic Worker (windows): fix cache ownership issues. Clean up ACLs so prior task users aren't referenced anymore.
=> fix(generic-worker): clean up cache ACLs and fix permission issues on windows

changelog/bCcRR_sGRVKYZdADicMirg.md, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure/index.js, services/worker-manager/src/providers/google.js, services/worker-manager/test/provider_aws_test.js, services/worker-manager/test/provider_azure_test.js, services/worker-manager/test/provider_google_test.js
Spotted in logs on dev for worker pool without launch configs
```
TypeError: Cannot read properties of undefined (reading 'length')
at AzureProvider.provision (file:///app/services/worker-manager/src/providers/azure/index.js:312:58)
```
=> feat(w-m): Fix edge case with empty launch configs

changelog/issue-7545-1.md, changelog/issue-7545.md, generated/references.json, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml, tools/d2g/genericworker/generated_types.go, workers/generic-worker/artifacts.go, workers/generic-worker/artifacts/artifacts.go, workers/generic-worker/artifacts_multiuser_test.go, workers/generic-worker/artifacts_test.go, workers/generic-worker/d2g_test.go, workers/generic-worker/generated_insecure_darwin.go, workers/generic-worker/generated_insecure_freebsd.go, workers/generic-worker/generated_insecure_linux.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/helper_test.go, workers/generic-worker/main.go, workers/generic-worker/schemas/insecure_posix.yml, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml
Fixes #7545.
>Generic Worker: adds `optional` field to payload artifacts to ignore any artifact upload errors, for example, if the artifact isn't known to exist at the end of a task but you don't want the task to resolve as `failed/failed`. This makes the transition from Docker Worker --> Generic Worker (through d2g) more seamless, as Docker Worker does not resolve tasks as `failed/failed` if the artifact doesn't exist.
>D2G: sets each payload artifact as `optional` so tasks won't resolve as `failed/failed` if the artifact doesn't exist, like Docker Worker does.
=> feat(generic-worker): adds `optional` payload artifact field

changelog/issue-7411.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, workers/generic-worker/d2g_test.go, workers/generic-worker/insecure_linux.go, workers/generic-worker/loopback_audio_linux.go, workers/generic-worker/loopback_audio_linux_test.go, workers/generic-worker/loopback_video_linux.go, workers/generic-worker/loopback_video_linux_test.go, workers/generic-worker/multiuser_linux.go
Fixes #7411.
>Generic Worker: no longer `chown` loopback video/audio devices to the task user. Explicitly change group of the devices to `video`/`audio`, respectively, so that users in those groups may still access them.
=> fix(generic-worker): don't `chown` loopback devices

changelog/B9fb36vqR2CQHDmydFAArA.md, infrastructure/tooling/src/build/tasks/generic-worker-image.js, infrastructure/tooling/src/build/tasks/monoimage.js, infrastructure/tooling/src/build/tasks/release.js, infrastructure/tooling/src/build/tasks/taskcluster-proxy.js, infrastructure/tooling/src/build/tasks/websocktunnel.js, infrastructure/tooling/src/utils/command.js, infrastructure/tooling/src/utils/crates.js, infrastructure/tooling/src/utils/pypi.js
I _believe_ this should fix https://github.com/taskcluster/taskcluster/issues/3018 (already closed as completed for some reason).
Release error logs like:
```bash
node:events:502
throw er; // Unhandled 'error' event
^
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
at _write (node:internal/streams/writable:489:11)
at Writable.write (node:internal/streams/writable:510:10)
at Socket.ondata (node:internal/streams/readable:1009:22)
at Socket.emit (node:events:524:28)
at addChunk (node:internal/streams/readable:561:12)
at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
at Readable.push (node:internal/streams/readable:392:5)
at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)
Emitted 'error' event on WriteStream instance at:
at WriteStream.onerror …
```
=> fix(release): don't share logfiles during release pipeline

changelog/issue-7568.md, workers/generic-worker/taskcluster_proxy.go
Fixes #7568.
>Generic Worker: fixes panic while trying to refresh `taskcluster-proxy` credentials.
Note: this issue only occurs with d2g tasks.
=> fix(generic-worker): fix PUT url for refreshing tc proxy creds

changelog/R4r4rObuQ1eT7iiUMzwrWw.md, services/worker-manager/src/data.js, services/worker-manager/src/launch-config-selector.js, services/worker-manager/test/data_test.js, services/worker-manager/test/launch_config_selector_test.js
CapacityPerInstance=2 and while(toSpawn) didn't work well together.. when w-p has minCapacity: 1, while(toSpawn) underflows and goes to negative infinity (capped at wp max capacity)
=> feat(w-m): Fixes edge-case with provisioner

changelog/MMddbGelSSaXAnDk0Jre1g.md, workers/generic-worker/taskcluster_proxy.go
Fixes a nil pointer dereference which would look like this in the task logs:
```bash
[taskcluster:error] could not start taskcluster proxy: timeout waiting for taskcluster-proxy port 80 to be active
[taskcluster:error] goroutine 1 [running]:
[taskcluster:error] runtime/debug.Stack()
[taskcluster:error] 	/home/task_174121127671722/go/go/src/runtime/debug/stack.go:26 +0x5e
[taskcluster:error] main.(*TaskRun).Run.func2()
[taskcluster:error] 	/home/task_174121127671722/taskcluster/workers/generic-worker/main.go:999 +0x9d
[taskcluster:error] panic({0xa80580?, 0x1095e40?})
[taskcluster:error] 	/home/task_174121127671722/go/go/src/runtime/panic.go:785 +0x132
[taskcluster:error] github.com/taskcluster/taskcluster/v83/workers/generic-worker/tcproxy.(*TaskclusterProxy).Terminate(0xc000254d80?) …
```
=> fix(generic-worker): don't panic when stopping tc-proxy feature

changelog/OU8YgOZpT_O2KZBLB3QecQ.md, workers/generic-worker/taskcluster_proxy.go, workers/generic-worker/tcproxy/tcproxy.go
In the presence of more than one address on the docker bridge network, we were assuming the gateway could be found on the first network, which is not necessarily the case.  Instead, we now get all gateways from `docker network inspect`, and select the first ipv4 one (ipv6 addresses would need more massaging to work in URLs, so we skip them).
=> fix(g-w): better detection of the docker bridge ip address

.goreleaser.yaml, changelog/Kajl-SVPShaOFM7yemQ_TQ.md, infrastructure/tooling/src/build/tasks/client-shell.js
>Upgrades `goreleaser` to v2.7.0 for building `client-shell` binaries during releases.
=> chore: bump `goreleaser` to v2.7.0

changelog/issue-7581.md, tools/d2g/d2g.go, tools/d2g/d2gtest/d2g_test.go, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml, workers/generic-worker/d2g_test.go
Fixes #7581.
Should have been handled in https://github.com/taskcluster/taskcluster/pull/7551.
>D2G: add `audio`/`video` os-groups and scopes needed when the Docker Worker task payload requests these loopback devices.
=> fix(d2g): add `audio`/`video` os-groups and scopes

changelog/Qgfg20wZSni3PRa0gxb84A.md, workers/generic-worker/d2g_test.go, workers/generic-worker/mounts.go, workers/generic-worker/runtime/runtime_linux.go
I think this is left over from podman days, and no longer needed.
@Eijebong can you confirm?
Thanks!
=> Generic Worker: don't update /etc/subgid since podman support dropped

changelog/bihkSU9hSAe8aBJ7aJMLLg.md, tools/d2g/d2g.go, tools/d2g/d2gtest/d2g_test.go, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml, workers/generic-worker/d2g_test.go, workers/generic-worker/loopback_audio_linux.go, workers/generic-worker/loopback_video_linux.go
Reverts taskcluster/taskcluster#7583
>Generic Worker: only warn about missing `audio`/`video` os groups for non-d2g tasks.
A great callout by @jcristau here https://github.com/taskcluster/taskcluster/pull/7583#issuecomment-2733983296
=> Revert "fix(d2g): add `audio`/`video` os-groups and scopes"

.taskcluster.yml, changelog/dJVjhHlYSl2A3CKKG9n83g.md, taskcluster/kinds/client/kind.yml, taskcluster/kinds/db/kind.yml, taskcluster/kinds/library/kind.yml, taskcluster/kinds/lint/kind.yml, taskcluster/kinds/meta/kind.yml, taskcluster/kinds/service/kind.yml, taskcluster/kinds/ui/kind.yml
Mainly to test/use the `chain-of-trust-additional-data.json` d2g/gw feature.
=> chore: enable CoT on CI tasks

.taskcluster.yml, changelog/Ex6It1SVQgWNlehACJqdlA.md
Prevents issues like:
```bash
export TASKCLUSTER_ROOT_URL='https://community-tc.services.mozilla.com/' && verify_cot --task-type decision a2d7wQF5QxeHl4l_wZFX5Q
scriptworker.exceptions.CoTError: 'path public/actions.json not in decision a2d7wQF5QxeHl4l_wZFX5Q chain of trust artifacts! This is likely a bug in a2d7wQF5QxeHl4l_wZFX5Q: docker-worker does not fail if a declared artifact was never generated by the task. Please download and make sure the artifact public/actions.json is the one you expect. If it is, then please reach out to the Release Engineering team. For more information: https://github.com/taskcluster/taskgraph/issues/47'
```
=> fix(decision): don't remove `artifacts/actions.json` so CoT can still verify

changelog/issue-6464.md, generated/references.json, go.mod, go.sum, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml, tools/d2g/genericworker/generated_types.go, workers/generic-worker/README.md, workers/generic-worker/generated_insecure_darwin.go, workers/generic-worker/generated_insecure_freebsd.go, workers/generic-worker/generated_insecure_linux.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/gwconfig/config.go, workers/generic-worker/helper_test.go, workers/generic-worker/main.go, workers/generic-worker/process/insecure.go, workers/generic-worker/process/multiuser_posix.go, workers/generic-worker/process/multiuser_windows.go, workers/generic-worker/process/posix.go, workers/generic-worker/process/process.go, workers/generic-worker/resource_monitor.go, workers/generic-worker/schemas/insecure_posix.yml, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml, workers/generic-worker/usage.go
Fixes https://github.com/taskcluster/taskcluster/issues/6464.
Fixes https://github.com/taskcluster/taskcluster/issues/6894.
>Generic Worker: adds memory usage monitoring during tasks and reports average and peak memory used, in addition to the system's total available memory.
>
>If the total percentage of memory used exceeds 90% for 5 consecutive measurements at 0.5s intervals, the worker will abort the task to prevent OOM crashes and errors. If `disableOOMProtection` (default `false`) is set to `true` in the worker configuration, the worker will continue to monitor and report on memory usage, but will not abort the task if memory consumption is high.
>
>Resource monitoring can be disabled with worker config `enableResourceMonitor` (default `true`) or per task via …
=> feat(generic-worker): monitor memory usage during tasks and help prevent OOMs

changelog/issue-7594.md, generated/references.json, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/chain_of_trust_test.yml, tools/d2g/d2gtest/testdata/testcases/container_engine_test.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/dw_features_tests.yml, tools/d2g/d2gtest/testdata/testcases/env_escaping_test.yml, tools/d2g/d2gtest/testdata/testcases/no_artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml, tools/d2g/dockerworker/generated_types.go, tools/d2g/genericworker/generated_types.go, workers/docker-worker/schemas/v1/payload.yml, workers/generic-worker/d2g_test.go, workers/generic-worker/generated_insecure_darwin.go, workers/generic-worker/generated_insecure_freebsd.go, workers/generic-worker/generated_insecure_linux.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/schemas/insecure_posix.yml, workers/generic-worker/schemas/multiuser_posix.yml
Fixes #7594.
>Docker Worker (D2G): adds `volume` type for artifacts. This is strictly used for D2G purposes only. Use this type to have D2G volume mount your artifact path instead of `docker cp`'ing the artifact at the end of the task run. This can be useful under spot termination instances where the `docker cp` command doesn't get a chance to run, instead a volume mount will have the files on the host ready for upload as soon as the spot termination requests comes in.
=> feat(d2g): add volume mount artifact type

changelog/issue-7606.md, ui/src/components/WorkerDetailsCard/index.jsx
=> feat(ui): Display quarantine history with pagination

changelog/issue-7543.md, docker-compose.dev.yml, infrastructure/tooling/src/generate/generators/docker-compose.js, ui/.dockerignore, ui/Dockerfile
At some point yarn switched to Plug'n'Play modules installation which results in no 'node_modules' folder present.
I'm not exactly sure how it should work inside docker container, since yarn couldn't find the packages it installed.
Switching to the node_modules behaviour.
Also fixing mapped folders and adding missing port mapping for dev ui
Fixes #7543
=> feat(dev): Fixes local broken UI container

changelog/issue-6783.md, generated/docs-search.json, generated/docs-table-of-contents.json, infrastructure/tooling/src/generate/generators/generic-worker.js, ui/docs/reference/workers/generic-worker/README.mdx, ui/docs/reference/workers/generic-worker/usage.mdx
Fixes #6783.
>Docs: adds Generic Worker Configuration help page to the reference docs.
=> feat(docs): add generic worker config page

.github/dependabot.yml, changelog/O4PcaC2FTK2ZJBDj15Xwtw.md
Will prevent future PRs like the following https://github.com/taskcluster/taskcluster/pulls?q=is%3Apr+is%3Aclosed+in+%2Fworkers%2Fdocker-worker+author%3Aapp%2Fdependabot+
https://github.com/taskcluster/taskcluster/pull/7631 was the most recent that I closed. We don't need to spend CI resources on keeping docker worker deps up-to-date.
=> chore(deps): ignore docker worker dependabot updates

changelog/Whg-6bCnTgSZzeNFwnSdXg.md, workers/generic-worker/artifactfeature.go, workers/generic-worker/main.go
Generic Worker now handles artifact upload inside a task feature rather than the main processing loop of the task execution. This refactor improves code modularity.
=> Generic Worker - make artifacts a task feature

changelog/issue-7650.md, workers/generic-worker/multiuser_windows.go
Fixes #7650.
>Generic Worker (windows): fixes cache mount issue where generic worker fails to reset permissions on the cache directory. First noticed in [v81.0.3](https://docs.taskcluster.net/docs/changelog?version=v81.0.3).
=> fix(generic-worker): fix gw windows reset permissions on cache dir

changelog/issue-7652.md, workers/generic-worker/chain_of_trust.go
>Generic Worker: remove temp file created while adding additional data to chain of trust file.
=> fix(generic-worker): clean up temp files

changelog/issue-7368.md, go.mod, go.sum, workers/generic-worker/artifacts/s3.go
Fixes #7368.
>Generic Worker: increase performance of artifact uploads by removing a redundant file copy operation.
The additional logs should give more insight into #7623.
=> fix(generic-worker): remove redundant file copy during artifact upload process

changelog/PwkwA18BRaeBP7UfNB95YQ.md, ui/src/components/WMWorkerPoolEditor/index.jsx, ui/src/views/Provisioners/ViewWorkers/index.jsx
>UI: don't show `Requested` filter option on `Queue Workers` view, link to `W-M Workers` filtered view when clicking on `Requested Capacity` or `Stopping Capacity` buttons, don't redirect to Worker Manager Worker Pools page after saving Worker Pool config changes.
=> chore(ui): small navigation and filtering tweaks

changelog/issue-7664.md, services/github/src/utils.js, services/github/test/utils_test.js
The `extractLog` function was not respecting `maxPayloadLength` when the number of lines was less than the amount requested, even if the content of said lines were exceeding the max length. Which leads to github rejecting some checks updates if logs had long lines in their tail.
Fixes #7664
=> Properly truncate logs even if it contains less lines than requested

changelog/issue-7671.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml, workers/generic-worker/d2g_test.go
Fixes #7671.
>D2G: removes unneeded `kvm` and `libvirt` OS groups for generic worker task user if KVM device is requested.
=> fix(d2g): remove unneeded os groups when using kvm

changelog/issue-7678.md, tools/d2g/d2g.go, tools/d2g/d2gtest/testdata/testcases/artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/chain_of_trust_test.yml, tools/d2g/d2gtest/testdata/testcases/container_engine_test.yml, tools/d2g/d2gtest/testdata/testcases/decision_task_tests.yml, tools/d2g/d2gtest/testdata/testcases/devices_tests.yml, tools/d2g/d2gtest/testdata/testcases/docker_image_tests.yml, tools/d2g/d2gtest/testdata/testcases/dw_features_tests.yml, tools/d2g/d2gtest/testdata/testcases/env_escaping_test.yml, tools/d2g/d2gtest/testdata/testcases/fuzzing_tests.yml, tools/d2g/d2gtest/testdata/testcases/no_artifacts_test.yml, tools/d2g/d2gtest/testdata/testcases/task_def_test.yml, tools/d2g/dockerimageartifact.go, tools/d2g/indexeddockerimage.go, workers/generic-worker/artifact_feature.go, workers/generic-worker/d2g_feature.go, workers/generic-worker/helper_test.go, workers/generic-worker/insecure_linux.go, workers/generic-worker/insecure_other.go, workers/generic-worker/main.go, workers/generic-worker/model.go, workers/generic-worker/multiuser_linux.go, workers/generic-worker/multiuser_other.go, workers/generic-worker/multiuser_windows.go, workers/generic-worker/payload_linux.go, workers/generic-worker/process/insecure.go
Fixes #7678.
Fixes #7599.
>D2G: pre and post-task-processing (image pulling/loading/saving, copying artifacts out of container, creating chain of trust additional data file, removing container/volumes, handling max runtime) now happens within the D2G Task Feature in Generic Worker, as opposed to within the resulting translated task payload. This slims the translated task payload to only the `docker run ...` command.
=> feat(d2g): convert d2g to generic worker task feature

changelog/issue-5786.md, workers/generic-worker/tcproxy/tcproxy.go
On posix systems, when killing a child process, the parent process has to call `wait(2)` on it or the child process will be left in a "zombie" state until the parent exits, at which point PID 1 will do that.
For generic worker, it means that every time it starts a proxy, it leaks one zombie as it's never waiting for it until it gets restarted which in some cases could be never (headless multiuser, insecure engine).
By simply calling `Wait` on the proxy process after killing it, it now ends up calling `wait(2)` on it, reaping it. We simply ignore the actual return status and print an error in case something went horribly wrong.
I got bitten by this this weekend where after processing a few hundred tasks, linux was just refusing to start new processes leading to the worker being unable to …
=> Properly reap the proxy process when stopping the feature

changelog/issue-7628.md, ui/docs/reference/workers/generic-worker/usage.mdx, workers/generic-worker/README.md, workers/generic-worker/gwconfig/config.go, workers/generic-worker/helper_test.go, workers/generic-worker/main.go, workers/generic-worker/metadata_feature.go, workers/generic-worker/usage.go
Fixes https://github.com/taskcluster/taskcluster/issues/7628.
>Generic Worker: adds a `Metadata` feature (controlled with worker config `enableMetadata` [default: `true`], not controllable in the task payload) that writes out a file `generic-worker-metadata.json` (in the current working directory of the generic worker process) containing information about the last task run.
>
>Currently, the file will look something like this:
>
>```json
>{
>	"lastTaskUrl": "https://firefox-ci-tc.services.mozilla.com/tasks/Klc17PU-TMmo4axlfihKJQ/runs/0"
>}
>```
>
>Additional data may be added to this file in future releases.
=> feat(generic-worker): add metadata task feature for data on recent task run

changelog/WRhF7-PBTZSXxbpUkHvzhw.md, ui/docs/reference/workers/generic-worker/usage.mdx, workers/generic-worker/README.md, workers/generic-worker/gwconfig/config_linux.go, workers/generic-worker/gwconfig/config_other.go, workers/generic-worker/gwconfig/config_windows.go, workers/generic-worker/payload_linux.go, workers/generic-worker/usage_linux.go
>Generic Worker (D2G): no longer logs translated payload and our recommendation to migrate all tasks to Generic Worker payload format. Worker config `d2gConfig.logTranslation` is now unused and will be removed in a future release.
=> chore(d2g): remove D2G warnings/logs

changelog/D269EGPRTcu5qphZJ66W6A.md, workers/generic-worker/artifact_feature.go
While reading through the artifact feature code, I realized that we could potentially run into a variable shadowing issue due to conflicting variable names for the task artifacts we're looping over and the input to the goroutine that handles the upload.
=> chore(generic-worker): remove potential future variable shadowing issues in artifact feature

changelog/issue-7630.md, workers/generic-worker/artifact_feature.go, workers/generic-worker/artifacts/artifacts.go, workers/generic-worker/artifacts/link.go, workers/generic-worker/artifacts/redirect.go, workers/generic-worker/artifacts_test.go
Will improve artifact upload performance for tasks with more than one artifact included in their payload. Could help in cases like https://github.com/taskcluster/taskcluster/issues/7630.
>Generic Worker: improves artifact upload process by parallelizing the scanning of the system for file/directory artifacts from the payload.
=> feat(generic-worker): parallelize file scanning for artifacts

changelog/bug-1967254.md, workers/generic-worker/artifacts/error.go
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1967254.
>Generic Worker (d2g): uses info log level when uploading error artifacts if the artifact was marked optional. Previously, the log would contain `[taskcluster:error]` which Treeherder would identify as a failure, even if the task is successful.
=> fix(generic-worker): use info level when uploading optional error artifact

changelog/issue-4943.md, ui/src/utils/getArtifactUrl.js, ui/src/utils/getArtifactUrl.test.js
This happened because user session is being initialized twice. First time it is initialized right after successful callback from external provider, and at this point credentials are not being issued. Second time it is initialized when AuthController detects that credentials are missing, so it fetches them and updates user session with valid credentials.
So between those two events error happened and tried to sign a url without valid credentials.
Fixes #4943
=> feat(ui): Fix signed url issue without credentials

changelog/issue-7757.md, services/queue/src/api.js, services/queue/test/querytasks_test.js
There was a slight mismatch between output schema validation and input validation, which resulted in 500 errors instead of 400
Fixes #7757
=> Queue API validation rules

changelog/issue-7763.md, infrastructure/k8s/templates/taskcluster-queue-deployment-workerMetrics.yaml, infrastructure/tooling/src/generate/generators/k8s.js
We force replcas:0 for such deployments
Fixes #7763
=> feat(k8s): Disable metrics-only deployments without prometheus

changelog/issue-7769.md, changelog/issue-7770.md, generated/references.json, tools/d2g/genericworker/generated_types.go, ui/docs/reference/workers/generic-worker/usage.mdx, workers/generic-worker/README.md, workers/generic-worker/generated_insecure_darwin.go, workers/generic-worker/generated_insecure_freebsd.go, workers/generic-worker/generated_insecure_linux.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/gwconfig/config.go, workers/generic-worker/helper_test.go, workers/generic-worker/main.go, workers/generic-worker/process/process.go, workers/generic-worker/resource_monitor_feature.go, workers/generic-worker/schemas/insecure_posix.yml, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml, workers/generic-worker/taskstatus.go, workers/generic-worker/usage.go
Fixes #7769.
>Generic Worker: resource monitor will print out its usage summary after aborting the task.
Fixes #7770.
>Generic Worker: adds additional resource monitoring auto-abortion configuration to better fine-tune how your worker aborts running task processes.
>
>  * `absoluteHighMemoryThreshold`: The minimum amount of available memory (in bytes) required before considering task abortion. If available memory drops below this value, it may trigger an abort. Default: `524288000` (500MiB).
>  * `relativeHighMemoryThreshold`: The percentage of total system memory usage that, if exceeded, contributes to the decision to abort the task. Default: `90`.
>  * `allowedHighMemoryDurationSecs`: The maximum duration (in seconds) that high memory usage conditions can persist before the task is …
=> feat(generic-worker): fine-tune auto-abortion of tasks

changelog/ZPZBjOAmQhCB9OdPXWL-cQ.md, generated/references.json, tools/d2g/genericworker/generated_types.go, ui/docs/reference/workers/generic-worker/usage.mdx, workers/generic-worker/README.md, workers/generic-worker/generated_insecure_darwin.go, workers/generic-worker/generated_insecure_freebsd.go, workers/generic-worker/generated_insecure_linux.go, workers/generic-worker/generated_multiuser_darwin.go, workers/generic-worker/generated_multiuser_freebsd.go, workers/generic-worker/generated_multiuser_linux.go, workers/generic-worker/generated_multiuser_windows.go, workers/generic-worker/gwconfig/config.go, workers/generic-worker/helper_test.go, workers/generic-worker/main.go, workers/generic-worker/process/process.go, workers/generic-worker/resource_monitor_feature.go, workers/generic-worker/schemas/insecure_posix.yml, workers/generic-worker/schemas/multiuser_posix.yml, workers/generic-worker/schemas/multiuser_windows.yml, workers/generic-worker/usage.go
Follow-up on https://github.com/taskcluster/taskcluster/pull/7775.
>Generic Worker: renamed the following worker configuration options to avoid confusion:
>
>  * `absoluteHighMemoryThreshold` --> `minAvailableMemoryBytes`
>  * `relativeHighMemoryThreshold` --> `maxMemoryUsagePercent`
=> chore(generic-worker)!: rename OOM config options

changelog/issue-7786.md, services/github/src/handlers/job.js, services/github/test/handler_test.js
If `/taskcluster xx` command didn't produce any tasks - comment would receive a reaction
Fixes #7786
=> feat(github): Github service reacts to empty tasks

changelog/dVLM3e4gRgeY-uPKledW2Q.md, workers/generic-worker/helper_multiuser_test.go, workers/generic-worker/process/multiuser_darwin.go
This should improve coverage of the new launch agent setup on macOS, by enabling its use by default in CI tests.
=> Generic Worker: run CI tests via launch agent on macOS by default

changelog/U-1xwYs4Q7WO2PNapNeVHg.md, workers/generic-worker/process/multiuser_darwin.go
It occurred to me that there may be a risk that the side of the pipes that are forwarded to the launch agent might get freed prematurely by the go runtime garbage collector. It may be this isn't needed, e.g. if go internally holds onto one side of a pipe if the other side is still referenced, but better to be safe than sorry. It certainly won't do any harm holding on to these references, and may prevent intermittent issues, or future proof against them if the garbage collector mechanics change in a future go release.
=> Generic Worker: keep both ends of Launch Agent pipes alive while in use

changelog/issue-7842.md, services/queue/src/api.js, services/queue/src/claimresolver.js, services/queue/src/deadlineresolver.js, services/queue/src/dependencytracker.js, services/queue/test/deadline_test.js
=> queue: always include task tags in task-pending and task-exception pulse messages

changelog/K6jPN8gxTNChW1TEcw2YEQ.md, clients/client-web/package.json, clients/client/package.json
Followup to https://github.com/taskcluster/taskcluster/pull/7865.
>Fix releases of `@taskcluser/client` and `@taskcluster/client-web` by making their access public by default.
=> fix(release): make npm packages public by default

changelog/issue-7680.md, services/worker-manager/src/providers/aws.js
Fixes #7680.
>Worker Manager (AWS): terminates workers that are in the stopped state.
=> fix(worker-manager): terminate aws workers that are in stopped state

changelog/issue-7914.md, services/worker-manager/src/providers/azure/index.js, services/worker-manager/test/provider_azure_test.js
Fixes #7914.
>Worker Manager (Azure): uses `Static` public IP allocation with the `Standard` SKU.
=> fix(worker-manager): use static public ip allocation for azure

changelog/d2bDYorTQ8CdzChNWDPgPg.md, tools/worker-runner/provider/azure/azure.go
>Worker Runner/Generic Worker (Azure): polls the metadata service for events the worker should gracefully terminate on every second (down from 15s). This frequency is recommended by Microsoft [here](https://learn.microsoft.com/en-us/azure/virtual-machines/windows/scheduled-events#polling-frequency) and will hopefully reduce tasks resolving as `claim-expired`.
=> fix(worker-runner): poll azure metadata service every second

go.mod, go.sum
Reverts taskcluster/taskcluster#7920 due to https://github.com/google/go-containerregistry/issues/2072.
=> Revert "build(deps): bump github.com/docker/docker from 27.5.0+incompatible to 28.0.0+incompatible"

changelog/IlCVzyfhQbKqmnj4j1epPQ.md, go.mod, go.sum
https://github.com/taskcluster/taskcluster/pull/7936 broke our releases due to https://github.com/ulikunitz/xz/issues/65.
>Bumps `github.com/ulikunitz/xz` from v0.5.14 to v0.5.15 to fix our release process. v88.1.0 was broken due to https://github.com/ulikunitz/xz/issues/65.
=> fix(release): bump go dep that broke release

changelog/EoscfzMoTPWBsC3kEIvYOw.md, internal/mocktc/queue.go, tools/worker-runner/provider/aws/awsprovider.go, tools/worker-runner/provider/azure/azure.go, tools/worker-runner/provider/azure/azure_test.go, tools/worker-runner/provider/azure/metadata.go, tools/worker-runner/provider/azure/metadata_test.go, tools/worker-runner/provider/google/google.go, tools/worker-runner/worker/genericworker/runmethod_windows.go, tools/workerproto/protocol.go, tools/workerproto/protocol_test.go, workers/generic-worker/main.go
>Worker Runner: adds additional logging around sending `graceful-termination` request to worker.
>
>Worker Runner (windows): fixes protocol pipe connection so that Generic Worker can communicate with Worker Runner. This allows `graceful-termination` requests to be properly sent and received, among other message types. You must include `--with-worker-runner` in your Generic Worker service configuration on the `run` subcommand.
=> fix(worker-runner): protocol pipe now works on windows

changelog/TaDW6njEQ-OrgiJdMf6G5Q.md, tools/worker-runner/worker/genericworker/runmethod_windows.go
>Worker Runner (Windows): capture Generic Worker service exit code and exit early if the worker is rebooting, preventing a Worker Manager `removeWorker` API call.
=> fix(worker-runner): capture windows service exit code for reboots

changelog/issue-7500.md, services/github/src/handlers/status.js, services/github/test/handler_test.js
=> feat(github): Marking github builds as failed after no retries left

changelog/issue-7969.md, workers/generic-worker/d2g_feature.go
Fixes #7969.
>D2G: fixes issue with loading the docker image artifact if the image already exists with a separate ID, causing the following output to be improperly parsed by D2G: `The image <imageName> already exists, renaming the old one with ID <sha> to empty string`.
=> fix(d2g): duplicate image with separate IDs get handled properly
