taskcluster/taskcluster

services/hooks/test/helper.js, services/index/test/helper.js, services/notify/test/helper.js, services/queue/test/helper.js, services/secrets/test/helper.js
Lots of our tests assume exclusive access to some global resource.  This switches to using a uniquely-named resource for each test run, to avoid such conflicts.
=> Bug 1517662 - fix tests that fail when run simultaneously

libraries/api/README.md, libraries/api/src/middleware/auth.js, libraries/api/src/middleware/handle.js, libraries/api/test/auth_test.js, libraries/testing/test/fakeauth_test.js
The important thing here is not losing track of the message template, so
users still see the explanation of their InsufficientScopes error.  But
this also factors out the translation of AuthorizationError ->
InsufficientScopes and AuthenticationError -> AuthenticationFailed.
=> Bug 1518137 - better libraries/api error handling, fix InsufficientScopes

.taskcluster.yml, infrastructure/builder/package.json, services/auth/package.json, services/github/package.json, services/hooks/package.json, services/index/package.json, services/login/package.json, services/notify/package.json, services/purge-cache/package.json, services/queue/package.json, services/secrets/package.json, services/treeherder/package.json
Later version of Node (`10.14.2` and up) could break tests in tc-lib-references (there was a change in Node 10.14.2 for which `fs-mock` library we use to mock the file system needs a patch).
=> Switch to Node 10.14

services/login/package.json, services/login/src/handlers/mozilla-auth0.js, yarn.lock
We used to use an Auth0 library for headless browser 🕸🎃🕷👻, latest version of which is completely broken in Node. This PR is to switch to the Node library
=> Switch to Auth0 library for correct runtime env

services/purge-cache/test/helper.js
Fixes the unhandled rejection in
https://tools.taskcluster.net/groups/WXtqNAdkSRuG5EWQ5egjXA/tasks/RBrIVyBhQ4-QH6XFEdeW0w/runs/0/logs/public%2Flogs%2Flive_backing.log
=> Properly await table row removal in tests

services/queue/schemas/v1/post-artifact-request.yml
(ported from https://github.com/taskcluster/taskcluster-queue/pull/309)
=> Bug 1516463 - use minItems, not minLength, for array length

infrastructure/builder/src/build/repo.js, infrastructure/builder/taskcluster-spec/build.yml
This will get changed pretty radically when we build into a single docker image (bug 1516347). But the fundamental problem is still there: balancing ease of development against security.
Building from your working copy makes it easy to, for example, build an image of your current work in progress and test it in a dev deployment.  As I've implemented this, doing otherwise would require pushing to a github repo, then editing the spec to point to that branch on that repo, then building.
Other ideas:
* `git clone` from the working copy by default, and warn if `git status` shows un-checked-in files.  This would safely ignore everything that git ignores
* `git clone` from the working copy when given a command-line option (e.g., `--local-repo`)
thoughts?
=> Bug 1520061 - build monorepo from a git clone, not working copy

services/notify/src/irc.js
The `util.promisify` doesn't seem to have worked and I'm not sure why! This should work I hope.
Currently:
```
Jan 15 09:03:16 taskcluster-notify app/irc.1: 2019-01-15T17:03:16.591Z taskcluster-lib-loader error while loading component 'irc': TypeError: this.once is not a function 
Jan 15 09:03:16 taskcluster-notify app/irc.1: TypeError: this.once is not a function 
Jan 15 09:03:16 taskcluster-notify app/irc.1:     at Client.connect (/app/node_modules/irc-upd/lib/irc.js:785:14) 
Jan 15 09:03:16 taskcluster-notify app/irc.1:     at Promise (internal/util.js:276:30) 
Jan 15 09:03:16 taskcluster-notify app/irc.1:     at new Promise (<anonymous>) 
Jan 15 09:03:16 taskcluster-notify app/irc.1:     at internal/util.js:275:12 
Jan 15 09:03:16 taskcluster-notify app/irc.1:     at IRCBot.start …
```
=> Fix promises in irc

services/notify/src/irc.js
One last thing to fix I think. Native promises don't have a `timeout()`
=> Try again at fixing irc-upd stuff

package.json
We no longer need this after remotely-signed-s3 was released
=> Remove outdated resolution

.github/CODEOWNERS
Note that the last match for a file wins, so this does not override the
more-specific assignments to specific people.
=> Make services-reviewers responsible for some services, libraries

services/github/src/handlers.js, services/github/test/handler_test.js
I retain task id in the check names to ensure different tasks with the same name will get different check runs without throwing errors. But I have the task name from `taskDefinition.metadata` preceding that, so that when you look at the list of 27 tasks, you could instantly tell which is which. I am also missing link to the task group - so I added it to the task description.
Downside of this particular solution is that I make additional network call. Alternative solution would be to add metadata to the pulse messages. (I would actually prefer the alternative solution, unless there are objections. I think queue service won't die if it will send some additional bit of data, wheres additional network calls here make tc-gh more brittle. On the other hand, those messages are public API, so …
=> Have a better task info in Checks

libraries/validate/src/schemaset.js
This rewritten schema points to the metaschema, as enforced by other
validation checks.
=> Bug 1260285 - publish legacy schemas with a rewritten $schema

services/github/src/handlers.js, services/github/src/tc-yaml.js
I decided to try this: since we get all the tasks anyway, I added a check to examine their `routes` field. If at least a single task belongs to the checks API - stop the whole handler.
I also modified the loop so that we stop iterating as soon as we found a failing task. For all the above I have to use good old `for` loop (I know, I'm so fancy ✨)
Finally, I scratched my lodash itch
=> Bug in checks: creates a checkrun for the whole group

netlify.toml
I'm currently trying to switch netlify to use taskclusluster-web from the monorepo. The logs are currently complaining:
```bash
7:10:07 AM: error taskcluster-web@1.0.0: The engine "node" is incompatible with this module. Expected version "10.14.0". Got "10.0.0"
```
=> Update netlify node version

ui/src/components/Button/index.jsx, ui/src/components/WorkerTypesTable/index.jsx
A [commit](https://github.com/taskcluster/taskcluster-web/commit/508ff89e65304d8e67723f039b62502c5ed91dbe) later added after the migration of tc-web to the monorepo has started.
=> Fix: Worker types view modal not opening

package.json
From IRC:
```
<dustin> hassan: do we need to adjust renovate settings somehow for tc-web?  That's a lot of PRs :)
9:34 AM 
<hassan> dustin: yeah :) i think having renovate send a PR once a week would be good. thoughts?
9:36 AM 
<dustin> for just one dependency?  I suspect we would fall behind at that rate, judging by the number of PRs we've seen just for the other services
9:38 AM 
<hassan> dustin: no, for all dependencies. I prefer to deal with all renovate PRs at once than to be notified every couple of hours
9:38 AM 
<dustin> ah, that seems reasonable then.  Let's see what brian says
```
=> Configure renovate to send PRs on a weekly basis

services/hooks/config.yml, services/hooks/package.json, services/hooks/src/data.js, services/hooks/src/main.js, services/hooks/src/v1.js, services/hooks/test/api_test.js, services/hooks/test/expires_test.js
Another alternative solution is to get the hookIds from the Hook table. Then load from `Lastfires`  for  each hookId and delete instead of one long scan in the current patch. Because i'm think there can be memory leak with the present solution.
=> [Bug 1491551] continue - expire limit lastfires to 100 per hookId

libraries/references/test/built-services_test.js, package.json, yarn.lock
Not sure why this wasn't caught by renovate. We'll have to check our config.
=> Use newer mock-fs to allow us to upgrade node

.taskcluster.yml
In one of the failures of `yarn generate`, the task timed out with `--more--` at the bottom, suggesting it was running a pager and waiting for input..
=> only show a diff when generate produces one, and don't use a pager

services/built-in-workers/src/main.js
Bugzilla Bug: [1522307](https://bugzilla.mozilla.org/show_bug.cgi?id=1522307)
/cc @hybrid1999 
This fixes a combination of => and `function` syntax, so the component actually works.  Without this it was just exiting immediately on startup.
=> Bug 1522307 - fix startup of built-in-workers

services/login/src/main.js
This requires "production" auth0 credentials which are easy to leak.
There are better ways to determine this information, anyway.
Bugzilla Bug: [1519943](https://bugzilla.mozilla.org/show_bug.cgi?id=1519943)
=> Bug 1519943 - remove utility to display user profiles

services/hooks/src/taskcreator.js
This separates the different firedBy options, and also distinguishes
task-creation that results in a task from that which results in no task
("declined").
This should allow us to see any spikes in task-creation if, for example,
there is abuse of the pulse bindings option.
Bugzilla Bug: [1517000](https://bugzilla.mozilla.org/show_bug.cgi?id=1517000)
=> Bug 1517000 - add counts of all fires

services/index/src/api.js, services/index/test/api_test.js, services/index/test/helper.js, services/index/test/index_test.js
Bugzilla Bug: [1523215](https://bugzilla.mozilla.org/show_bug.cgi?id=1523215)
I managed to reproduce a race condition locally, where the polling detected one index route being added and started the rest of the assertions before the other index routes had been added.
For the timeout in `api_test.js`, I took a wild guess that it was an actual timeout -- from creating a bunch of entities sequentially -- rather than a hang.  I couldn't reproduce that issue locally with or without the fix.
=> Bug 1523215 - improve index tests

libraries/api/test/auth_test.js
This timeout failed for me, probably when there was a "hiccup" with the disk on the VM I was using causing loading of schemas to take longer than 500ms.
=> increase a half-second timeout in lib-api tests

README.md, generated/docs/worker-manager/README.md, services/README.md, services/worker-manager/README.md
This is needed so that the table of content for /docs is generated properly. The content of the README can be filled out later.
=> Add missing README

infrastructure/terraform/hooks-service.tf, services/hooks/src/data.js
Since this changes the keys, we cannot use the same table.  So this also
updates the table name in the Terraform configuration to point to a
fresh new table.
Bugzilla Bug: [1524406](https://bugzilla.mozilla.org/show_bug.cgi?id=1524406)
=> Bug 1524406 - Fix keys for LastFire table

libraries/monitor/test/uncaught_test.js
Without this, the DEBUG output obscures the expected stdout..
(found while looking for flaky tests)
=> Omit DEBUG when running a node subprocess

clients/client-web/README.md, clients/client-web/package.json, clients/client-web/src/credentials.js, clients/client-web/yarn.lock
This also adds a check that the library can be require`d in a Node
environment, which helps at least one user (Treeherder) to run some
of its tests in a Node environment.  We do *not* guarantee that any of
the module's functionality actually works outside of a browser.
Bugzilla Bug: [1523376](https://bugzilla.mozilla.org/show_bug.cgi?id=1523376)
=> Bug 1523376 - use crypto-js instead of stealing Hawk's copy

services/hooks/src/listeners.js
Bugzilla Bug: [1527416](https://bugzilla.mozilla.org/show_bug.cgi?id=1527416)
=> Bug 1527416 - get a fresh copy of the hook before triggering

libraries/loader/README.md, libraries/loader/package.json, libraries/loader/src/loader.js, libraries/loader/test/loader_tests.js, libraries/loader/test/runtests.sh, services/auth/src/main.js, services/built-in-workers/src/main.js, services/github/src/main.js, services/hooks/src/main.js, services/index/src/main.js, services/login/src/main.js, services/notify/src/main.js, services/purge-cache/src/main.js, services/queue/src/main.js, services/secrets/src/main.js, services/treeherder/src/main.js, services/web-server/src/index.js, services/worker-manager/lib/main.js
This simplifies the setup at the bottom of the `main.js` in our services and allows for easier requiring of components in modules that otherwise are not loaded by the loader. An example of what I want to do is:
```js
const monitor = require('./main')('monitor').prefix('script');
monitor.info('whatever', {foo: 5});
```
This way we can configure monitor in one place, using configuration loaded in the same way as all of our other components but also allow people to have modules that exist outside the `main.js` setup.
Bugzilla Bug: [1527723](https://bugzilla.mozilla.org/show_bug.cgi?id=1527723)
=> [Bug 1527723] Allow setting defaults for loader virtual components

package.json
As described in https://help.heroku.com/P5IMU3MP/heroku-node-js-build-script-change-faq
iiuc, `heroku-run-build-script` is just there so that we can opt in to the new behavior now rather than being surprised on the 11th.
=> Set build settings to the way heroku wants them

libraries/pulse/src/client.js, libraries/pulse/src/consumer.js, libraries/pulse/src/publisher.js
* Be more careful to remove events on client, since it is long-lived
* Allow more than the default 10 events on client and connection, since
in normal use the number might be much larger.
Bugzilla Bug: [1527427](https://bugzilla.mozilla.org/show_bug.cgi?id=1527427)
=> Bug 1527427 - fix event emission in lib-pulse

.taskcluster.yml
Bugzilla Bug: [1527699](https://bugzilla.mozilla.org/show_bug.cgi?id=1527699)
=> Bug 1527699 - don't ignore exit status from yarn generate

ui/src/components/TaskGroupTable/index.jsx
Fixes https://github.com/taskcluster/taskcluster/issues/246.
=> Make task group default sort clearer

infrastructure/terraform/hooks-service.tf
Bugzilla Bug: [1525448](https://bugzilla.mozilla.org/show_bug.cgi?id=1525448)
This will reqiure #241.
=> Bug 1525448 - add hooks expiration cronjob

clients/client-web/src/clients/Notify.js, clients/client/src/apis.js, generated/docs/notify/references/api.json, generated/references.json, services/notify/config.yml, services/notify/src/api.js, services/notify/src/data.js, services/notify/src/main.js, services/notify/src/notifier.js, services/notify/test/api_test.js, services/notify/test/helper.js
@imbstack suggested using a term with less cultural baggage (at least in the US) than "blacklist".  Seems reasonable! /cc @OjaswinM
=> Rename Blacklist to Denylist

services/web-server/src/clients.js, services/web-server/src/graphql/Notify.graphql, services/web-server/src/graphql/Root.graphql, services/web-server/src/loaders/notify.js, services/web-server/src/resolvers/Notify.js
Bugzilla Bug: [1520918](https://bugzilla.mozilla.org/show_bug.cgi?id=1520918)
Alright so I tried making some changes but I'm getting an AssertionErro:- 
```
ojaswin@ojaswin-Inspiron-3521:~/TaskCluster/taskcluster-services/services/web-server$ yarn start
yarn run v1.12.3
$ NODE_ENV=development webpack
webpack is watching the files…
Hash: fcd1679f2701661734b7
Version: webpack 4.28.4
Time: 5163ms
Built at: 02/18/2019 9:39:34 PM
Asset     Size  Chunks             Chunk Names
index.js  493 KiB   index  [emitted]  index
No Pulse namespace defined; no Pulse messages will be received.
AssertionError [ERR_ASSERTION]: config taskcluster.rootUrl is required
at setup (/home/ojaswin/TaskCluster/taskcluster-services/services/web-server/build/index.js:1405:52)
at Promise …
```
=> [Bug 1520918] Add denylist queries to web-server

services/auth/package.json, services/github/package.json, services/hooks/package.json, services/index/package.json, services/notify/package.json, services/purge-cache/package.json, services/queue/package.json, services/secrets/package.json, yarn.lock
```
(v10.15.1) dustin@lamport ~/p/taskcluster [upgrade-azure-entities*] $ yarn why buffertools
yarn why v1.13.0
[1/4] Why do we have the module "buffertools"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
error We couldn't find a match!
Done in 1.43s.
```
Thanks to @sudipt1999!
=> Upgrade azure-entities to drop buffertools dep

package.json
Especially when we have a big batch of renovate requests, they tend to add a lot of load as they all rebase and re-run all CI jobs on every commit to master.  In most cases, this rebasing isn't necessary, and in the cases where it is it's easy enough to check the checkbox in the PR.
=> Stop renovate from rebasing stale PRs

generated/references.json, services/hooks/schemas/v1/trigger-response.yml, services/hooks/src/listeners.js, services/hooks/src/scheduler.js, services/hooks/src/taskcreator.js, services/hooks/src/v1.js, services/hooks/test/taskcreator_test.js, ui/docs/generated/hooks/schemas/v1/trigger-response.json, ui/docs/generated/references.json
This refactors TaskCreator.fire to do a better job of error handling,
consistently updating LastFire and returning an API response or an
error.
This also drops an unused schema file and deletes some additional (now
moot) modifications of the lastFire field in the Hooks table.
Bugzilla Bug: [1527424](https://bugzilla.mozilla.org/show_bug.cgi?id=1527424)
cc: @ydidwania
=> Bug 1527424 - clean up error handling in TaskCreator

services/github/config.yml, services/github/src/data.js, services/github/src/handlers.js, services/github/src/main.js, services/github/test/helper.js
Bugzilla Bug: [1531606](https://bugzilla.mozilla.org/show_bug.cgi?id=1531606)
I need this for [retrigger implementation](https://bugzilla.mozilla.org/show_bug.cgi?id=1528650#c1). For retriggering a task, I plan the usual `this.context.ChecksToTasks.load({checkSuiteId, checkRunId})`, and for retriggering the whole task group - `this.context.ChecksToTasks.query({checkSuiteId})`.
=> DB migration: add a table

infrastructure/references/relativize.js
I'm not sure where to document this -- to be honest our documentation of deployment-related stuff is almost completely absent.  But, hopefully this will help @petemoore with client generation, as it allows a single HTTP request to get all of the necessary data without having to "spider" the references and schemas URLs.
Bugzilla Bug: [1525130](https://bugzilla.mozilla.org/show_bug.cgi?id=1525130)
=> Bug 1525130 - write out 'references.json' for use by client builders

.github/CODEOWNERS
This supports the notion that we're all in this together, I think :)
=> Remove use of single users in CODEOWNERS

generated/references.json, services/hooks/schemas/v1/hook-metadata.yml, ui/docs/generated/hooks/schemas/v1/hook-metadata.json, ui/docs/generated/references.json
Bug 1519969 
https://bugzilla.mozilla.org/show_bug.cgi?id=1519969
currently stuck at the implementation to find email of the person creating the Hook !
Kindly help me out here !
=> Bug 1519969 - Sending an email to an invalid address fails

infrastructure/references/relativize.js, infrastructure/terraform/secrets-service.tf, infrastructure/terraform/taskcluster.tf.json, infrastructure/terraform/web-ui.tf
* set `FORCE_SSL` for secrets (c.f. #354)
* set `proc_name` for tc-ui so that it runs the right entrypoint (ui/web) and has the correct deployment name (taskcluster-ui-web).  Note that terraform and kubernetes don't get along here, leaving the taskcluster-ui-static deployment abandoned.
* fix #353 (derp)
=> update to new monoimage, with fixes

services/hooks/config.yml, services/hooks/src/main.js, services/hooks/src/v1.js, services/hooks/test/api_test.js
This PR involves checking the exchanges in the hook definition against a `denyList`at creation/updation of a hook. I have also written 2 tests one for each.
The `config.yml` looks like
```
pulse:
denylist: 
exchanges: [taskcluster-queue, taskcluster-hooks]
```
@djmitche I am guessing you'd want some changes to the above format. Do let me know while reviewing :)
Bugzilla Bug: [1523801](https://bugzilla.mozilla.org/show_bug.cgi?id=1523801)
=> [Bug 1523801] Blacklist listening to some specific exchanges

services/queue/test/deadline_test.js, services/queue/test/dependency_test.js, services/queue/test/helper.js, services/queue/test/queueservice_test.js, services/queue/test/retry_test.js, services/queue/test/taskgroup_test.js
This makes some weirdness from changing time mocks before teardown a non-issue I think.
The tests are now fast again but also actually run.
=> Speed back up queue tests

services/github/test/helper.js
This changes the table name to match elsewhere in the code.  #376 is centralizing withEntities and will require that these match everywhere.
=> Fix table name in github tests

libraries/monitor/src/monitor.js, services/notify/src/irc.js, services/notify/src/main.js
I believe a too-strict check is hiding an actual error [in this](https://console.cloud.google.com/errors/CL6y69eE1bPn_AE?time=PT1H&project=heroku-logging&organizationId=442341870013).
Bugzilla Bug: [1533972](https://bugzilla.mozilla.org/show_bug.cgi?id=1533972)
=> [Bug 1533972] Be more permissive with uncaught errors

clients/client-web/src/clients/Auth.js, clients/client/src/apis.js, generated/references.json, services/auth/schemas/v1/list-roles-response.yml, services/auth/src/v1.js, services/auth/test/role_test.js, ui/docs/generated/auth/references/api.json, ui/docs/generated/references.json
Bugzilla Bug: [1534022](https://bugzilla.mozilla.org/show_bug.cgi?id=1534022)
This doesn't actually fix anything, but does restore the schema restriction on unique items, which should help at least to detect this sooner next time.  Then maybe we can see in the logs what modified the roles.
=> Bug 1534022 - add more tests regarding duplicate roles

services/hooks/src/v1.js
Display the bindings of the hook definition in the error message in case of denied exchanges being used.
Bugzilla Bug: [1523801](https://bugzilla.mozilla.org/show_bug.cgi?id=1523801)
=> Bug 1523801 : Blacklist listening to some specific exchanges

ui/src/utils/ScrollToTop.jsx, ui/src/views/Documentation/index.jsx
Given that pages are loaded asynchronously, it doesn't make sense for the
window to scroll to the the top once the pathname changes (current behavior for docs) since it doesn't necessarily mean the next/previous page is fully loaded. Let's rely on a `scrollKey` prop instead and only scroll to the top when it changes.
Fixes https://github.com/taskcluster/taskcluster/issues/392.
=> [UI] Remove reliance on url pathname in ScrollToTop

infrastructure/builder/src/generate/generators/docs-tocs.js, ui/src/autogenerated/docs-table-of-contents.json
Also added a `path` property for root nodes since it was missing (relates to https://github.com/taskcluster/taskcluster/issues/397).
=> [UI] Rely on "Next Steps" instead of next/previous page for the tutorial

.taskcluster.yml
This will currently send an email for each task that fails. Perhaps later we can make a summary task that sends a single email instead.
=> Send notification on failures/exceptions in master

services/login/src/scanner.js
There don't appear to be any tests to run the scanner.  Login never got a lot of tests -- it used to be mostly UI.  And it will soon be merged into web-server, so I'm not sure it's worth adding any.  Even if we did have tests, they would have faked out the auth service, so this *particular* bug would have snuck through.
Bugzilla Bug: [1534711](https://bugzilla.mozilla.org/show_bug.cgi?id=1534711)
=> Bug 1534711 - pass rootUrl when initializing tc-client

libraries/iterate/README.md, libraries/iterate/src/iterate.js, libraries/iterate/src/watchdog.js, libraries/iterate/test/iterate_test.js, libraries/iterate/test/watchdog_test.js, services/queue/src/claimresolver.js, services/queue/src/deadlineresolver.js, services/queue/src/dependencyresolver.js, services/worker-manager/src/main.js, services/worker-manager/src/provisioner.js, services/worker-manager/test/provisioner_test.js
This isn't everything I want to do with this library, but it's a start: simplification, better docs, remove some unused features, refactorings.
The big thing I want to finish up is the interface by which this is used in a process.  It has some weird behavior around throwing an unhandled error in the nextTick right now.  I think a better approach might be to provide an async `run` method that returns a promise when iteration is complete and rejects if there are too many failures.  But I'll do that in another PR.
=> tc-lib-iterate updates

services/login/src/scanner.js
Bugzilla Bug: [1535366](https://bugzilla.mozilla.org/show_bug.cgi?id=1535366)
=> Scanner calls a function that is gone

services/github/test/api_test.js, services/github/test/helper.js, services/github/test/sync_test.js
There's a bit of "how did this ever work" going on here!  Without tests, these suites should skip, but until this patch would have been calling `helper.Builds.create(..)` etc.  At any rate, this `if (skipping()) ..` is an idiom used in all of the other services, so it's easy to add it here.  Similarly for the default value for rootUrl.
=> Make tc-github tests run without credentials.

ui/src/components/Search/index.jsx
Before:
After:
Fixes https://github.com/taskcluster/taskcluster/issues/428.
=> Reduce padding in Search component

infrastructure/builder/src/build/index.js, libraries/config/README.md, libraries/config/src/config.js, libraries/config/src/schema.js, libraries/config/test/config_test.js, libraries/config/test/test-env.yml, services/login/config.yml, services/queue/config.yml
* Remove `!env:flag` due to it being confusing and `!env:bool` is good enough
* Allow specifying which config files are allowed to be missing
* Stop catching and logging errors that should just be thrown
* Refactor to be easier to read
This is work in preparation for modifying lib-config to allow it to tell us what all of the `!env` vars are in order to automatically generate kubernetes configs.
Apologies for the one-giant-commit
=> Simplify lib-config

generated/references.json, services/auth/schemas/v1/websocktunnel-token-response.yml, services/auth/src/websocktunnel.js, services/auth/test/websocktunnel_test.js, ui/docs/generated/auth/schemas/v1/websocktunnel-token-response.json, ui/docs/generated/references.json
The websocktunnel already requires:
> The client ID must be URL-safe, specifically matching
> /^[a-zA-Z0-9_~.-%]+$/. It is recommended to urlencode any string to meet
> this requirement.
So apply the same limits here.
(I only just noticed / remembered this restriction)
=> Restrict the allowable charcters for wstClient

services/login/src/handlers/mozilla-auth0.js, services/login/test/handlers_mozilla_auth0_test.js
Now that we link identities, the format of the `identities` property has
changed, invalidating some assumptions.  Happily those assumptions were
represented with assertions so we got errors instead of undefined
behavior!
In particular, an account with a github identity now has an identity
like:
```json
{
"provider": "github",
"connection": "github",
"profileData": {
"userId": 1234,
"nickname": "developer1234"
}
},
```
and an account with a firefoxaccounts sign-in has
```json
{
"profileData": {
"email": "foo@bar.com",
"fxa_sub": "97ff4ba365255c2a92d362ea017baa15",
...
},
"provider": "oauth2",
"user_id": "firefoxaccounts|97ff4ba365255c2a92d362ea017baa15",
"connection": "firefoxaccounts",
"isSocial": true
}
```
Bugzilla Bug: [1536435](https://bugzilla.mozilla.org/show_bug.cgi?id=1536435)
=> Bug 1536435 - support linked identities

infrastructure/terraform/auth-service.tf, infrastructure/terraform/outputs.tf, infrastructure/terraform/taskcluster.tf.json
Bugzilla Bug: [1533591](https://bugzilla.mozilla.org/show_bug.cgi?id=1533591)
This is exposed as an output because whoever deploys the worker services will need to configure the websocktunnel service with the same secret.
=> Bug 1533591 - set WEBSOCKTUNNEL_SECRET and expose as output

services/auth/package.json, yarn.lock
Bugzilla Bug: [1531871](https://bugzilla.mozilla.org/show_bug.cgi?id=1531871)
This is safer than the last time I tried to upgrade, since it doesn't rewrite the schema file at all.  So (a) I'm more confident this will work and (b) I'm very confident it can be rolled back easily.
A nice side-benefit is that this brings us down to just one copy of Ajv installed :)
P.S.  I think renovate didn't do this since it had already filed a bug to upgrade to v4.
=> Bug 1531871 - upgrade azure-blob-storage

ui/docs/resources.md
This also drops the Travis-CI link.  We don't use Travis-CI for much
anymore.
Fixes #472.
=> Replace dead link to presentations to a link to the youtube group

.taskcluster.yml, libraries/testing/src/with-entity.js, package.json, services/auth/package.json, services/auth/test/cleanup.js
This just cleans up tables, but could easily be extended to any other kind of resource, e.g., SQS queues, Azure containers.
I guess ideally this would be a crontask, but in the absence of good support for those, I think running this just on pushes is a decent compromise.
Bugzilla Bug: [1533937](https://bugzilla.mozilla.org/show_bug.cgi?id=1533937)
=> Bug 1533937 - cleanup after tests (azure tables, at least) on push

services/login/src/handlers/mozilla-auth0.js, services/login/test/handlers_mozilla_auth0_test.js
Apparently I totally mis-interpreted the results I saw from Auth0 last time I modified this code.  That, or it's changed since then.  At any rate, I've adjusted the tests to match what I see from auth0, and they continue to pass.  I also tested this by calling `getUser` with my own userid and a few others I found in the logs.
Bugzilla Bug: [1536863](https://bugzilla.mozilla.org/show_bug.cgi?id=1536863)
=> Bug 1536863 - fix handling of github logins via auth0

generated/references.json, libraries/monitor/README.md, libraries/monitor/src/index.js, libraries/monitor/test/base_test.js, libraries/monitor/test/logger_test.js, services/queue/config.yml, services/queue/src/api.js, services/queue/src/claimresolver.js, services/queue/src/deadlineresolver.js, services/queue/src/dependencytracker.js, services/queue/src/main.js, services/queue/src/monitor.js, services/queue/src/workclaimer.js, services/queue/test/claimwork_test.js, services/queue/test/createtask_test.js, services/queue/test/dependency_test.js, services/queue/test/helper.js, services/queue/test/queueservice_test.js, services/queue/test/resolvetask_test.js
This should allow us to search for `jsonPayload.Fields="<taskId>"` and find all of the interesting bits about a task.
Bugzilla Bug: [1538152](https://bugzilla.mozilla.org/show_bug.cgi?id=1538152)
=> Bug 1538152 - "tell a story" about tasks in queue logging

services/login/src/handlers/mozilla-auth0.js, services/login/test/handlers_mozilla_auth0_test.js
This is sort of sticking our fingers in our ears and hoping it keeps working.  The new implementation in web-server will, I hope, use the People API, and hopefully that's a bit more stable.
Bugzilla Bug: [1536863](https://bugzilla.mozilla.org/show_bug.cgi?id=1536863)
=> Bug 1536863 - be a little more flexible in reading the chimeric Auth0 profiles

ui/src/components/TaskGroupTable/index.jsx
Fixes https://github.com/taskcluster/taskcluster/issues/409.
=> [UI] Ignore casing when filtering in task group view

services/worker-manager/package.json, services/worker-manager/src/main.js, services/worker-manager/src/providers/gcpprovider.js, services/worker-manager/src/worker.js
Bugzilla Bug: [1487699](https://bugzilla.mozilla.org/show_bug.cgi?id=1487699)
Feedback I am looking for and questions I am having:
1. Should I add objects for AWS and packet.net, and work on all three in parallel? For example, after this PR I would make a similar PR (object + `listWorkers` method) for AWS and packet.net. Or is it better to finish GCP object first?
2. Please look at creation of Worker objects - does the information I get into it make sense?
3. What on Earth is `providerData`?
4. Is it even a thing, a worker of capacity > 1? If not, maybe just remove the `capacity` prop from Worker objects?
Nota bene: I am not adding tests at this point, because it's unclear to me whether any redesign is happening, and they are just not too useful at the moment. My messy working branch (can …
=> Add GCP provider object. Implement listWorkers method

clients/client/README.md
In particular, I noticed that `retry` was missing when I went looking for it.
=> document all options to client constructor

clients/client/README.md, infrastructure/builder/docs/services.md, infrastructure/builder/docs/terraform-json.md, infrastructure/terraform/README.md, libraries/api/README.md, libraries/app/README.md, libraries/docs/README.md, libraries/pulse/README.md, libraries/references/README.md, libraries/scopes/README.md, libraries/testing/README.md, services/auth/README.md, services/treeherder/README.md, services/web-server/README.md
Almost all links are updated ! Still a second cross check would be helpful!
https://github.com/taskcluster/taskcluster-lib-azure/releases in azure README.md
https://github.com/taskcluster/schema-validator-publisher/blob/master/package.json in valida README.md
these links are still need to be updated ! couldn't find the updated links!
=> Update links in documentation

ui/src/components/Breadcrumbs/index.jsx, ui/src/components/TaskDetailsCard/index.jsx, ui/src/components/TaskRunsCard/index.jsx, ui/src/views/Tasks/ViewTask/index.jsx
**Problem 1**: Users of Taskcluster usually don't care about most of the information presented in the Task Group view. All that information displayed at once tend to confuse people.
**Solution 1**: Only show the most important information a user usually cares about. Hide everything else under the "More..." panel.
**Problem 2**: The relationship between a task group and a task id is not clearly shown in the task group view
**Solution 2**: Use breadcrumbs.
=> Task Group UX (breadcrumbs, hide metadata)

clients/client/package.json, clients/client/src/client.js, libraries/api/test/noncemanager_test.js, libraries/app/src/index.js, libraries/testing/test/fakeauth_test.js, libraries/validate/src/publish.js, package.json, services/hooks/src/data.js, services/hooks/src/scheduler.js, yarn.lock
Since Node 0.12, Promise has been built-in and available as a global.
For a while, we used a Promise library because `Promise.race` was not
available.  It is available now.
=> Stop using the promise dependency

infrastructure/terraform/auth-service.tf
Bugzilla Bug: [1544601](https://bugzilla.mozilla.org/show_bug.cgi?id=1544601)
=> Bug 1544601 - use correct table name for hooks

infrastructure/terraform/queue-service.tf
This was changed from `!env:flag` to `!env:bool` in `service/queue/config.yml` a while back and that caused the service to fail on startup.
=> include a value for FORCE_SSL for queue

.taskcluster.yml
Bugzilla Bug: [1538169](https://bugzilla.mozilla.org/show_bug.cgi?id=1538169)
=> Bug 1538169 - retry yarn operations in a new task on failure

services/web-server/config.yml, services/web-server/src/index.js, services/web-server/src/servers/createApp.js
It probably doesn't hurt to have the playground out there in production, but it seems like leaving dangling functionality is unnecessary risk.
=> only serve /playground in development

libraries/pulse/src/client.js, libraries/pulse/test/client_test.js, services/hooks/src/listeners.js, services/hooks/test/listeners_test.js
Bugzilla Bug: [1544608](https://bugzilla.mozilla.org/show_bug.cgi?id=1544608)
Well, the last PR didn't do the trick, because it still tried to close the "poisoned" channel, which failed because the channel was poisoned.  This adds special handling for that case to `withChannel`, and then reconfigures hooks to use `withChannel`.
=> Bug 1544608 - really, don't kill connection on channel errors

ui/src/views/Tasks/ViewTask/index.jsx
This will make sure data is up-to-date when user visits an already cached task.
=> [UI] Add fetchPolicy network-only to task view

services/queue/src/workerinfo.js, services/queue/test/workerinfo_test.js
In the case where we add a new workerInfo row, the `await` was omitted,
leading to race conditions in the tests.
This also improves the tests to give better diagnostic output, instead
of just a boolean.
Bugzilla Bug: [1526705](https://bugzilla.mozilla.org/show_bug.cgi?id=1526705)
=> Bug 1526705 - await workerinfo updates

services/web-server/src/PulseEngine/index.js, services/web-server/src/index.js
The old incarnation used tc-lib-pulse's FakeClient, which was intended
only for testing and is no longer exposed by that library.
Refs #618
=> Support web-server without pulse directly

services/queue/src/dependencytracker.js
This had me briefly wondering if something had stuck a `,` into a taskId
(which wouldn't be too hard with Python's treatment of `foo,` as a
tuple)
=> Omit needless punctuation in error message

ui/README.md, ui/src/App/index.jsx, ui/src/components/SignInDialog/index.jsx, ui/src/components/UserMenu/index.jsx, ui/src/views/Profile/index.jsx, ui/src/views/Secrets/ViewSecret/index.jsx, ui/src/views/Tasks/InteractiveConnect/index.jsx
`resetStore` causes the store to be cleared and all active queries to be refetched. The only problem is that for many of our views, we depend on`fetchMore` to fetch the full list. Refetching active queries will only fetch the first query. There would probably be other problems with some of our subscriptions.
To fix this issue, we should rely on the key prop and the `networkPolicy` property to refetch active queries. Changing the `key` prop of a component in React will re-render that component. This will have a similar effect as `resetStore` & `clearStore`.
Fixes https://github.com/taskcluster/taskcluster/issues/654.
=> [UI] Rely on key and fetchPolicy instead of resetStore

services/web-server/src/index.js
Reverts taskcluster/taskcluster#664
Now that configs are set in heroku, the service will run smoothly.
=> Revert "HOTFIX: Do not run strategy if config for strategy is undefined"

libraries/pulse/README.md, libraries/pulse/src/client.js, libraries/pulse/src/publisher.js
Bugzilla Bug: [1543378](https://bugzilla.mozilla.org/show_bug.cgi?id=1543378)
This just adds the property and a log message.  I'd like this in-place next time we see issues.  If it proves a reliable indicator, then we can start to build `if (this.publisher.blocked) { .. return 503 .. }` into things like `queue.createTask`.
I did test this with a local rabbitmq with
```
docker run -e RABBITMQ_VM_MEMORY_HIGH_WATERMARK=100MiB -ti --rm -p 5672:5672 rabbitmq:alpine
```
and noted that the functionality here works.  But also, even with a consumer running at full speed, RabbitMQ still hits that VM high watermark.  Maybe it's too low and just the statistics cause it to hit?  At any rate, i don't want to futz with getting a CI test that hits this limit.  This is enough.
=> Bug 1543378 - detect and warn on pulse blockage

ui/src/views/Clients/ViewClients/index.jsx
Fixes #513 
- Removed loading userId as default search query for logged in users
- Added in search query param in URL
- Logging in and out will not reset search results now
Demo:
=> [UI] Remove search pattern for clients viewer

ui/src/views/Documentation/index.jsx
Make switching documentation pages in mobile faster. We don't need to do
this for the rest of the app because most users typically view one
micro service per visit whereas in docs people tend to view multiple pages. This commit enhances the performance in page transitions in docs.
`eager`: Generates no extra chunk. All modules are included in the current chunk and no additional network requests are made. A Promise is still returned but is already resolved. In contrast to a static import, the module isn't executed until the call to import() is made.
=> [UI] Load docs in a single chunk

generated/references.json, libraries/pulse/src/publisher.js
Results from forcing this to occur during tests:
```
taskcluster.lib-pulse WARNING: pulsePublisherBlocked:
taskcluster.lib-pulse         blocked: true
taskcluster.lib-pulse         v: 1 +0ms
```
Note that this log message will only be documented for services which
publish to pulse.
Bugzilla Bug: [1548348](https://bugzilla.mozilla.org/show_bug.cgi?id=1548348)
=> Bug 1548348 - log on pulse publishing blockage

libraries/monitor/src/monitor.js, libraries/monitor/test/monitor_test.js
..at least, in Fields.stack and in message, which are the two fields
StackDriver is concerned with.
Bugzilla Bug: [1550000](https://bugzilla.mozilla.org/show_bug.cgi?id=1550000)
=> Bug 1550000 - strip all but the first line of multiline errors

ui/src/components/SchemaTable/index.jsx, ui/src/views/Documentation/Reference/Entry.jsx, ui/src/views/Documentation/Reference/SchemaIndex.jsx
This moves the logic to calculate entry schema references into the Entry
class.  It's still a bit awkward to show both actual reference entries
*and* schemas using the same Entry class, but it gets all the nice
expanding and hash reference behavior without code duplication.
I suppose an alternative would be to factor that behavior out into a ReferenceExpansionPanel class and then use that in both Entry and SchemaPanel.
Fixes #657, fixes #689.  cc: @arshadkazmi42
=> Fix SchemaTable to parse refs relatively

package.json, static.json
Relates to https://github.com/taskcluster/taskcluster/issues/725.
`static.json` is now shared with two heroku applications:
* taskcluster-ui
* taskcluster-net
https://taskcluster-ui.herokuapp.com/
=> [UI] Move taskcluster-web.netlify.com to heroku

libraries/monitor/src/monitor.js
Without this, errors are reported as in the "gce_instances" service :)
=> Fix the serviceName for logging

clients/client-py/README.md, clients/client-py/taskcluster/aio/auth.py, clients/client-py/taskcluster/auth.py, clients/client-web/src/clients/Auth.js, clients/client/src/apis.js, generated/references.json, services/auth/src/api.js, services/auth/src/gcp.js, services/auth/src/main.js, services/auth/test/gcp_test.js, services/auth/test/helper.js
This changes the API method signature to require an explicit project_id in the request.  That means that later we can add support for multiple projects without changing the API.
This also supports mock testing with a fake google API implementation.
=> Use an explicit project for GCP credentials

ui/src/components/TaskRunsCard/index.jsx
Relates to https://github.com/taskcluster/taskcluster/issues/763.
Before:
After:
=> [UI] Make artifact pagination buttons more visible

infrastructure/terraform/auth-service.tf
Without this, temporary credentials don't work for github logins, since they require that the issuer have `auth:create-client:<clientId>`.
=> Add github client-related scopes

ui/src/components/ConnectionDataTable/index.jsx
Relates to https://github.com/taskcluster/taskcluster/issues/763.
Fix the following issues:
* `previousCursor` being `undefined`
* missing pages in a table
=> [UI] Enhance ConnectionDataTable

clients/client-py/README.md, clients/client-py/taskcluster/aio/workermanager.py, clients/client-py/taskcluster/workermanager.py, clients/client-web/src/clients/WorkerManager.js, clients/client/src/apis.js, generated/references.json, services/worker-manager/README.md, services/worker-manager/config.yml, services/worker-manager/schemas/v1/pulse-workertype-message.yml, services/worker-manager/schemas/v1/workertype-full.yml, services/worker-manager/src/api.js, services/worker-manager/src/data.js, services/worker-manager/src/estimator.js, services/worker-manager/src/main.js, services/worker-manager/src/monitor.js, services/worker-manager/src/provider.js, services/worker-manager/src/provider_google.js, services/worker-manager/src/provider_testing.js, services/worker-manager/src/provisioner.js, services/worker-manager/src/util.js, services/worker-manager/test/api_test.js, services/worker-manager/test/provider_google_test.js, services/worker-manager/test/provisioner_test.js, services/worker-manager/test/util_test.js
This is of the form `<provisionerId>/<workerType>`, but within the
worker-manager is treated as a single unit.
Note that this is a breaking change, as it changes the indexes for the
Azure tables.  That means all installs will need to delete existing
tables and allow the service to re-create them.  At this point in
deployment of this service, that's not a great harm.
An unfortunate downside of this change is that URLs look like
`/api/worker-manager/v1/worker-type/some-provisioner%7Esome-worker-type`,
with the `/` inside the workerTypeName escaped.  I played around a bit
with the route matching and it seems like `path-to-regexp` (which
Express uses to parse its routes) is completely broken regarding
parameter expressions in the version used by Express 4.  Express 5
should do better, so …
=> Bug 1552238 - [BREAKING] refer to workerTypes with workerTypeName

services/worker-manager/README.md, services/worker-manager/schemas/v1/workertype-full.yml
(just docs, since the formats for `workerGroup` and `providerId` already match)
=> Add note that provisionerId and workerGroup are often the same

services/queue/src/queueservice.js, services/queue/src/workclaimer.js
..and use whole-second takenUntil values to avoid encoding/decoding
errors.
I'm not sure the second part is necessary, but I think it can't hurt.
Bugzilla Bug: [1551249](https://bugzilla.mozilla.org/show_bug.cgi?id=1551249)
=> Bug 1551249 - always hide claim messages for at least one second

.codecov.yml
This should stop the coverage check flaking on master and such. If this doesn't help, we can just turn the check off on master or something.
Another option is to figure out why coverage seemingly randomly changes by tiny amounts on each patch but that is harder and probably best left for another day.
=> Be less precise with coverage diffs

libraries/monitor/src/monitor.js, services/worker-manager/src/main.js
I noticed these empty `.childMonitor()` in worker-manager.
=> disallow an empty argument to childMonitor

package.json
Otherwise virtualenvs in this directory contain JS files which eslint
proceeds to check.
=> Ignore client-py in eslint

ui/src/auth/AuthController.js, ui/src/utils/constants.js
The delay (in milliseconds) for `setTimeout` is a 32 bit signed quantity, which limits it to 2^31-1 ms (2147483647 ms) or 24.855 days. Renewal timers are sometimes 1000 years so we should make sure we don't go past the max value.
=> [UI] Make setTimeout work with large timeout values

package.json, yarn.lock
This addresses [WS-2019-0063](https://github.com/nodeca/js-yaml/pull/480).
It's low severity since the vuln applies to `yaml.load` but we use `yaml.safeLoad`.  Still, better safe than sorry!
=> Upgrade js-yaml

infrastructure/builder/src/build/index.js, infrastructure/builder/src/build/monoimage.js, infrastructure/builder/src/release/index.js
Either this never worked, or it worked once and `program` changed how it
interprets `--no-foo` options.
=> Use cmdOptions.cache

infrastructure/terraform/main.tf
This seemed to fix issues where Azure was complaining that disabling encryption was not supported.  I'm guessing some default has changed?
=> enable encryption on azure resources

infrastructure/builder/src/build/index.js, infrastructure/builder/src/build/monoimage.js, infrastructure/builder/src/utils/docker.js, package.json, yarn.lock
This requires a good deal more manual copying back and forth, but means
that the `yarn install` operations run entirely on a docker volume,
rather than over a bind mount.  Bind mounts don't work reliably on
Docker for Mac, so this change allows `yarn build` to operate correclty
on such systems.
Bugzilla Bug: [1551607](https://bugzilla.mozilla.org/show_bug.cgi?id=1551607)
=> Bug 1551607 - use docker volumes for building

generated/references.json, services/hooks/src/monitor.js, services/hooks/src/taskcreator.js, services/hooks/test/taskcreator_test.js
This reports *all* fires, bot successful, failed, and declined.  It's
easy enough for consumers interested only in failures to filter those
out.
Bugzilla Bug: [1547729](https://bugzilla.mozilla.org/show_bug.cgi?id=XXXXX)
=> Bug 1547729 - use structured logging to report hook fires

services/worker-manager/src/providers/google.js, ui/docs/manual/design/namespaces.md
For the moment, let's allow both worker-type:.. and worker-pool:...
=> use worker-pool secrets and roles instead of worker-type

ui/.neutrinorc.js
`process.env.PORT` is not defined in `.neutrinorc.js`. Because of this, `devServer` was defaulting to port 8080. This commit fixes this issue.
=> [UI] Make port 5080 the default port

infrastructure/builder/src/build/monoimage.js
I missed this in the yarn-build-on-mac PR.
=> add missing build dependency on docker images

libraries/api/src/api.js, libraries/api/test/route_test.js
This also adds a check that we are not "strict", so trailing slashes are
OK.
=> Ensure API routes are case-sensitive

infrastructure/terraform/web-server-service.tf, services/web-server/README.md, services/web-server/config.yml, services/web-server/src/loaders/auth.js, services/web-server/src/login/strategies/github.js, services/web-server/src/login/strategies/mozilla-auth0.js, services/web-server/src/utils/jwt.js, services/web-server/test/jwt_test.js
This also adds configuration to terraform to invent an HMAC secret.
The *generation* of these JWTs is tested to work locally.  I can't test more than that because the `callback.ejs` page has `window.opener = null`, so it doesn't actually call back.  I'll try this in dustin-dev as well to see if it works better there.  @helfi92 is that something you've seen in your local testing of signins?
Bugzilla Bug: [1559471](https://bugzilla.mozilla.org/show_bug.cgi?id=1559471)
=> Bug 1559471 - use JWTs with HS256 for logins

clients/client-py/taskcluster/generated/aio/workermanager.py, clients/client-py/taskcluster/generated/workermanager.py, clients/client/src/apis.js, generated/references.json, services/worker-manager/schemas/constants.yml, services/worker-manager/schemas/v1/create-worker-pool-request.yml, services/worker-manager/schemas/v1/update-worker-pool-request.yml, services/worker-manager/schemas/v1/worker-pool-full.yml, services/worker-manager/src/api.js, services/worker-manager/test/api_test.js
This allows `workerPoolId`, `created`, and `lastModified`, ignoring the
latter two, for user convenience in something like
```js
wp = await wm.workerPool(wpId);
wp.config.foo = 'bar';
await wm.updateWorkerPool(wpId, wp);
```
Bugzilla Bug: [1556526](https://bugzilla.mozilla.org/show_bug.cgi?id=1556526)
=> Bug 1556526 - allow extra fields in updateWorkerPool

.github/CODEOWNERS
With the idea that worker-reviewers tend to be the Golang experts on the team (note that we already send client-web reviews to frontend-reviewers for similar reasons, and that we often cancel review requests to that team for API-references-only changes).
=> add worker-reviewers as reviewers of the go client

generated/references.json, libraries/monitor/src/monitor.js, libraries/pulse/src/client.js, services/web-server/Procfile, services/web-server/procs.yml, services/web-server/src/PulseEngine/Subscription.js, services/web-server/src/PulseEngine/index.js, services/web-server/src/main.js, services/web-server/src/monitor.js
```
{"EnvVersion":"2.0","Fields":{"v":1},"Hostname":"lamport","Logger":"taskcluster.web-server.pulse-client","Pid":3736,"Severity":6,"Timestamp":1560836735114000000,"Type":"pulse.connected","serviceContext":{"service":"web-server"},"severity":"INFO"}
{"EnvVersion":"2.0","Fields":{"subscriptionId":"ImIJ5mbsRO-GXifGMRoYFg","v":1},"Hostname":"lamport","Logger":"taskcluster.web-server.pulse-engine","Pid":3736,"Severity":7,"Timestamp":1560836738247000000,"Type":"bind-pulse-subscription","serviceContext":{"service":"web-server"},"severity":"DEBUG"}
{"EnvVersion":"2.0","Fields":{"subscriptionId":"ImIJ5mbsRO-GXifGMRoYFg","v":1},"Hostname":"lamport","Logger":"taskcluster.web-server.pulse-engine","Pid":3736,"Severity":7,"Timestamp":1560836738753000000,"Type":"unbind-pulse-subscription","serviceConte …
```
=> [web-server] use montior logging, don't console.log in prod

changelog/allow-https-sub-endpoint.md, netlify.toml, ui/.neutrinorc.js, ui/README.md, ui/src/App/index.jsx
Then it can be constructed from rootUrl just using string concatenation.
=> Allow subscription endpoint to use https too

libraries/api/test/route_test.js, services/web-server/config.yml, services/web-server/src/main.js, services/web-server/src/servers/createApp.js, services/web-server/test/helper.js, services/web-server/test/server_test.js
This should work OK for local development, PRs, and on https://taskcluster-ui.herokuapp.com.
The intent is to set ADDITIONAL_ALLOWED_CORS_ORIGIN to `/https://deploy-preview-\\d+--taskcluster-web\\.netlify\\.com/` in whatever deployment we choose to aim the deploy previews at (ideally staging, at least soon).
Bugzilla Bug: [1544917](https://bugzilla.mozilla.org/show_bug.cgi?id=1544917)
=> Bug 1544917 - limit access to web-server using CORS

services/web-server/test/helper.js
This was a semantic merge conflict between two recently-merged PRs.
=> (hotfix) Load httpServer instead of server in web-server tests

services/worker-manager/src/providers/provider.js
This clears up some of the confusion I had in #923, and is based on how the method is called.
I did notice that if `setup` fails, the process startup will fail.  For things like creating IAM users, that could mean that e.g., an EC2 outage would stop the worker-manager from starting up.  Should we try to soften that requirement a little bit?  Ideas how?  I can file a followup bug..
=> Better documentation of the provider.setup method

ui/src/components/ClientForm/index.jsx, ui/src/components/HookForm/index.jsx, ui/src/components/RoleForm/index.jsx, ui/src/utils/scopeLink.js, ui/src/utils/scopeRedirect.js, ui/src/views/Scopes/ScopesetExpander/index.jsx
Scopes that start with 'assume:' will now direct to `/auth/roles/...` and scopes that don't will maintain their original linkage `/auth/scopes/...`.
Fixes #884.
=> Redirect UI linkage for scopes starting with 'assume:'

services/worker-manager/src/main.js, services/worker-manager/src/providers/provider.js, services/worker-manager/src/providers/testing.js, services/worker-manager/src/provisioner.js, services/worker-manager/src/worker-scanner.js, services/worker-manager/test/provisioner_test.js, services/worker-manager/test/worker_scanner_test.js
This defers calling removeResources until all workers in the pool for a
specific provider are STOPPED.
This brings up some questions that might lead to good followups:
* how are workers removed from the Worker table?
* should we consider workers in the STOPPED state but still in the table to be a reason to hold onto the provider's resources?
Bugzilla Bug: [1555213](https://bugzilla.mozilla.org/show_bug.cgi?id=1555213)
=> Bug 1555213 - remove previous providers when they are done

changelog/bug-1547077.md, services/notify/src/templates/css/common.css, services/notify/src/templates/fullscreen/html.pug, services/notify/src/templates/simple/html.pug
Bugzilla Bug: [1547077](https://bugzilla.mozilla.org/show_bug.cgi?id=1547077)
=> [Bug 1547077] Use new logo on notify emails

libraries/pulse/src/consumer.js, libraries/pulse/test/consumer_test.js, libraries/pulse/test/helper.js, libraries/testing/README.md, libraries/testing/src/with-monitor.js
amqplib's failure handling is pretty poor -- it seems this particluar
error doesn't match IllegalOperationError.  This patch also adds some
lib-testing support to handle testing for error messages.  And it
sets prefetch=1 in a few places to get more stable test behavior.
Bugzilla Bug: [1558187](https://bugzilla.mozilla.org/show_bug.cgi?id=1558187)
=> Bug 1558187 - handle connection failures better

changelog/github-scheduler.md, services/github/src/tc-yaml.js, services/github/test/tc-yaml_test.js, ui/docs/reference/integrations/github/taskcluster-yml-v1.md
=> [github] Allow `.taskcluster.yml` to set `schedulerId`.

ui/src/components/Log/index.jsx
Fixes https://github.com/taskcluster/taskcluster/issues/908
Resets `follow` in `Log` component's state when `lineNumber` is updated from the `Go to Line` dialog.
=> Fix 'Go to Line' functionality when 'Follow Log' is enabled

generated/docs-table-of-contents.json, ui/docs/reference/core/worker-manager/README.md, ui/docs/reference/core/worker-manager/worker-interaction.md
This outlines the common bits -- the per-provider docs will have more detail.
A few notes:
* we should probably allow `registerWorker` to return a config blob, so it's consistent across providers (depending on userdata excludes static provider, for example)
* this section can be expanded to include conventions for deploymentId, etc.
=> Document worker-manager / worker interaction

ui/docs/tutorial/hack-tc.md
The `async-javascript` tutorial is not present in the docs and I wasn't sure what to replace it with. So, I removed the content with the broken link.
Should we instead redirect to another link (for instance, [MDN docs on async functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function))? :thinking:
=> Remove content with broken link

ui/src/styleguide/StyleGuideRenderer.jsx
This is a minor refactoring PR simplifying `ui/src/styleguide/StyleGuideRenderer.jsx`
=> Refactor StyleGuideRenderer to be a functional component

changelog/1530644.md, clients/client-go/tcqueueevents/types.go, generated/references.json, services/queue/schemas/v1/task-completed-message.yml, services/queue/schemas/v1/task-defined-message.yml, services/queue/schemas/v1/task-exception-message.yml, services/queue/schemas/v1/task-failed-message.yml, services/queue/schemas/v1/task-pending-message.yml, services/queue/schemas/v1/task-pulse-definition.yml, services/queue/src/api.js, services/queue/test/createtask_test.js, services/queue/test/resolvetask_test.js
Addition of tags to these pulse messages will allow listeners to better
classify the tasks that are appearing, especially after we add ~3 fields.
Bugzilla Bug: [1530644](https://bugzilla.mozilla.org/show_bug.cgi?id=1530644)
=> [Bug 1530644] Add tags to pulse messages

services/worker-manager/src/providers/google.js, ui/docs/reference/core/worker-manager/google.md
This value is required to call registerWorker, since by that time the
worker pool's primary provider might have changed.
Note that this also drops the unused credentialsUrl.
Bugzilla Bug: [1563342](https://bugzilla.mozilla.org/show_bug.cgi?id=1563342)
=> Bug 1563342 - Provide providerId in instance attributes

test/meta_test.js, ui/docs/tutorial/apis.md
Bugzilla Bug: [1562752](https://bugzilla.mozilla.org/show_bug.cgi?id=1562752)
Also updates the content to reflect changes to the codebases.
=> Remove reference to tools.taskcluster.net in APIs tutorial doc

netlify.toml
From reading the documentation, I noticed that redirects are not applied if the file with the path mentioned in `from` exists. To override it, the `force` option has to be set to `true`.
Fixes #969
=> Force redirect from netlify domain to Heroku app

generated/docs-table-of-contents.json, infrastructure/builder/src/generate/generators/docs-tocs.js, package.json, ui/package.json, ui/yarn.lock, yarn.lock
This brings in some non-vulnerable dependencies.  However, the behavior
changes in that extensions are no longer automatically stripped, so we
do so directly.
Taskcluster-ui does not appear to use md-directory anymore (according to
`git grep`)
(this is a resubmit of #1001)
Bugzilla Bug: [1564122](https://bugzilla.mozilla.org/show_bug.cgi?id=1564122)
=> Bug 1564122 - update md-directory

clients/client-shell/README.md, infrastructure/builder/src/main.js, infrastructure/builder/src/release/index.js, infrastructure/builder/src/release/tasks.js
With this change, `yarn release` now requires a github PAT, and will
fail if `--push` is given without a PAT.
Bugzilla Bug: [1558519](https://bugzilla.mozilla.org/show_bug.cgi?id=1558519)
=> Bug 1558519 - create a github release as part of yarn release

generated/docs-table-of-contents.json, ui/docs/reference/core/worker-manager/google.md, ui/docs/reference/core/worker-manager/static.md
If this fixes #1056 then we should probably either fail when generating docs with no title, or default to title = name.
=> Add titles for missing docs

deployment-docs/clouds.md, generated/docs-table-of-contents.json, infrastructure/builder/src/generate/generators/docs-tocs.js, ui/docs/manual/design/conventions/README.md, ui/docs/manual/design/conventions/decision-task.md, ui/docs/manual/design/conventions/task-logs.md, ui/docs/reference/core/worker-manager/README.md
This uncovered two more "missing" docs files.  With this change, they will at least appear in the TOC, if with an unexpected name.
=> Fix up handling of titles in the TOC

ui/src/components/Log/index.jsx
There is a small different from the old UI is that the old version would not retain `follow log` if we refresh the page. 
I'm not sure this is a correct action, but I think it is because of the component triggers onScroll event and once we refreshing the page and condition `this.state.follow && scrollHeight - scrollTop !== clientHeight` will be `true` even though we not scroll the page yet.
I add a condition to prevent this situation so that the log always starts from the bottom now.
Fixes: #839
=> Set default to bottom and follow log while viewing active log

ui/src/components/HookForm/index.jsx, ui/src/views/Hooks/ViewHook/index.jsx
Fixes #957 
@helfi92 
Before: No confirmation dialog on deleting hook.
After:
Confirmation dialog box comes first on deleting hook.
Let me know if this needs any changes!
Thank you! :)
=> Created confirmation dialog before deleting hook

ui/package.json, ui/yarn.lock
Fixes #985
To understand the fix, please see https://github.com/mozilla-frontend-infra/react-lazylog/pull/43
=> Upgrade react-lazylog to 4.2.0

.codecov.yml
This is proving to be more annoying than useful for now.
=> Remove patch coverage report

services/hooks/test/validate_test/create-hook-request.json, test/meta_test.js, ui/docs/reference/core/notify/usage.md, ui/docs/reference/guide.md, ui/docs/reference/integrations/github/intro.md, ui/docs/reference/integrations/github/taskcluster-yml-v0.md, ui/docs/reference/integrations/github/taskcluster-yml-v1.md, ui/docs/reference/platform/queue/worker-hierarchy.md, ui/docs/tutorial/authenticate.md, ui/docs/tutorial/create-task-via-api.md, ui/docs/tutorial/debug-task.md, ui/docs/tutorial/download-task-artifacts.md, ui/docs/tutorial/finding-tasks.md, ui/docs/tutorial/gecko-decision-task.md, ui/docs/tutorial/gecko-tasks.md, ui/docs/tutorial/hello-world.md, ui/docs/tutorial/monitor-task-status.md, ui/src/components/HookForm/index.jsx
Bugzilla Bug: [1562752](https://bugzilla.mozilla.org/show_bug.cgi?id=1562752)
I am not sure about the changes made to the tutorial docs, "Hello World" and "Authentication", specifically.
/cc @djmitche
=> Remove references to tools.taskcluster.net in docs and hooks service test

Dockerfile, changelog/issue-1084.md
Optionally we could do this as well. I think it skips `yarn install` if you haven't changed `package.json`. This should cut down on build time significantly in most cases during development?
=> Reorder docker build steps to skip yarn install if no change

services/web-server/src/servers/createApp.js, ui/src/App/index.jsx
Logging in with the mozilla-auth strategy works in localhost but fails in production with error "Authentication is required to generate credentials". This error is coming from `loaders/auth.js`.
The reason why this is happening is because the cookies are not being sent from the browser and so `req.user` is undefined. I figured https://www.apollographql.com/docs/react/recipes/authentication/#cookie might be the fix 🤞
=> Possible fix for cookies not being sent in production

infrastructure/builder/src/release/tasks.js
@milescrabill asking for your review for your golang brain.
this is the bit of the services stuff that updates our go clients when we release a new version. The shell library relies on the go-client library. Before this change, trying to cut a release yelled about not finding the version of the go-client library that we wanted. I believe it was because this was updating
```
github.com/taskcluster/taskcluster/clients/client-go/v14 v14.0.0-20190713182157-1b8e18d76d60
```
to 
```
github.com/taskcluster/taskcluster/clients/client-go/v15 v14.0.0-20190713182157-1b8e18d76d60
```
which obviously doesn't make any sense. Now it updates it to 
```
github.com/taskcluster/taskcluster/clients/client-go/v15 v15.0.0
```
Does that make sense to you?
cc @djmitche so you can tell if this was actually …
=> Fix go mod in release for client-shell

infrastructure/builder/src/release/tasks.js
Removes the stray `"` from the download link.
=> Fix Taskcluster shell linux binary download link

changelog/issue-1062.md, clients/client-shell/cmds/task/actors.go, clients/client-shell/cmds/task/actors_test.go, clients/client-shell/cmds/task/task.go
This bit us again in Fx 69.0b9 this week. This appears to work in my limited testing:
- I can't rerun a green task without `--force`.
- I can rerun the green task with `--force`.
- I can rerun a red task without `--force`.
Fixes #1062.
=> require --force to rerun a non-failed, non-exception task

ui/package.json, ui/src/components/Log/index.jsx, ui/yarn.lock
Fixes #1002 
-
Update react-lazylog version to 4.3.0 and add caseInsesitive flag in LazyLog component
=> Update react-lazylog version to 4.3.0

services/web-server/src/loaders/artifacts.js
Fixes #1079 
Always encoding artifact url but leaving / un-escaped.
Is this what was required?
=> Encoding artifact url correctly

package.json
This package is not versioned using go modules, and gets updates all the
time, meaning that we get a renovate PR for it every week (such as #1115).
=> renovate: ignore golang.org/x/tools

changelog/bug1553953.md, clients/client-go/tcqueue/types.go, clients/client-go/tcqueueevents/types.go, generated/references.json, services/queue/schemas/constants.yml, services/queue/schemas/v1/list-provisioners-response.yml, services/queue/schemas/v1/list-workertypes-response.yml, services/queue/schemas/v1/pending-tasks-response.yml, services/queue/schemas/v1/provisioner-response.yml, services/queue/schemas/v1/task.yml, services/queue/schemas/v1/worker-response.yml, services/queue/schemas/v1/workertype-response.yml, services/queue/test/claimresolver_test.js, services/queue/test/claimwork_test.js, services/queue/test/helper.js, services/worker-manager/schemas/constants.yml
This brings these symbols into correspondence with the limits on
workerPoolId, which are designed to be compatible with various cloud
providers.
Bugzilla Bug: [1553953](https://bugzilla.mozilla.org/show_bug.cgi?id=1553953)
=> Bug 1553953 - limit chars in provisionerId and workerType

ui/src/components/Dashboard/SidebarList.jsx, ui/src/components/Log/ViewDifferentTaskButton.jsx, ui/src/components/Log/index.jsx, ui/src/views/Tasks/TaskLog/index.jsx
* Related Issue #818 
* Move `Raw Log`  button into a `SpeedDial` component
* Add `View Different Task` button in `SpeedDial` to let users go to different tasks
=> [UI/Enhancement] Add a way to jump to a task ID/task group from the log viewer in less clicks

changelog/bug1572764.md, clients/client-go/http.go
By default, only logs method, hostname, port, and response body.
It avoids leaks of secrets contained in the requests.
If the environment variable `TASKCLUSTER_DEBUG` is defined, then the
full request is logged.
Bugzilla Bug: [1572764](https://bugzilla.mozilla.org/show_bug.cgi?id=1572764)
=> Bug 1572764: Do not automatically log HTTP transactions in go client

generated/references.json, services/worker-manager/src/api.js, services/worker-manager/src/data.js, services/worker-manager/src/main.js, services/worker-manager/src/monitor.js, services/worker-manager/src/providers/google.js, services/worker-manager/test/worker_pool_errors_test.js
These aren't reported as errors in the service log (so wouldn't go to
StackDriver, for example), but still constitute useful data for service
operators who might, for example, monitor the frequency of such errors
and use that to get alerted of cloud-related outages (with attendant
false-positives from someone misconfiguring their worker pool).
Bugzilla Bug: [1571133](https://bugzilla.mozilla.org/show_bug.cgi?id=1571133)
=> Bug 1571133 - report worker pool errors to service log

ui/src/components/SecretForm/index.jsx, ui/src/views/Secrets/ViewSecret/index.jsx
Added confirmation dialog box for secret form which appears when deleting a secret
=> Added confirmation dialog box for secret form

changelog/bug1574656.md, generated/references.json, services/worker-manager/schemas/v1/config-google.yml, services/worker-manager/src/providers/google.js, services/worker-manager/test/api_test.js, services/worker-manager/test/provider_google_test.js, ui/docs/reference/core/worker-manager/google.md
The `userData` property remains just so that existing configs continue to work after this change.  It is ignored by tc-worker-runner.
I didn't see an easy way to assert this was being added to the metadata, but it seems clear enough.
Bugzilla Bug: [1574656](https://bugzilla.mozilla.org/show_bug.cgi?id=1574656)
=> Bug 1574656 - add workerConfig to google configs

services/index/src/main.js
taskcluster-index-handlers fails to start in v16.1.0 with the error ` "Error: Operation failed: QueueDeclare; 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - access to queue 'queue/takslcuster-index/index/incoming-tasks2'` because the namespace has a typo.
=> Fix pulse namespace for index

dev-docs/best-practices/docs.md
Having written this, I have a few refactoring ideas:
* Now that we have a stable `docs.taskcluster.net`, it probably makes sense to put deployment docs on that site, rather than in the repo.
* There's some stuff in `dev-docs` that should probably be in `deployment-docs`
* Worker-manager has some deployment docs in its reference
=> add a best-practice for documenting things

Dockerfile, entrypoint, infrastructure/builder/src/generate/generators/entry-script.js, ui/.neutrinorc.js, ui/README.md, ui/generate-env-js.js
Bugzilla Bug: [1530517](https://bugzilla.mozilla.org/show_bug.cgi?id=1530517)
I found in my testing that `yarn start` would always use the config from the *last* run of `yarn start`.  Switching the order seemed to help (0d7ce96).
@imbstack I'm curious for your feedback on the Dockerfile changes.  I know you ordered things in there carefully, and I'm not sure I understood well enough to do the right thing.
=> Bug 1530517 - Part 2 - build the UI as part of docker image building

ui/src/index.html
Nested links are not working in the UI after adding `<script src="./static/env.js"></script>`. This PR makes it absolute rather than relative.
=> [hotfix] Make script path absolute

services/worker-manager/test/api_test.js
This was a semantic merge conflict: a PR landed to add a new provider at
about the same time as a PR landed assuming the current number of
providers.
=> [hotfix] Fix worker-manager tests

static.json
The interactive connect feature doesn't work on Firefox & Chrome but works on Safari. I'm not sure why but probably because safari is more lenient.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src#Syntax
This is a similar fix as https://github.com/taskcluster/taskcluster-tools/pull/607.
=> Interactive connect CSP

services/worker-manager/config.yml, services/worker-manager/src/providers/google.js, services/worker-manager/test/fake-google.js, services/worker-manager/test/provider_google_test.js, ui/docs/manual/deploying/workers.md
This removes the ability for google provider to set up its own service accounts for workers. This both simplifies the code significantly and makes worker-manager much safer to run! Couple of other QOL improvements here as well. Part 2 should be coming soon where we clean up a few last TODOs and add some rate limiting logic.
=> Google provider cleanup part 1

ui/src/theme.js
Fixes #1211 
Hey @helfi92 !
I couldn't locally test the changes after the latest commit on package.json in ```ui/package.json```, the start script throws this error:
```
$ GENERATE_ENV_JS=1 webpack-dev-server --mode development
'GENERATE_ENV_JS' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I believe this is some kind of issue with windows. Could you please tell me a way around this?
Also, do we need a ripple affect on button click, or the hover effects would suffice?
And I did see the deploy preview, and we can copy from scope expander now! =)
And, what other changes does this need?
Thanks! =)
=> fix - can't copy from scope expander

package.json
We have a lot of un-updated dependencies.  My guess is that we're
getting two Node and two Golang PR's per week (running once per week
with prHourlyLimit=2), and have been falling behind quickly.  So this
opens things up quite a bit.  If my hunch is correct, and once we get
up-to-date, we can scale this back to run daily so that PRs aren't
popping up mid-day.
=> Let renovate run more often and make more PRs

.taskcluster.yml, package.json, yarn.lock
It has a security vulnerability (CVE-2019-10747).  It's indirectly depended on by old versions of mocha, which @renovate-bot has not been updating for us (#1276).  So I did it :)
=> Stop using `set-value`

generated/references.json, package.json, services/worker-manager/src/monitor.js, services/worker-manager/src/providers/google.js, services/worker-manager/test/fake-google.js, services/worker-manager/test/provider_google_test.js, ui/docs/manual/deploying/workers.md, yarn.lock
This should do a better job of trying to keep us from hitting api rate limit issues with google.
I didn't use `withFakeTime` in the tests because `azure-entities` date validation doesn't like it. Instead just allowed passing in a shorter backoff base for testing.
=> Google update pt2 (rate limiting)

infrastructure/tooling/src/dev/aws.js
`yarn dev:init` was throwing:
```shell
TypeError: Cannot read property 'lastAppliedPublicBucketPolicy' of undefined
at module.exports (/Users/haali/Documents/Mozilla/projects/taskcluster/infrastructure/tooling/src/dev/aws.js:76:24)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
=> Fix yarn dev:init

clients/client-go/go.mod, clients/client-go/go.sum, clients/client-shell/go.mod, clients/client-shell/go.sum
This basically replicates the role of gopkg.in, which seems to be having load issues (and seems mostly unmaintained, honestly).  This is going to be a PITA as things get updated, since renovate will not know to update the `replace` lines, but it will at least get our CI working again until either gopkg.in is fixed or useful packages like gopkg.in/yaml move to more stable hosting.
See https://github.com/niemeyer/gopkg/issues/67 for the gopkg.in issue.
Bugzilla Bug: [1580512](https://bugzilla.mozilla.org/show_bug.cgi?id=1580512)
=> Bug 1580512 - use replace to avoid the need for gopkg.in

ui/src/views/Tasks/TaskGroup/index.jsx
Fix for #1366.
Removing **input** styling worked as it was not referenced anywhere.
=> Issue #1366: Fix [JSS] warning

changelog/bug1582376.md, clients/client-go/tcqueue/types.go, generated/references.json, libraries/pulse/src/credentials.js, libraries/pulse/src/publisher.js, libraries/pulse/test/credentials_test.js, services/queue/schemas/v1/task.yml, ui/docs/manual/deploying/pulse.mdx
I tested this with 128 routes on a single message, no problem.
256 caused a buffer overflow in node, but let's pretend that didn't happen.  The current max for routes in a task is 64, and that seems a good number.
Bugzilla Bug: [1582376](https://bugzilla.mozilla.org/show_bug.cgi?id=1582376)
=> Bug 1582376 - increase AMQP frame size

clients/client-py/taskcluster/aio/asyncclient.py
Without this change, you often see
```
taskcluster.exceptions.TaskclusterRestFailure: None
```
which isn't exactly helpful.  This occurs when `data` is `{}`, so we
check for that case and fall back to a default message when that occurs.
=> Return better errors from tc-client-py

services/worker-manager/src/providers/google.js
Let's at least fix this for now
=> Fix too-long workerpool names for google cloud

services/github/src/tc-yaml.js
If a user writes:
```yaml
tasks:
$if: ..
then: [ .. ]
```
then in the case where the conditional is false, the resutling config
will not have a `tasks` property.  Adding `else: []` would fix that, but
let's be nice and accept `undefined` as equivalent to `[]`.
This occurred at https://github.com/servo/webrender/pull/3755#issuecomment-532653876 (I'm the one who changed the `.taskcluster.yml`, so that's why I started digging..)
=> Allow tc.yml to produce undefined 'tasks'

dev-docs/development-process.md
Fixed  typo in development-process.md changing TASKCLUSTER_ROOT_URL from "https://taskcluster-staging.net" to "https://taskcluster.net"
=> Fix typo in development-process.md

services/auth/test/containers_test.js
This fixes an intermittent failure that occurred when the test queried the blob before the blob was deleted.
Bugzilla Bug: [1580666](https://bugzilla.mozilla.org/show_bug.cgi?id=1580666)
=> Bug 1580666 - add missing await

CHANGELOG.md
**What the PR does**
Fix typo in the CHANGELOG.md file.
**Description**
The screenshot below shows a typo that exists in the current CHANGELOG file for this project.
It should be `It uses sessions to keep track of users` instead of `It uses a sessions to keep track of users`.
=> Fix CHANGELOG typo.

ui/docs/manual/using/namespaces.mdx
This may not be the best fix -- ideally the content of `<Warning>` would
be treated as Markdown, and in markdown `<` is not a special character
when included in backticks.
Refs #1472.
=> Fix syntax error in namespace.mdx

ui/docs/tutorial/hello-world.mdx
Remove broken video link from the Hello World tutorial.
The video link on the hello world tutorial was broken and needed to be removed.
Issue: [1058](https://github.com/taskcluster/taskcluster/issues/1058)
=> [Docs] Fix video link

clients/client-go/go.mod, clients/client-go/go.sum, clients/client-shell/go.sum
It's not clear why `go mod` introduced this error.
Fixes #1492.
=> Fix the pseudo-version for github.com/streadway/amqp

package.json
Issues like #1492 seem to keep croppping up.  This might be a bug in
renovate, but is probably just buggy `go mod`.  Let's let the versions
sit still for a while -- the go client doesn't have a whole lot of
dependencies anyway.
=> Only manage node packages with renovate

ui/src/components/HookForm/index.jsx
Added tooltips to add and delete buttons under Schedule.
Resolves https://github.com/taskcluster/taskcluster/issues/1409.
=> Add Tooltips to button icons

ui/src/views/Tasks/NoTask/index.jsx, ui/src/views/Tasks/NoTaskGroup/index.jsx
A unique placeholder has been added for  '/tasks' and '/tasks/groups' routes. 
Resolves #1416
=> Placeholder for '/tasks' and '/tasks/groups'

dev-docs/best-practices/changelog.md
This brings the changelog best-practices into line what what we've been doing.  I think we're doing the right thing in generating fairly sparse changelogs -- users don't need to know about every UI tweak, for example.
=> Write fewer changelog entries

ui/src/components/RoleForm/index.jsx
change the role editor description from initial text-entry box 
to a tabbed view showing both a preview and a place to write the description.
-------------------------------------------------------------------
- replaced `TextField` component to `MarkdownTextArea` component for the description part in `RoleForm` UI component
- added `name` property to component in order to make use of `handleInputChange` function for onChange property
---------------------------------------------------------------------
- before fix: 
- after fix:
Closes https://github.com/taskcluster/taskcluster/issues/1459.
=> [UI] role editor description to rendered markdown

ui/src/components/ErrorPanel/index.jsx, ui/src/theme.js
Added contrastText key in error theme, referencing to light theme color, and created a new class to change fill property of svg in ErrorPanel component.
Closes #1385
=> Fix ErrorPanel "X" close button in light theme

infrastructure/tooling/src/smoketest/checks/secrets.js
This PR addresses #1247, which is to create a secret, read it back and then read it again and if it is the same one as the created, remove the secret then try to get the secret again which fails.
After running `yarn smoketest`
@djmitche @helfi92
=> Add create secret and read it back smoketest

ui/src/components/Search/index.jsx
**Issue:**
When the placeholder value has been changed inside the search box, the overflow of text happened inside the search box of the route - `/tasks/groups`, since the number of characters were more in this.
**What did I do to resolve this:**
I have increased the overall width of the search box while in stationary mode. In transition mode, it works like before.
**Before bug fix:**
**After bug fix:**
=> [UI] Resolve text-overflow inside the search box

ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx
**Issue:**
The heading was displayed as the `Index Browser` in `/tasks/index` route which mismatches the current navbar heading for this route.
**What did I do to resolve this:**
Hence, I made the heading for this route as `Task Index` to match the navbar.
=> Heading change in /tasks/index route

ui/src/views/CachePurges/ViewCachePurges/index.jsx
**Issue:**
The heading was displayed as the `Cache Purges` in the `/purge-caches` route which mismatches the current navbar heading for this route.
**What did I do to resolve this:**
Hence, I made the heading for this route as `Purge Caches` to match the navbar.
=> Heading change in /purge-caches

infrastructure/tooling/src/smoketest/checks/purgeCache.js
This PR which addresses the issue #1248  adds a new test to the yarn smoketest by adding a module to `infrastructure/tooling/src/smoketest/checks/`. It calls the purge-cache service to create a purge, then pretend to be a worker and see that the purge was properly recorded.
=> Add purgecache smoketest

ui/docs/tutorial/hello-world.mdx
Removed [https://tc.example.com/tasks/create] from Hello-World tutorial and added a reference to the Task-Creator tool instead.
=> Remove old Task Creator link from 'hello-world' tutorial

infrastructure/tooling/src/main.js
The key here is `console.error(err.toString())` instead of `console.error(err)`; the latter prints some object-like notation, whereas the former calls the error's stringify function, which assertion errors use to format the nice diff display.
=> improve error output for tooling

services/web-server/config.yml
This allows the service to start up without azure credentials.  With
just accountId set, it will "mostly" work -- everything except the
sign-in and third-party sign-in support.
=> Include azure.accountId in web-server settings for development

ui/src/views/Documentation/Reference/ApiReference.jsx
**Closes Issue #1577**
visually divide API references into categories
- use categories as small "headings" in the list of API methods for cases where there is more than one category (such as the Auth service). 
- In cases where there is only one category, there should be no change.
**Changes Applied**
1. Added `groupBy()` function which creates an array of API methods grouped by categories
2. Added `GroupEntry` component which uses conditional rendering to add headings and display lists of API methods
- if category has only one method, displays single entry usng `entry` component
- if category has more than one methods, displays heading and list of API methods using `entry` component
**Result**
- before
- after
=> visually divide API references into categories

services/notify/test/api_test.js, services/notify/test/helper.js
I looked into this yesteday because I thought it might be related to failure in prod. Turns out it is fine, but this should remove the unhandled rejection and make it a real failure. I also "fixed" the failure by removing a check that was invalid with real creds.
I think we should eventually add more tests for this that we've removed here but don't have time now. I'll update the bug stating that we should add tests for this if this is accepted.
=> Bug 1587901 unhandled rejection in notify tests

ui/src/components/SpeedDialAction/index.jsx
Add 'other' parameter with component 'span' into SpeedDialAction(/ui/src/components/SpeedDialAction/index.jsx) for preventing warning in console
Closes #1407.
=> [Bug 1407]: [UI] Remove material-ui warning in console

changelog/MoCoX17AQJ2rq32qWOhbTw.md, infrastructure/tooling/src/changelog/index.js, infrastructure/tooling/src/main.js
Commander treats `--no-xxx` arguments specially, setting `xxx` to false
rather than setting `noXxx`.
=> Fix yarn changelog --no-bug

changelog/issue-1682.md, ui/src/components/Dashboard/index.jsx, ui/src/views/WorkerManager/WMViewErrors/index.jsx
**Closes Issue** #1682 
view title should preserve the worker pool ID as it is w/o formatting
- ex. Errors For Taskcluster Imaging Taskcluster Imaging Ci
- ->  Errors For "taskcluster-imaging/taskcluster-imaging-ci"
**Changes Applied**
- added `disableTitleFormatting` prop to Dashboard component
- set the `disableTitleFormatting` prop to true for the dashboard in WMViewErrors
=> Fix view title for worker pool view error page

ui/src/components/Search/index.jsx, ui/src/views/Tasks/TaskIndex/IndexedTask/index.jsx, ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx
This PR allows search for indexed tasks like in old site https://tools.taskcluster.net/index/
1) Users can put `buildbot.branches.mozilla-esr52/linux64-asan` or `buildbot.branches.mozilla-esr52.linux64-asan` in searchbox or URL and see the task
2) Users can put `buildbot.branches` in searchbox or URL and see `/tasks/index/buildbot.branches`
3) Searchbox tracks namespace
@helfi92 kindly review this PR. It works but I think it could be done better)
Idea: 
I think we can move the searchbox above Indexed Tasks and Namespaces titles because it's hard to read and write long namespaces in the box 
Closes #1148
=> [UI] Allow task search

changelog/V9gQQys8RWiQUxYiQwsQSg.md, services/worker-manager/src/providers/aws.js, services/worker-manager/test/provider_aws_test.js
This came up in slack today as a 500 and I figured we could do better.
I changed 'Token validation' since there's no token being validated, so it's kind of a misleading error message.
=> Improve error messages for registerWorker with invalid inputs

changelog/issue-1688.md, ui/src/components/WMWorkerPoolEditor/index.jsx
Hi @helfi92 , I found the problem with this issue was that the `aws` provider does not have a `workerPool.Config` value (it returns an empty string). Please let me know if what I have done is sufficient to resolve this issue.
Closes #1688
=> Resolve error message in code editor component

changelog/bug-1590848.md, services/github/src/tc-yaml.js, services/github/test/data/configs/taskcluster.single.v1.yml, services/github/test/intree_test.js, ui/docs/reference/integrations/github/taskcluster-yml-v1.mdx
This should help with having more than one TC deployment (temporarily) enabled for a given GitHub repository.
https://bugzilla.mozilla.org/show_bug.cgi?id=1574648 tracks migrating the Servo project to the new community deployment of Taskcluster. Since Servo’s usage of TC is somewhat complex, I’d like to do this transition progressively or at least with some testing before “flipping the switch”. This means having, for a time, both https://github.com/apps/taskcluster and https://github.com/apps/community-tc-integration/ enabled on the repository and reacting to the same GitHub events based on the same `.taskcluster.yml` file.
However we’ll likely want to generate tasks with different payloads for each deployment. (If only with a different `provisionerId`.) Providing the deployment’s root …
=> Add `taskcluster_root_url` to the JSON-e context for `.taskcluster.yml`

ui/docs/reference/core/web-server/README.mdx
Relative links are tricky in the docs, but origin-relative will always work..
=> Fix readme links

infrastructure/tooling/src/smoketest/checks/role.js
This PR is a follow up to #1724  which is to accomplish the following tasks. The original issue is #1246
I am not sure if this is an efficient way to do it, please guide me if I am taking the wrong approach here. )
@djmitche
=> Add cleanup for role smoketest 

changelog/issue-1839.md, ui/src/components/SignInDialog/index.jsx
Credit to @glandium for the fix!
Github Bug/Issue: Fixes #1839.
=> Add ref=opener to sign-in buttons

changelog/bug-1590175.md, generated/references.json, services/worker-manager/src/estimator.js, services/worker-manager/src/monitor.js, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/google.js, ui/docs/reference/core/worker-manager/README.mdx
Bugzilla Bug: [1590175](https://bugzilla.mozilla.org/show_bug.cgi?id=1590175)
This involved some changes to how each provider loops over launch configs. I've tested the google provider in dev but it would be nice if @owlishDeveloper or someone can test the aws provider. I can provide an image for whoever wants it so they can avoid building it again themselves.
=> Estimator updates to support `capacityPerInstance`

infrastructure/tooling/src/main.js
The commander upgrade in #1860 led to `program.args` always being
empty, leading to always printing help, and commander helpfully calls
process.exit after printing help.
=> Fix `yarn changelog` no longer running.

changelog/bug-1593142.md, services/worker-manager/docs/providers.md, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/cloudapi.js, services/worker-manager/src/providers/google.js, services/worker-manager/src/providers/provider.js, services/worker-manager/src/providers/testing.js, services/worker-manager/src/provisioner.js, services/worker-manager/src/worker-scanner.js, services/worker-manager/test/provider_google_test.js
Bugzilla Bug: [1593142](https://bugzilla.mozilla.org/show_bug.cgi?id=1593142)
I'm running this in heroku currently and it appears to work at least from a not-throwing-errors perspective. I see it logging `cloud-api-paused` and `cloud-api-resumed` so that's good news too. Each loop of the provisioning and worker-scanning loops seems to finish with plenty of time remaining for now. I'd like to watch this a bit longer before landing this PR but put it up for review now.
=> [bug 1593142] Generalize support for backoffs and queueing in worker-manager

changelog/Zw5_mm9kR-umKNhHehdGag.md, infrastructure/tooling/src/changelog/index.js
I think this is a bit more friendly than linking to a directory of changelog files.  Example output:
---
▶ Additional changes not described here: [bug 1234](http://bugzil.la/1234), [#4567](https://github.com/taskcluster/taskcluster/issues/4567).
=> Link to issues not otherwise mentioned in the release

changelog/bug-1593754.md, services/web-server/src/main.js
Bugzilla Bug: [1593754](https://bugzilla.mozilla.org/show_bug.cgi?id=1593754)
It turns out this was just a bug where we were using the wrong config value.
=> Bug 1593754 - use pulse.namespace for the pulse namespace

changelog/HlsKXj6YSXyheh1KWKDMCA.md, services/index/src/api.js
It seems that `query` returns an empty array in the not-found case, rather than throwing an error.  At any rate, an expired entry is probably best represented as "not found" anyway.
=> Improve 404 error message for index service

changelog/bug-1593809.md, services/github/config.yml, services/github/src/api.js, services/github/test/api_test.js, services/github/test/github-auth.js, ui/docs/manual/deploying/github.mdx
Bugzilla Bug: [1593809](https://bugzilla.mozilla.org/show_bug.cgi?id=1593809)
This does two linked things:
* Takes BOT_USERNAME as a config, since it is different per deployment.  From GitHub's perspective, the username is the App name plus `[bot]`, e.g., `cloudopsstage-taskcluster[bot]`.  Partially to simplify configuration and partially because @edunham already set all of the config to names lacking `[bot]`.
* Handles 404's from the github API method by passing them along to the caller -- both for badges (with a new-repo svg) and for latest.
=> Bug 1593809 - github.bot_username and 404's from github.latest

infrastructure/tooling/src/smoketest/checks/role.js
This PR is a follow up to the Add cleanup for role smoketest #1776 pull request which traces back to the original issue #1246. The issue for not cleaning up was with the time condition.
- Updated the for loop syntax
- Cleans up by deleting the role if the last modified time is 1 hour or more
@djmitche
=> Fix clean up of role smoketest

infrastructure/tooling/src/smoketest/checks/createClient.js
This PR creates a create client smoketest which traces back to the issue #1245. The new client is set to expire in 1 hour after being created.
@djmitche
=> Add create client smoketest

changelog/issue-niSSIctzX93Fh5QmnvSE2T8QnUhwF19a.md, package.json
`schedule:earlyMondays` already defines a schedule property in https://github.com/renovatebot/presets/blob/2cda948b40835151157e778ccb3f96387b7974eb/packages/renovate-config-schedule/package.json#L12-L15. It's possible that `"schedule": "at any time",` was overwriting the preset's value.
=> Attempt to fix renovate PRs (weekly instead of daily)

changelog/bug-1595418.md, services/web-server/src/loaders/tasks.js
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1595418 and https://bugzilla.mozilla.org/show_bug.cgi?id=1595506.
=> Dependencies not shown when a task doesn't have a decision task

changelog/issue-1946.md, dev-docs/development-process.md
Change `export TASKCLUSTER_ROOT_URL=https://taskcluster.net` to `export TASKCLUSTER_ROOT_URL=https://community-tc.services.mozilla.com`
Closes  #1946
=> [docs] update devdocs

changelog/bug-1574854.md, ui/src/components/NotFound/index.jsx
Bugzilla Bug: [1574854](https://bugzilla.mozilla.org/show_bug.cgi?id=1574854)
=> Bug 1574854 - Remove "404" from pages not found

changelog/bug-1585141.md, clients/client-go/README.md, clients/client-go/tcqueue/tcqueue.go, clients/client-py/README.md, clients/client-py/taskcluster/generated/aio/queue.py, clients/client-py/taskcluster/generated/queue.py, clients/client-shell/apis/services.go, clients/client-shell/cmds/group/actors_test.go, clients/client-web/src/clients/Queue.js, clients/client/src/apis.js, generated/references.json, libraries/scopes/README.md, services/github/config.yml, services/github/test/data/configs/taskcluster.dependencies.v1.yml, services/hooks/test/validate_test/create-hook-request.json, services/notify/test/handler_test.js, services/queue/src/api.js, services/web-server/README.md, ui/docs/manual/tasks/README.mdx, ui/docs/manual/using/scheduled-tasks.mdx, ui/docs/reference/integrations/github/taskcluster-yml-v1.mdx, ui/docs/reference/platform/auth/scopes.mdx, ui/docs/tutorial/authenticate.mdx, ui/docs/tutorial/monitor-task-status.mdx, ui/src/components/HookForm/index.jsx, ui/src/views/Quickstart/index.jsx, ui/src/views/Tasks/CreateTask/index.jsx
Bugzilla Bug: [1585141](https://bugzilla.mozilla.org/show_bug.cgi?id=1585141)
We could consider, in a followup, and once the workerPoolId / taskQueueId stuff is done, making a top-level `default_worker_pool_id` config that is passed to tc-github and the UI and used to generate these default tasks.
=> Bug 1585141 - remove references to aws-provisioner-v1

changelog/issue-1754.md, ui/src/components/WMWorkerPoolsTable/index.jsx, ui/src/views/Clients/ViewClients/clients.graphql, ui/src/views/Clients/ViewClients/index.jsx, ui/src/views/Roles/ViewRoles/Roles.jsx, ui/src/views/Secrets/ViewSecrets/index.jsx
Make search case insensitive for Roles and Secrets by adding regexp option \i
Github Bug/Issue: Fixes #1754
=> Fix 1754: [UI] Make search case insensitive

changelog/bug-1596171.md, ui/src/views/Tasks/CreateTask/index.jsx
Bugzilla Bug: [1596171](https://bugzilla.mozilla.org/show_bug.cgi?id=1596171)
=> Bug 1596171 - default to schedulerId taskcluster-ui in task-creator

changelog/issue-1908.md, ui/src/components/TaskGroupTable/index.jsx
Github Bug/Issue: Fixes #1908
The only page I found with the issue is the page that displays a Task Group. Please let me know if I missed another page with the same issue.
I added breakpoints for small devices to remove extra padding on the right and left sides of the table being displayed and made it so the entire status is visible and the name takes up the rest of the space.
Result:
=> Make Task Group status more visible on mobile

changelog/fYinNUocTZuYjdVanB_8Ag.md, generated/docs-table-of-contents.json, ui/docs/reference/core/README.mdx, ui/docs/reference/integrations/README.mdx, ui/docs/reference/platform/README.mdx, ui/docs/reference/url-structure.mdx
This moves some documentation out of tc-lib-urls, so I'll file a corresponding PR to remove it there.
=> Document the services' URL structure

changelog/GNPpHu8QTT6LQ73vfWmIrw.md, services/web-server/src/servers/oauth2.js, services/web-server/src/utils/unpromisify.js, services/web-server/test/unpromisify_test.js
I like what this does to oauth2.js -- a simple wrapper that allows use of async functions without any trouble.
The unpromisify.js is pretty gnarly, though.  There appears to be no better way to set a function's arity, and oauth2orize will call functions completely differently based on their arity, so we need to match the original arity including the trailing `done` method.
Like elsewhere, there's one spot in here where I made a function `async` even though it doesn't use `await`, because that allows any thrown exceptions to be treated as Promise rejections.
=> Wrap async callbacks functions to call done(..)

changelog/pr-2028.md, clients/client-py/README.md, clients/client-py/taskcluster/helper.py
This is a relatively thin wrapper around the taskcluster library to provide some easier access to secrets and services in different authentication contexts.
We (Mozilla relman/salltt teal) use this class across different projects:
- in [mozilla/code-review](https://github.com/mozilla/code-review/blob/master/tools/code_review_tools/taskcluster.py)
- in [mozilla/code-coverage](https://github.com/mozilla/code-coverage/blob/master/tools/code_coverage_tools/taskcluster.py)
- in [mozilla/libmozevent](https://github.com/mozilla/libmozevent/blob/master/libmozevent/taskcluster.py)
The idea is to instanciante only one `TaskclusterConfig` in the user's project, authenticate once (usually at the beginning of runtime), then access all the Taskcluster services through that wrapper so they all get the …
=> Add Python client helper for easier usage.

changelog/Vgd_TWwSRZya05pr1h0mBA.md, services/web-server/src/login/strategies/mozilla-auth0.js, services/web-server/test/login_strategies_mozilla_auth0_test.js
Resolves https://sentry.prod.mozaws.net/operations/taskcluster-firefox-ci/issues/6734112/.
=> Fix TypeError when profile has no identites

changelog/bug-1491551.md, clients/client/src/client.js, clients/client/test/client_test.js
This works around a bug in Superagent.
Bugzilla Bug: [1491551](https://bugzilla.mozilla.org/show_bug.cgi?id=1491551)
=> Bug 1491551 - return ECONNABORTED with a good message for timeout

changelog/bug-1597276.md, services/web-server/src/entities/Artifact.js
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1597276.
=> Bug 1597276 - Only open log viewer when artifact is plain text

changelog/X5QnJXUUTMSMk8sPWS9P1g.md, ui/docs/manual/deploying/github.mdx, ui/docs/manual/deploying/login-strategies.mdx
Running the UI was throwing `SyntaxError: unknown: Expected corresponding JSX closing tag for <deployment-name>`.
=> Fix docs parser mdx

changelog/bug-1599122.md, services/worker-manager/src/providers/aws.js, services/worker-manager/test/fake-aws.js, services/worker-manager/test/provider_aws_test.js
Bugzilla Bug: [1599122](https://bugzilla.mozilla.org/show_bug.cgi?id=1599122)
Note that while this addresses an overprovisioning, it is a *limited* overprovisioning -- at most one instance per launchConfig, and there were 10 launchConfigs in the worker pool that led to bug 1599122.  So this cannot (alone) account for 100's of additional instances.
=> Bug 1599122 - spawn a more precise number of instances

changelog/bug-1600125.md, ui/src/components/SecretForm/index.jsx
Bugzilla Bug: [1600125](https://bugzilla.mozilla.org/show_bug.cgi?id=1600125)
=> [UI] Bug 1600125 - Secret form save button outside text area

changelog/bug-1601149.md, services/github/src/github-auth.js, services/github/test/github-auth_test.js
Bugzilla Bug: [1601149](https://bugzilla.mozilla.org/show_bug.cgi?id=1601149)
=> Bug 1601149 - accept non-escaped github PEMs with multiple lines

ui/package.json, ui/yarn.lock
Resolves https://github.com/taskcluster/taskcluster/issues/1878.
```
> yarn why acorn
[1/4] 🤔  Why do we have the module "acorn"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "acorn@5.7.3"
info Has been hoisted to "acorn"
info Reasons this module exists
- Hoisted from "react-styleguidist#acorn"
- Hoisted from "react-styleguidist#buble#acorn"
- Hoisted from "react-styleguidist#buble#acorn-dynamic-import#acorn"
- Hoisted from "react-styleguidist#buble#acorn-jsx#acorn"
info Disk size without dependencies: "1.08MB"
info Disk size with unique dependencies: "1.08MB"
info Disk size with transitive dependencies: "1.08MB"
info Number of shared dependencies: 0
=> Found "webpack#acorn@6.3.0"
info This module exists because …
```
=> [UI] Update eslint to v6

infrastructure/tooling/src/main.js, infrastructure/tooling/src/release/index.js, infrastructure/tooling/src/release/tasks.js, infrastructure/tooling/src/utils/index.js, infrastructure/tooling/src/utils/npm.js, infrastructure/tooling/src/utils/pypi.js
Bugzilla Bug: [1598649](https://bugzilla.mozilla.org/show_bug.cgi?id=1598649)
This will be the first step: automating all parts of the release but still running it locally.  The next step will be to split this up and run most of it in CI, so that `yarn release` tags and pushes, with the rest of the fun happening remotely.
=> Bug 1598649 - automate the release process

.yarnrc, changelog/bug-2114.md, package.json, ui/package.json
This is accomplished via `yarn policies set-version` and then
updating the `package.json` engines sections (both ui and metapackage). I've left that note in the commit comment so we can remember how to do this next time.
This replaces #2114
=> Update yarn to latest release

changelog/bug-1577839.md, services/worker-manager/src/providers/aws.js, services/worker-manager/test/fake-aws.js, services/worker-manager/test/fixtures/schemas/sample-aws-worker-pull.json, services/worker-manager/test/fixtures/schemas/sample-google-config.json, services/worker-manager/test/provider_aws_test.js, services/worker-manager/test/schema_validate_test.js
Bugzilla Bug: [1577839](https://bugzilla.mozilla.org/show_bug.cgi?id=1577839)
I'd like some feedback on the way I stub `EC2.describeInstanceStatus`, especially from @djmitche (I know bstack approves)
I disabled "comma-dangle" for the file because I'd like to format long function arguments on every line, and you don't need a comma after the last function argument or parameter
I used Dustin's idea of `fake.call` in the `EC2.runInstances` stub. Re: [this comment in the old Dustin's PR](https://github.com/taskcluster/taskcluster/pull/1701/files#diff-71648e88330ea7c4c8837b3d2fadf21eR5) - the bug in the fixture was that in my eternal wisdom I instantiated the stub and passed in default `TagSpecifications`, so that was the only thing the stub could assert on. In case of user-defined tags, we …
=> Bug 1587511 pt 1 tests

changelog/bug-1595749.md, services/web-server/src/login/strategies/mozilla-auth0.js, services/web-server/test/login_strategies_mozilla_auth0_test.js
Bugzilla Bug: [1595749](https://bugzilla.mozilla.org/show_bug.cgi?id=1595749)
Looks like we didn't change identityFromProfile after switching to the CIS API (v2 of the PersonAPI)
Here's the [profile](https://github.com/mozilla-iam/cis/blob/master/well-known-endpoint/tpl/profile.schema) schema.
=> Bug 1595749 (comment 4) - Fix identityFromProfile

changelog/bug-1577839.md, changelog/bug-1587511.md, generated/references.json, services/worker-manager/schemas/v1/config-aws.yml, services/worker-manager/schemas/v1/config-google.yml, services/worker-manager/schemas/v1/worker-lifecycle.yml, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/google.js, services/worker-manager/test/fake-aws.js, services/worker-manager/test/fixtures/schemas/sample-aws-config.json, services/worker-manager/test/fixtures/schemas/sample-aws-worker-pull.json, services/worker-manager/test/fixtures/schemas/sample-google-config.json, services/worker-manager/test/provider_aws_test.js, services/worker-manager/test/provider_google_test.js, services/worker-manager/test/schema_validate_test.js
Bugzilla Bug: [1587511](https://bugzilla.mozilla.org/show_bug.cgi?id=1587511)
This is just part one because the bug is for terminating workers if they go idle for a long time and don't try to claim or reclaim work. That will be a bigger project requiring queue<-->w-m interaction.
Sticking this key inside a `lifecycle` field allows us to add more settings like this in the future but if it feels unwieldy, let me know and I will move it up. Also happy to change names, etc. As an example, we could add the `runningTimeout` to account for the 96 hour thing in this bug.
TODO:
=> [Bug 1587511] (part 1) Terminate workers that don't register 

changelog/bug-1602642.md, services/auth/config.yml
Bugzilla Bug: [1602642](https://bugzilla.mozilla.org/show_bug.cgi?id=1602642)
Note: This can either land on master and deploy with 24.1.0 or it can land and then we make a branch to make 24.0.2.
=> [bug 1602642] Fix typo in allowed buckets config

changelog/issue-2152.md, ui/src/components/ProvisionerDetailsTable/index.jsx
Github Bug/Issue: Fixes #2152
Before 
After 
_transitions slowed down just for the gifs_
=> Ui bug/drawer provisioner

db/0001.yml, libraries/postgres/src/Database.js, libraries/postgres/src/Schema.js, libraries/postgres/test/database_test.js, libraries/postgres/test/db-simple/0001.yml, libraries/postgres/test/db-simple/0002.yml, libraries/postgres/test/schema_test.js
Rather than rely on capital letters, I thought about disallowing them. Using snake case for method names would align better with method names. Capital letters should probably just be SQL commands. Let me know if you disagree. Also, this is not tested.
=> [tc-lib-postgres] Do not allow capital letters for db methods

changelog/bug-1602985.md, clients/client-py/release.sh, infrastructure/tooling/src/release/tasks.js
..and fix the log filenames in 'yarn release'
Bugzilla Bug: [1602985](https://bugzilla.mozilla.org/show_bug.cgi?id=1602985)
=> Bug 1602985 - don't check for dirty repo when releasing py client

changelog/issue-2187.md, ui/src/views/Clients/ViewClient/index.jsx
* Fixes #2187 
* When we click `save` button, it would trigger rerender multiple times since `GraphQL` would update `error` and `loading` props. This makes `initialClient`'s `expires` update. Therefore, when `key` props changed, the component `ClientForm` would create a new instance and reset form's value.
* To prevent the resetting, use `memoize` function from `fast-memoize` to cache function `getClientFormKey` return value and use `serializer` to set the `cache key`.
=> [UI] Prevent form resetting value when creating a new client

changelog/issue-1660.md, ui/src/components/ErrorPanel/index.jsx, ui/src/views/Documentation/index.jsx
Closes https://github.com/taskcluster/taskcluster/pull/1756.
Fixes #1660.
Thanks to @THEozmic for the help in getting this started in https://github.com/taskcluster/taskcluster/pull/1756.
=> [UI] Properly center error panel in docs

.taskcluster.yml, db/README.md, db/access.yml, db/src/main.js, db/src/upgrade.js, db/test/helper.js, db/versions/0001.yml, generated/db-schema.json, generated/docs-search.json, generated/docs-table-of-contents.json, infrastructure/tooling/src/generate/generators/db-schema.js, infrastructure/tooling/src/generate/generators/db-user-docs.js, infrastructure/tooling/src/generate/generators/readme-stored-procedures.js, libraries/postgres/src/Database.js, libraries/postgres/src/Schema.js, libraries/postgres/test/database_test.js, libraries/postgres/test/helper.js, libraries/postgres/test/schema_test.js, libraries/testing/README.md, libraries/testing/src/index.js, libraries/testing/src/with-db.js, ui/docs/manual/deploying/README.mdx, ui/docs/manual/deploying/database.mdx
Handling of permissions for tc-lib-postgres.
Reference:
* https://www.postgresql.org/docs/9.0/sql-grant.html
* note that it appears that `GRANT .. on ALL TABLES IN SCHEMA` just enumerates the current set of tables and grants on each of them -- it does not automatically expand to include newly-added tables!
* https://www.postgresql.org/docs/11/infoschema-table-privileges.html
I tested and verified that permissions changes are handled transactionally just like almost everything else in postgres, so these grants / revokes won't take effect until the transaction commits.
My next steps:
=> tc-lib-postgres permissions

changelog/P-IpBKPgQyCIbt7HWVq6gA.md, clients/client-py/taskcluster/aio/asyncclient.py, clients/client-py/taskcluster/client.py, clients/client-py/test/test_client.py, clients/client-shell/cmds/group/actors.go, clients/client-shell/config/serialization.go, infrastructure/tooling/src/utils/docker.js, libraries/monitor/src/monitormanager.js, libraries/references/src/validate.js, services/auth/test/stories_test.js, services/hooks/src/data.js, services/queue/src/artifacts.js, services/queue/src/dependencytracker.js
This has some relatively low-impact changes to remove TODO's from the monorepo.
There are still a few:
```
clients/client-web/.neutrinorc.js:              // TODO: Override using tap() so as to not have to repeat the
clients/client-web/.neutrinorc.js:        // TODO: Remove this when fixed in @neutrinojs/library.
infrastructure/tooling/src/dev/aws.js:  // TODO: Add both blob buckets
infrastructure/tooling/src/dev/aws.js:  // TODO: Also set up auth/notify aws stuff
infrastructure/tooling/src/dev/rabbit.js:        if (!['hooks', 'auth'].includes(service)) { // These services hardcode namespace TODO: fix?
infrastructure/tooling/src/dev/taskcluster.js:  // TODO: Figure out what any of these should be set to
infrastructure/tooling/src/dev/taskcluster.js:  //TODO: These github things can/should …
```
=> Remove some TODOs

changelog/bug-1598649.md, entrypoint, infrastructure/tooling/src/build/index.js, infrastructure/tooling/src/build/monoimage.js, infrastructure/tooling/src/main.js, infrastructure/tooling/src/publish/index.js, infrastructure/tooling/src/publish/tasks.js, infrastructure/tooling/src/release/index.js, infrastructure/tooling/src/release/tasks.js, infrastructure/tooling/src/utils/command.js, infrastructure/tooling/src/utils/docker.js, package.json
Bugzilla Bug: [1598649](https://bugzilla.mozilla.org/show_bug.cgi?id=1598649)
Next step will be to perform the `yarn release:publish` portion in CI on pushes to tags.
=> Bug 1598649 - split into 'yarn release' and 'yarn release:publish'

changelog/issue-2031.md, ui/src/components/AuthConsent/index.jsx, ui/src/components/ClientForm/index.jsx, ui/src/components/DatePicker/index.jsx, ui/src/components/SecretForm/index.jsx, ui/src/theme.js, ui/src/utils/constants.js
- Replaced `KeyboardDatePicker` with `KeyboardDateTimePicker` to additionally allow choosing time in pickers across the UI
- Removed `format` prop from three components that render `DatePicker` - `SecretForm`, `ClientForm` and `AuthConsent`, so the new `format` in `DatePicker` works correctly
- Introduced new styles in `theme.js` so that the hour and clock hands display prominently in the pickers, across both dark and light themes
For choosing prominent colors for the clock hands, I started by looking at how the colors were displayed on the [material-ui-pickers demo page](https://material-ui-pickers.dev/demo/datetime-picker). It looks like their clock hand colors match the color of the main toolbar, so I decided to go the same route for the picker here, and chose the color of the main …
=> [UI] Add DateTimePicker in UI; fix  clock styles

changelog/issue-2201.md, ui/src/components/WMWorkerPoolEditor/index.jsx
Save WM button is enabled only when all fields are filled, including owner field.
Fixes https://github.com/taskcluster/taskcluster/issues/2201.
=> Make worker manager form invalid if owner not provided

.taskcluster.yml, changelog/bug-1606948.md
Bugzilla Bug: [1606948](https://bugzilla.mozilla.org/show_bug.cgi?id=1606948)
=> Bug 1606948 - remove no-longer-necessary installs

changelog/CVgKPSmcRsqCpRkeHIDwoQ.md, ui/src/views/Documentation/components/Warning/index.jsx
Before             |  After
:-------------------------:|:-------------------------:
Before             |  After
:-------------------------:|:-------------------------:
=> [UI] Revamp the Warning component in docs

changelog/bug-1608176.md, clients/client-go/codegenerator/model/api.go, clients/client-go/creds_test.go, clients/client-go/http.go, clients/client-go/http_test.go, clients/client-go/tcauth/tcauth.go
Bugzilla Bug: [1608176](https://bugzilla.mozilla.org/show_bug.cgi?id=1608176)
This is functionality we had long, long ago, and on which [taskcluster-proxy depended](https://github.com/taskcluster/taskcluster-proxy/pull/46).  It's easy enough to re-introduce it!
I also added some tests for bewit support.  Happily, they passed :)
=> Bug 1608176 - allow `client.SignedURL(..)` to take a full URL again

changelog/bug-1604649.md, services/queue/src/workerinfo.js
This is a very minor reduction in total queries to Azure.  I don't expect this to "fix" the ServerBusy errors at all..
Bugzilla Bug: [1604649](https://bugzilla.mozilla.org/show_bug.cgi?id=1604649)
=> Bug 1604649 - skip loading a worker if no tasks are claimed

changelog/KS3gz-X8TumrS-e0eSl6og.md, netlify.toml
After re-linking the repo ([see comment](https://github.com/taskcluster/taskcluster/pull/2274#issuecomment-575216982)), Netlify is failing with "Deploy directory 'ui/ui/build' does not exist". https://community.netlify.com/t/deploy-directory-web-web-public-does-not-exist/4405 suggests that the publish command now gets run inside the base directory.
=> Adjust netlify publish command

changelog/NzegYUX3TxSDwwDh-6xqrA.md, clients/client-py/setup.py
We now use normalize_root_url, so require the version where that was
introduced.
See https://github.com/taskcluster/tc-admin/pull/60
=> Require newer tc-lib-urls in python client

package.json
This will also keep us the free-tier for Netlify.
https://docs.renovatebot.com/configuration-options/#rebaseconflictedprs
=> [renovate] Do not rebase to save CI cycles

changelog/bug-1604175.md, clients/client-go/tcqueue/types.go, clients/client-go/tcqueueevents/types.go, generated/references.json, services/queue/schemas/constants.yml, services/queue/src/api.js
Reverts #2218.  Bugzilla Bug: [1604175](https://bugzilla.mozilla.org/show_bug.cgi?id=1604175)
I could be convinced to flag this as a major change.
=> Bug 1604175 - Revert max task deadline to 5 days

.taskcluster.yml
This avoids console-taskgraph outputting animation, which makes for a very large and repetitive logfile.
=> Convince 'yarn test:meta' that it is not running in a terminal

changelog/bug-1611266.md, services/worker-manager/src/providers/azure.js
Bugzilla Bug: [1611266](https://bugzilla.mozilla.org/show_bug.cgi?id=1611266)
Quick fix to azure-provider to generate valid names for azure resources by limiting generated names to alphanumeric
=> [Bug 1611266] - azure-provider: generate valid resource names

changelog/bug-1611696.md, services/github/src/handlers.js
Bugzilla Bug: [1611696](https://bugzilla.mozilla.org/show_bug.cgi?id=1611696)
=> Bug 1611696 - ignore status messages for unrecognized taskGroups

changelog/pull-2313.md, ui/docs/manual/deploying/cloud-credentials.mdx
Per https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_grammar.html: "For IAM policies, basic alphanumeric characters (A-Z,a-z,0-9) are the only allowed characters in the Sid value."
This patch represents the change I had to make to successfully create the policy in AWS.
Tangentially related to https://bugzilla.mozilla.org/show_bug.cgi?id=1609276 in that I had to fix this to make progress on it. No changelog entry as it's literally just fixing a typo in the docs.
=> Docs: Fix invalid SID

infrastructure/tooling/src/smoketest/checks/createClient.js
Github Bug/Issue: Fixes #2310 
Added `deleteOnExpiration` in the payload which is used to create a new client. By default `deleteOnExpiration` is set to false.
@djmitche
=> Add deleteOnExpiration in create client smoketest

changelog/bug-1608828.md, clients/client-go/README.md
This calls out the import path change explicitly (and also fixes import paths in the client README)
=> Changelog addendum for generic-worker merge

README.md, workers/README.md
Should we remove any of the sub-directories that are showing up here?
=> Nest generic-worker README under 'Workers'

changelog/bug-1615312.md, workers/generic-worker/gw-decision-task/tasks.yml, workers/generic-worker/multiuser_posix.go, workers/generic-worker/simple_docker.go
Bugzilla Bug: [1615312](https://bugzilla.mozilla.org/show_bug.cgi?id=1615312)
This is a more aggressive cleanup of task directories on POSIX workers (Linux/macOS).
Currently our [raspberry pi worker](https://community-tc.services.mozilla.com/provisioners/proj-taskcluster/worker-types/gw-ci-raspbian-stretch) (Linux/ARM) keeps running out of disk space, and this should fix it. For the meantime, I manually deleted all task directories using the `chmod` and `rm` commands from this PR, to keep it running.
=> Bug 1615312 - more aggressive cleanup of task directories on Linux/macOS

changelog/J5L-zmdmQEqb8W2h1HgBNA.md, libraries/postgres/src/Database.js
This check is mainly a security check for deployments, and will continue to work in that capacity.  But, when performing db-version tests, we upgrade to specific non-latest versions, so checking permissions against access.yml doesn't make sense (and fails).
=> only check access.yml when upgrading to the latest version

changelog/bug-1615631.md, infrastructure/tooling/src/publish/tasks.js, workers/generic-worker/build.sh
This uses `build.sh` to build the artifacts, running it in such a way
that it skips the tests (which should already have passed) and simply
builds the artifacts.
Bugzilla Bug: [1615631](https://bugzilla.mozilla.org/show_bug.cgi?id=1615631)
=> Bug 1615631 - include generic-worker artifacts in GH release

changelog/bug-1616022.md, infrastructure/tooling/src/release/tasks.js
Bugzilla Bug: [1616022](https://bugzilla.mozilla.org/show_bug.cgi?id=1616022)
=> Bug 1616022 - fix regexp for updating generic-worker version on release

changelog/bug-1616022.md, infrastructure/tooling/src/release/tasks.js
Bugzilla Bug: [1616022](https://bugzilla.mozilla.org/show_bug.cgi?id=1616022)
This is the second attempt to fix [bug 1616022](https://bugzilla.mozilla.org/show_bug.cgi?id=1616022). The first occurred in PR #2369 (released in [25.2.0](https://github.com/taskcluster/taskcluster/releases/tag/v25.2.0)), but was __unsuccessful__. I'm currently testing by making a staging release in branch [`staging-release/bug1616022-v2`](https://github.com/taskcluster/taskcluster/commits/staging-release/bug1616022-v2).
=> Bug 1616022 - use multiline regexp for updating generic-worker version number

changelog/issue-2375.md, clients/client-web/.neutrinorc.js, clients/client-web/test/Auth_test.js, clients/client-web/test/Queue_test.js, clients/client-web/test/helper.js
Until now, these tests have been using the legacy URL.
Github Bug/Issue: Fixes #2375
=> Update tc-client-web tests to use a given rootUrl

changelog/Otc0tAj0TMK39FQJ68OX6g.md, clients/client-go/codegenerator/model/model.go, clients/client-go/creds_test.go, clients/client-go/integrationtest/integration_test.go, internal/scopes/scopes_test.go, internal/testrooturl/testrooturl.go, workers/generic-worker/gw-decision-task/main.go, workers/generic-worker/tcproxy/tcproxy_test.go
Aside from the `./workers/generic-worker` package (which requires a build tag), this makes all of the go packages pass or skip when running a bare `go test`.  When running under CI, `NO_TEST_SKIP` is set, and these tests will fail if not given the proper credentials.
This follows on to #2356 and contains its commits.  I can rebase once that lands.
=> Allow running go test ./... without rootURL

changelog/bug-1558240.md, workers/generic-worker/artifacts_multiuser_test.go, workers/generic-worker/main.go
Bugzilla Bug: [1558240](https://bugzilla.mozilla.org/show_bug.cgi?id=1558240)
=> Bug 1558240 - separate '=== Task Finished ===' from log output

package.json
This also switches from ignoring updates to frequently-updated packages
to just getting a weekly PR for those updates.  That will let us keep
reasonably up-to-date with those packages without being overwhelmed.
Bugzilla Bug: [1616921](https://bugzilla.mozilla.org/show_bug.cgi?id=1616921)
=> Bug 1616921 - enable gomod in renovate

changelog/bug-1616900.md, tools/taskcluster-worker-runner/protocol/protocol_test.go
This avoids a subtle race condition where `runnerProto` is not
considered initialized until some time *after* the `hello` message is
received, as the function handling that message must run.
`go test -race` missed this because the use of a Mutex avoids an actual
data race.  The bug here is at a higher level than that.
Bugzilla Bug: [1616900](https://bugzilla.mozilla.org/show_bug.cgi?id=1616900)
=> Bug 1616900 - wait for proto initialization in tests

changelog/bug-1600071.md, services/worker-manager/docs/providers.md, services/worker-manager/src/estimator.js, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure.js, services/worker-manager/src/providers/google.js, services/worker-manager/src/providers/provider.js, services/worker-manager/src/providers/testing.js, services/worker-manager/src/provisioner.js, services/worker-manager/test/estimator_test.js, services/worker-manager/test/provider_aws_test.js, services/worker-manager/test/provider_azure_test.js, services/worker-manager/test/provider_google_test.js, services/worker-manager/test/provisioner_test.js
For workers that are booting, worker-manager considers them as "ready"
and possibly running tasks, and it ignores the fact that they will
eventually claim the current pending tasks. This is not a problem if the
instances of these workers boot relatively quickly.
If the instances take a long time to get ready (like baremetal
instances), worker-manager will keep spawning more instances while there
are pending tasks and until we reach the maximum capacity, causing an
overprovisioning problem.
We fix this by subtracting the number of instances in the REQUESTED
state from the total number to spawn.
=> Bug 1600071: Fix overprovisioning for workers that are slow to boot up

changelog/aeki4OImR8iFYCwyo-Mr1A.md, changelog/bug-1616922.md, workers/generic-worker/artifacts_broken_on_docker_test.go
A [test failure](https://community-tc.services.mozilla.com/tasks/groups/PoP3IcGlTHyVUYov269yyw) crept in for `TestFileArtifactTwiceInPayload` in #2399 but went unnoticed due to [bug 1533235](https://bugzilla.mozilla.org/show_bug.cgi?id=1533235).
The failure is due to a slight change in behaviour introduced in #2399 that disallows duplicate artifacts being entered in a task payload. Previously it was allowed, as no conflict of information ensues from having identical entries. It was a [permissive approach](https://en.wikipedia.org/wiki/Robustness_principle) but I'm also ok with us being more restrictive, as it may help avoid bugs in downstream code that parse task payloads and assume that entries are unique.
=> Bug 1616922 - adapt TestFileArtifactTwiceInPayload to disallow same artifact twice

changelog/enDr6FUCT_SDvWCgQcd6SQ.md, workers/generic-worker/expose/local.go, workers/generic-worker/expose/local_test.go, workers/generic-worker/livelog.go
In #2408 I initially thought perhaps we were closing the exposure twice, so this also adds a commit to set `l.exposure` to nil after closing it, avoiding that particular situation.
Github Bug/Issue: Refs #2408
=> Avoid closing the listener to which an https.Server was attached

changelog/bug-1433854.md, workers/generic-worker/multiuser_windows.go
Bugzilla Bug: [1433854](https://bugzilla.mozilla.org/show_bug.cgi?id=1433854)
Tested and working on Windows 10 / ARM laptop. After upgrading the worker to the version built from this branch, the several hundred previous task directories lurking on the machine were deleted successfully. Note this was causing around 15 min delay between a task completing and the next one starting, so this is a big performance gain on workers that didn't have their own cleanup (Note OpenCloudConfig was doing a similar cleanup itself).
Note, the inspiration for this approach came from [this article](https://www.ghacks.net/2017/07/18/how-to-delete-large-folders-in-windows-super-fast/).
=> Bug 1433854 - remove files and directories more forcefully on windows

changelog/bug-1616649.md, generated/references.json, services/worker-manager/src/data.js, services/worker-manager/src/monitor.js, services/worker-manager/src/providers/azure.js, services/worker-manager/src/provisioner.js, services/worker-manager/test/fake-azure.js, services/worker-manager/test/provider_azure_test.js, tools/taskcluster-worker-runner/provider/azure/azure.go, tools/taskcluster-worker-runner/provider/azure/azure_test.go, tools/taskcluster-worker-runner/provider/azure/metadata.go
Bugzilla Bug: [1616649](https://bugzilla.mozilla.org/show_bug.cgi?id=1616649)
note: consulted with @ajvb about changing workerId to key off of generated names, got a 👍
I have tested this in my dev environment end-to-end, I used a custom build of worker-runner and was able to successfully register. Due to unrelated issues with the azure docker-worker VM tasks weren't claimed, but everything else works!*
\* to a reasonable observable degree of confidence
=> Bug 1616649: azure-provider avoid blocking operations

changelog/EMxihKGCRHmzKZT9nXtG-w.md, clients/client-go/tcworkermanager/types.go, generated/references.json, services/worker-manager/schemas/v1/register-worker-response.yml, services/worker-manager/src/api.js
We are having issues with the shutdown behavior in AWS instances.
When the worker is done, it calls `shutdown -h now` to stop the
instances and then the `workerManager` can terminate it later. The
problem is that sometimes the shutdown process stalls inside the
instance, hanging the worker forever.
Granting the scope to call `registerWorker` allows the worker to request
`workerManager` to terminate the worker, avoiding the shutdown issue.
=> Grant scope to the worker to terminate itself

changelog/bug-1558240.md, workers/generic-worker/artifacts_multiuser_test.go, workers/generic-worker/main.go
Reverts taskcluster/taskcluster#2406
[Bug 1558240](https://bugzil.la/1558240) was raised for docker-worker, so unfortunately this fix doesn't apply. Although generic-worker logs a similar line, it does not log it directly after the command output (it logs the exit status of the command after the command output). Also note that in generic-worker there can be several commands, so a fix would need to occur once per command rather than once per task. A unit test would have demonstrated this. 😜  Also note each log line is prefixed by a timestamp, so the fix would have left a trailing timestamp at the end of the command output too.
I'm also not sure a new line should be added, in the same way that if a command executed from a bash session completes without outputting a trailing newline …
=> Revert "Bug 1558240 - separate '=== Task Finished ===' from log output"

changelog/1596171.md, ui/src/utils/constants.js, ui/src/views/Tasks/CreateTask/index.jsx, ui/src/views/Tasks/ViewTask/index.jsx
Bugzilla Bug: [1596171](https://bugzilla.mozilla.org/show_bug.cgi?id=1596171)
=> Use a non-`-` schedulerId when editing a task in the UI.

changelog/bug-1618983.md, generated/references.json, services/worker-manager/schemas/v1/config-static.yml, services/worker-manager/schemas/v1/worker-lifecycle.yml, services/worker-manager/src/providers/static.js, services/worker-manager/test/provider_static_test.js
Bugzilla Bug: [1618983](https://bugzilla.mozilla.org/show_bug.cgi?id=1618983)
This will allow static workers to run for 31 days, if configured that way.  And if they reboot in that time, then they can run forever.
=> Bug 1618983 - support reregistrationTimeout in static provider

changelog/brSrfgj3Sxi1ECduQiqZuw.md, package.json, tools/taskcluster-worker-runner/renovate.json
Context:
* https://github.com/renovatebot/config-help/issues/558#issuecomment-594010549
* https://docs.renovatebot.com/configuration-options/#postupdateoptions
=> Force `go mod tidy` to be run by renovate

changelog/AXXNEjbFSQGBb_g28-RMbw.md, workers/generic-worker/gw-decision-task/tasks.yml
I noticed the [following failure](https://community-tc.services.mozilla.com/tasks/Xwz-vWvpSA6E5BPbLyu3GA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FXwz-vWvpSA6E5BPbLyu3GA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive_backing.log#L11420) on the master branch, which happened on the raspberry pi tester:
```
../../../golangci-lint/golangci-lint-1.23.6-*/golangci-lint run --build-tags "${ENGINE}"
+ ../../../golangci-lint/golangci-lint-1.23.6-linux-armv6/golangci-lint run --build-tags simple
level=error msg="Timeout exceeded: try increase it by passing --timeout option"
[taskcluster 2020-03-03T19:19:50.001Z]    Exit Code: 4
[taskcluster 2020-03-03T19:19:50.001Z]    User Time: 10m12.912047s
[taskcluster 2020-03-03T19:19:50.001Z]  Kernel Time: …
```
=> Increase golangci-lint timeout since sometimes it times out

changelog/bug-1559434.md, libraries/pulse/src/credentials.js, libraries/pulse/test/credentials_test.js
Bugzilla Bug: [1559434](https://bugzilla.mozilla.org/show_bug.cgi?id=1559434)
=> Bug 1559434 - encode slashes in pulse passwords

changelog/bug-1619925.md, workers/generic-worker/taskstatus.go
Bugzilla Bug: [1619925](https://bugzilla.mozilla.org/show_bug.cgi?id=1619925)
Should fix this intermittent panic (that caused our Windows 10 / amd64 CI worker to go out of commission and our CI backlog to build up):
```
panic: Could not PUT to http://localhost:80/credentials: Put http://localhost:80/credentials: read tcp 127.0.0.1:50828->127.0.0.1:80: wsarecv: An existing connection was forcibly closed by the remote host.
goroutine 37 [running]:
main.(*TaskclusterProxyTask).Start.func1(0xa8f230, 0x9)
C:/Users/task_1582745095/taskcluster/workers/generic-worker/taskcluster_proxy.go:103 +0x77c
main.(*TaskStatusManager).updateStatus(0xc000466a00, 0xa8f230, 0x9, 0xc000045e28, 0xc00024c3e0, 0x2, 0x2, 0x0, 0x0)
C:/Users/task_1582745095/taskcluster/workers/generic-worker/taskstatus.go:295 +0x5d0 …
```
=> Bug 1619925 - lock taskstatus mutex while deregistering taskstatus change listeners

libraries/postgres/src/Database.js, libraries/postgres/test/database_test.js, ui/docs/manual/deploying/database.mdx
Both of these values are substituted directly into SQL queries, so out of an abundance of caution let's make sure they have an appropriate format.
Github Bug/Issue: Fixes #2454
=> Enforce the format of some DB config variables

changelog/issue-244.md, package.json, services/hooks/test/taskcreator_test.js, yarn.lock
I'm a renovate bot 🤖
The new json-e version adds support for boolean logic operators short-circuiting, so hopefully writing `.taskcluster.yml`s will now be less of a pain. Thank you @Nicrii for the work on json-e!
=> Add boolean operators short-circuiting for `.taskcluster.yml`s

db/test/versions/0002_test.js, libraries/entities/src/index.js, libraries/entities/test/db/versions/0001.yml, libraries/entities/test/entity_scan_test.js
This adds tests and some comments about the dangers of the tc-lib-entities `scan` method.
Happily, no issues found :)
Github Bug/Issue: Fixes #2457
=> Add SQLi tests for the scan method

infrastructure/tooling/src/release/tasks.js
Fixes #2479.
I looked at adding a `go sometihng` run to `yarn release` to make sure we got all of these, but [there is no simple invocation to do this](https://github.com/golang/go/issues/15513) and anyway generic-worker's tests don't compile under a simple `go test`.  So this will do.
=> include internal/ in version bumps in yarn release

changelog/bug-1621630.md, package.json, services/hooks/test/taskcreator_test.js, yarn.lock
Bugzilla Bug: [1621630](https://bugzilla.mozilla.org/show_bug.cgi?id=1621630)
See the bug for details -- this caused errors in production.
=> Bug 1621630 - roll back JSON-e to 3.0.2 temporarily

changelog/bug-1621630-2.md, package.json, yarn.lock
Bugzilla Bug: [1621630](https://bugzilla.mozilla.org/show_bug.cgi?id=1621630)
=> Revert json-e dependency to 3.0.1

changelog/YJtFHaNFSRiqY9Gpa3fEEA.md, tools/taskcluster-worker-runner/protocol.md, tools/taskcluster-worker-runner/protocol/capabilities.go, tools/taskcluster-worker-runner/protocol/capabilities_test.go, tools/taskcluster-worker-runner/protocol/protocol.go, tools/taskcluster-worker-runner/protocol/protocol_test.go, tools/taskcluster-worker-runner/provider/aws/awsprovider.go, tools/taskcluster-worker-runner/provider/aws/awsprovider_test.go, tools/taskcluster-worker-runner/provider/azure/azure.go, tools/taskcluster-worker-runner/provider/azure/azure_test.go, tools/taskcluster-worker-runner/provider/google/google.go, tools/taskcluster-worker-runner/provider/google/google_test.go, tools/taskcluster-worker-runner/provider/provider/common.go, tools/taskcluster-worker-runner/provider/provider/iface.go, tools/taskcluster-worker-runner/provider/provider/shutdown_linux.go, tools/taskcluster-worker-runner/provider/provider/shutdown_windows.go, tools/taskcluster-worker-runner/provider/standalone/standalone.go, tools/taskcluster-worker-runner/provider/static/static.go, tools/taskcluster-worker-runner/runner/run.go, tools/taskcluster-worker-runner/tc/fakeworkermanager.go, tools/taskcluster-worker-runner/tc/fakeworkermanager_test.go, tools/taskcluster-worker-runner/tc/workermanager.go
The "shutdown" message is implemented for AWS, Azure and GCP providers.
When received, worker-runner will call the worker-worker manager
RemoveWorker API. If it fails, it will fall back to the system
shutdown.
For Linux, the "system shutdown" is the execution of the command
"shutdown -h now". For Windows, it will call the Win32 API
InitiateSystemShutdownEx.
The static and standalone providers don't implement the "shutdown"
message.
=> Implement "shutdown" message

changelog/QoaFRYyEQSyH0y3mXS1GfA.md, infrastructure/tooling/src/generate/generators/worker-runner.js, infrastructure/tooling/src/publish/tasks.js, infrastructure/tooling/src/release/tasks.js, tools/taskcluster-worker-runner/build.sh, tools/taskcluster-worker-runner/provider/provider/shutdown_unix.go
* `yarn generate` runs `util/update-readme.go`
*  `yarn release` updates `worker-runner` version
* `yarn release:publish` add `worker-runner` binaries to the release artifacts
Each commit is self contended to make reviewing easier.
=> Add worker-runner to the release process

infrastructure/tooling/src/meta/checks/test-only.js
It's fine to use `test.only(..)` in development, but let's remember to
remove it before landing!
=> Check that test scripts do not use test.only(..)

changelog/VxQghtPGTDSilg3zoHTrxQ.md, infrastructure/tooling/src/changelog/index.js
In particular, this should whitelist renovate's changes
=> Do not reqiure a changelog for changes that only affect go.mod/sum

changelog/bug-1621270.md, infrastructure/tooling/src/publish/tasks.js
Bugzilla Bug: [1621270](https://bugzilla.mozilla.org/show_bug.cgi?id=1621270)
=> Bug 1621270 - retry GitHub artifact uploads

.taskcluster.yml, changelog/bug-1622052.md, tools/taskcluster-worker-runner/credexp/credexp_test.go, tools/taskcluster-worker-runner/protocol.md, tools/taskcluster-worker-runner/protocol/capabilities.go, tools/taskcluster-worker-runner/protocol/protocol.go, tools/taskcluster-worker-runner/protocol/protocol_test.go, tools/taskcluster-worker-runner/protocol/testing.go, tools/taskcluster-worker-runner/protocol/transport.go, tools/taskcluster-worker-runner/provider/aws/awsprovider.go, tools/taskcluster-worker-runner/provider/aws/awsprovider_test.go, tools/taskcluster-worker-runner/provider/azure/azure.go, tools/taskcluster-worker-runner/provider/azure/azure_test.go, tools/taskcluster-worker-runner/provider/google/google.go, tools/taskcluster-worker-runner/provider/google/google_test.go, workers/generic-worker/gw-decision-task/main.go, workers/generic-worker/main.go
This makes capabilities a private property of Protocol, with methods to
manipulate it.  It also prohibits adding a capability after
protocol.Start is called.
This change simplifies the interface, but makes the tests a bit more
verbose!
Bugzilla Bug: [1622052](https://bugzilla.mozilla.org/show_bug.cgi?id=1622052)
I've cherry-picked the try-checks thing so that I can see the g-w results in the github checks on this PR.  If #2500 doesn't land as-is, I'll remove that commit before merging this PR.
=> Bug 1622052 - distinguish local and remote proto capabilities

changelog/bug1618991.md, clients/client-go/http.go, clients/client-go/http_test.go, go.mod, go.sum
Check that 500's result in an error eventually.  This isn't the case, but https://github.com/taskcluster/httpbackoff/pull/15 should fix it.
Bugzilla Bug: [1618991](https://bugzilla.mozilla.org/show_bug.cgi?id=1618991)
=> Bug 1618991 - ensure 500's result in an error

clients/client-web/yarn.lock, yarn.lock
Fixes https://github.com/advisories/GHSA-7fhm-mqm4-2wp7
This patch updates some but not all instances of minimist in yarn.lock.  The minimist requirement in TC is because old versions of mkdirp require it, and various things require old versions of mkdirp.  So it's not something we can update immediately until those intermediate dependencies are fixed.  Hopefully dependabot pinged them too!  Anyway, minimist is a command-line parser, and mkdirp uses it for its command-line interface (`bin/cmd.js`), which we don't use (at all, and certainly not in production), so I'm confident that the vulnerable code is not used.
=> Update Acorn 7 to 7.1.1 and Minimist to 1.2.5

changelog/QF5L1OhCR_y8k8B2RF4zQA.md, ui/docs/reference/workers/generic-worker/support-tiers.mdx, workers/generic-worker/gw-decision-task/tasks.yml
The worker pools behind these tasks are single workers or otherwise
unable to keep up with demand.  So, rather than merging PRs with yellow
dots or eventually red X's when the tasks time out, let's disable them.
Of these platforms, Windows 10 is a tier-1 platform, but that platform's
testing is covered by the Windows 2012 worker pool.  And linux-arm is a
tier-1 platform, but in the larger Mozilla scope is tier-2 at this
point.
=> Disable tasks on pools with insufficient capacity, linux-arm to tier 2

package.json, yarn.lock
This upgrades mocha to 7.x, but that still requires mkdirp 0.5.1 which
requires a vulnerable minimist.  So this forces a resolution to use
0.5.3 instead.  [0.5.1..0.5.3](https://github.com/substack/node-mkdirp/compare/0.5.1...isaacs:v0.5.3) is just the minimist version bump.
This should finally get rid of the nagging warnings about minimist!
=> Remove ancient minimist versions by forcing mocha dependency

changelog/issue-2527.md, services/queue/src/api.js
Support for blob artifacts was removed some time ago.  This check uses
non-date conditions in `Entity.scan`, which isn't supported in postgres.
This code doesn't do anything when there are no blob artifacts, and there never are.
=> Remove check that all (unsupported) blob artifacts are complete

changelog/BcRMAjAzQhePEpkylqhbCA.md, infrastructure/tooling/src/generate/generators/generic-worker.js, ui/docs/reference/workers/generic-worker/README.mdx
This fixes the broken payload links in https://community-tc.services.mozilla.com/docs/reference/workers/generic-worker.
=> No bug - trivial doc links fix

.taskcluster.yml
This is just removing some unused cruft.
We can re-add matrix notifications if desired.  I don't desire but I don't object..
=> Stop trying to report to irc

changelog/bug-1623183.md, libraries/postgres/src/Database.js
The node-pg docs do not mention it, but a read of the source verifies
that it's up to the user of a Client object to intercept `error` events
while it's checked out from the pool (and then to stop intercepting them
before releasing it to the pool).
=> Bug 1623183 - handle error events from pg Clients

changelog/asLY7YXqQRaZQdlOXgm7eQ.md, tools/taskcluster-worker-runner/logging/protocol/proto.go, tools/taskcluster-worker-runner/logging/protocol/proto_test.go, tools/taskcluster-worker-runner/runner/run.go, workers/generic-worker/workerrunner.go
A malformed log message would have made worker-runner panic and crash,
which would be unfortunate and hard to debug, so this also adds some
resiliency there and tests it.
This was an oversight on my part -- I changed the design while working on #2435 and missed to change it in generic-worker.
I'd like to get this landed since it's broken in master, but afterward we could thin of adding purpose-specific `Send` messages for each defined message type in the protocol, to prevent this in the future.
=> Update generic-worker to send log messages with a 'body' prop

changelog/SBYYr-RSRBKXzkPOsMaGMw.md, generated/docs-search.json, libraries/postgres/src/Database.js, ui/docs/manual/deploying/database.mdx
This adds documentation for DB connection counts.  In load-testing my dev env, I found that the default `max_connections` for an N1 CloudSQL instance was too small.  Note that Postgres is not designed to scale into lots and lots of connections -- it allocates memory for each one -- so massively over-estimating this number is not good.
This is still pretty vague -- basically a guess and some advice.  @edunham do you think that's sufficient?  The errors when the connections max out are pretty easy to spot.
=> document DB connection counts

changelog/issue-2536.md, db/versions/0004.yml, generated/db-schema.json, libraries/postgres/src/Database.js
This fixes failures of tests to run on machines not in UTC.
Actually, only the first commit is required, but the second is something else I tried to fix this, and is a good idea anyway -- it makes very clear to anyone else using the database the precise time that the timestamps indicate, without guessing "UTC? Mountain View?"
I added a card to https://github.com/taskcluster/taskcluster/projects/3 to track checking for and rejecting TIMESTAMP columns, so I don't make the same mistake again.
The entities tables do not have any timestamp(tz) columns, so no change needed.
Github Bug/Issue: Fixes #2536
=> Use UTC with Postgres

changelog/issue-2553.md, db/versions/0005.yml, generated/db-schema.json, libraries/azqueue/test/get_messages_test.js
When getting multiple messages from the queue in the same call, Azure
Queues returns those messages in the order they were received.  This
updates the Postgres implementation to do the same.
=> Fix ordering of queue pops when numberOfMessages > 1

changelog/bug-1622943.md, generated/references.json, services/worker-manager/schemas/v1/worker-lifecycle.yml
Bugzilla Bug: [1622943](https://bugzilla.mozilla.org/show_bug.cgi?id=1622943)
=> Bug 1622943 - limit lifecycle.reregistrationTimeout to 30 days

changelog/VFoTTBIjRfOrc18KrZ_MyQ.md, libraries/postgres/test/database_test.js
This removes the `badrole` from `test-service2` after the
tc-lib-postgres tests complete.  Without this, other tests fail if
run against the same DB instance.
=> Reset DB user roles after tests

changelog/bug-1552323.md, generated/docs-search.json, generated/docs-table-of-contents.json, services/github/src/constants.js, services/github/src/handlers.js, services/github/src/utils.js, services/github/test/handler_test.js, ui/docs/reference/integrations/github/checks.mdx
Bugzilla Bug: [1552323](https://bugzilla.mozilla.org/show_bug.cgi?id=1552323)
as well as the Finix feature request.
The general idea is that if people want custom task results in checkruns, they need:
* Arrange for an artifact with markdown-formatted output in `.md` format
* Put the artifact's name in the task definition's `extra.github`
* Taskcluster-github will post the contents of the artifact in the check run
=> Add output.text from an artifact

db/src/setup.js, libraries/postgres/src/Database.js, services/auth/src/main.js, services/github/src/main.js, services/hooks/src/main.js, services/index/src/main.js, services/notify/src/main.js, services/purge-cache/src/main.js, services/queue/src/main.js, services/secrets/src/main.js, services/web-server/src/main.js, services/worker-manager/src/main.js
Note that this will conflict with #2571 :(
Github Bug/Issue: Fixes #2566
=> Use a 30s query timeout in web API processes

libraries/postgres/src/Database.js
Stackdriver aggregates log-based metrics into 1 minute buckets. By
outputting this log info once a minute, we can ensure every process is
represented in every bucket. Without doing this, metrics derived from it
would be much harder to interpret, since the processes whose data was
represented in each bucket would vary depending on when they were
started.
=> Log DB info once a minute

changelog/CQPTekd3S8yeaGupCoR94w.md, tools/worker-runner/provider/aws/awsprovider.go, tools/worker-runner/provider/google/google.go
If the worker process panics and exits, the instance stays in a zombie
state.
To mitigate the situation, when the worker exits, we request a worker
termination to worker-manager.
=> Request worker termination when the worker process exits

changelog/T4aTRVi3RGiCS6slQohlgQ.md, services/notify/src/main.js
From slack:
> hmm, what we're seeing is the error at https://github.com/taskcluster/taskcluster/blob/master/libraries/postgres/src/Database.js#L58
> from https://github.com/taskcluster/taskcluster/commit/979653f465104abb27709e7532128a9cf5963dbc
> which is new in v28.2.0. we were on v28.1.0 before
_untested_ but should work.
=> Fix notify monitor is required error

infrastructure/tooling/src/importer/importer.js, infrastructure/tooling/src/importer/index.js, infrastructure/tooling/src/importer/util.js
Make import faster by splitting large tables into multiple imports.
The two largest tables that are currently preventing us from being within the 8 hours range are QueueTasks and QueueArtifacts:
```
--- QueueTasks ---
Rows imported: 14060373
Elapsed time: 10h 5m 4.4s
--- QueueArtifacts ---
Rows imported: 125737200
Elapsed time: 1d 2m 34.1s
```
=> Make importer faster

changelog/issue-2522.md, db/src/setup.js, db/test/helper.js, generated/references.json, libraries/entities/test/helper.js, libraries/postgres/src/Database.js, libraries/postgres/test/database_test.js, libraries/postgres/test/helper.js, libraries/testing/src/with-db.js, services/auth/src/main.js, services/github/src/main.js, services/hooks/src/main.js, services/index/src/main.js, services/notify/src/main.js, services/purge-cache/src/main.js, services/queue/src/main.js, services/secrets/src/main.js, services/web-server/src/main.js, services/worker-manager/src/main.js
This is the other half of #2522.  The first commit here is cherry-picked from master, and the second updated to include #2601.  We'll count #2601 fixed when this merges back to master.
=> Set up monitors for all TC services' `db` property

infrastructure/tooling/src/importer/importer.js, infrastructure/tooling/src/importer/util.js, libraries/entities/src/entitytypes.js, libraries/entities/test/blobtype_test.js, services/hooks/test/api_test.js, services/queue/test/createtask_test.js
Roles are in a container in Azure.  We're transitioning to storing them in a single row in postgres, due to some complex inter-dependencies between roles requiring atomic updates.
Bugzilla Bug: [1627807](https://bugzilla.mozilla.org/show_bug.cgi?id=1627807)
=> Bug 1627807 - add ability to import roles

libraries/postgres/src/Database.js
Github Bug/Issue: Fixes #2577
My testing confirms that now when the system is overloaded, it doesn't fail with errors about idle sessions.
=> Set idle_in_transaction_timeout to 20s

changelog/eA9N0icbTX6yaJv6_b7ojg.md, dev-docs/dev-config-example.yml, infrastructure/tooling/src/dev/index.js, infrastructure/tooling/src/dev/k8s.js, infrastructure/tooling/src/generate/generators/k8s.js
Dev environments are almost always idle, using basically none of their
CPU request but causing us to provision k8s nodes for the default amount
(50m). That's wasting resources.  Let's dial it back by default, and
anyone who needs more CPU can increase the values in their config.
=> Set a lower default for cpu requests in dev environments.

db/src/setup.js, infrastructure/tooling/src/importer/index.js, infrastructure/tooling/src/importer/util.js, libraries/postgres/README.md, libraries/postgres/src/Database.js
This will get us partway to making this configurable on a per-deployment basis, too.
=> Use a bigger pool for postgres connections when importing

changelog/YvhNWH3jSkyQSgAcrLf-Bg.md, dev-docs/best-practices/security.md
This came up in a meeting at some point followed by "huh, we should write that down".  And now it's written.
The two things I can think of that don't follow this are:
* hooks with `bindings` set to something (really more of a user-configuration issue)
* tc-github, which iirc stores the payload of each GH webhook in a pulse message.  I think there's a bug to change that to store the payload in a table, which has the nice side-effect of being able to review previous webhook payloads for a repo.
=> Add a best practice around trusting the content of pulse messages

changelog/QuzMVVs9Rta6AoOwbZTOgA.md, netlify.toml
Hopefully this will fix the failing netlify jobs.  But maybe not: it had been installing yarn 1.10, but because we embed yarn in the repo, it was actually using 1.22.4 to do the install.
Still, I can't reproduce the issue locally, so let's give this fix a shot..
=> Update yarn version in netlify.toml

changelog/bug-1525419.md, workers/generic-worker/build.sh, workers/generic-worker/envvars_broken_on_docker_test.go, workers/generic-worker/helper_windows_test.go, workers/generic-worker/multiuser_windows.go, workers/generic-worker/win32/win32_windows.go
Bugzilla Bug: [1525419](https://bugzilla.mozilla.org/show_bug.cgi?id=1525419)
This should fix the escaping of special characters in environment variables on Windows (except newline/linefeed characters which is tracked in [bug 1495760](https://bugzilla.mozilla.org/show_bug.cgi?id=1495760)).
We'll need to wait for the CI to complete - I haven't manually tested on Windows.
=> Bug 1525419 - escape env variable contents on Windows properly

yarn.lock
This addresses CVE-2019-20149.  It leaves kind-of 3.x unchanged, but that appears to be a requirement of the command line of some deeply-buried sub-dependency, so likely unused.
=> Ugrade kind-of 6.x to 6.0.3

.taskcluster.yml, changelog/NCM67ernT4im7Oh-SEJeNg.md, entrypoint, infrastructure/docker-images/build-node-and-go.sh, package.json, test/go-lint.sh
This makes it easy to see when tests pass but there are some lints to fix, without having to open up logs and search for issues.
This PR also removes the check added in #1492, which is no longer necessary.
=> Run gofmt / go lint at the top level, like for JS

changelog/QsU9-aBbSFaXRjTKMYv4iA.md, services/auth/test/helper.js, services/github/test/helper.js, services/hooks/test/helper.js, services/index/test/helper.js, services/notify/test/helper.js, services/queue/test/helper.js, services/web-server/test/graphql/artifacts_graphql_test.js, services/web-server/test/graphql/roles_test.js, services/web-server/test/graphql/tasks_graphql_test.js, services/web-server/test/graphql/workermanager_test.js, services/web-server/test/helper.js, services/web-server/test/loaders/roles_loader_test.js, services/web-server/test/loaders/tasks_loader_test.js, services/worker-manager/test/helper.js
This makes the tests pass locally for all services afaict. However, I'm not 100% sure that what I've updated the `resetTables` functions to be is semantically correct so please check there. Otherwise it was just adding some `db` to nested test files.
=> Make mocked db work again

ui/docs/reference/core/notify/usage.mdx
Copied from the corresponding API schema docs in `services/notify/schemas/v1/matrix-request.yml`. The previous one was misleading since `matrixFormat` does not set `msgtype`
=> More helpful doc for `task.extra.notify.matrixFormat`

changelog/bug-1630113.md, clients/client-go/tcnotify/types.go, generated/references.json, services/notify/schemas/v1/matrix-request.yml, services/notify/src/handler.js, services/notify/src/matrix.js, services/notify/src/notifier.js, services/notify/test/api_test.js, services/notify/test/handler_test.js, ui/docs/reference/core/notify/usage.mdx
This adds support for the basic `m.text`, `m.notice`, and `m.emote` msgtypes.
We can add support for more complicated types later if we want them but this
should cover most of our bases for now.
Thanks to @SimonSapin for the initial code and the idea.
Bugzilla Bug: [1630113](https://bugzilla.mozilla.org/show_bug.cgi?id=1630113)
=> [Bug 1630113] Support multiple matrix msgtypes

changelog/bug-1621420.md, services/github/src/handlers.js
Bugzilla Bug: [1621420](https://bugzilla.mozilla.org/show_bug.cgi?id=1621420)
If this is not done, tc-gh will be broken once we upgrade Octokit to v17 (the current latest version).
=> Replace deprecated things for Octokit

changelog/bug-1628141.md, infrastructure/k8s/values.yaml, infrastructure/tooling/src/generate/generators/k8s.js
Bugzilla Bug: [1628141](https://bugzilla.mozilla.org/show_bug.cgi?id=1628141)
Note that this will be overridden for dev deploys, to avoid over-provisioning CPU.  So this is just for "real" deployments.
=> Bug 1628141 - adjust default k8s resources based on cloudops' research

changelog/issue-2268.md, clients/client-go/README.md, clients/client-go/codegenerator/model/model.go, clients/client-go/tcauth/tcauth.go, clients/client-go/tcauthevents/tcauthevents.go, clients/client-go/tcgithub/tcgithub.go, clients/client-go/tcgithubevents/tcgithubevents.go, clients/client-go/tchooks/tchooks.go, clients/client-go/tchooksevents/tchooksevents.go, clients/client-go/tcindex/tcindex.go, clients/client-go/tcnotify/tcnotify.go, clients/client-go/tcnotifyevents/tcnotifyevents.go, clients/client-go/tcpurgecache/tcpurgecache.go, clients/client-go/tcqueue/tcqueue.go, clients/client-go/tcqueueevents/tcqueueevents.go, clients/client-go/tcsecrets/tcsecrets.go, clients/client-go/tcworkermanager/tcworkermanager.go, clients/client-go/tcworkermanagerevents/tcworkermanagerevents.go
Fixes #2268 
This PR addresses issue #2268, which is to generate godoc links in README.me file when `yarn generate` is run in the directory `client/client-go`.
This is the first time I am writing a piece of code in Golang. I was able to generate the links in the readme file when ``yarn generate`` is run. I would like to get some feedback and nudge me in the right direction if this is not what we need to achieve, please. 
@djmitche
=> Add a function to generate links in clients-go readme

services/web-server/src/servers/createApp.js
Possibly a fix for [bug 1597777](https://bugzilla.mozilla.org/show_bug.cgi?id=1597777).
=> [web-server] Allow OPTIONS cors for graphql endpoints

changelog/bug-1630124.md, tools/livelog/helper_test.go, tools/livelog/sequence_test.go, tools/livelog/writer/stream.go, tools/livelog/writer/stream_handle.go
Bugzilla Bug: [1630124](https://bugzilla.mozilla.org/show_bug.cgi?id=XXXXX)
The second commit here fixes a deadlock.  The bug was an oversight on my part in a modification I made while migrating to the monorepo -- so a new, never-released bug.
In trying to reproduce this I filled my `/tmp`, so I added some support for deleting temp files in tests.
I'm not confident this is going to fix bug 1630124, as the deadlock was in code that handles the situation where a consumer has more than 100 log output "events" buffered.  If it doesn't deadlock, then the effect is to cut off the consumer early, which should cause the test to fail.  But, I can't reproduce that behavior locally, and the test is set up such that it produces data more slowly than it consumes it (ChunkReader has a 20ns delay …
=> Bug 1630124 - fix deadlock in livelog

changelog/bug-1619286.md, ui/src/views/Quickstart/index.jsx
Bugzilla Bug: [1619286](https://bugzilla.mozilla.org/show_bug.cgi?id=1619286)
=> Bug 1619286 - add a site-specific link to github app to the quickstart

changelog/bug-1540804.md, workers/generic-worker/README.md, workers/generic-worker/chain_of_trust.go, workers/generic-worker/config_test.go, workers/generic-worker/gwconfig/config.go, workers/generic-worker/helper_test.go, workers/generic-worker/main.go, workers/generic-worker/simple_docker_test.go, workers/generic-worker/usage.go, workers/generic-worker/win32/merge_test.go, workers/generic-worker/win32/win32_windows_test.go
Bugzilla Bug: [1540804](https://bugzilla.mozilla.org/show_bug.cgi?id=1540804)
Although this makes `publicIP` optional, we should still provide the config setting on workers where the RDP feature is needed, since without it RDP will no longer be possible until we have interactive tasks running through websocktunnel. However, we can already stop providing the config setting for linux/mac workers with this change, so long as their livelogs are already configured to be served through websocktunnel. @escapewindow has [already confirmed](https://bugzilla.mozilla.org/show_bug.cgi?id=1540804#c3) that the reference to public IP in Chain of Trust is optional.
=> Bug 1540804 - generic-worker: publicIP config optional

changelog/bug-1631638.md, libraries/monitor/src/monitor.js, libraries/monitor/src/plugins/sentry.js, libraries/monitor/src/plugins/testreporter.js, libraries/monitor/test/reporter_test.js, services/worker-manager/src/estimator.js, services/worker-manager/test/estimator_test.js
This is a quite hacky fix to an already hacky alert. If you don't like this approach
feel free to r- it and my feelings will not be hurt. I see this whole part of w-m
getting a pretty good pass shortly with postgres support and cost-savings work
so I mostly want this to stop scaring me every couple weeks for now.
This also passes through tags into sentry reports that we were dropping before
Bugzilla Bug: [1631638](https://bugzilla.mozilla.org/show_bug.cgi?id=1631638)
=> [Bug 1631638] Make the runaway provisioning error a bit less flaky

changelog/issue-2681.md, db/versions/0005.yml, db/versions/0006.yml, db/versions/0007.yml, generated/db-schema.json, libraries/postgres/README.md, libraries/postgres/src/Database.js, libraries/postgres/src/Version.js, libraries/postgres/src/util.js, libraries/postgres/test/version_test.js
We have had two revisions now with no upgrade/downgrade scripts, so this seems a reasonable tweak.
=> Make migrationScript and downgradeScript optional

changelog/bug-1631829.md, services/worker-manager/src/providers/azure.js, ui/docs/reference/core/worker-manager/azure.mdx
Bugzilla Bug: [1631829](https://bugzilla.mozilla.org/show_bug.cgi?id=1631829)
=> Bug 1631829 - tag all azure worker resources with standard tags

changelog/U3wqIgKuSVu-QZfE_5AAog.md, package.json
The package is not `required`, just configured for express.
Not sure how to catch this automatically so we'll just manually make
it special.
Probably want to make a release with this first thing monday!
=> Add back ejs to prod because web-server uses it for login page

changelog/bug-1631099.md, services/github/src/github-auth.js
Bugzilla Bug: [1631099](https://bugzilla.mozilla.org/show_bug.cgi?id=1631099)
Based on [this comment](https://github.community/t5/GitHub-API-Development-and/Random-401-errors-after-using-freshly-generated-installation/m-p/23531/highlight/true#M1680) (and the thread around it).
=> Bug 1631099 - retry on 401's (Bad Credentials) from GitHub

changelog/bug-1606006.md, libraries/pulse/src/consumer.js
Bugzilla Bug: [1606006](https://bugzilla.mozilla.org/show_bug.cgi?id=1606006)
=> Bug 1606006 - generate a new ephemeral queue name on every connection

changelog/bug-1633622.md, infrastructure/tooling/src/utils/npm.js
Bugzilla Bug: [1633622](https://bugzilla.mozilla.org/show_bug.cgi?id=1633622)
This is not something we can test in a staging release (since it involves pushing a package), but I did test it locally by running `npm pack` as root both without and with `unsafe-perm`.
=> Bug 1633622 - build the build directory in tc-client-web

ui/src/views/Tasks/TaskIndex/ListNamespaces/index.jsx
Fixes https://github.com/taskcluster/taskcluster/issues/2662.
=> [UI] Do not show breadcrumb component before picking a namespace

services/web-server/src/ConnectionLoader.js
This used to be a hack back when we were running under azure where we
sometimes get a continuation token but no entries in the response. In postgres, if we get
a continuation token, there will always be a set of entries with it.
=> Avoid fetching on empty pages

infrastructure/k8s/templates/taskcluster-auth-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-built-in-workers-deployment-server.yaml, infrastructure/k8s/templates/taskcluster-github-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-github-deployment-worker.yaml, infrastructure/k8s/templates/taskcluster-hooks-deployment-listeners.yaml, infrastructure/k8s/templates/taskcluster-hooks-deployment-scheduler.yaml, infrastructure/k8s/templates/taskcluster-hooks-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-index-deployment-handlers.yaml, infrastructure/k8s/templates/taskcluster-index-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-notify-deployment-handler.yaml, infrastructure/k8s/templates/taskcluster-notify-deployment-irc.yaml, infrastructure/k8s/templates/taskcluster-notify-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-purge-cache-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-queue-deployment-claimResolver.yaml, infrastructure/k8s/templates/taskcluster-queue-deployment-deadlineResolver.yaml, infrastructure/k8s/templates/taskcluster-queue-deployment-dependencyResolver.yaml, infrastructure/k8s/templates/taskcluster-queue-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-references-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-secrets-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-ui-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-web-server-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-deployment-provisioner.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-deployment-web.yaml, infrastructure/k8s/templates/taskcluster-worker-manager-deployment-workerscanner.yaml, infrastructure/tooling/templates/k8s/deployment.yaml
In order to track cpu and memory utilization per cronjob or deployment,
we need each one to have a unique container name. This is because
Stackdriver does not tag those metrics based on their metadata, but does
tag them based on the container name. Currently, it looks like all the
cronjobs have unique names but many of the deployments share container
names. This commit changes the deployment naming to match the cronjob
naming.
https://bugzilla.mozilla.org/show_bug.cgi?id=1616858
=> Ensure all deployments have unique container names

changelog/Frzjxl83ReqEFnwDdjO2VQ.md, db/fns.md, db/src/fakes/purge_cache.js, db/test/fns/purge_cache_test.js, db/versions/0009.yml, generated/db-schema.json, services/purge-cache/src/main.js, services/purge-cache/test/expire_test.js
This function only just landed and certainly hasn't been released, so
there is no harm in changing it in-place.
=> Rename stored db function to expire_cache_purges

changelog/issue-1536.md, clients/client-web/.neutrinorc.js, clients/client-web/package.json
Move these packages instead to the list of peer-dependencies. It has the
same effect. webpack [seems to have an issue](https://github.com/webpack/webpack/issues/4824) with externals when the
build target is umd.
=> [client-web] Remove external packages from webpack external

changelog/bug-1633882.md, infrastructure/tooling/src/publish/tasks.js
See https://octokit.github.io/rest.js/v17#repos-upload-release-asset
=> Bug 1633882 - use updated call to uploadReleaseAssert

changelog/bug-1633882.md, infrastructure/tooling/src/publish/tasks.js
Bugzilla Bug: [1633882](https://bugzilla.mozilla.org/show_bug.cgi?id=1633882)
https://octokit.github.io/rest.js/v17#repos-upload-release-asset is *very* misleading.  It's correct about one of the four parameters it lists, and fails to mention three others.
=> Bug 1633882 - fix uploadReleaseAsset call

dev-docs/postgres-phase-2-guidelines.md
There's still a TODO here for the services migration step.  @helfi92, feel free to push to this PR and mark it up for review once that's ready.
When we've finished all of these migrations, this file will be a pretty rich store of best practices for using the database, and we can rewrite it in that direction.
=> Add guidelines for migrating from tc-lib-entities tables

changelog/CJ3o8el8TdW1nVrh1JMgUw.md, services/purge-cache/src/main.js
Resolves https://sentry.prod.mozaws.net/operations/taskcluster-cloudops-stage/issues/8324310/?referrer=alert_email.
=> Add 'db' in purge-cache expires entry

clients/client-web/package.json
Treeherder turns out no longer uses a couple of the peer dependencies. Treeherder is okay with a bigger package size so I'm adding them back here.
=> Bug 1587145 - Add peer dependencies to the list of dependencies

changelog/KuCkLEk0SRKlqWZBqtGwiw.md, workers/generic-worker/gw-decision-task/tasks.yml, workers/generic-worker/livelog.go, workers/generic-worker/livelog/livelog.go
=> Issue 2734 - use monorepo livelog/taskcluster-proxy in generic-worker CI

changelog/issue-2783.md, workers/generic-worker/aws_helper_test.go, workers/generic-worker/gcp_helper_test.go, workers/generic-worker/helper_test.go, workers/generic-worker/livelog.go
=> Use a distinct port for internalGETPort in tests, too

.taskcluster.yml
Github Bug/Issue: Refs https://github.com/mozilla/community-tc-config/pull/265
=> Use the proj-taskcluster/dw-ci builder for docker-worker tests

changelog/issue-2788.md, generated/docs-table-of-contents.json, infrastructure/tooling/src/publish/tasks.js, tools/worker-runner/worker/dockerworker/dockerworker.go, tools/worker-runner/worker/dockerworker/dockerworker_test.go, ui/docs/reference/workers/docker-worker/deployment.md, ui/docs/reference/workers/worker-runner/linux-services.mdx, ui/docs/reference/workers/worker-runner/windows-services.mdx, ui/docs/reference/workers/worker-runner/workers.mdx, workers/docker-worker/release.sh
Github Bug/Issue: Fixes #2788
There's a staging push [here](https://github.com/taskcluster/taskcluster/runs/657783821)
I snuck in an unrelated commit here to avoid uploading packges to npm / pypi until the GH release is done.
=> Generate a documented release tarball for docker-worker

changelog/bug-1637104.md, infrastructure/tooling/src/publish/tasks.js
Bugzilla Bug: [1637104](https://bugzilla.mozilla.org/show_bug.cgi?id=1637104)
=> Bug 1637104 - use static binaries in utility docker images

changelog/issue-2808.md, infrastructure/tooling/src/publish/tasks.js, workers/docker-worker/release.sh
Github Bug/Issue: Fixes #2808
I took the third option, running this build in a docker image.  This also drops some TODOs to sort out the node versions, but that's going to be fixed soon in the ref'd bug.
=> Build docker-worker tarballs in an environment that can compile extensions

changelog/bug-1635897.md, services/github/src/handlers.js, services/github/test/github-auth.js, services/github/test/handler_test.js
Bugzilla Bug: [1635897](https://bugzilla.mozilla.org/show_bug.cgi?id=1635897)
=> Bug 1635897 - use repos.getCommit for getting releases' sha

infrastructure/tooling/src/publish/tasks.js
This is what caused the 29.5.0 release to succeed but not do anything.
=> Return correct dependency value for docker-worker artifact

changelog/bug-1638002.md, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure.js, services/worker-manager/src/providers/google.js, services/worker-manager/test/fake-aws.js, services/worker-manager/test/provider_aws_test.js, services/worker-manager/test/provider_azure_test.js, services/worker-manager/test/provider_google_test.js, ui/docs/reference/core/worker-manager/aws.mdx, ui/docs/reference/core/worker-manager/azure.mdx, ui/docs/reference/core/worker-manager/google.mdx
Bugzilla Bug: [1638002](https://bugzilla.mozilla.org/show_bug.cgi?id=1638002)
Note that for AWS this is the best we can get, as it's possible to configure EC2 launchConfigs to allow EC2 to select the AZ.  For Azure, location is as specific as it gets.  But for Google, we could potentially use `cfg.zone` as that's a required configuration value.
=> Bug 1638002 - use region / location for workerGroup in dynamically-provisioned workers

changelog/JOVMlrV9RmKalqOITppiMQ.md, clients/client/src/client.js, clients/client/test/client_test.js
We were using the internal rootUrl as the real rootUrl for children instances made by `taskclusterPerRequestInstance`
=> Fix perRequestInstance service discovery interaction

changelog/YbCrJBWqTLW2KDAMYuCF0A.md, dev-docs/postgres-phase-2-guidelines.md, libraries/testing/README.md, libraries/testing/src/with-db.js, services/auth/test/helper.js, services/github/test/helper.js, services/hooks/test/helper.js, services/index/test/helper.js, services/notify/test/helper.js, services/queue/test/helper.js, services/web-server/test/helper.js, services/worker-manager/test/helper.js
This should save a bit of time by not setting up a new postgres
connection for each table.
=> Truncate multiple tables at once in testing

changelog/bug-1638047.md, services/web-server/src/entities/Artifact.js
Bugzilla Bug: [1638047](https://bugzilla.mozilla.org/show_bug.cgi?id=1638047)
=> [Bug 1638047] - limit log viewer to public text/plain *.log files

changelog/Zju_nhigQ0KlRslJbNfSCQ.md, workers/docker-worker/src/lib/devices/audio_device_manager.js, workers/docker-worker/src/lib/devices/video_device_manager.js
This seems a common error mode with docker-worker, and until today I didn't realize it could be configured around!
This should at least give better logging..
=> Fail with a useful error message when audio/video loopback are not available

changelog/bug-1627769.md, generated/references.json, libraries/references/src/validate.js, services/worker-manager/schemas/v1/worker-lifecycle.yml, services/worker-manager/src/providers/provider.js, services/worker-manager/test/provider_test.js
Previous to this, the default lifecycles weren't getting applied. This was
fine in the 99% case where the worker succesfully registered as at that time
the `terminateAfter` date gets set to the `expires` of the creds returned.
However for workers that did not register, the `reregisterTimeout` was null
and these workers were allowed to live forever. To apply this to all currently
existing pools, we should run `ci-admin apply`/`tc-admin apply`.
We had to add a default to all places where the lifecycle `$ref` was used. However Ajv does not allow the default to be specified outside of `properties` and `items` so we just do it where it is "imported".
This also changes our reference validation because in Ajv, `$ref` doesn't actually have to be alone. It can have siblings that it will merge …
=> [Bug 1627769] Fix slow leak of wedged workers

changelog/bug-1638370.md, services/worker-manager/src/providers/azure.js, services/worker-manager/test/fake-azure.js, services/worker-manager/test/provider_azure_test.js
This should ensure we always have the vmId for registerWorker if the
vm exists. 
This is safe to do because we are using the vm name to fetch the vmId
which is what we are doing in checkWorker anyway. Even if someone passes
in a different worker to `registerWorker` we'll get a different vmId than
the one they can sign and provide as proof.
Bugzilla Bug: [1638370](https://bugzilla.mozilla.org/show_bug.cgi?id=1638370)
=> [Bug 1638370] Fetch vmId in registerWorker for azure provider if it does not exist yet

changelog/bug-1587145.md, clients/client-web/package.json, clients/client-web/webpack.config.js
Generating two separate builds seems to have caused some issues when importing. It should be fine to generate a single umd build (default) which is compatible everywhere. Tested this locally and seems to fix the issue sclement was seeing.
=> [client-web] Bug 1587145 - generate a single build asset

.taskcluster.yml, changelog/N__STNQESvKiZq0PO2_M8g.md, services/auth/test/helper.js, services/github/test/helper.js, services/hooks/test/helper.js, services/index/test/helper.js, services/notify/test/helper.js, services/purge-cache/test/helper.js, services/queue/test/helper.js, services/secrets/test/helper.js, services/web-server/test/helper.js, services/worker-manager/test/estimator_test.js, services/worker-manager/test/helper.js, workers/generic-worker/gw-decision-task/tasks.yml
The auth service still needs an account for its tests, but other
services do not, so moved this credential into tc-auth's secret.
I also deleted the pamplemousse storage account and re-created it, so auth's tests might fail.. Hopefully not.
=> Stop loading the `azure` secret

workers/generic-worker/gw-decision-task/main.go
The CI was broken in commit d150e72543df134bfd59069b1b8f6905ceb18652 with [this error](https://community-tc.services.mozilla.com/tasks/GpX7eJP5TXCUhNYC2_nvXA/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FGpX7eJP5TXCUhNYC2_nvXA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive_backing.log) from #2895:
```
[taskcluster 2020-05-23T00:35:16.109Z] Worker Type (proj-taskcluster/gw-ci-windows2012r2-amd64) settings:
[taskcluster 2020-05-23T00:35:16.109Z]   {
[taskcluster 2020-05-23T00:35:16.109Z]     "availability-zone": "us-east-1b",
[taskcluster 2020-05-23T00:35:16.109Z]     "config": {
[taskcluster 2020-05-23T00:35:16.109Z]       "deploymentId": "31956a952b9dc567"
[taskcluster 2020-05-23T00:35:16.109Z]     },
[taskcluster 2020-05-23T00:35:16.109Z] …
```
=> Fixed bustage from PR 2895

changelog/WmP_hUuOSO6kds4-yD691A.md, services/web-server/src/servers/createApp.js
I was able to replicate the bug in my dev environment, and will verify the fix while this runs in CI.
=> Fix web-server relative path causing sign-ins to fail

changelog/issue-2876.md, ui/src/components/CachePurgesTable/index.jsx, ui/src/utils/constants.js, ui/src/views/CachePurges/ViewCachePurges/index.jsx
Fixes #2865
> Expected behaviour
> You should be able to search for a cache
> 
> Actual behaviour
> There is no easy way to search for a cache name. You need to click the next page button until you find the cache you are looking for.
_Screenshots_
=> [UI] Add search feature in purge caches page

changelog/issue-2913.md, libraries/pulse/src/consumer.js, libraries/pulse/test/consumer_test.js
This avoids a race condition where a consumer's onConnected callback
could be called *after* the first message is delivered.
This commit also fixes `consumer_test.js` to only start publishing
messages once connected.  This avoids the risk that the messages would
all be published before the consumer began; since this is an ephemeral
consumer, that would mean it receives no messages.
Github Bug/Issue: Fixes #2913
=> Prevent onConnected from occuring before a message

ui/src/views/Secrets/ViewSecrets/index.jsx
@helfi92 I noticed the intended behavior for `/secrets` already exists in `/hooks`, and can be seen here (as an example) - https://firefox-ci-tc.services.mozilla.com/hooks?search=project-
So I figured it might be worth a try to replicate the functionality already present in `ListHooks/index.jsx`. 
This change uses the `qs` package to parse out the search term from the query string, and pushes it onto `history`. Thus, once you do the following steps -
1. Visit `/secrets` and search for an item, example `project/`
2. Click on a secret
3. Go back
The browser URL now contains the search term you searched for -
whereas it is currently just `/secrets` after you go back -
However, the page still lists all the available results at `/secrets`. 
I wasn't quite sure about why this behavior at …
=> [UI] Deep Link search in /secrets

workers/docker-worker/test/integration/container_volume_caching_test.js
I'm not sure how to replicate the issue locally but here's some tests for https://community-tc.services.mozilla.com/tasks/W3NTy3axQ1GiaIfLwkwtgQ/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FW3NTy3axQ1GiaIfLwkwtgQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log.
Relates to https://github.com/taskcluster/taskcluster/pull/2874.
=> [docker-worker] Add test for empty cache

changelog/bug-1632929.md, services/github/src/handlers.js, services/github/test/handler_test.js
Bugzilla Bug: [1632929](https://bugzilla.mozilla.org/show_bug.cgi?id=1632929)
=> Bug 1632929 - use target_commitish to get SHA for releases

changelog/bug-1640267.md, changelog/issue-2890.md, changelog/issue-2951.md, internal/workerproto/README.md, workers/docker-worker/src/bin/worker.js, workers/docker-worker/src/lib/devices/audio_device_manager.js, workers/docker-worker/src/lib/devices/video_device_manager.js, workers/docker-worker/src/lib/docker/indexed_image.js, workers/docker-worker/src/lib/host/test.js, workers/docker-worker/src/lib/host/worker-runner.js, workers/docker-worker/src/lib/queueservice.js, workers/docker-worker/src/lib/runtime.js, workers/docker-worker/src/lib/task_listener.js, workers/docker-worker/test/integration/container_volume_caching_test.js, workers/docker-worker/test/integration/file_artifact_test.js, workers/docker-worker/test/superseding_test.js
This does some refactoring in docker-worker.  It doesn't touch generic-worker, because I want to wait until #2854 lands as that will conflict pretty badly.
Note that worker-runner doesn't send this message yet, as the reregisterWorker call doesn't exist yet.
Github Bug/Issue: refs #2890
=> Support new-credentials message in docker-worker

changelog/c20QJm0BT0e_6VKlDpp2yQ.md, libraries/monitor/src/logger.js
I noticed this while working on the google provider tests.  Apparently I failed to notice this when I tested 2f57cefb4dc698f680041d4c70c4eb5a3ee5e85d manually!  That commit hasn't been released yet, so this just fixes the fix.
=> correctly include metadata in fields

.taskcluster.yml, changelog/cqjJ1HiqSJ-6J_1sUyymNA.md
I think this is what was confusing task-graph and our scopes.
If this doesn't work, we may need to make our releases happen on gh release events like the other taskgraph projects do?
=> Fix release branch

changelog/EP7fStTETSijolmkfxmm0Q.md, taskcluster/ci/release/kind.yml
Fetching secrets doesn't happen in staging releases so I missed this.
=> Add taskcluster-proxy to releases

changelog/bug-1639713.md, workers/docker-worker/src/lib/devices/shared_memory_device_manager.js, workers/docker-worker/src/lib/task.js
Bugzilla Bug: [1639713](https://bugzilla.mozilla.org/show_bug.cgi?id=1639713)
Capability devices normally use the equivalent of `--device` for mounting devices from the host into the container. `/dev/shm` is different since it is a tmpfs volume, and it should be mounted using a bind mount equivalent to `--volume`.
Note that a test already exists for this, but I'm not sure if those are run, since it should have exhibited the same error reported in bugzilla.
=> Bug 1639713: /dev/shm should be a bind mount, not a device mount

changelog/GyYxIoiJTgCktahTEIIoyg.md, db/src/fakes/index.js, db/test/all_fns_test.js, libraries/postgres/README.md, libraries/postgres/src/Database.js, libraries/postgres/src/Schema.js, libraries/postgres/test/database_test.js
As part of working on the existing-capacity stuff I found that deprecating db functions didn't actually work. This splits those changes out into a PR by itself.
=> Allow deprecated functions

changelog/ZCZhEhhoQ82YA86-T2lavA.md, db/test/helper.js
=> Update TEST_DB_URL missing failure message to point to dev docs

changelog/QCZ2xnUdSa6lZ8U5VdKoBQ.md, changelog/issue-2962.md, db/src/setup.js, db/test/helper.js, libraries/postgres/README.md, libraries/postgres/src/Database.js, libraries/postgres/src/Keyring.js, libraries/postgres/test/database_test.js, libraries/postgres/test/keyring_test.js, libraries/testing/src/with-db.js, services/worker-manager/src/main.js
This fixes a typo in `services/worker-manager/src/main.js` (`crytoKeys`), and additionally calls the value `dbCryptoKeys` throughout, rather than using different names in the configuration and the source code.
=> use 'dbCryptoKeys' everywhere, fix typo

changelog/issue-3080.md, taskcluster/ci/docker-worker/kind.yml, workers/docker-worker/src/bin/worker.js, workers/docker-worker/src/lib/shutdown_manager.js, workers/docker-worker/src/lib/task.js, workers/docker-worker/src/lib/task_listener.js, workers/docker-worker/test/integration/shutdown_test.js, workers/docker-worker/test/shutdown_manager_test.js
This avoids the issue where the worker starts shutting down while
waiting for a claimWork call that eventually returns tasks (which
otherwise leaves those tasks timing out to claim-expired).
This substantially refactors ShutdownManager and TaskListener to match.
If this passes CI, I'll refactor the "host.getTerminationTime" thing a bit (it doesn't even return a time! and it doesn't distinguish graceful from immediate shutdown)
Github Bug/Issue: Fixes #3080
=> Only shut down between claimWork calls.

changelog/issue-3093.md, internal/workerproto/testing/worker.go, tools/worker-runner/errorreport/errorreport.go, tools/worker-runner/errorreport/errorreport_test.go, tools/worker-runner/exit/exit.go, tools/worker-runner/exit/exit_test.go, tools/worker-runner/exit/shutdown_unix.go, tools/worker-runner/exit/shutdown_windows.go, tools/worker-runner/provider/aws/awsprovider.go, tools/worker-runner/provider/aws/awsprovider_test.go, tools/worker-runner/provider/azure/azure.go, tools/worker-runner/provider/azure/azure_test.go, tools/worker-runner/provider/google/google.go, tools/worker-runner/provider/google/google_test.go, tools/worker-runner/provider/provider/common.go, tools/worker-runner/runner/run.go, tools/worker-runner/tc/fakeworkermanager.go
..and some other refactors while I was in there.
On the refactors: I have been mulling the idea of having a bunch of component structs and a Component interface with `SetProtocol(..)`, `WorkerStarted(..)`, `WorkerFinished(..)`, etc.,  Then the runner would basically construct a bunch of components and, for each phase of the run, call the corresponding method on each component.  It would move the tool from a big long "run" method that does a bunch of stuff to a series of well-defined phases.  So this refactor of errorreport into an object is leading toward that design.
Github Bug/Issue: Fixes #3093
=> Handle shutdowns in one place in worker-runner

changelog/U1wFteWOS-aP0VkZF3C1hQ.md, db/test/versions/0016_test.js, db/versions/0016-downgrade.sql, db/versions/0016-migration.sql, db/versions/0016.yml, generated/db-schema.json
This is prep for #2932 but will be useful for other migrations, too.
=> add uuid_to_slugid and slugid_to_uuid db functions

changelog/issue-3116.md, db/test-setup.sh, dev-docs/development-process.md, infrastructure/docker-images/build-node-and-pg.sh, libraries/postgres/src/Database.js, ui/docs/manual/deploying/database.mdx
This implements the "enforce" option from #3116.
Github Bug/Issue: Fixes #3116
=> Issue #3116 - Enforce en_US.UTF8

changelog/GEGO8q6FRH-kZ4EmCpn4NA.md, libraries/api/src/middleware/per-request-context.js
This gives a much clearer error for things like `ctx.Foo`.
=> Allow undefined properties in per-request context

changelog/f-9bI23DQn2GElKxqVdIuA.md, clients/client-web/yarn.lock, ui/yarn.lock
Addresses GHSA-6c8f-qphg-qjgp
```
lamport ~/p/taskcluster [kindof-update] $ yarn why kind-of
yarn why v1.22.4
[1/4] Why do we have the module "kind-of"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "kind-of@6.0.3"
info Has been hoisted to "kind-of"
info Reasons this module exists
- "workspace-aggregator-a034b6db-003d-4feb-9abc-59b27859136b" depends on it
- Hoisted from "_project_#md-directory#gray-matter#kind-of"
- Hoisted from "_project_#md-directory#gray-matter#section-matter#kind-of"
info Disk size without dependencies: "32KB"
info Disk size with unique dependencies: "32KB"
info Disk size with transitive dependencies: "32KB"
info Number of shared dependencies: 0
=> Found "align-text#kind-of@3.2.2"
info This module exists …
```
=> update kind-of for clients/client-web and ui

.taskcluster.yml
=> Issue #3145 - use latest mozillareleases/taskgraph docker image in decision task

changelog/issue-3147.md, infrastructure/tooling/src/main.js, infrastructure/tooling/src/release/index.js
This was accidentally deleted when adding `yarn staging-release`
Github Bug/Issue: Fixes #3147
=> re-introduce the `yarn release` command

changelog/J4NBGYcFStS4-s4PSBL-jw.md, clients/client-py/test/base/__init__.py, clients/client/test/creds_test.js
Now that auth.taskcluster.net is shut down, we need to stop using it for tests :)
=> do not rely on auth.taskcluster.net for tests

changelog/Y06b6qh6Qm2X8Fama43t0w.md, libraries/postgres/src/Database.js
I'm not sure how to introduce a dropped attribute, so I'm not sure how to test this, but it's a simple enough change to something that's already basically a test, so I think "doesn't fail" is good enough.
=> Ingore dropped pg attributes when checking db/tables.yml

changelog/bug-1637302.md, workers/docker-worker/src/lib/upload_to_s3.js
Bugzilla Bug: [1637302](https://bugzilla.mozilla.org/show_bug.cgi?id=1637302)
Fix hashing of compressed files so that we hash the uncompressed file
=> Make sure to get the hash of the uncompressed file

changelog/EQ5GAP53RziRnNw_ZicrAg.md, infrastructure/tooling/src/build/index.js, infrastructure/tooling/src/build/tasks/common.js, infrastructure/tooling/src/build/tasks/monoimage.js, infrastructure/tooling/src/utils/docker.js
This fixes:
* not pushing docker images since v31.0.0 (I've pushed them manually)
* missing monoimage-devel image tag in output at the end
* `version.json` containing `[Object object]`
=> Push docker images on release

ui/docs/manual/task-execution/workers.mdx
Update link pointing to the archived generic-worker/docker-worker directories.
=> update link to generic-worker and docker-worker;

changelog/issue-3191.md, services/github/src/handlers.js
Github Bug/Issue: Fixes #3191
This probably should have tests, but better to have the fix now than to wait until it's slotted into a sprint later.
=> Fix determination of annotationsArtifactName

changelog/issue-2937.md
The audience is a little vague, to be honest, but for the major changes, the audience was deployers, so let's be consistent.
=> changelog audience=deployers for DB migrations

changelog/QwlDxmO1Qwm6c2h6tIYTpw.md, libraries/postgres/src/Database.js
I don't really know what's going on here, but my docker image suddenly started spelling this `en_US.UTF-8`.
```
Error: Postgres database must have default collation en_US.utf8 or en_US.UTF8; this database is using en_US.UTF-8.
```
The [docs](https://www.postgresql.org/docs/11/collation.html) do say "By design, ICU will accept almost any string as a locale name and match it to the closest locale it can provide, using the fallback procedure described in its documentation."   But `en_US.UTF8` is a libc collation:
```
postgres=# \dOS+
...
pg_catalog | en_US                  | en_US.utf8       | en_US.utf8       | libc     | yes            | 
pg_catalog | en_US.utf8             | en_US.utf8       | en_US.utf8       | libc     | yes            | 
```
also, on the same DB that gave the error …
=> Test for collation by behavior, rather than name

changelog/bug-1645032.md, services/web-server/src/login/strategies/mozilla-auth0.js, services/web-server/test/login_strategies_mozilla_auth0_test.js
Bugzilla Bug: [1645032](https://bugzilla.mozilla.org/show_bug.cgi?id=1645032)
I think the issue here was that we are using `profile.nickname` which is not even a documented thing.
=> Drop support for suffixing user identities with github username..

package.json
This should help us keep up with the number of updates required (we've
fallen behind) without getting PRs filed at all hours, and without ever
opening more than 9 at a time.
=> Run renovate daily

changelog/CqpwVrWxR-6Yct2DpZO6gw.md, package.json, yarn.lock
This drops a bunch of other deps, too, largely from the `winston` logging framework.
=> upgrade sentry-api to drop lodash-3 requirement

changelog/issue-3224.md, infrastructure/tooling/src/smoketest/checks/createClient.js, infrastructure/tooling/src/smoketest/checks/ping.js, infrastructure/tooling/src/smoketest/checks/role.js, infrastructure/tooling/src/smoketest/index.js, infrastructure/tooling/src/smoketest/util.js
As the comments in the diff indicate, auth doesn't guarantee you can use a role or client immediately on changing it -- there's a small delay while all the web processes get notified via pulse and update their resolvers.  So, retry enough to last that out.
Github Bug/Issue: Fixes #3224
=> Retry auth failures in smoketests

changelog/issue-3184.md, libraries/postgres/README.md, libraries/postgres/src/index.js, libraries/postgres/src/util.js, libraries/postgres/test/util_test.js, services/hooks/src/api.js, services/hooks/src/utils.js, services/worker-manager/src/api.js, services/worker-manager/src/data.js, services/worker-manager/src/provisioner.js, services/worker-manager/src/worker-scanner.js, services/worker-manager/test/expiration_test.js, services/worker-manager/test/helper.js, services/worker-manager/test/provider_aws_test.js, services/worker-manager/test/provider_azure_test.js, services/worker-manager/test/provider_google_test.js, services/worker-manager/test/provider_test.js, services/worker-manager/test/worker_test.js
This function calls paginated DB functions and translates the results
into an async iterator of rows.
Github Bug/Issue: Fixes #3184
I changed most custom pagination functions to use this.  The one I didn't change is the function scanning for expiration of artifacts, which has a workaround for #3278 in place.  So let's wait until that issue is fixed to change that function.
=> Introduce `paginatedIterator` and use it

changelog/issue-3170.md, libraries/postgres/src/Database.js
=> Fail early on upgrade if a --db-version does not exist

changelog/UqMeg67CQvmStJVJND1veg.md, services/hooks/src/main.js, services/web-server/src/main.js
This was missed for these two services.  @imbstack just pointed out I missed it in #3234, so I'm confident it will be remembered in the secrets service :)
This causes a minor issue for v35.0.0, which included the github access tokens table.  It won't start without DB_CRYPTO_KEYS set.  I updated the relase notes in the GitHub release appropriately.  It was a major release, so that's probably enough.
=> pass azureCryptoKeys to db setup

changelog/issue-3176.md, infrastructure/tooling/src/build/tasks/livelog.js
Github Bug/Issue: Fixes #3176
I built this locally and ran it.  The binary is statically linked, and doesn't execute anything, so it doesn't need any other files in the image.
=> Build livelog image from scratch

changelog/GQ7vBictTQK3Ti_GiH3M1A.md, services/worker-manager/src/providers/aws.js, services/worker-manager/src/providers/azure.js, services/worker-manager/src/providers/google.js
https://sentry.prod.mozaws.net/operations/taskcluster-cloudops-stage/issues/8766602/
Fixes #3054 (which was already fixed??)
=> Handle the case where a worker pool has no launch configs

changelog/issue-2992.md, ui/src/components/TaskRunsCard/index.jsx
`public/logs/live_backing.log` is reachable via `https://community.taskcluster-artifacts.net/a3TRMvMERZuRwCGHb9dpcA/0/public/logs/live_backing.log` but in order to access a private log, it looks like the artifact name is encoded rather than nested (e.g., `../debug-logs%2Flivelog-docker-push.log?bewit=...` rather than `.../debug-logs/livelog-docker-push.log?bewit=...`)?
The log viewer grabs the URL to render from the UI which means the URL is encoded (e.g., `https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2Fa3TRMvMERZuRwCGHb9dpcA%2Fruns%2F0%2Fartifacts%2Fdebug-logs%2Ftaskcluster-proxy-docker-build.log%3Fbewit%3D...`). Upon decoding it, `%2F` becomes `/` so then it will try to access the artifact `debug-logs/taskcluster-proxy-docker-build.log` which doesn't  exist. …
=> Private artifact links in UI

changelog/issue-3342.md, infrastructure/tooling/src/build/tasks/taskcluster-proxy.js
Docker-worker already expects this tag.  Generic-worker uses the
executable.
Github Bug/Issue: Fixes #3342
=> Build taskcluster/taskcluster-proxy with a v in the tag

services/auth/test/helper.js
I mixed this up when rotating credentials, so let's write it down somewhere.
=> add comment about the tests for auth's gcp support

changelog/issue-3483.md, workers/docker-worker/src/lib/task.js
This rarely happens, and is unlikely to succeed even with this fix when it does happen, but it was an easy fix anyway.
Github Bug/Issue: Fixes #3483
=> Pass an actual reason code to task.abort()

clients/client-web/yarn.lock, ui/yarn.lock
Note that this is only used for mocha, so not a big risk anyway.
=> Upgrade yargs-parser for GHSA-p9pc-299p-vxgp

changelog/issue-3502.md, services/auth/src/scoperesolver.js
If my hunch is correct that `client.scopes` is being set to a non-array and then returned from the clientLoader, then this will show what type it has at that point.  If we see schema-validation error again without this assertion failing, then my hunch is incorrect.  Divide and conquer!
Github Bug/Issue: Refs #3502
=> #3502 - get more data when scopes is not an array

infrastructure/tooling/src/generate/generators/yarn-minify.js, workers/docker-worker/package.json, workers/docker-worker/yarn.lock
I cherry-picked a few non-minified requirements to remove, as a way of chipping away at the list.
=> Minify some of the docker-worker dependencies

dev-docs/README.md
Observed that the Best Practices link in the dev-docs README.md was landing on a 404 page. 
Made a slight edit so that it now lands in the best-practices directory.
=> Fix broken link in dev-docs README.md

changelog/issue-3561.md, services/worker-manager/src/providers/static.js, services/worker-manager/test/provider_static_test.js
Sentry issue: [9644729](https://sentry.prod.mozaws.net/operations/taskcluster-community/issues/9644729/?referrer=alert_email)
It looks like the request body gets passed in to the provider updateWorker call as:
```js
worker = await provider.updateWorker({
workerPool,
worker,
input: {
capacity: 1,
...req.body,
},    
}); 
```
So the request body is included in `input`.
Then in the static provider:
```js
async updateWorker({ workerPool, worker, input }) {
await worker.update(this.db, worker => {
worker.expires = input.expires;
worker.capacity = input.capacity;
worker.providerData = { 
...worker.providerData,
staticSecret: input.providerData.staticSecret,
};  
}); 
return worker;
}
```
So it looks for `input.providerData.staticSecret` but that should be `input.providerInfo.staticSecret` …
=> fix workermanager.updateWorker for static provider with static secret

changelog/Lb224mAkRF28OgKo1sZ36Q.md, tools/livelog/main.go, workers/generic-worker/artifacts.go
(based on an issue found by GitHub's code-scanning)
=> Remove unnecessary logging of HTTP headers in livelog

changelog/issue-3358.md, services/github/src/api.js
The sitewide content-security-policy evalutes to `style-source: 'none'`,
but these icons set their colors with bits like `style="fill:#333333"`.
This is harmless and the content is static, so the fix is to adjust the
CSP to allow inline styles.
Github Bug/Issue: Fixes #3358
=> Fix rendering of tc-github badges.

changelog/LFAj1M-IT9-jSqryiOxE-Q.md, libraries/postgres/src/Database.js
The sorting is not "case-insensitive", as that would only be a partial
order.  The important thing for sorting slugids is that different cases
of the same letter be sorted together, which is not what the C collation
does.
=> Fix error message when postgres collation is bad

changelog/issue-3599.md, libraries/postgres/src/Database.js
This reverts commit 0404810a36f2a3dddd0d56780a229415e589a77f (PR 3599).
See https://github.com/taskcluster/taskcluster/issues/3598#issuecomment-701315161 for context.
=> Revert "Issue 3598 - fix db collation check"

package.json, yarn.lock
https://github.com/googleapis/google-api-nodejs-client/releases is not exactly helpful regarding what "breaking" changes have occurred.  @imbstack do you have an idea about how best to test this upgrade?
=> Upgrade googleapis to latest, to remove dependency on vulnerable node-forge

package.json
See https://docs.renovatebot.com/configuration-options/#dependencydashboard
Per advice in https://github.com/renovatebot/config-help/issues/912.
=> enable the renovate dependencyDashboard

changelog/issue-3639.md, services/queue/src/api.js, services/queue/test/createtask_test.js
This change prefetches an initial empty status which is used in taskDefined messages. This means that taskDefined messages always has a state of 'unscheduled'.
Github Bug/Issue: Fixes #3639
This ended up being slightly more wiry than I hoped because
=> Issue 3639 - Make sure taskDefined messages are marked unscheduled

libraries/api/test/logging_test.js
After poking at this for a while I believe this is actually a result of the logging that we're asserting here happens _after_ the response is sent. This means that the `await` on the response isn't actually ensuring that the log has been written. This poll felt like the easiest way to fix it. 
The test is still failing but in a different and more fixable way now. Feel free to either land this or a better fix. I can help more tomorrow on reviewing and determining if this test should actually pass or fail, etc
=> Fix timing issue in auth logging tests

changelog/issue-3659.md, services/notify/src/handler.js
Github Bug/Issue: Fixes #3659 
I suspect this is a hangover from the old taskcluster.net URLs but this should correct links to the task group in Email & Slack notifications. (I'm just ashamed I didn't notice the link was broken during testing.)
Should I add a test for this? I could technically scrape the Slack or Email outputs from the tests to see if the URL appears.
=> Issue 3659 - Notification Task Group URL correction

package.json
Per advice from Rhys, this lets renovate run for 8 hours every day.  The [dependency dashboard](https://github.com/taskcluster/taskcluster/issues/3630) shows that we're missing lots of upgrades because they are not scheduled.
=> run renovate during more hours

changelog/issue-3640.md, services/notify/src/handler.js, services/notify/test/handler_test.js
This change adds support for all task lifecycle states to notify. It also creates two new pseudostates: 'on-resolved' to replace 'on-any' and 'on-transition' which covers all states.
'on-any' is now deprecated.
Github Bug/Issue: Fixes #3640
=> Issue 3640 - More notify states

changelog/issue-3521.md, tools/taskcluster-proxy/authorization_test.go, tools/taskcluster-proxy/routes.go, workers/docker-worker/src/lib/features/taskcluster_proxy.js
Github Bug/Issue: Refs #3521.
Once this is done, we can park #3521 until we want to remove this support.
=> Restore existing tc-proxy behavior of adding content-type header when it is missing

changelog/DOrI5ptoQYG7I2dsMK_ndA.md, infrastructure/tooling/src/utils/docker.js
I missed testing this when looking for `got` invocations that changed in the major version upgrade.
=> (hotfix) fix got invocation in image-build process

changelog/issue-3463.md, services/index/README.md, services/index/src/helpers.js
In ``insertTask``, when a task is asynchronously created between loading it and creating it, a ``UNIQUE_VIOLATION`` is raised. Catch the error, load the task, and proceed to check if it needs updating.
I borrowed the error-handling technique from ``ensureNamespace`` later in ``helper.js``. It appears that this and other database error handlers are untested, so I did not add tests.
For the changelog entry, I guessed what the API caller would see when the bug was triggered. Please let me know if you have a better guess or know what the response would be.
Github Bug/Issue: Fixes #3463
=> Handle indexed tasks created during insertTask

clients/client-web/package.json, clients/client-web/yarn.lock
`rm yarn.lock && yarn` -- just for client-web, which doesn't have a lot of dependencies and is pretty simple and well-tested.
This addresses the old minimist version, which was deeply buried in a karma dependency.  And it will hopefully save some renovate PRs.
=> update all deps of client-web

changelog/issue-3704.md, services/auth/src/static-scopes.json, services/web-server/scopes.yml, services/web-server/src/login/User.js, services/web-server/test/login_strategies_github_test.js, services/web-server/test/login_strategies_mozilla_auth0_test.js
As described in #3704, the anonymous scopes are implicitly included everywhere, so there's no need to do so explicitly.
=> Revert web server anonymous scopes

changelog/issue-3730.md, clients/client-py/setup.py
This uses environment markers to specify packages specific to python
versions, rather than conditionals in setup.py.  Suggested by @ahal.
Fixes #3730.
=> Use environment markers for client-py

changelog/bug-1609067.md, tools/worker-runner/perms/perms_windows.go
Bugzilla Bug: [1609067](https://bugzilla.mozilla.org/show_bug.cgi?id=1609067)
=> Include filename in file permissions errors from worker-runner

changelog/issue-3721.md, clients/client-go/tcindex/tcindex.go, clients/client-py/taskcluster/generated/aio/index.py, clients/client-py/taskcluster/generated/index.py, clients/client-shell/apis/services.go, clients/client/src/apis.js, generated/references.json, services/index/src/api.js, ui/docs/reference/core/index/README.mdx
Github Bug/Issue: Fixes #3721 
I have not done yarn generate. ( there is some problem with OS: ubuntu installation. I am trying to set up the environment from the past 3 days; hoping it to resolve soon)
=> Slashes not allowed in index paths documentation addition to  api.js and index/README.mdx

changelog/W3n9_fEuQ5e1rxWHfTqxyg.md, services/web-server/src/PulseEngine/index.js
This fixes an (apparently harmless?) error that appears in the UI when
viewing the TaskGroup page, as noted in #3831.
=> Set up PulseEngine before setting onConnected hook

changelog/KP27G54ETjCRPvXdlgfnAQ.md, infrastructure/tooling/src/changelog/index.js, infrastructure/tooling/src/main.js
..since I keep typing this, now that we're tracking things on GitHub and not Bugzilla.
=> Allow --no-issue in yarn changelog

changelog/issue-3843.md, services/auth/src/signaturevalidator.js, services/auth/test/signaturevalidator_test.js, workers/docker-worker/src/lib/docker/indexed_image.js, workers/docker-worker/test/image_manager_test.js
Basic summary:
1.  d-w was using its own creds instead of the task's creds to talk to index service for indexed images. That wasn't a problem before rfc 165 since it was public before.
2. We need to expand scopes _before_ we limit them with `authorizedScopes` because a client that is granted a scope that is in `authorizedScopes` by virtue of it being in `assume:anonymous` must have it at that time. Not doing this results in the error seen in the linked bug. I believe to keep the behavior we've decided for rfc 165 we actually have to apply `assume:anonymous` and expand scopes _again_ after limiting to `authorizedScopes` because otherwise anything limited in that fashion will not have those scopes. This is a bit of a more confusing situation however, happy to debate/change/etc.
Github …
=> Update d-w and scope resolution

lerna.json
This seems to be distracting renovate, and now that we've imported everything I think we don't actually use lerna anymore.  Please yell if I'm wrong!
=> remove lerna.json

changelog/issue-3865.md, infrastructure/tooling/src/build/tasks/livelog.js, tools/livelog/main.go
- Use busybox for livelog image in order to get /tmp back
- Support TLS in livelog again
This feels like a sorta hacky way to make it work but the whole thing is a hack so whatever.
Github Bug/Issue: Fixes #3865
=> Fix Livelog TLS Support

changelog/issue-3836.md, ui/src/App/index.jsx, ui/src/auth/AuthController.js
The previous solution was an attempt to renew credentials on a schedule,
synchronized across tabs.  It had some pretty bad race conditions, one
of which was between page-load and renewal when the existing creds had
expired.
This switches to a simpler model, where credentials are fetched if
necessary (if they're expired) before making a GraphQL query.
Github Bug/Issue: Fixes #3836
=> Rewrite browser-side auth to fetch credentials on-demand

changelog/issue-3874.md, services/auth/src/static-scopes.json, services/notify/scopes.yml
Github Bug/Issue: Fixes #3874
This adds `queue:get-task:*` to the notify service, which lets the handler run without `get-task` being public. I've tested that this is the only required scope by adding just this to anonymous on our testing TC.
=> Add get-task scope to notify service

changelog/issue-3837.md, ui/src/components/ConnectionDataTable/index.jsx
This modifies the handleHeaderClick to return the header, just like
DataTable does.  Returning `target.id` didn't work reliably because the
potential event targets do not all have the correct id.
Github Bug/Issue: Fixes #3837.
=> Fix sorting in ConnectionDataTable

changelog/issue-3873.md, ui/src/components/WorkerTypesTable/index.jsx
This was caused by the upgrade to change-case, when functions like
`camelCase` stopped returning `''` when givien `undefined`, and started
failing instead.  I spotted most cases where this was an issue but
missed this one.
Github Bug/Issue: Fixes #3873
=> Fix failure in /provisioners when no sortBy

changelog/issue-3899.md, workers/docker-worker/config.yml
=> add .lz4 to the list of extensions docker-worker will not try to compress

changelog/issue-3908.md, services/notify/src/handler.js
=> Issue 3908 - make groupHref in the notify handler use task.taskGroupId

changelog/issue-3903.md, services/auth/src/signaturevalidator.js, services/auth/test/signaturevalidator_test.js
This is pretty much a return to how things
worked before rfc165 here. We now expand no matter what before checking
`authorizedScopes`.
Github Bug/Issue: Fixes #3903
=> Expand scopes in between pulling them from cert and checking authorizedScopes

changelog/issue-3901.md, services/web-server/src/loaders/tasks.js, services/web-server/src/utils/fetch.js
Github Bug/Issue: Fixes #3901
This issue was caused by `node-fetch` passing headers to further redirects, including the eventual S3 signed URL. In particular Taskcluster's `fetch()` sets `Content-Type` by default, which is a header which must be included in the signature.
=> Issue 3901 - fix forbidden error when using actions with public artifact URL signing

package.json
We just updated to v64 and v65 is out already..
=> Only update `googleapis` once a week

changelog/issue-3867.md, services/github/src/handlers.js, services/github/test/handler_test.js, ui/docs/reference/integrations/github/checks.mdx
I believe this should solve this issue in the most direct way possible.
What we're doing here is giving the queue client in tc-gh's handler creds so that it
can use its own scopes and then limiting it to only a task's scopes when it is
acting on behalf of a task in a way that the task can alter what it does.
This should not break anything in community/firefoxci because those have `anonymous`
roles and so it will work without this fix even.
Github Bug/Issue: Fixes #3867
=> Give tc-gh handler queue client some scopes

changelog/issue-3578-1.md, clients/client-go/tcqueue/tcqueue.go, clients/client-go/tcqueue/types.go, clients/client-py/taskcluster/generated/aio/queue.py, clients/client-py/taskcluster/generated/queue.py, clients/client-shell/apis/services.go, clients/client-web/src/clients/Queue.js, clients/client/src/apis.js, generated/references.json, services/queue/schemas/constants.yml, services/queue/schemas/v1/list-taskqueues-response.yml, services/queue/schemas/v1/taskqueue-response.yml, services/queue/src/api.js, services/queue/test/workerinfo_test.js
Github Bug/Issue: Fixes #3578 (part 2)
Follow-up to #3641 to add `listTaskQueues` and `getTaskQueue` methods to the queue service API, mapping to the future hierarchy of using taskQueueId in place of the pair provisionerId / workerType.
@djmitche Hopefully I understood this correctly :smiley:.
=> Add listTaskQueues and getTaskQueue to queue service api

changelog/issue-3899.md, workers/docker-worker/src/lib/util/artifact_download.js, workers/docker-worker/test/fixtures/image_artifacts.js, workers/docker-worker/test/integration/pull_image_test.js
Github Bug/Issue: Fixes #3899.
=> docker-worker: Un-gzip images with gzip content-encoding

changelog/issue-3954.md, workers/docker-worker/test/images/vnc-test/Dockerfile
Docker-hub deleted the older version, and installs on alpine-3.2 no
longer work.
Github Bug/Issue: Fixes #3954
=> Update vnc-test image to use a newer alpine

changelog/RD53QBBsRLiaWl_XfNFLag.md, workers/docker-worker/src/features/interactive.js
This addresses a failure seen in tests:
https://community-tc.services.mozilla.com/tasks/eaeauS32Rge3V1QvBF1CdQ
```
error: "Could not kill states properly. Error: Error: Error calling 'killed' for dockerInteractive : TypeError: Cannot read property 'httpServ' of undefined\n" +
'    at WebsocketServer.killed (/worker/src/features/interactive.js:382:18)\n' +
'    at /worker/src/states.js:50:28\n' +
'    at Array.map (<anonymous>)\n' +
'    at States._invoke (/worker/src/states.js:49:13)\n' +
'    at States.killed (/worker/src/states.js:158:17)\n' +
'    at Task.abortRun (/worker/src/task.js:562:25)\n' +
'    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
'    at Task.run (/worker/src/task.js:934:14)\n' +
'    at Task.start (/worker/src/task.js:758:17)\n' +
'    at …
```
=> Fix early killing of interactive feature

changelog/issue-3982.md, services/github/src/api.js, services/github/test/github-auth.js, ui/src/views/Quickstart/index.jsx
This replaces the deprecated pagination functions.  The new function is rather hard to mock correctly, so I've double-checked this in development.  I also tested the UI change by hand.
Github Bug/Issue: Fixes #3982
=> Fix use of deprecated github pagination functions
