taskcluster/taskcluster

.taskcluster.yml

Start using checks api for our .tc.yml tests

---

libraries/scopes/src/expressions.js

This was r+'d in https://github.com/taskcluster/taskcluster-lib-scopes/pull/26 -- should we just land it?

Use hasOwnProperty as it is faster and more sane

---

infrastructure/builder/docs/building-taskcluster.md

A couple of broken links I stumbled on...

Fix broken links in taskcluster building docs

---

services/auth/src/azure.js
services/auth/test/azure_test.js

I think later we should make sure we clean up the resources we leave
behind but let's get things working for now.

Bug 1518896 - Fix container listing test

---

services/purge-cache/test/helper.js

This should fix up another flake.

Bug 1417662: fix flaky purge-cache tests

---

README.md

Add some tc-gh goodness to README

---

package.json
services/web-server/.neutrinorc.js
services/web-server/Procfile
services/web-server/package.json
services/web-server/src/PulseEngine/index.js
services/web-server/src/graphql/Tasks.graphql
services/web-server/src/resolvers/Tasks.js
services/web-server/src/servers/createApp.js
yarn.lock

Review after this one is merged https://github.com/taskcluster/taskcluster/pull/74

Add web-server to monorepo: Fix linting

---

services/treeherder/Procfile
services/web-server/Procfile

This will make http://bugzil.la/1516347 a lot easier..

All services should have a write-docs target

---

libraries/client/src/apis.js

I think this api will also be required while fixing Bug 1520857 (tc web).

Add new api listLastFires in client

---

libraries/pulse/README.md
libraries/pulse/src/consumer.js

Reverts taskcluster/taskcluster#119

Revert "Expire queues after 4 days of not being used"

---

netlify.toml
ui/yarn.lock

`yarn.lock` requires to be refreshed after https://github.com/taskcluster/taskcluster/pull/126#discussion_r250193404.

[UI] Update yarn.lock

---

ui/package.json
ui/yarn.lock

Bugzilla Bug: [1522913](https://bugzilla.mozilla.org/show_bug.cgi?id=1522913)

[Bug 1522913] Update "Extra" section when changing taskIds

---

services/auth/test/trie_test.js

This brings the auth tests down to 20 seconds total.

Bug 1521798 - run auth tests more quickly

---

services/hooks/docs/firing-hooks.md

Bugzilla Bug: [1522888](https://bugzilla.mozilla.org/show_bug.cgi?id=1522888)

Bug 1522888 - add docs of pulse-message json-e context

---

ui/src/components/AwsProvisionerErrorsTable/index.jsx

Bugzilla Bug: [1524942](https://bugzilla.mozilla.org/show_bug.cgi?id=1524942)

[Bug 1524942] [UI] Add default sort to AWS provisioning recent errors

---

libraries/api/src/middleware/express-error.js
services/hooks/schemas/v1/trigger-hook-response.yml
services/hooks/schemas/v1/trigger-response.yml
services/hooks/src/taskcreator.js
services/hooks/src/v1.js
services/hooks/test/api_test.js
services/hooks/test/helper.js

Bugzilla Bug: [1522891](https://bugzilla.mozilla.org/show_bug.cgi?id=1522891)

Bug 1522891 - update triggerHook output to allow no task creation

---

.taskcluster.yml
infrastructure/browser-test/README.md
netlify.toml
package.json
ui/package.json

Bugzilla Bug: [1526607](https://bugzilla.mozilla.org/show_bug.cgi?id=1526607)

Switch to Node 10.15.1

---

services/login/src/handlers/mozilla-auth0.js
services/login/test/handlers_mozilla_auth0_test.js

Bugzilla Bug: [1518680](https://bugzilla.mozilla.org/show_bug.cgi?id=1518680)
This is not super-needed because the service is working just fine :) I did this in my free time because when I was working with `login` I found it difficult to read (please keep in mind that I am a very primitive creature, only emojis are easy to read for me and I am confused very easily). The main objective here was reorginizing the code to reduce the amount of functions in the auth0 module; the logic itself is preserved exactly as it was (I hope). The tests suffered from me extensively as well.
`checkIfActive` boolean is worth a honorary mention, because I noticed in the code when we get `user` from `clientId` we don't check if the user is active, and when we get it from request - we do. I wonder why is that. …

Refactor 🤪

---

infrastructure/builder/taskcluster-spec/build.yml
infrastructure/terraform/ingress.yaml
infrastructure/terraform/web-server-service.tf
infrastructure/terraform/web-ui.tf

Bugzilla Bug: [1522924](https://bugzilla.mozilla.org/show_bug.cgi?id=1522924)

Web server on kube

---

generated/docs/hooks/schemas/v1/bindings.json
generated/references.json
services/hooks/schemas/v1/bindings.yml
services/hooks/src/v1.js
services/hooks/test/api_test.js

Bugzilla Bug: [1527183](https://bugzilla.mozilla.org/show_bug.cgi?id=1527183)

Bug 1527183 - fix schema for bindings

---

ui/src/components/HookForm/index.jsx
ui/src/components/Snackbar/index.jsx
ui/src/views/Hooks/ViewHook/index.jsx

I have compared the two hook objects using the equals method and disabled the save button accordingly. It would be of great help if you could review the code and provide some direction further. Thanks.
Resolves https://github.com/taskcluster/taskcluster/issues/227.

Hooks: Disable save button unless some values have changed #390

---

services/web-server/src/index.js

Just one more nit I forgot in #228

Catch one more case of loader update

---

ui/package.json
ui/yarn.lock

https://www.youtube.com/watch?v=Fw66W4stDhI

Remove husky from tc-ui

---

services/hooks/src/listeners.js
services/hooks/test/api_test.js
services/hooks/test/listeners_test.js

Bugzilla Bug: [1527428](https://bugzilla.mozilla.org/show_bug.cgi?id=1527428)

Bug 1527428 - fix removal of listeners, and add tests

---

libraries/loader/src/loader.js
services/web-server/src/index.js

I think this should be the last time we need to fix this.

Fix web-server usage of loader again

---

services/github/src/handlers.js

Bugzilla Bug: [1446768](https://bugzilla.mozilla.org/show_bug.cgi?id=1446768)
This pr deals with the second and third part. I didn't understand how I can implement the flag variable(which can disable this bug completely) in taskcluster.yml in the master branch.
@owlishDeveloper can you describe me, how we implemented the flag for allowPullRequests.

Only post "No taskcluster jobs.." to a PR once part2 and part3

---

ui/src/components/TaskDetailsCard/index.jsx
ui/src/theme.js

Fixes https://github.com/taskcluster/taskcluster/issues/250.

Make text in routes & scopes visible

---

libraries/pulse/src/consumer.js

Bugzilla Bug: [1528249](https://bugzilla.mozilla.org/show_bug.cgi?id=1528249)

Bug 1528249 - only stop listening for connections when consumer stops

---

clients/client-web/src/clients/Notify.js
clients/client/src/apis.js
generated/docs/notify/references/api.json
generated/docs/notify/schemas/v1/notification-address-list.json
generated/docs/notify/schemas/v1/notification-address.json
generated/references.json

This got missed in #127 due to #244 not being merged to that branch.

(hotfix) run yarn generate

---

infrastructure/terraform/auth-service.tf
infrastructure/terraform/built-in-workers-service.tf

Bugzilla Bug: [1522307](https://bugzilla.mozilla.org/show_bug.cgi?id=1522307)

Bug 1522307 - deploy built-in-workers service

---

ui/src/components/SpeedDial/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/171.

[UI] Fix: touch screen users not being able to open menu

---

ui/src/views/Tasks/NoTask/index.jsx
ui/src/views/Tasks/NoTaskGroup/index.jsx
ui/src/views/Tasks/TaskGroup/index.jsx
ui/src/views/Tasks/ViewTask/index.jsx

Fixes #208 
@helfi92 can you merge this? thanks!

Adding missing view titles

---

ui/package.json
ui/src/components/TaskGroupTable/index.jsx
ui/src/views/Tasks/TaskGroup/index.jsx

Fixes #247.
Fixes https://github.com/taskcluster/taskcluster/issues/231.

[UI] Task group list enhancement

---

ui/package.json
ui/src/views/Hooks/ListHooks/index.jsx
ui/yarn.lock

Fixes https://github.com/taskcluster/taskcluster/issues/220.

[UI] Allow opening hooks in a new tab

---

ui/package.json
ui/src/views/Hooks/ListHooks/index.jsx
ui/yarn.lock

Fixes https://github.com/taskcluster/taskcluster/issues/219.

[UI] Hook search matches

---

ui/src/utils/db.js
ui/src/views/Tasks/CreateTask/index.jsx

Fixes #164
@helfi92 can you review my initial commit?

Showing recently added task in create task

---

ui/src/components/Dashboard/index.jsx
ui/src/components/NotFound/index.jsx

Regarding issue #225 
@helfi92 can you make some comment on this. The only problem is that when I am making `drawerOpen true`  I am able to show the drawer in desktop mode but I am not able to remove it when I am clicking on any sidebar list. can you take a look or suggest me anything after looking this?

Always allow collapsing the drawer

---

ui/src/views/Secrets/ViewSecrets/index.jsx
ui/src/views/Secrets/ViewSecrets/secrets.graphql

Added Search bar to Secret where you can filter required secrets. 
This closes #175

Add Search feature to Secrets

---

ui/src/components/Dashboard/index.jsx
ui/src/theme.js

Fixes https://github.com/taskcluster/taskcluster/issues/289.

[UI] Add maximum page width

---

infrastructure/terraform/ingress.yaml
infrastructure/terraform/modules/deployment/deployment.yaml
infrastructure/terraform/taskcluster.tf.json
infrastructure/terraform/web-ui.tf

Bugzilla Bug: [1525180](https://bugzilla.mozilla.org/show_bug.cgi?id=1525180)

Change terraform to deploy ui from the monoimage

---

ui/src/components/SignInDialog/index.jsx

[UI] Remove redundant sign-in chooser

---

clients/client-web/.neutrinorc.js
clients/client-web/README.md

Relates to https://github.com/taskcluster/taskcluster/issues/285.

Add crypto-js to webpack's externals

---

clients/client-web/package.json

CHANGELOG: https://github.com/taskcluster/taskcluster/commit/6f881ee1fc0ac547189cd2982cea1649f910f159

Bump client-web version

---

ui/package.json
ui/src/components/Helmet/index.jsx
ui/src/theme.js
ui/src/utils/db.js
ui/src/utils/formatTaskMutation.js
ui/src/utils/prop-types.js
ui/src/utils/upperSnakeCase.js
ui/src/views/Tasks/CreateTask/index.jsx
ui/src/views/Tasks/ViewTask/index.jsx
ui/src/views/Tasks/submitTaskAction.js
ui/yarn.lock

Fixes https://github.com/taskcluster/taskcluster/issues/300.

[UI] Fix task definition mutation validation

---

ui/src/components/Dashboard/index.jsx
ui/src/views/Documentation/PageMeta.jsx

Resolves https://github.com/taskcluster/taskcluster/issues/296.

[UI] Line length

---

ui/src/views/Tasks/TaskGroup/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/317.

[UI] Add default value for the search component in task group view

---

clients/client-web/src/clients/Hooks.js
clients/client/src/apis.js
generated/references.json
services/hooks/src/data.js
services/hooks/src/v1.js
services/hooks/test/api_test.js
services/hooks/test/scheduler_test.js
ui/docs/generated/hooks/references/api.json
ui/docs/generated/references.json

Bugzilla Bug: [1530849](https://bugzilla.mozilla.org/show_bug.cgi?id=1530849)

Bug 1530849 - make getHookStatus return last-fire information again

---

ui/src/components/Dashboard/DocsSidebarList.jsx

Indented the code using `yarn lint --fix`

Bug #286 [UI] Reopen the section menu when clicking "next"

---

libraries/monitor/package.json
libraries/monitor/src/index.js
libraries/monitor/src/logger.js
libraries/monitor/src/monitor.js
libraries/monitor/test/logger_test.js
services/auth/config.yml
services/built-in-workers/config.yml
services/github/config.yml
services/hooks/config.yml
services/index/config.yml
services/login/config.yml
services/notify/config.yml
services/purge-cache/config.yml
services/queue/config.yml
services/secrets/config.yml
services/treeherder/config.yml
services/web-server/config.yml
services/worker-manager/config.yml
yarn.lock

Now disabling just disables process metrics collection and catching unhandled errors. Everything else should work like normal.
Bugzilla Bug: [1531121](https://bugzilla.mozilla.org/show_bug.cgi?id=1531121)

[bug 1531121] Simplify what disabling monitoring does

---

libraries/loader/README.md
libraries/loader/src/loader.js
libraries/loader/test/loader_tests.js
services/auth/src/main.js
services/built-in-workers/src/main.js
services/github/src/main.js
services/hooks/src/main.js
services/index/src/main.js
services/login/src/main.js
services/notify/src/main.js
services/purge-cache/src/main.js
services/queue/src/main.js
services/secrets/src/main.js
services/treeherder/src/main.js
services/web-server/src/index.js
services/worker-manager/lib/main.js

Bugzilla Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1527969
`crashOnError()` method added to the `loader.js` file 
ran the test locally !
test result : https://gist.github.com/sudipt1999/a3180149f259b1139e88f18172b957c4
kindly cross check for update 
Thank You

Bug 1527969  Add function to lib-loader that is for using when file is executed

---

infrastructure/terraform/auth-service.tf

Bugzilla Bug: [1532489](https://bugzilla.mozilla.org/show_bug.cgi?id=1532489)

Add Check-related Azure scopes to the terraform for Kube deployments

---

services/queue/src/claimresolver.js
services/queue/src/deadlineresolver.js
services/queue/src/dependencyresolver.js
services/queue/src/main.js
services/queue/test/helper.js

This is missing whatever is needed to start and stop the pollers in the
queue unit tests because I cannot make sense of how polling is managed
in the tests.
Bugzilla Bug: [1527583](https://bugzilla.mozilla.org/show_bug.cgi?id=1527583)

Bug 1527583 - Queue doesn't take jobs from "unscheduled" to "pending"

---

ui/src/views/Quickstart/index.jsx

Bugzilla Bug: [1515673](https://bugzilla.mozilla.org/show_bug.cgi?id=1515673)

Bug 1515673 - YML changed for v1 in QuickStart

---

infrastructure/terraform/auth-service.tf
infrastructure/terraform/index-service.tf
infrastructure/terraform/variables.tf

Related: taskcluster/taskcluster-mozilla-terraform#45
Bugzilla Bug: [1533493](https://bugzilla.mozilla.org/show_bug.cgi?id=1533493)

[Bug 1533493] Remove old auditlogs terraform

---

.taskcluster.yml

Bugzilla Bug: [1532469](https://bugzilla.mozilla.org/show_bug.cgi?id=1532469)

Bug 1532469 - use a yarn cache

---

libraries/monitor/src/index.js
libraries/monitor/src/logger.js
package.json
services/auth/package.json
services/built-in-workers/package.json
services/github/package.json
services/hooks/package.json
services/index/package.json
services/login/package.json
services/notify/package.json
services/purge-cache/package.json
services/queue/package.json
services/secrets/package.json
services/treeherder/package.json
services/worker-manager/package.json

I've tested this on my dev instance and it seems to work!
Reference: https://cloud.google.com/error-reporting/docs/formatting-error-messages

Update how we do git version stuff

---

services/hooks/config.yml
services/hooks/src/v1.js
services/hooks/test/api_test.js

This suits bastien's needs, in particluar.
/cc @ydidwania

Allow listening to the queue's task-completed exchange

---

libraries/testing/README.md
libraries/testing/src/testing.js
libraries/testing/src/with-entity.js
services/auth/config.yml
services/auth/test/azure_test.js
services/auth/test/helper.js
services/github/test/helper.js
services/hooks/test/api_test.js
services/hooks/test/expires_test.js
services/hooks/test/helper.js
services/hooks/test/listeners_test.js
services/hooks/test/schedule_hooks_test.js
services/hooks/test/scheduler_test.js
services/hooks/test/taskcreator_test.js
services/index/test/helper.js
services/notify/test/api_test.js
services/notify/test/helper.js
services/purge-cache/test/helper.js
services/queue/src/main.js
services/queue/test/helper.js
services/secrets/test/api_test.js
services/secrets/test/helper.js

Bugzilla Bug: [1533937](https://bugzilla.mozilla.org/show_bug.cgi?id=1533937)

Bug 1533937 - centralize azure table setup in testing

---

services/web-server/src/index.js

https://github.com/taskcluster/taskcluster/commit/cea855021d349d20892bc554d1ee3b9ae7c9c269 overwrote the fix from https://github.com/taskcluster/taskcluster/commit/c8fa923a5be6d11c6b1d3d126d649406c50da348.

Fix: web-server usage of loader

---

ui/src/components/TaskGroupProgress/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/361.

[UI] Enhance task group progress

---

.github/ISSUE_TEMPLATE/bug_report.md

Based on discussion in this week's team meeting.  I tried to be brief, rather than enumerating a long decision tree for figuring out where to post something.

Point bug-filers to Bugzilla

---

services/worker-manager/README.md
ui/docs/generated/worker-manager/README.md

Add WIP note to Worker Manager's README

---

generated/references.json
ui/docs/generated/auth/schemas/v1/list-roles-response.json
ui/docs/generated/references.json
ui/src/views/Documentation/PageMeta.jsx
ui/src/views/Documentation/components/Anchor/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/395.

[UI] Add proper theming to "Next Steps" section in docs

---

libraries/testing/src/with-entity.js
services/auth/test/helper.js

That's at least three fewer of my dumb mistakes in the codebase.  A drop in the bucket..

Fix auth with entities

---

ui/src/components/Search/index.jsx
ui/src/components/TaskGroupTable/index.jsx
ui/src/views/Tasks/TaskGroup/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/245.

[UI] Add ability to filter tasks in Task Group view

---

infrastructure/terraform/built-in-workers-service.tf
infrastructure/terraform/github-service.tf
infrastructure/terraform/hooks-service.tf
infrastructure/terraform/index-service.tf
infrastructure/terraform/notify-service.tf
infrastructure/terraform/queue-service.tf
infrastructure/terraform/secrets-service.tf
infrastructure/terraform/web-server-service.tf

Bugzilla Bug: [1534812](https://bugzilla.mozilla.org/show_bug.cgi?id=1534812)

Bug 1534812 set MONITORING_ENABLE=true for all services

---

services/web-server/src/graphql/Hooks.graphql
ui/src/views/Hooks/ViewHook/hook.graphql

[UI] Fix: Hooks not displaying

---

ui/src/components/TaskGroupProgress/index.jsx
ui/src/theme.js

Fixes https://github.com/taskcluster/taskcluster/issues/406.

[UI] WIP - Add focus state (accessibility)

---

ui/src/components/TaskRunsCard/index.jsx

Relates to https://github.com/taskcluster/taskcluster/issues/383.

Make live logs button more prominent

---

services/github/src/github-auth.js

Bugzilla Bug: [1534294](https://bugzilla.mozilla.org/show_bug.cgi?id=1534294)

Retry 404 and higher errors

---

services/auth/config.yml
services/auth/src/api.js

Minor cleanups I missed in the first PR for this bug.
Bugzilla Bug: [1533591](https://bugzilla.mozilla.org/show_bug.cgi?id=1533591)

Bug 1533591 - minor fixes

---

services/queue/src/artifacts.js

This changes 500 ISE into 400 BadInput errors
Bugzilla Bug: [1524187](https://bugzilla.mozilla.org/show_bug.cgi?id=1524187)

Bug 1524187 - Internal Server Errors when calling queue.completeArtifact

---

libraries/monitor/src/index.js

Add gitversion to root as well

---

ui/src/components/TaskGroupTable/index.jsx
ui/src/theme.js

Fixes https://github.com/taskcluster/taskcluster/issues/447.

Fix weird focus state in task group view (FF only)

---

.eslintrc.yml
.taskcluster.yml
clients/client-web/.eslintrc.js
clients/client-web/.neutrinorc.js
clients/client-web/README.md
clients/client-web/karma.conf.js
clients/client-web/package.json
clients/client-web/src/Client.js
clients/client-web/src/WebListener.js
clients/client-web/src/emitter.js
clients/client-web/test/Auth_test.js
clients/client-web/test/WebListener_test.js
clients/client-web/test/buildUrl_test.js
clients/client-web/test/fromNow_test.js
clients/client-web/test/reference-harness.js
clients/client-web/test/slugid_test.js
clients/client-web/test/utils.js
clients/client-web/webpack.config.js
clients/client-web/yarn.lock
package.json

Relates to https://github.com/taskcluster/taskcluster/issues/285.

client-web neutrino v9, esm output, share linting

---

services/github/src/github-auth.js

Sorry I don't know what I was thinking when I wrote the last review. If this makes sense to you it will be basically what you had before.

Fix my wrong review

---

services/github/src/github-auth.js

Actually fix retries this time (again)

---

services/queue/src/api.js

Bugzilla Bug: [1536927](https://bugzilla.mozilla.org/show_bug.cgi?id=1536927)

[Bug 1536927] Only log taskIds

---

.taskcluster.yml

This will allow for both times that queues are backed up and
reruns of failed tasks.

Increase deadline for tasks

---

libraries/monitor/src/logger.js
libraries/monitor/test/logger_test.js

This should be one layer in helping protect us from accidental leaks.
Bugzilla Bug: [1537907](https://bugzilla.mozilla.org/show_bug.cgi?id=1537907)

[Bug 1537907] Elide secret values

---

generated/docs-table-of-contents.json
ui/docs/reference/libraries/README.md
ui/docs/reference/operations/README.md
ui/docs/reference/workers/README.md

Drop unused reference categories

---

ui/docs/README.md
ui/docs/tutorial/README.md
ui/src/views/Documentation/components/ExploreCard/index.jsx
ui/src/views/Documentation/views/GetStarted/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/440.

[UI] Add custom get started view

---

ui/src/views/Clients/ViewClient/createClient.graphql
ui/src/views/Clients/ViewClient/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/480.

[UI] Show access token when creating a client

---

generated/docs-table-of-contents.json
ui/docs/manual/design/logs/README.md
ui/src/views/Documentation/Reference/LogsReference.jsx

Cleanup logs docs pages 

---

ui/src/components/Dashboard/index.jsx
ui/src/components/SkipNavigation/index.jsx
ui/src/components/TaskGroupProgress/index.jsx

Created a new component for SkipNavigation.
fixes #314

[UI] Add skip to content- keyboard accessibility

---

services/web-server/src/graphql/index.js

Bugzilla Bug: [1538996](https://bugzilla.mozilla.org/show_bug.cgi?id=1538996)

Bug 1538996 - fix module loading with new raw loader

---

ui/src/components/TaskGroupProgress/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/519.

[UI] Treat task with status exception as failed (favicon)

---

services/queue/src/claimresolver.js
services/queue/src/deadlineresolver.js
services/queue/test/claimresolver_test.js
services/queue/test/deadline_test.js

And add tests for them.
Bugzilla Bug: [1540699](https://bugzilla.mozilla.org/show_bug.cgi?id=1540699)

Bug 1540699 - fix calls to monitor.log.task*

---

ui/src/components/SecretForm/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/511.

[UI] Fix ability to add new secrets

---

ui/src/components/TaskRunsCard/index.jsx
ui/src/views/Tasks/ViewTask/index.jsx

Display unscheduled task properly

---

.eslintrc.yml
clients/client-web/src/WebListener.js
services/auth/src/api.js
services/github/src/api.js
services/login/test/handlers_mozilla_auth0_test.js
services/notify/src/handler.js
services/queue/src/artifacts.js
services/treeherder/src/handler.js
services/treeherder/src/util/route_parser.js
services/web-server/src/resolvers/Tasks.js
services/worker-manager/bin/convert.js

Bugzilla Bug: [1540891](https://bugzilla.mozilla.org/show_bug.cgi?id=1540891)

Change linting rules for switches

---

infrastructure/builder/README.md
infrastructure/builder/src/build/monoimage.js

Bugzilla Bug: [1540160](https://bugzilla.mozilla.org/show_bug.cgi?id=1540160)

Bug 1540160 - add bash to the built image

---

services/hooks/src/taskcreator.js
services/hooks/test/scheduler_test.js
services/hooks/test/taskcreator_test.js
services/queue/test/createtask_test.js

Bugzilla Bug: [1540697](https://bugzilla.mozilla.org/show_bug.cgi?id=1540697)

Bug 1540697 - improve idempotency of task creation, especially in hooks

---

package.json
static.json
ui/.neutrinorc.js
ui/README.md
ui/src/components/Dashboard/index.jsx

Relates to https://github.com/taskcluster/taskcluster/issues/413.

taskcluster.net (heroku config)

---

libraries/pulse/src/consumer.js
libraries/pulse/test/consumer_test.js

This adds a new test that simulates the errors detailed in the bug, and
then ignores them.  They come from trying to cleanly shut down a
connection that has already failed.
Bugzilla Bug: [1534713](https://bugzilla.mozilla.org/show_bug.cgi?id=1534713)

Bug 1534713 - ignore errors draining a broken channel

---

services/github/src/handlers.js

Bugzilla Bug: [1446768](https://bugzilla.mozilla.org/show_bug.cgi?id=1446768)
This pr belongs to the 1st part of this bug.
@owlishDeveloper I added options in policy. How I can check the policy if it is collaborators or not?

Bug[1446768] Adding new policy in .taskcluster.yml

---

ui/src/components/DatePicker/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/533.

[UI] Fix calendar icon positioning on date picker

---

ui/src/views/Documentation/Reference/Entry.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/405.

[UI] Fix hashing issue in docs when viewing an entry log

---

ui/docs/reference/integrations/github/taskcluster-yml-v1.md

Bugzilla Bug: [1446768](https://bugzilla.mozilla.org/show_bug.cgi?id=1446768)

Add docs for collaborators_quiet policy

---

ui/src/components/SecretForm/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/512.

[UI] Hide secret initially

---

ui/src/views/Secrets/ViewSecrets/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/587.

[UI] Fix: Stop showing secret after deletion

---

ui/src/views/Tasks/TaskGroup/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/592.

[UI] Display proper error message when task group does not exist

---

infrastructure/terraform/auth-service.tf
infrastructure/terraform/ingress.yaml
infrastructure/terraform/purge-cache-service.tf
infrastructure/terraform/taskcluster.tf.json

Bugzilla Bug: [1545260](https://bugzilla.mozilla.org/show_bug.cgi?id=1545260)

Bug 1545260 - run purge-cache in the cluster

---

ui/src/components/ClientForm/index.jsx
ui/src/components/RoleForm/index.jsx
ui/src/components/SecretForm/index.jsx
ui/src/components/SpeedDialAction/index.jsx
ui/src/views/AwsProvisioner/ViewAwsWorkerTypeDefinition/index.jsx

Fixes #543 
-
Moved delete button above save button in SpeedDial everywhere.

[UI] Unify order of delete buttons

---

ui/src/views/Tasks/ViewTask/index.jsx

Relates to https://github.com/taskcluster/taskcluster/issues/594.

[UI] Fix task action dialog not showing

---

ui/src/utils/ajv.js

Fixes https://github.com/taskcluster/taskcluster/issues/594.

Support v7 schemas

---

ui/src/components/UserMenu/UserMenuList.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/567.

Fix: Sign in dialog not hiding after "cancel" click

---

libraries/api/src/middleware/auth.js
libraries/api/test/auth_test.js
libraries/monitor/src/logger.js
libraries/monitor/test/logger_test.js

Bugzilla Bug: [1544807](https://bugzilla.mozilla.org/show_bug.cgi?id=1544807)

Bug 1544807 - improve handling of huge error messages

---

infrastructure/terraform/auth-service.tf
infrastructure/terraform/ingress.yaml
infrastructure/terraform/purge-cache-service.tf
infrastructure/terraform/taskcluster.tf.json
services/web-server/src/graphql/Hooks.graphql
services/web-server/src/loaders/hooks.js
services/web-server/src/resolvers/Hooks.js
ui/src/components/ClientForm/index.jsx
ui/src/components/ConnectionDataTable/index.jsx
ui/src/components/DataTable/index.jsx
ui/src/components/HookForm/index.jsx
ui/src/components/HookLastFiredTable/index.jsx
ui/src/components/RoleForm/index.jsx
ui/src/components/SecretForm/index.jsx
ui/src/components/SpeedDialAction/index.jsx
ui/src/components/UserMenu/UserMenuList.jsx
ui/src/utils/ajv.js
ui/src/utils/labels.js
ui/src/views/AwsProvisioner/ViewAwsWorkerTypeDefinition/index.jsx
ui/src/views/Hooks/ViewHook/hook.graphql
ui/src/views/Hooks/ViewHook/index.jsx
ui/src/views/Tasks/ViewTask/index.jsx

Continue PR of https://github.com/taskcluster/taskcluster-web/pull/413

ui to display lastfires

---

generated/references.json
services/hooks/README.md
services/hooks/schemas/v1/list-lastFires-response.yml
services/hooks/test/api_test.js

Change firedBy to enum

---

libraries/testing/src/poll.js
services/queue/test/claimresolver_test.js
services/queue/test/deadline_test.js
services/queue/test/queueservice_test.js
services/queue/test/retry_test.js
services/queue/test/taskgroup_test.js

Bugzilla Bug: [1528384](https://bugzilla.mozilla.org/show_bug.cgi?id=1528384)

Bug 1528384 - improvements to polling

---

libraries/pulse/src/client.js
services/hooks/src/listeners.js
services/hooks/test/listeners_test.js

Bugzilla Bug: [1544608](https://bugzilla.mozilla.org/show_bug.cgi?id=1544608)

Bug 1544608 - better handling for errors binding queues

---

ui/src/views/Documentation/Reference/Entry.jsx

Fixes #605 
-
Adds `payload` as function parameter of signature in api docs

Add payload in Signature in API Docs

---

libraries/api/src/middleware/auth.js
libraries/api/test/logging_test.js

Bugzilla Bug: [1541741](https://bugzilla.mozilla.org/show_bug.cgi?id=1541741)

Bug 1541741 - handle API methods that are sometimes public

---

clients/client-web/src/clients/PurgeCache.js
clients/client/src/apis.js
generated/references.json
services/purge-cache/config.yml
services/purge-cache/src/api.js
services/purge-cache/user-config-example.yml

Bugzilla Bug: [1545265](https://bugzilla.mozilla.org/show_bug.cgi?id=1545265)

Bug 1545265 - remove mention of pulse from purge-cache documentation

---

ui/src/components/Dashboard/index.jsx

Continuation of https://github.com/taskcluster/taskcluster/pull/584.
Fixes #498.

[UI] Remove toggle effect from title on sidebar

---

ui/src/components/Dashboard/index.jsx
ui/src/views/Documentation/components/HeaderWithAnchor/index.jsx

[UI] Add top margin to headers in documentation

---

dev-docs/best-practices/microservices.md

Bugzilla Bug: [1546804](https://bugzilla.mozilla.org/show_bug.cgi?id=1546804)

Add note on continuation token to best practices

---

clients/client-web/src/clients/Notify.js
clients/client/src/apis.js
generated/references.json
services/notify/src/api.js
services/notify/test/api_test.js
services/web-server/src/loaders/notify.js

Bugzilla Bug: [1542212](https://bugzilla.mozilla.org/show_bug.cgi?id=1542212)

[Bug 1542212] Change denylist scope and rename list()

---

ui/docs/manual/design/apis/hawk/README.md
ui/docs/manual/design/apis/hawk/clients.md
ui/docs/manual/design/apis/hawk/roles.md
ui/docs/manual/design/apis/hawk/scopes.md
ui/docs/manual/design/namespaces.md
ui/docs/manual/task-execution/workers.md
ui/docs/manual/tasks/README.md
ui/docs/manual/tasks/runs.md
ui/docs/manual/using/actions/spec.md
ui/docs/manual/using/artifacts.md
ui/docs/manual/using/handling-high-load.md
ui/docs/manual/using/integration/frontend.md
ui/docs/manual/using/s3-uploads.md
ui/docs/manual/using/scheduled-tasks.md
ui/docs/manual/using/task-notifications.md
ui/docs/reference/core/notify/usage.md
ui/docs/reference/guide.md
ui/docs/reference/integrations/github/taskcluster-yml-v1.md
ui/docs/reference/integrations/login/getting-user-creds.md
ui/docs/reference/platform/queue/actions.md
ui/docs/reference/platform/queue/worker-hierarchy.md
ui/docs/tutorial/create-task-via-api.md
ui/src/components/HookForm/index.jsx

Relates to https://bugzilla.mozilla.org/show_bug.cgi?id=1546927.

Fix: Links in documentation

---

services/github/test/handler_test.js

Bugzilla Bug: [1542405](https://bugzilla.mozilla.org/show_bug.cgi?id=1542405)

Bug 1542405 - update tc-github handler tests to use new fake pulse support

---

ui/src/components/HookForm/index.jsx
ui/src/components/HookLastFiredTable/index.jsx

[UI] Fix ambiguity in column name (lastfire table)

---

clients/client-web/src/clients/NotifyEvents.js
clients/client/src/apis.js
generated/references.json
services/notify/config.yml
services/notify/src/exchanges.js
services/notify/src/irc.js
services/notify/src/main.js
services/notify/src/notifier.js
services/notify/test/api_test.js
services/notify/test/handler_test.js
services/notify/test/helper.js
ui/docs/reference/core/notify/README.md

(https://bugzilla.mozilla.org/show_bug.cgi?id=1519730)

 [Bug 1519730] Replace sqs with pulse

---

libraries/app/src/index.js

That will teach me to trust StackOverflow :)
Tested in dustin-dev.  I expect this will work in Heroku, too.
Bugzilla Bug: [1547733](https://bugzilla.mozilla.org/show_bug.cgi?id=1547733)

Bug 1547733 - actually set 'trust proxy'

---

services/notify/config.yml
services/notify/src/api.js
services/notify/src/denier.js
services/notify/src/main.js
services/notify/src/notifier.js
services/notify/test/api_test.js
services/notify/test/handler_test.js
services/notify/test/helper.js

Bugzilla Bug: [1547589](https://bugzilla.mozilla.org/show_bug.cgi?id=1547589)

Bug 1547589 - denylisting fixes

---

clients/client-web/src/clients/WorkerManager.js
clients/client/src/apis.js
generated/references.json
services/worker-manager/schemas/v1/workertype-list
services/worker-manager/schemas/v1/workertype-list.yml
services/worker-manager/src/api.js

Bugzilla Bug: [1546789](https://bugzilla.mozilla.org/show_bug.cgi?id=1546789)

Add `list worker types` endpoint to worker manager

---

clients/client-web/src/clients/NotifyEvents.js
clients/client/src/apis.js
generated/references.json
services/notify/config.yml
services/notify/schemas/v1/pulse-request.yml
services/notify/src/api.js
services/notify/src/exchanges.js
services/notify/src/handler.js
services/notify/src/irc.js
services/notify/src/main.js
services/notify/src/monitor.js
services/notify/src/notifier.js
services/notify/test/api_test.js
services/notify/test/handler_test.js

This fixes a couple things that I missed in the initial review!

Fix notify irc

---

ui/src/auth/AuthController.js
ui/src/components/SignInDialog/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/668.
I believe a rebase in https://github.com/taskcluster/taskcluster/pull/547 caused this issue.

[UI] Fix manual login

---

services/web-server/src/login/strategies/mozilla-auth0.js
services/web-server/src/utils/verifyJwt.js

Fixes https://github.com/taskcluster/taskcluster/issues/663.

[web-server] Check the audience when verifying the jwt

---

services/web-server/src/utils/verifyJwt/index.js
services/web-server/src/utils/verifyJwt/jwksClient.js

Fixes https://github.com/taskcluster/taskcluster/issues/659.

[web-server] Construct jwks once

---

services/web-server/README.md
services/web-server/config.yml
services/web-server/src/graphql/Auth.graphql
services/web-server/src/login/strategies/github.js
services/web-server/src/resolvers/Auth.js
services/web-server/user-config-template.yml
ui/src/components/SignInDialog/index.jsx
ui/src/utils/getPictureFromUser.js

Fixes https://github.com/taskcluster/taskcluster/issues/661.

[web-server] Use github instead of github-oauth2 for identityProviderId

---

services/web-server/README.md
ui/README.md

Fixes https://github.com/taskcluster/taskcluster/issues/629.

Document login strategies

---

ui/src/components/IndexTaskNamespaceTable/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/679.

[UI] Preload indexed task view

---

netlify.toml
ui/README.md

(hotfix) update login strategy config for tc-ui

---

services/web-server/config.yml

I think `login.strategies` is an object, not an array.

[web-server] Nit: login.strategies

---

ui/src/auth/AuthController.js
ui/src/views/Tasks/ViewTask/index.jsx

Also removed `__typename` prop after querying credentials. We probably don't want to have that value appear in locale storage :)

[UI] Add missing @withApollo line

---

ui/package.json
ui/src/views/Documentation/index.jsx
ui/yarn.lock

Fixes https://github.com/taskcluster/taskcluster/issues/508.

[UI] Fix inability to open the context-menu in docs

---

services/github/src/handlers.js
services/github/test/github-auth.js

Bugzilla Bug: [1548961](https://bugzilla.mozilla.org/show_bug.cgi?id=1548961)
I noticed there's a deprecation message

Switch from deprecated code to status

---

ui/docs/manual/using/administration.md
ui/docs/reference/integrations/github/taskcluster-yml-v0.md
ui/docs/reference/integrations/github/taskcluster-yml-v1.md
ui/docs/reference/integrations/treeherder/README.md

Fixes https://github.com/taskcluster/taskcluster/issues/700.

[Docs] only one h1 tag per page

---

services/github/src/handlers.js
services/github/src/tc-yaml.js
services/github/test/data/configs/taskcluster.dependencies.v1.yml
services/github/test/intree_test.js

Bugzilla Bug: [1548633](https://bugzilla.mozilla.org/show_bug.cgi?id=1548633)

Sort tasks topologically

---

ui/src/utils/Link.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/685.

[UI] Reload page when chunk fails to load

---

ui/src/views/Tasks/CreateTask/index.jsx
ui/src/views/Tasks/routes.js

Fixes https://github.com/taskcluster/taskcluster/issues/716.

[UI] Fix: Interactive toggle fails to change on first click

---

services/web-server/src/createContext.js
services/web-server/src/loaders/auth.js
services/web-server/src/loaders/index.js
services/web-server/src/main.js
services/web-server/src/monitor.js

Fixes https://github.com/taskcluster/taskcluster/issues/662.

[web-server] Log credential generation

---

infrastructure/builder/src/generate/generators/service-refs.js

remove debug print

---

dev-docs/login-process.md

Fixes https://github.com/taskcluster/taskcluster/issues/629.

[docs] Document login process

---

ui/src/views/PulseMessages/index.jsx

Remove duplicate handleInput from PulseMessages

---

ui/src/views/Roles/ViewRole/index.jsx

Relates to https://github.com/taskcluster/taskcluster/issues/739.

[UI] Change fetchPolicy for ViewRole

---

services/web-server/test/strategyMozillaAuth0_test.js

Relates to https://github.com/taskcluster/taskcluster-rfcs/issues/142.

Add tests to web-server mozilla-auth0 strategy

---

.taskcluster.yml
clients/client-web/src/clients/Auth.js
clients/client/src/apis.js
generated/references.json
services/auth/config.yml
services/auth/schemas/v1/gcp-credentials-response.yml
services/auth/src/api.js
services/auth/src/gcp.js
services/auth/src/main.js
services/auth/test/azure_test.js
services/auth/test/client_test.js
services/auth/test/containers_test.js
services/auth/test/gcp_test.js
services/auth/test/helper.js
services/auth/test/purgeExpiredClients_test.js
services/auth/test/remotevalidation_test.js
services/auth/test/role_test.js
services/auth/test/rolelogic_test.js
services/auth/test/s3_test.js
services/auth/test/scoperesolver_test.js
services/auth/test/sentry_test.js
services/auth/test/staticclients_test.js
services/auth/test/statsum_test.js
services/auth/test/stories_test.js
services/auth/test/testauth_test.js
services/auth/test/websocktunnel_test.js
services/auth/user-config-example.yml
yarn.lock

The gcsCredentials API returns a temporary oauth2 access token for the
given service account.
Bugzilla Bug: [1544871](https://bugzilla.mozilla.org/show_bug.cgi?id=1544871)

Bug 1544871: Implement gcsCredentials API

---

libraries/monitor/src/logger.js
libraries/monitor/src/monitor.js
libraries/monitor/test/monitor_test.js

Bugzilla Bug: [1550000](https://bugzilla.mozilla.org/show_bug.cgi?id=1550000)

Bug 1550000 - adjust logging to stackdrier's satisfaction

---

infrastructure/terraform/auth-service.tf
infrastructure/terraform/taskcluster.tf.json

Add extra bits of terraform for w-m in google

---

README.md
services/README.md
services/github/README.md

mainly for `run the tess` -> `run the tests`. made a few other minor adjustments. let me know if I should change any of them.

fix minor typos in README

---

libraries/pulse/test/client_test.js

try harder to make a timing-based test pass

---

services/worker-manager/src/provider_google.js
services/worker-manager/test/api_test.js

I think I lost this check in the shuffle to get this landed

Stop reclaiming of credentials

---

.codecov.yml

This should make codecov start making sense

Wait on taskcluster tasks to complete

---

generated/references.json
services/worker-manager/schemas/v1/create-workertype-request.yml
services/worker-manager/schemas/v1/workertype-full.yml
services/worker-manager/src/api.js
services/worker-manager/src/data.js
services/worker-manager/test/api_test.js
services/worker-manager/test/provider_google_test.js
services/worker-manager/test/provisioner_test.js

Just a `sed` run :)
Bugzilla Bug: [1552239](https://bugzilla.mozilla.org/show_bug.cgi?id=1552239)

Bug 1552239 - change wantsEmail to emailOnError

---

ui/src/utils/constants.js

Relates to https://github.com/taskcluster/taskcluster/issues/763.

[UI] Adjust number of artifacts displayed

---

infrastructure/terraform/web-server-service.tf
services/web-server/procs.yml

Fixes https://github.com/taskcluster/taskcluster/issues/769.

[web-server] Add scanner cron process to web-server login

---

ui/src/auth/AuthController.js

Relates to https://github.com/taskcluster/taskcluster/issues/768.

[UI] Apply randomization to avoid multiple tabs renewal at same time

---

.codecov.yml
.taskcluster.yml
test/fetch-coverage.js

Handle cases where not all coverage uploads succeeded

---

ui/src/components/DataTable/index.jsx

Regression from https://github.com/taskcluster/taskcluster/pull/466.

[UI] DataTable regression

---

ui/docs/tutorial/debug-task.md
ui/src/views/Tasks/ViewTask/index.jsx

[UI] Interactive Task re-wording

---

ui/package.json
ui/src/components/Log/index.jsx
ui/yarn.lock

Fixes https://github.com/taskcluster/taskcluster/issues/792.

Enable search in log

---

ui/src/views/Tasks/ViewTask/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/795.

Add task name page title

---

README.md
deployment-docs/README.md
services/web-server/README.md

This is quite incomplete but I figured I'd get a start so we have something to improve on.

Add some basic deployment docs

---

ui/package.json
ui/src/components/Log/index.jsx
ui/yarn.lock

Reverts taskcluster/taskcluster#793
Regression in https://github.com/taskcluster/taskcluster/issues/799. Issue seems to happen in production only.

Revert "Enable search in log"

---

services/web-server/src/login/strategies/github.js
services/web-server/src/login/strategies/mozilla-auth0.js
services/web-server/src/views/callback.ejs
ui/src/auth/AuthController.js
ui/src/auth/UserSession.js
ui/src/components/SignInDialog/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/768.

[UI] Staying signed in

---

ui/docs/manual/design/apis/hawk/signed-urls.md

Better links, and an illustrative example.

Update signed-urls docs

---

services/web-server/src/login/strategies/github.js
services/web-server/src/login/strategies/mozilla-auth0.js
services/web-server/src/utils/login.js
services/web-server/src/views/callback.ejs

Relates to https://github.com/taskcluster/taskcluster/issues/806.

[web-server] Remove window.opener.location and stop decoding jwt

---

services/web-server/README.md
services/web-server/config.yml
services/web-server/src/login/strategies/mozilla-auth0.js
services/web-server/test/strategyMozillaAuth0_test.js

Relates to https://github.com/taskcluster/taskcluster/issues/806.

[web-server] Modify audience and scope fields in mozilla-auth0

---

clients/client-py/README.md
clients/client-py/taskcluster/generated/aio/workermanager.py
clients/client-py/taskcluster/generated/workermanager.py
clients/client-web/src/clients/WorkerManager.js
clients/client/src/apis.js
generated/references.json
libraries/loader/src/index.js
libraries/references/src/validate.js
services/worker-manager/Procfile
services/worker-manager/config.yml
services/worker-manager/procs.yml
services/worker-manager/schemas/v1/config-null.yml
services/worker-manager/schemas/v1/worker-pool-full.yml
services/worker-manager/src/api.js
services/worker-manager/src/data.js
services/worker-manager/src/main.js
services/worker-manager/src/providers/index.js
services/worker-manager/src/providers/null.js
services/worker-manager/src/provisioner.js
services/worker-manager/test/api_test.js
services/worker-manager/test/expiration_test.js
services/worker-manager/test/provider_google_test.js
services/worker-manager/test/provisioner_test.js

With some more tests for expirations (+fixes) and with a tweak to the loader so that it doesn't get confused when a component's value is `undefined`.
Bugzilla Bug: [1553965](https://bugzilla.mozilla.org/show_bug.cgi?id=1553965)

Bug 1553965 - delete worker pools by setting providerId="null"

---

ui/docs/manual/design/namespaces.md
ui/docs/manual/using/secrets.md
ui/docs/reference/platform/auth/scopes.md
ui/src/views/Secrets/ViewSecret/index.jsx

Bugzilla Bug: [1555787](https://bugzilla.mozilla.org/show_bug.cgi?id=1555787)

Bug 1555787 - remove references to garbage secrets

---

clients/client-py/README.md
clients/client-py/taskcluster/generated/aio/workermanagerevents.py
clients/client-py/taskcluster/generated/workermanagerevents.py
clients/client-web/src/clients/WorkerManagerEvents.js
clients/client/src/apis.js
generated/references.json
services/worker-manager/src/exchanges.js
services/worker-manager/src/provisioner.js
services/worker-manager/test/provisioner_test.js

This is no longer sent, so no need to listen for it..

Remove workerPoolDeleted event

---

services/worker-manager/Procfile
services/worker-manager/procs.yml
services/worker-manager/src/api.js
services/worker-manager/src/main.js
services/worker-manager/src/provisioner.js
services/worker-manager/test/api_test.js
services/worker-manager/test/helper.js
services/worker-manager/test/provisioner_test.js

Handle unknown providerId without crashing

---

ui/src/components/SecretForm/index.jsx

Secrets view UX

---

ui/src/views/Secrets/ViewSecret/index.jsx

Added confirmation message when saving secret

added confirmation message when saving secret

---

clients/client-py/README.md

Bugzilla Bug: [1556432](https://bugzilla.mozilla.org/show_bug.cgi?id=1556432)

Bug 1556432 - fix broken link in Python client

---

libraries/testing/src/time.js
services/worker-manager/src/data.js
services/worker-manager/src/main.js
services/worker-manager/src/providers/google.js
services/worker-manager/src/providers/index.js
services/worker-manager/src/providers/provider.js
services/worker-manager/src/providers/testing.js
services/worker-manager/src/worker-scanner.js
services/worker-manager/test/helper.js
services/worker-manager/test/provisioner_test.js
services/worker-manager/test/worker_pool_errors.js
services/worker-manager/test/worker_scanner_test.js
test/fetch-coverage.js

Add more tests and such. Hooray coverage.

Worker manager updates

---

services/queue/src/api.js

Was going through queue's apis and discovered an incorrect comment

Correct comment description of endpoint

---

services/web-server/src/login/strategies/mozilla-auth0.js

[web-server] hotfix: check for user before generating jwt

---

ui/src/components/DataTable/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/847.

[UI] Fix pagination issue in DataTable

---

ui/src/components/ClientForm/index.jsx
ui/src/components/RoleForm/index.jsx

Auth_Client_UX_#598

---

ui/src/views/Clients/ViewClient/index.jsx
ui/src/views/Roles/ViewRole/index.jsx

snackbar confirmation for client and role form

---

build-config.yml
infrastructure/builder/src/build/index.js
infrastructure/builder/src/build/monoimage.js
infrastructure/builder/src/build/utils.js
infrastructure/builder/src/generate/generators/docs-tocs.js
infrastructure/builder/src/generate/generators/node-version.js
infrastructure/builder/src/generate/generators/procfiles.js
infrastructure/builder/src/generate/generators/readme-tocs.js
infrastructure/builder/src/generate/generators/service-refs.js
infrastructure/builder/src/generate/generators/tc-client-py.js
infrastructure/builder/src/generate/generators/tc-client-web.js
infrastructure/builder/src/generate/generators/tc-client.js
infrastructure/builder/src/generate/index.js
infrastructure/builder/src/main.js
infrastructure/builder/src/release/index.js
infrastructure/builder/src/release/tasks.js
infrastructure/builder/src/utils/docker.js
infrastructure/builder/src/utils/git.js
infrastructure/builder/src/utils/index.js
infrastructure/builder/src/utils/repo.js
infrastructure/builder/src/utils/tasks.js
package.json
yarn.lock

Bugzilla Bug: [1555490](https://bugzilla.mozilla.org/show_bug.cgi?id=1555490)
The first major release would be 14.1.0, since tc-client is already at 14.0.0.
This doesn't handle:
* making a github release
* pushing client packages to various packaging things
* determining appropriate level and constructing changelog

Bug 1555490 - implement yarn release

---

.nycrc.yml
clients/client-py/README.md
clients/client-py/taskcluster/generated/aio/workermanager.py
clients/client-py/taskcluster/generated/workermanager.py
clients/client-web/src/clients/WorkerManager.js
clients/client/src/apis.js
generated/references.json
services/worker-manager/schemas/v1/worker-pool-error-list.yml
services/worker-manager/schemas/v1/worker-pool-error.yml
services/worker-manager/src/api.js
services/worker-manager/src/main.js
services/worker-manager/src/providers/testing.js
services/worker-manager/test/api_test.js
services/worker-manager/test/helper.js
services/worker-manager/test/provisioner_test.js
services/worker-manager/test/worker_pool_errors_test.js

Each commit here should be fairly self-contained with stuff I wanted to do to make w-m nicer.
The most unrelated thing is where I ignore `main.js` in coverage stuff but that's just because it was annoying me that was dragging things down.

worker pool errors, deprovisioning stuff, more coverage

---

services/worker-manager/src/providers/google.js
services/worker-manager/test/api_test.js
services/worker-manager/test/fake-google.js
services/worker-manager/test/provider_google_test.js

Didn't quite get to provider tables yesterday but here's what I did get
done.

More worker-manager coverage and fixes

---

infrastructure/references/relativize.js
ui/docs/manual/design/apis/reference-format.md

Bugzilla Bug: [1557487](https://bugzilla.mozilla.org/show_bug.cgi?id=1557487)
Docs, except the last paragraph, were already reviewed in #852.

Bug 1557487 - fix /references/references.json, add docs

---

dev-docs/best-practices/microservices.md
services/web-server/README.md
services/web-server/src/graphql/AwsProvisionerWorkerTypes.graphql
services/web-server/src/graphql/Hooks.graphql
services/web-server/src/graphql/Provisioners.graphql
services/web-server/src/graphql/WorkerTypes.graphql

My hope is for this styleguide to stay minimal :)
Relates to https://github.com/taskcluster/taskcluster/pull/843#discussion_r291286012.

[web-server] Add initial styleguide

---

clients/client-py/README.md
clients/client-py/taskcluster/generated/aio/workermanager.py
clients/client-py/taskcluster/generated/workermanager.py
clients/client-web/src/clients/WorkerManager.js
clients/client/src/apis.js
generated/references.json
services/worker-manager/schemas/v1/worker-full.yml
services/worker-manager/schemas/v1/worker-list.yml
services/worker-manager/src/api.js
services/worker-manager/src/data.js
services/worker-manager/src/main.js
services/worker-manager/test/api_test.js

Bugzilla Bug: [1558713](https://bugzilla.mozilla.org/show_bug.cgi?id=1558713)

Bug1558713 - add endpoint to list workers for a given workerpool

---

ui/docs/manual/README.md
ui/docs/manual/task-execution/worker-pools.md

(hotfix) headings in docs

---

SECURITY.md

Bugzilla Bug: [1555093](https://bugzilla.mozilla.org/show_bug.cgi?id=1555093)

[Bug 1555093] Create SECURITY.md

---

deployment-docs/README.md

bstack showed me the production TC's app and I wrote down what perms it had.

Deployment docs: how to set up app

---

libraries/api/README.md
libraries/api/test/route_test.js
services/worker-manager/src/api.js
services/worker-manager/src/providers/google.js

Bugzilla Bug: [1560645](https://bugzilla.mozilla.org/show_bug.cgi?id=1560645)

Bug 1560645 - test, doc, and use unescaped slash support

---

ui/src/theme.js

Hook list focus state

---

ui/src/components/Log/GoToLineButton.jsx
ui/src/components/Log/index.jsx
ui/src/views/Tasks/TaskLog/index.jsx

Reposition log action buttons

---

CHANGELOG.md
changelog/bug1558523.md
dev-docs/best-practices/changelog.md
infrastructure/builder/src/build/monoimage.js
infrastructure/builder/src/changelog/index.js
infrastructure/builder/src/main.js
infrastructure/builder/src/release/index.js
infrastructure/builder/src/release/tasks.js
infrastructure/builder/src/utils/repo.js
package.json

Bugzilla Bug: [1558523](https://bugzilla.mozilla.org/show_bug.cgi?id=1558523)

Bug 1558523 - Support Changelog and tagging/pushing automatically

---

ui/src/components/DialogAction/index.jsx
ui/src/components/TaskGroupProgress/index.jsx
ui/src/utils/constants.js
ui/src/views/Tasks/TaskGroup/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/304 and https://github.com/taskcluster/taskcluster/issues/305.

[UI] Add feature to notify on task failures & group success

---

clients/client-go/tcworkermanager/tcworkermanager.go
clients/client-go/tcworkermanager/types.go
clients/client-py/README.md
clients/client-py/taskcluster/generated/aio/workermanager.py
clients/client-py/taskcluster/generated/workermanager.py
clients/client-web/src/clients/WorkerManager.js
clients/client/src/apis.js
generated/references.json
services/worker-manager/schemas/v1/report-worker-error-request.yml
services/worker-manager/src/api.js
services/worker-manager/src/data.js
services/worker-manager/src/main.js
services/worker-manager/test/api_test.js

Bugzilla Bug: [1558346](https://bugzilla.mozilla.org/show_bug.cgi?id=1558346)

Bug 1558346 - add workerManager.reportWorkerError

---

test/meta_test.js
ui/docs/manual/using/administration.md
ui/docs/reference/core/notify/README.md
ui/docs/reference/core/purge-cache/README.md
ui/docs/reference/core/secrets/README.md
ui/docs/reference/core/worker-manager/README.md
ui/docs/reference/integrations/login/README.md
ui/docs/reference/integrations/treeherder/task-treeherder-config.md
ui/docs/reference/platform/auth/README.md
ui/docs/reference/platform/queue/task-schema.md

headings-in-docs-file

---

ui/src/components/TaskGroupTable/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/931.

[UI] Show task full name and add tooltip

---

ui/package.json
ui/yarn.lock

Fixes https://github.com/taskcluster/taskcluster/issues/932.

[UI] Log - search on enter

---

ui/src/components/SecretForm/index.jsx

Added autoFocus to the first textfield as per the instructions here: https://github.com/taskcluster/taskcluster/issues/825
Bug: [825](https://github.com/taskcluster/taskcluster/issues/825)

Bug #825 Added autoFocus

---

ui/src/views/Quickstart/index.jsx

Added autoFocus to the first textfield as per the instructions here: https://github.com/taskcluster/taskcluster/issues/825
Bug: [825](https://github.com/taskcluster/taskcluster/issues/825)

Bug: 825 Added autoFocus

---

.github/pull_request_template.md

Bugzilla Bug: [1562751](https://bugzilla.mozilla.org/show_bug.cgi?id=1562751)

Bug 1562751 - request a changelog entry for each PR

---

test/meta_test.js
ui/docs/manual/using/administration.md
ui/docs/reference/core/notify/README.md
ui/docs/reference/core/purge-cache/README.md
ui/docs/reference/core/secrets/README.md
ui/docs/reference/core/worker-manager/README.md
ui/docs/reference/integrations/login/README.md
ui/docs/reference/integrations/treeherder/task-treeherder-config.md
ui/docs/reference/platform/auth/README.md
ui/docs/reference/platform/queue/task-schema.md

removed one test and fixed files

---

ui/src/components/HookForm/index.jsx

Bug: 825: Added Auto Focus to first textfield

---

dev-docs/best-practices/ui.md
services/web-server/README.md
ui/README.md

There's probably more stuff to add but this is what came to mind when writing this document.

[Docs] Add UI best practices

---

ui/src/components/IndexedEntry/index.jsx

Add relative date in a tooltip
Fixes #970

[UI] Show relative date in a tooltip

---

netlify.toml

Relates to https://github.com/taskcluster/taskcluster/issues/969.

[UI] Redirect netlify master branch to heroku app

---

changelog/bug1563341.md
clients/client-go/tcworkermanager/tcworkermanager.go
clients/client-go/tcworkermanager/types.go
clients/client-py/README.md
clients/client-py/taskcluster/generated/aio/workermanager.py
clients/client-py/taskcluster/generated/workermanager.py
clients/client-web/src/clients/WorkerManager.js
clients/client/src/apis.js
generated/references.json
services/worker-manager/schemas/v1/create-worker-request.yml
services/worker-manager/src/api.js
services/worker-manager/src/providers/google.js
services/worker-manager/src/providers/provider.js
services/worker-manager/src/providers/testing.js
services/worker-manager/test/api_test.js

Bugzilla Bug: [1563341](https://bugzilla.mozilla.org/show_bug.cgi?id=1563341)

Bug 1563341 - create / remove workers in worker-manager

---

test/meta_test.js

Bugzilla Bug: [1562752](https://bugzilla.mozilla.org/show_bug.cgi?id=1562752)

no references to tools.taskcluster.net

---

services/worker-manager/README.md
services/worker-manager/providers.md
services/worker-manager/src/providers/provider.js

This is mostly just moving info out of comments in `provider.js` and into a markdown file.. with more detail.

Document provider implementation a markdown file

---

dev-docs/best-practices/security.md

I also had "don't allow scopes to threaten platform" in my notes, but I'm not sure what that means.

add a security best-practice

---

deployment-docs/clouds.md
generated/docs-table-of-contents.json
ui/docs/reference/core/worker-manager/google.md
ui/docs/reference/core/worker-manager/static.md

This has some open TODO's for @imbstack to answer :)

Provide user-oriented docs for providers

---

ui/src/components/RoleForm/index.jsx

Added autoFocus, and replaced the ternary operator with a logical operator
Bug: 825

Bug #825: Added autoFocus, and removed the ternary operator

---

test/meta_test.js

The previous version used `glob` over the whole repository and as a
result found instances of tools.taskcluster.net in `node_modules` and
other non-checked-in files.  And, it missed dotfiles like `.taskcluster.yml`.

Fix the tools.taskcluster.net meta-test

---

services/worker-manager/src/providers/provider.js

Fix error in signature (Provider's method)

---

dev-docs/principles.md

Fixes broken Idempotent APIs link in `dev-docs/principles.md`

Fix broken link

---

package.json
yarn.lock

Bugzilla Bug: [1564121](https://bugzilla.mozilla.org/show_bug.cgi?id=1564121)

Bug 1564121 - update JSON-parameterization

---

changelog/bug1563341.md
clients/client-go/tcworkermanager/types.go
generated/references.json
services/worker-manager/schemas/v1/create-worker-request.yml
services/worker-manager/schemas/v1/register-worker-request.yml
services/worker-manager/src/providers/provider.js
services/worker-manager/src/providers/static.js
services/worker-manager/test/api_test.js
ui/docs/reference/core/worker-manager/static.md

Bugzilla Bug: [1563341](https://bugzilla.mozilla.org/show_bug.cgi?id=1563341)

Bug 1563341- require static workers be managed manually, identified by secrets

---

services/notify/test/api_test.js
test/meta_test.js

Bugzilla Bug: [1562752](https://bugzilla.mozilla.org/show_bug.cgi?id=1562752)

Remove reference to tools.taskcluster.net in API tests

---

ui/docs/reference/core/worker-manager/google.md

Docs: add examples

---

changelog/fix-python-package.md
clients/client-py/setup.py

[client-py] Include generated APIs in python package.

---

services/worker-manager/src/providers/google.js
services/worker-manager/src/providers/index.js
services/worker-manager/src/providers/provider.js
services/worker-manager/test/provider_google_test.js

Bugzilla Bug: [1566567](https://bugzilla.mozilla.org/show_bug.cgi?id=1566567)
I feel like FakeCloudApis could use some refactoring, too, but maybe not right now :)

Bug 1566567 - refactor provider constructors

---

ui/src/views/AwsProvisioner/ViewAwsWorkerTypeDefinition/index.jsx
ui/src/views/AwsProvisioner/ViewAwsWorkerTypes/index.jsx
ui/src/views/CachePurges/CreatePurgeCacheRequest/index.jsx
ui/src/views/Tasks/CreateTask/index.jsx

Fixed Buttons/icons inconsistency

---

.taskcluster.yml
clients/client-shell/README.md
infrastructure/builder/src/release/tasks.js
infrastructure/builder/src/utils/git.js
test/meta_test.js

Minor release fixups

---

ui/src/components/ClientForm/index.jsx
ui/src/components/RoleForm/index.jsx
ui/src/views/Clients/ViewClient/index.jsx

added confirmation dialog box on delete button for client view.

added confirmation dialog client view

---

ui/docs/reference/guide.md

Fix minor typo

---

infrastructure/builder/src/main.js
infrastructure/builder/src/release/index.js

I keep forgetting `--push` and the result is a messed up local repo and
me trying to either undo that or manually push stuff.  Yuck.

Default to pushing in `yarn release`

---

package.json
yarn.lock

2.0.0 is 0.2.0 with upgraded dependencies.  No changes to the syntax.

upgrade json-parameterization to 2.0.0

---

.yarnrc

As it says on the tin. [Documented here](https://yarnpkg.com/en/docs/cli/policies)

Upgrade yarn

---

infrastructure/builder/src/dev/taskcluster.js

Update web server config in dev deployments

---

dev-docs/development-process.md

add explanation for Route53 steps

---

ui/src/App/index.jsx

Relates to #1099
Credits to @djmitche for identifying the issue and the fix.

Fix credentials option in HttpLink

---

ui/src/App/index.jsx

Reverts taskcluster/taskcluster#1110

Revert "Fix credentials option in HttpLink"

---

changelog/bug-1552970.md
services/auth/src/gcp.js
services/auth/test/gcp_test.js
services/auth/test/helper.js

Bugzilla Bug: [1552970](https://bugzilla.mozilla.org/show_bug.cgi?id=1552970)

Bug 1552970: Do not set IAM policy before generating a temp. token

---

services/worker-manager/src/providers/google.js

Update worker labels to account for new worker pool ids

---

ui/src/views/Tasks/TaskLog/index.jsx
ui/src/views/Tasks/TaskLog/task.graphql

Fixes #639
@helfi92 
**After fix :**

Log favicon state update while viewing logs

---

libraries/app/src/index.js
libraries/app/test/app_test.js
libraries/app/test/bin/app.js

App library cleanup

---

infrastructure/builder/src/dev/aws.js

This should set up the policy for public artifacts correctly. Confirmed
with
https://taskcluster.imbstack.com/tasks/fEVs05IqSJiABVSlPhvtvw/runs/1/logs/https%3A%2F%2Ftaskcluster.imbstack.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FfEVs05IqSJiABVSlPhvtvw%2Fruns%2F1%2Fartifacts%2Fpublic%2Flogs%2Flive.log
Bugzilla Bug: [1570800](https://bugzilla.mozilla.org/show_bug.cgi?id=1570800)

[Bug 1570800] Add real support for public artifacts in dev envs

---

ui/docs/reference/core/worker-manager/google.md

(based on conversation with @imbstack)

Minor improvements to google provider docs

---

ui/.neutrinorc.js
ui/src/components/Dashboard/SidebarList.jsx
ui/src/components/WMWorkerPoolsTable/index.jsx

Per discussion with @owlishDeveloper and @helfi92

Point from worker-manager to existing workertypes view

---

ui/src/components/DenylistForm/index.jsx
ui/src/views/Denylist/ViewDenylistAddress/index.jsx

There is still another problem in denylist page

Added confirmation dialog box for denylist page

---

ui/package.json
ui/yarn.lock

Updated react-lazylog

---

ui/src/views/Provisioners/ViewProvisioners/index.jsx
ui/src/views/Provisioners/ViewWorker/index.jsx
ui/src/views/Provisioners/ViewWorkerTypes/index.jsx
ui/src/views/Provisioners/ViewWorkers/index.jsx

Fixes #325 
Hi @helfi92 !
Hope you are having a wonderful day!
This is a PR to start the discussion with. I made some changes and tested them locally. 
Let me know what other changes this needs! Thanks =)

Adding breadcrumbs to Provisioners view

---

services/web-server/src/servers/createApp.js

Handle an empty string as ADDITIONAL_ALLOWED_CORS_ORIGIN

---

ui/src/components/Log/index.jsx

Highlight filter icon when it's active

---

services/notify/src/notifier.js
services/notify/src/templates/fullscreen/html.pug
services/notify/src/templates/simple/html.pug
services/notify/test/api_test.js

Bugzilla Bug: [1574655](https://bugzilla.mozilla.org/show_bug.cgi?id=1574655)

[bug 1574655] Fix double escape in email

---

services/web-server/src/login/clients/GithubClient.js
services/web-server/src/login/strategies/github.js

Fixes https://github.com/taskcluster/taskcluster/issues/660.

[web-server; login] Use numeric github user ID rather than username

---

changelog/issue-1216.md
services/web-server/src/graphql/Auth.graphql
services/web-server/src/loaders/auth.js
services/web-server/src/resolvers/Auth.js
ui/src/App/Main.jsx
ui/src/App/isLoggedIn.graphql

Closes https://github.com/taskcluster/taskcluster/issues/1216.

[UI] Add isLoggedIn

---

generated/docs-table-of-contents.json
ui/docs/manual/deploying/workers.md
ui/docs/reference/core/worker-manager/README.md
ui/docs/reference/core/worker-manager/aws.md

Bugzilla Bug: [1577842](https://bugzilla.mozilla.org/show_bug.cgi?id=1577842)

Bug 1577842 - document aws provider

---

changelog/issue-1260.md

Add changelog for google provider changes

---

ui/package.json
ui/yarn.lock

Updated date-fns

---

services/worker-manager/src/data.js
services/worker-manager/src/providers/google.js

Just a little bug and some formatting niceness around error reporting

google provider quick fixes

---

package.json

Per https://github.com/renovatebot/config-help/issues/350 this should
get us updates for packages with versions that fall within the current
semver range.

Use renovate rangeStrategy: update-lockfile

---

services/auth/test/cleanup.js
services/auth/test/containers_test.js
services/auth/test/helper.js

Bugzilla Bug: [1579085](https://bugzilla.mozilla.org/show_bug.cgi?id=1579085)

Bug 1579085 - clean up azure containers, too

---

services/worker-manager/src/data.js

Bugzilla Bug: [1578902](https://bugzilla.mozilla.org/show_bug.cgi?id=1578902)

Change workflow in reportError

---

services/queue/test/claimresolver_test.js
services/queue/test/claimtask_test.js
services/queue/test/reruntask_test.js
services/queue/test/workerinfo_test.js

Bugzilla Bug: [1579496](https://bugzilla.mozilla.org/show_bug.cgi?id=1579496), [1580483](https://bugzilla.mozilla.org/show_bug.cgi?id=1580483)

Bug 1580483 - skip the worst offenders of bug 1579496

---

services/worker-manager/src/api.js
services/worker-manager/src/providers/static.js

This makes the code match what the schemas require

Fix static provider gotchas

---

infrastructure/k8s/templates/taskcluster-web-server-secret.yaml
services/web-server/config.yml
services/web-server/src/servers/createApp.js
ui/src/App/index.jsx

Deployed in https://hassan.taskcluster-dev.net. You can try logging in with GitHub. auth0 is not configured in web-server so that won't work.
Fixes https://github.com/taskcluster/taskcluster/issues/1099.

[UI] Fix cookies in production

---

generated/references.json
services/worker-manager/schemas/v1/config-google.yml
services/worker-manager/src/providers/google.js

Let's get this landed sooner rather than later and open up the api as described in 1581483 next.
Sorry this took a day longer than promised. If you like this, @petemoore you can merge it and deploy a new w-m in heroku!
This was tested in my dev env and seems to have worked correctly both with a display requested and not

Add display device to google instances

---

ui/src/components/Dashboard/index.jsx

Fixes #1273 
@helfi92 , Let me know if this needs any change,
Thanks :)

Removed warning in devtools

---

ui/src/views/WorkerManager/WMViewWorkerPools/index.jsx

https://deploy-preview-1368--taskcluster-web.netlify.com/worker-manager

[UI] Have the url control worker pools scheduled for deletion

---

ui/src/components/HookForm/index.jsx
ui/src/components/WMWorkerPoolEditor/index.jsx

Addedd MarkdownTextArea tab in WMWorkerPoolEditor/index.js for changing text field to text area

[UI] Change text field into text area

---

libraries/monitor/src/monitormanager.js

Bugzilla Bug: [1579216](https://bugzilla.mozilla.org/show_bug.cgi?id=1579216)

Bug 1579216 - bulletproof stringification

---

ui/src/views/Dashboard/index.jsx

Issue #1375: Add link to /tasks in homepage

---

libraries/testing/src/with-entity.js
services/queue/test/claimresolver_test.js
services/queue/test/claimtask_test.js
services/queue/test/reruntask_test.js
services/queue/test/workerinfo_test.js

Bugzilla Bug: [1579496](https://bugzilla.mozilla.org/show_bug.cgi?id=1579496)
This isn't great.  It's, what's the word.. "terrible".
But, it will get rid of the false positives we've been ignoring for so long, at our peril.

Disable real azure

---

ui/src/components/ClientForm/index.jsx
ui/src/components/SpeedDialAction/index.jsx

[UI] Remove warning

---

ui/src/views/Scopes/ScopesetExpander/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/1396.
This was a regression introduced after https://github.com/taskcluster/taskcluster/pull/1348.

[UI] Remove error when trying to expand scopes

---

ui/src/views/Tasks/TaskGroup/index.jsx

Resolves https://github.com/taskcluster/taskcluster/issues/1156.

[UI] Ignore error if task group without decision task

---

ui/src/components/HookForm/index.jsx
ui/src/components/PulseBindings/index.jsx

* Adjust spacing between sections/components
* Use same font size and weight for labels (e.g., "Bindings", "Task Template", "Trigger Schema" are no longer bold and look the same as the other labels)
* Put Hook Group ID and Hook ID in the same row since both are closely related and not editable when viewing an existent hook

[UI] Improve overall layout of hook view

---

services/github/src/handlers.js
services/github/test/handler_test.js

Bugzilla Bug: [1585035](https://bugzilla.mozilla.org/show_bug.cgi?id=1585035)

Bug 1585035 - allow graph.tasks to be undefined

---

services/github/src/github-auth.js
ui/docs/manual/deploying/github.mdx

Bugzilla Bug: [1585135](https://bugzilla.mozilla.org/show_bug.cgi?id=1585135)

Bug 1585135 - check format of GITHUB_PRIVATE_PEM

---

clients/client-go/tcworkermanager/tcworkermanager.go
clients/client-py/README.md
clients/client-py/taskcluster/generated/aio/workermanager.py
clients/client-py/taskcluster/generated/workermanager.py
clients/client-shell/apis/services.go
clients/client-web/src/clients/WorkerManager.js
clients/client/src/apis.js
generated/references.json
services/worker-manager/src/api.js
services/worker-manager/test/api_test.js

Bugzilla Bug: [1583928](https://bugzilla.mozilla.org/show_bug.cgi?id=1583928)

Bug 1583928 - allow deleting a worker pool without provider scope

---

ui/docs/manual/access-control/api.mdx
ui/docs/manual/design/conventions/actions/spec.mdx
ui/docs/manual/tasks/priority.mdx
ui/docs/manual/tasks/scopes.mdx
ui/docs/manual/tasks/workertypes.mdx
ui/docs/manual/using/namespaces.mdx

Fixes: #1388 
- Used `Warning_Components` in various places in docs

[UI] : Addition of Warning_Components is various docs file

---

services/github/src/handlers.js
services/github/test/handler_test.js

Bugzilla Bug: [1586114](https://bugzilla.mozilla.org/show_bug.cgi?id=1586114)

Change the shape of the url for the task groups

---

infrastructure/tooling/src/smoketest/checks/succeed.js

Creates a built-in/succeed smoketest for #1240

Built in/succeed smoketest

---

services/worker-manager/src/api.js
services/worker-manager/src/providers/google.js
services/worker-manager/src/providers/provider.js
services/worker-manager/src/providers/static.js
services/worker-manager/src/providers/testing.js
services/worker-manager/test/fake-google.js
services/worker-manager/test/provider_google_test.js

Next is a WIP I have going for a `removeAllWorkers` endpoint. That will work slightly differently.

Add terminate endpoint for google provider

---

changelog/1486.md
changelog/1495.md
ui/docs/reference/core/worker-manager/google.mdx

add changelog entries for next release

---

changelog/bug1586102.md
services/auth/src/static-scopes.json
services/github/scopes.yml
services/github/src/tc-yaml.js
services/github/test/intree_test.js
services/github/test/tc-yaml_test.js

Bugzilla Bug: [1586102](https://bugzilla.mozilla.org/show_bug.cgi?id=1586102)

Bug 1586102: provide necessary scopes directly from tc-github

---

ui/src/components/RoleForm/index.jsx

Resolves https://github.com/taskcluster/taskcluster/issues/1417.

[UI] Add helper text to scopes text field #1417

---

services/worker-manager/src/providers/google.js
services/worker-manager/test/provider_google_test.js

Each of the commits here is mostly self-explanatory. I believe after this lands we have fixed pretty much all "known" issues with the provider other than estimation being a bit wonky. That and `removeAll` will be my next steps. Testing this in dev now, will update this PR if something goes wrong.

[Bug 1586145] Fix a handful of google provider issues

---

services/auth/src/static-scopes.json
services/web-server/scopes.yml

Bugzilla Bug: [1586874](https://bugzilla.mozilla.org/show_bug.cgi?id=1586874)

Bug 1586874 - add github role scopes to web-server

---

ui/src/views/Profile/index.jsx

[BUG 1586874][UI] Profile shows n/a for scopes #1518

---

services/auth/src/static-scopes.json
services/hooks/scopes.yml

Use the correct table name for the hooks service

---

ui/src/components/SpeedDialAction/index.jsx
ui/src/components/TaskDetailsCard/index.jsx
ui/src/components/TaskRunsCard/index.jsx

Deleted <CopyToClipboard> components from 2 files
These good first issues really help me understand how to navigate in code!)
Closes #1395

[UI] Remove copy icon button from Task view

---

ui/src/components/ClientsTable/index.jsx
ui/src/components/RolesTable/index.jsx

Replace Link component with TableCellItem, remove hover effect from listItemCell classes
Now it works as expected
Closes #1448

[UI] Add hover effect to the link icon in /auth/clients and /auth/roles

---

ui/src/views/Documentation/Reference/Entry.jsx

[UI] Expand panel in Schema Index

---

ui/src/components/WMWorkerPoolEditor/index.jsx

Resolves #1413.
**Before**
**After**

[UI] Improve layout of worker pool view

---

ui/src/components/TaskRunsCard/index.jsx

This PR fixes the issue #1545  , which shows a bunch of `Warning: validateDOMNesting(...): warnings.` in the console when navigating to the link [http://localhost:5080/tasks/MH_HRhwxRZ-3zk7AvF0_vQ](url).

[UI] Remove warnings in console

---

ui/src/components/ClientForm/index.jsx

- Update the TextField to can preview the markdown way, updated to MarkdownTextArea and putted on context
Issue: #1460
---
Result:
- before fix:
- after fix:

[UI] Add markdown of discription view

---

ui/src/views/Tasks/TaskGroup/index.jsx

Relates to https://github.com/taskcluster/taskcluster/issues/1588#issuecomment-541406538.

[UI] Prevent "Cannot read property statusCode of undefined"

---

ui/src/components/HookForm/index.jsx

Bugzilla Bug: 1436421
replace usage of json with yaml

[Bug 1436421] Edit hooks in YAML instead of JSON

---

changelog/bug1585102.md
services/github/src/handlers.js
services/github/test/handler_test.js

Bugzilla Bug: [1585102](https://bugzilla.mozilla.org/show_bug.cgi?id=1585102)
The GitHub service now posts a more useful comment to pull requests and commits when an InsufficientScopes error occurs.

Bug 1585102 - improve InsufficientScopes error from tc-github

---

services/github/src/handlers.js

I noticed these in https://github.com/djmitche/taskcluster/runs/255790865

Update links from tc-github to point to new UI paths

---

infrastructure/tooling/src/main.js
infrastructure/tooling/src/smoketest/checks/builtin.js
infrastructure/tooling/src/smoketest/checks/index.js
infrastructure/tooling/src/smoketest/checks/ping.js
infrastructure/tooling/src/smoketest/checks/purgeCache.js
infrastructure/tooling/src/smoketest/checks/secrets.js
infrastructure/tooling/src/smoketest/index.js

Bug 1588083 - improve smoketests

---

services/web-server/src/graphql/Tasks.graphql
services/web-server/src/resolvers/Tasks.js
ui/src/components/HookForm/index.jsx
ui/src/utils/prop-types.js

This PR closes [Issue](https://github.com/taskcluster/taskcluster/issues/1406) concerning the propType validation console error for `taskPriority` at `/hooks/garbage/abc456`
- Clone this repository 
- Git checkout to `katherine95:Issue-1406`
- Run `yarn` then `yarn start`
- Navigate to hook view  `/hooks/garbage/abc456` and check the console
- You should see that there is no propType validation error on the console

[UI]Fix taskPriority propType validation error

---

ui/src/views/Profile/index.jsx

I added the message which the user can see while logged out. Please let me know if we need any other additions to this.

[UI] Invite user to login in /profile when logged out #1581

---

ui/src/components/TaskDetailsCard/index.jsx
ui/src/components/TaskRunsCard/index.jsx

Left-padding for Task Card and Task Run change from triple to double
Bugzilla Bug: [1589](https://github.com/taskcluster/taskcluster/issues/1589)
Closes #1589.

[Bug 1589] [UI] Card title is indented

---

ui/src/views/Provisioners/ViewWorkers/index.jsx

This PR fixes the issue #1584.  The expected behavior is achieved by using browser's local storage and react component lifecycle.

Deep link filterby  dropdown in provisioners

---

services/web-server/src/login/strategies/github.js
services/web-server/src/login/strategies/mozilla-auth0.js
services/web-server/src/main.js

Bugzilla Bug: [https://bugzilla.mozilla.org/show_bug.cgi?id=1587974](https://bugzilla.mozilla.org/show_bug.cgi?id=1587974)
Can't seem to reproduce but I think this is a possible fix.

Bug 1587974  - Catch error when retrieving profile

---

services/web-server/src/main.js

Fixes https://github.com/taskcluster/taskcluster/issues/1573.

[UI] Fix subscription in task group view

---

generated/references.json
services/worker-manager/schemas/v1/config-aws.yml
services/worker-manager/src/providers/aws.js
services/worker-manager/test/fake-aws.js
services/worker-manager/test/helper.js
services/worker-manager/test/provider_aws_test.js

Bugzilla Bug: [1578900](https://bugzilla.mozilla.org/show_bug.cgi?id=1578900)
This PR doesn't attempt to incorporate the estimator changes, only distributing the instances over different configs.

aws provider - distribute instances over configs

---

generated/references.json
services/worker-manager/schemas/v1/config-aws.yml
services/worker-manager/schemas/v1/config-google.yml
services/worker-manager/src/providers/aws.js
services/worker-manager/test/provider_aws_test.js

This works in concert with taskcluster/taskcluster-worker-runner#51.
This was mostly me guessing so feel free to yell that we should do this differently!

[bug 1588625] Add workerConfig to aws provider as well

---

changelog/issue-1665.md
services/web-server/src/servers/createApp.js
services/web-server/test/server_test.js

Resolves https://github.com/taskcluster/taskcluster/issues/1665.

Configure CORS for TPL endpoints

---

changelog/bug-1578900.md
ui/docs/manual/deploying/workers.mdx

Add docs and changelog for bug 1578900

---

changelog/bug1589368.md
services/github/src/handlers.js
services/github/test/handler_test.js

I thought that the error HTTP responses included `details`.  They don't.
Bugzilla Bug: [1589368](https://bugzilla.mozilla.org/show_bug.cgi?id=1589368)

Bug 1589368 - fix tc-github error overriding

---

ui/src/components/TaskRunsCard/index.jsx

@helfi92  @djmitche 
Closes https://github.com/taskcluster/taskcluster/issues/1588.

[UI] Center text vertically

---

ui/src/components/ClientScopesTable/index.jsx
ui/src/components/RoleScopesTable/index.jsx

Hi @helfi92  I opened a new PR for #1403.
How do I fix the failing test?

add hover effect to client and role scopes tables

---

changelog/issue-1713.md
ui/src/components/ClientForm/index.jsx
ui/src/views/Clients/ViewClient/index.jsx

Resolves https://github.com/taskcluster/taskcluster/issues/1713.
Sample URL: http://localhost:5080/auth/clients/create?client_id=foo&callback_url=http%3A%2F%2Flocalhost%3A9500&expires=3%20days&scope%5B%5D=assume%3Abar&description=client%20for%20cli%20usage

Implement CLI login

---

ui/src/components/SecretForm/index.jsx

Replace "foo:bar" in the secret creation view with a placeholder

---

changelog/issue-1713-1.md
ui/src/views/Clients/ViewClient/index.jsx

https://github.com/taskcluster/taskcluster/pull/1714#discussion_r337318237
Relates to #1713.

[UI] Rename "whitelist" and remove duplicated logic

---

infrastructure/tooling/src/smoketest/checks/dependencies.js

Adds dependency smoketest for #1242

adds dependpendency smoketest

---

changelog/issue-1529.md
ui/src/App/Main.jsx
ui/src/App/index.jsx
ui/src/views/ThirdPartyLogin/index.jsx

Add redirect and logic isOneLoginStrategy
Is behavior is right?
Closes #1529

[UI] Redirect third-party to login strategy directly when only 1 strategy

---

services/worker-manager/test/fixtures/schemas/sample-aws-config.json
services/worker-manager/test/schema_validate_test.js

I copied over the framework we have in queue for testing schemas, and added a sample test case. (I don't want to add more before I check if this is correct in the first place)
Dustin, is this what you were planning to add?

Schema testing for worker manager

---

infrastructure/tooling/src/smoketest/checks/role.js

This PR is a follow up to #1662 which is to accomplish the following tasks. 
Could you please tell me if this is the right way to add parameterized role? and also what exactly is `continuationToken `because when I call `listRoles2`, every role is being listed. Is `continuationToken `something which I can filter out specific role?
@djmitche

Add parameterized role in smoketest

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/pull_request_template.md

Chore: Enhancing PR and Issue templates

---

services/worker-manager/src/providers/aws.js

One commit is a long-discovered bug, fixes [1591308](https://bugzilla.mozilla.org/show_bug.cgi?id=1591308). Tests are coming separately :( 
The first commit fixes a bug that I discovered yesterday while debugging something else.

Two small quick fixes aws provider

---

changelog/issue-1835.md
services/web-server/src/login/strategies/mozilla-auth0.js
services/web-server/src/servers/oauth2.js
services/web-server/test/third_party_test.js

[web-server] Fix expires parameter for whitelisted clients

---

changelog/Xj_izVKCQQ-2TN5z2vm0HA.md
clients/client-go/tchooks/types.go
generated/references.json
services/hooks/schemas/v1/create-hook-request.yml
services/hooks/schemas/v1/hook-definition.yml

(mostly testing to make sure I've put back the secrets that I deleted..)

Fix firing-hooks link

---

changelog/issue-1840.md
services/web-server/src/graphql/Tasks.graphql
services/web-server/src/resolvers/Tasks.js

Fix firing action tasks by removing options from task definition

---

README.md

Because we use checks, the badge doesn't display any data anyway.
Also, I want to test #1838 :)

remove badge from README

---

changelog/issue-1771.md
ui/src/components/ClientForm/index.jsx

Fixes #1771 
Fixed the save button by adding deleteOnExpiration in the variable which controls the save button.

[UI] Saving an existent client #1771

---

changelog/issue-1758.md
clients/client-shell/cmds/signin/signin.go
ui/src/components/ClientForm/index.jsx
ui/src/views/Clients/ViewClient/index.jsx

Rename CLI login client_id to name and add slugId to avoid resetting token

---

changelog/issue-1857.md
services/auth/src/signaturevalidator.js
services/auth/test/signaturevalidator_test.js

..for better display in UI, but still readable for humans.
Fixes #1857.

Format authorizedScopes errors in Markdown

---

changelog/eEGjs2g0T_K8xpob3yrI3g.md
services/worker-manager/src/providers/aws.js

https://sentry.prod.mozaws.net/operations/taskcluster-community/issues/6590313/

Return from removeWorker once an error has been reported

---

changelog/bug-1588083.md
generated/docs-table-of-contents.json
infrastructure/tooling/src/build/monoimage.js
infrastructure/tooling/src/smoketest/checks/builtin.js
infrastructure/tooling/src/smoketest/checks/dependencies.js
infrastructure/tooling/src/smoketest/checks/index.js
infrastructure/tooling/src/smoketest/checks/ping.js
infrastructure/tooling/src/smoketest/checks/purgeCache.js
infrastructure/tooling/src/smoketest/checks/role.js
infrastructure/tooling/src/smoketest/checks/secrets.js
ui/docs/manual/deploying/smoketests.mdx

Bug 1588083 - improve smoketests, run from docker image

---

changelog/issue-1879.md
ui/src/components/IndexedEntry/index.jsx

[UI] Allow user to copy artifact link from index browser

---

changelog/issue-1892.md
ui/src/views/Tasks/ViewTask/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/1892.

[UI] Add retrigger task action

---

services/worker-manager/src/providers/aws.js
services/worker-manager/src/providers/cloudapi.js
services/worker-manager/src/providers/google.js

Add providerId to cloudapi logging

---

.taskcluster.yml

https://github.com/taskcluster/taskcluster/pull/1897#pullrequestreview-311904012

Only test changes on the master branch, leaving everythign else to PRs

---

changelog/issue-1895.md
ui/src/views/Clients/ViewClient/currentScopes.graphql
ui/src/views/Clients/ViewClient/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/1895.

[UI] Use intersection of scopes when using the CLI login

---

changelog/issue-1875.md
ui/src/components/TaskActionForm/index.jsx
ui/src/views/Tasks/ViewTask/cancelTask.graphql
ui/src/views/Tasks/ViewTask/index.jsx

[UI] Add cancel task action for a task

---

changelog/bug-1595238.md
services/queue/src/claimresolver.js
services/queue/src/deadlineresolver.js
services/queue/src/dependencyresolver.js

Bugzilla Bug: [1595238](https://bugzilla.mozilla.org/show_bug.cgi?id=1595238)

Bug 1595238 - sleep between queue polls to reduce Azure load

---

changelog/issue-1951.md
ui/src/components/WorkerDetailsCard/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/1951.

[UI] Properly display the quarantine until date

---

changelog/bug-1595667.md
ui/src/views/ThirdPartyLogin/index.jsx

Bugzilla Bug: [1595667](https://bugzilla.mozilla.org/show_bug.cgi?id=1595667).

Bug 1595667 - Make TP _first_ login experience smooth

---

changelog/issue-1923.md
services/auth/src/static-scopes.json
services/web-server/scopes.yml
services/web-server/src/data/SessionStorage.js
services/web-server/src/login/AzureSessionStore.js
services/web-server/src/main.js
services/web-server/src/servers/createApp.js
services/web-server/src/utils/constants.js
services/web-server/test/helper.js
services/web-server/test/session_store_test.js

Fixes https://github.com/taskcluster/taskcluster/issues/1554.
https://github.com/expressjs/session#session-store-implementation

Add an azure session store for express-session

---

changelog/issue-1962.md
ui/src/components/ErrorPanel/index.jsx

[UI] Make error panel scrollable

---

changelog/bug-1595838.md
services/queue/src/artifacts.js

Bugzilla Bug: [1595838](https://bugzilla.mozilla.org/show_bug.cgi?id=1595838)

Bug 1595838 - report errors completing blob uploads with 400

---

changelog/bug-1596523.md
services/web-server/src/login/strategies/github.js
services/web-server/src/login/strategies/mozilla-auth0.js
services/web-server/src/servers/createApp.js

Bugzilla Bug: [1596523](https://bugzilla.mozilla.org/show_bug.cgi?id=1596523)

Bug 1596523 - TypeError in login strategy

---

ui/src/components/DialogAction/index.jsx
ui/src/components/TaskGroupTable/index.jsx

fix tables and error in DialogAction

---

changelog/issue-1972.md
ui/src/utils/constants.js

Fixes https://github.com/taskcluster/taskcluster/issues/1972.

[UI] Increase entries per page in /provisioners

---

changelog/bug-1596531.md
services/notify/test/helper.js

Bugzilla Bug: [1596531](https://bugzilla.mozilla.org/show_bug.cgi?id=1596531)
This was definitely my fault, being a bit over-zealous cleaning up SQS queues a few days ago.

Bug 1596531 - fix notify tests

---

changelog/issue-1988.md
ui/src/views/Tasks/ViewTask/index.jsx

Don't remove taskId within task defs

---

changelog/issue-1995.md
services/web-server/src/servers/createApp.js

Resolves https://github.com/taskcluster/taskcluster/issues/1995.

Rely on MemoryStore in local development

---

changelog/bug-1595734.md
ui/src/views/Tasks/CreateTask/index.jsx
ui/src/views/Tasks/TaskRedirect/index.jsx
ui/src/views/Tasks/routes.js

Bugzilla Bug: [1595734](https://bugzilla.mozilla.org/show_bug.cgi?id=1595734)
Future improvement: Notify the user somehow of all the minor changes that are being made to the payload.

[UI] Create interactive tasks

---

changelog/issue-2005.md
ui/src/components/DateDistance/index.jsx
ui/src/utils/isDateWithin.js
ui/test/isDateWithin_test.js

Fixes https://github.com/taskcluster/taskcluster/issues/2005.

[UI] Date distance precision

---

changelog/issue-1911.md
ui/src/components/Button/index.jsx
ui/src/components/DialogAction/index.jsx
ui/src/theme.js

Fixes https://github.com/taskcluster/taskcluster/issues/1911.

[UI] Add a default variant to our button component

---

changelog/issue-1822.md
ui/src/components/TaskDetailsCard/index.jsx
ui/src/components/TaskRunsCard/index.jsx

Fixes #1822 
Changed the text from `More..` and` Less..` to `See More` and `See Less`.
`
Also, added the plus and minus icons in front of the text.
**Before Changes applied:**
**After Changes applied:**

[UI] Change "More..." to "See More" and add icon #1822

---

changelog/bug-1579496.md
libraries/testing/src/with-entity.js

Bugzilla Bug: [1579496](https://bugzilla.mozilla.org/show_bug.cgi?id=1579496)

Bug 1579496 - actually skip azure tests

---

changelog/issue-1421.md
ui/src/views/Tasks/ViewTask/index.jsx

…eaks.
Github Bug/Issue: Fixes #1421

[UI] Remove horizontal divider from Task Group view

---

changelog/issue-1715.md
ui/src/utils/constants.js

Update initial workerPool config value

---

changelog/issue-1751.md
ui/src/components/TaskRunsCard/index.jsx

closes [issue #1751](https://github.com/taskcluster/taskcluster/issues/1751)
@helfi92  @djmitche 
please review :)

Align artifact name

---

changelog/issue-1747.md
ui/src/App/docsRoutes.jsx
ui/src/components/UserMenu/index.jsx

fix: solving user_menu discrepancies and making enhancements

---

changelog/issue-1398.md
ui/src/views/Scopes/ScopesetComparison/index.jsx
ui/src/views/Scopes/ScopesetExpander/index.jsx

"Compare Scopesets" and "Expand Scopesets" should have a linkable URL.
Fixes #1398.

Implementation of Shareable Links #1398

---

.taskcluster.yml
Dockerfile
changelog/bug-1596615.md
dev-docs/development-process.md
libraries/loader/test/loader_tests.js
libraries/monitor/test/monitor_test.js
netlify.toml
package.json
services/worker-manager/test/api_test.js
ui/package.json

Bugzilla Bug: [1596615](https://bugzilla.mozilla.org/show_bug.cgi?id=1596615)
Github Bug/Issue: Fixes #1596615

Switch engine in package.json and .taskcluster.yml

---

changelog/bug-1586839.md
services/github/src/main.js
services/github/test/github-auth.js

Bugzilla Bug: [1586839](https://bugzilla.mozilla.org/show_bug.cgi?id=1586839)

Fix deprecated API call

---

changelog/M1DVrA3uQgiwpgoFsrhFwg.md
ui/package.json
ui/src/components/WMWorkerPoolsTable/index.jsx
ui/src/views/Clients/ViewClients/index.jsx
ui/src/views/Roles/ViewRoles/Roles.jsx
ui/src/views/Secrets/ViewSecrets/index.jsx
ui/yarn.lock

Relates to https://github.com/taskcluster/taskcluster/pull/1812.

[UI] Escape regex when searching in views

---

changelog/issue-2019.md
ui/src/theme.js

Add styles to MenuItem in theme.js
Closes #2019

[UI] Change menu items color

---

changelog/issue-1455.md
ui/package.json
ui/yarn.lock

Fixes https://github.com/taskcluster/taskcluster/issues/1455.

Update react schema viewer

---

changelog/T2I0_RrvQVSI9Qbdy5vIPw.md
netlify.toml

Make netlify rootUrl point to firefox-ci deployment

---

changelog/CNzGClgMSBm-TBX9latUcA.md
infrastructure/tooling/src/smoketest/checks/createClient.js
infrastructure/tooling/src/smoketest/checks/role.js

Make smoketests clean up after themselves a bit better

---

changelog/bug-1596098.md
package.json
services/hooks/src/api.js
services/hooks/test/api_test.js
services/queue/src/api.js
services/queue/test/createtask_test.js
yarn.lock

Bugzilla Bug: [1596098](https://bugzilla.mozilla.org/show_bug.cgi?id=1596098)
(draft so that I can see if the bare azure-entities upgrade passes CI)

Bug 1596098 - return 400 when entities are too big

---

changelog/ReKMPn8-QoaxpCmB-tduhw.md
static.json

Cleanup work.
https://github.com/heroku/heroku-buildpack-static#canonical-host

Redirect tc-ui herokuapp

---

changelog/issue-1412.md
ui/src/views/Quickstart/index.jsx

Fixes #1412 
Hey @helfi92!
I made some changes. Let me know what I can do to make this even better and I'd be happy to look at it.
Before: 
After: Reduced Spacing around main heading:
Before:
After: Made the checkboxes flex to use space efficiently:
Before:
After: Reduced spacing in general between all list items:
Before: 
After:
Reduced Spacing.
Stopped using ListSubHeader.
Made checkboxes flex to consume space efficiently.
Thanks!

[UI] improved layout of quickstart view

---

changelog/issue-1953.md
ui/src/components/Dashboard/SidebarList.jsx

[UI] Rename Purge Cache to Purge Caches

---

changelog/O5TUt4jhTim3pm6nAV5Cbg.md
services/web-server/src/servers/createApp.js
services/web-server/test/server_test.js

Remove special-cases for taskcluster-ui.herokuapp.com

---

changelog/bug-1597331.md
services/worker-manager/src/providers/aws.js
services/worker-manager/src/providers/google.js
services/worker-manager/test/provider_aws_test.js
ui/docs/reference/core/worker-manager/aws.mdx
ui/docs/reference/core/worker-manager/google.mdx

Bugzilla Bug: [1597331](https://bugzilla.mozilla.org/show_bug.cgi?id=XXXXX)

Bug 1597331 - provide a workerPoolId tag/label on instances

---

changelog/issue-1900.md
ui/src/components/TaskRunsCard/index.jsx

[UI]: Including reasons card in above

---

changelog/bug-1598329.md
package.json
services/queue/src/api.js
services/queue/src/queueservice.js
services/queue/test/queueservice_test.js

Bugzilla Bug: [1598329](https://bugzilla.mozilla.org/show_bug.cgi?id=1598329)

Bug 1598329 - remove queue.pollTaskUrls

---

changelog/issue-1997.md
ui/package.json
ui/src/components/Log/index.jsx
ui/yarn.lock

Fixes #1903.
Fixes https://github.com/taskcluster/taskcluster/issues/1990.
Fixes https://github.com/taskcluster/taskcluster/issues/1997.

[UI] Fix log horizontal scroll

---

changelog/issue-1949.md
ui/src/components/TaskRunsCard/index.jsx

Provide a link to the build artifacts in taskcluster community web pages. 

---

changelog/bug-1511676.md
libraries/scopes/README.md

Thanks, @arshadkazmi42 
Bugzilla Bug: [1511676 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1511676 )

Fix link in scopes docs

---

changelog/bug-1598788.md
ui/docs/reference/core/worker-manager/worker-interaction.mdx

Bugzilla Bug: [1598788](https://bugzilla.mozilla.org/show_bug.cgi?id=1598788)

Add docs for where workerConfig is stuck by w-m

---

changelog/issue-1874.md
ui/package.json
ui/src/components/ClientForm/index.jsx
ui/src/components/HookForm/index.jsx
ui/src/components/Log/index.jsx
ui/src/components/RoleForm/index.jsx
ui/src/components/SecretForm/index.jsx
ui/src/components/SpeedDial/index.jsx
ui/src/components/SpeedDialAction/index.jsx
ui/src/components/WMWorkerPoolEditor/index.jsx
ui/src/theme.js
ui/src/views/Provisioners/ViewWorker/index.jsx
ui/src/views/Provisioners/ViewWorkers/index.jsx
ui/src/views/PulseMessages/index.jsx
ui/src/views/Tasks/CreateTask/index.jsx
ui/src/views/Tasks/TaskGroup/index.jsx
ui/src/views/Tasks/ViewTask/index.jsx
ui/yarn.lock

Fixes https://github.com/taskcluster/taskcluster/issues/1874.

[UI] Enhance the speed dial component

---

changelog/issue-2078.md
ui/src/views/Provisioners/ViewWorkers/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/2078.

[UI] Show quarantined workers by default

---

changelog/issue-677.md
generated/docs-search.json
infrastructure/tooling/src/generate/generators/docs-search.js

Resolves https://github.com/taskcluster/taskcluster/issues/677.

Index documentation files

---

changelog/issue-2073.md
ui/src/components/TaskRunsCard/index.jsx

[UI] Properly link to the worker view from the Task view

---

changelog/bug-1596417.md
ui/docs/manual/using/artifacts.mdx

Bugzilla Bug: [1596417](https://bugzilla.mozilla.org/show_bug.cgi?id=1596417)

Bug 1596417: Updated docs warning about potential XSS between artifacts

---

changelog/bug-1598643.md
ui/test/isDateWithin_test.js

Resolves https://bugzilla.mozilla.org/show_bug.cgi?id=1598643.

Bug 1598643 - Fix intermittent UI test failure

---

changelog/bug-1599299.md
services/worker-manager/src/providers/google.js

Bugzilla Bug: [1599299](https://bugzilla.mozilla.org/show_bug.cgi?id=1599299)

[bug 1599299] Fix google provider tags

---

changelog/FKo_85KtQ9GCPKXaUomVdw.md
services/worker-manager/src/api.js
services/worker-manager/test/api_test.js

This was actually covered before by tests but this one makes it a bit more explicit. This scared the heck of of me for a few minutes.

Add a test for cross-pool creds

---

changelog/ARsUQbP1TxGDghD6RGvq7Q.md
services/worker-manager/src/providers/google.js

Fix google labels again

---

changelog/bug-1599291.md
generated/references.json
services/worker-manager/src/estimator.js
services/worker-manager/src/monitor.js
services/worker-manager/src/providers/aws.js
services/worker-manager/src/providers/google.js
services/worker-manager/test/estimator_test.js

Bugzilla Bug: [1599291](https://bugzilla.mozilla.org/show_bug.cgi?id=1599291)

[bug 1599291] Monitoring for worker pools improvements

---

changelog/Nwx2NhGeT9K7OJV_QXgDrg.md
generated/docs-search.json
ui/docs/manual/deploying/README.mdx
ui/docs/manual/deploying/github.mdx
ui/docs/manual/deploying/login-strategies.mdx
ui/docs/reference/core/web-server/README.mdx

Update GitHub app docs

---

changelog/bug-1597922.md
ui/web-ui-nginx-site.conf

https://bugzilla.mozilla.org/show_bug.cgi?id=1597922

Bug 1597922  - Add CSP headers

---

changelog/bug-1599564.md
services/purge-cache/config.yml
services/purge-cache/src/api.js
services/purge-cache/src/main.js
services/purge-cache/test/helper.js
services/purge-cache/test/purgecache_test.js

Bugzilla Bug: [1599564](https://bugzilla.mozilla.org/show_bug.cgi?id=1599564)

Bug 1599564 - fix purge-cache caching to recover from Azure errors

---

changelog/issue-450.md
generated/docs-search.json
infrastructure/tooling/src/generate/generators/docs-search.js
package.json
ui/docs/manual/deploying/README.mdx
ui/docs/manual/deploying/github.mdx
ui/docs/manual/deploying/login-strategies.mdx
ui/docs/manual/using/integration/guidelines.mdx
ui/src/components/DocSearch/index.jsx
ui/src/views/Documentation/index.jsx
yarn.lock

[UI] Add search to docs

---

.github/ISSUE_TEMPLATE/bug_report.md
changelog/Typo-Error.md

Typo Error

---

changelog/issue-2076.md
ui/src/components/SpeedDial/index.jsx

Resolves https://github.com/taskcluster/taskcluster/issues/2076.

[UI] Remove onhover effect on speed dial

---

changelog/bug-1600127.md
ui/src/views/Secrets/ViewSecret/index.jsx

Bugzilla Bug: [1600127](https://bugzilla.mozilla.org/show_bug.cgi?id=1600127)

Bug 1600127 - Secret view multiple saves 

---

changelog/bug-1599550.md
services/auth/src/main.js
services/auth/src/sentry.js
services/auth/src/sentrymanager.js
services/auth/test/helper.js
services/auth/test/sentry_test.js

Bugzilla Bug: [1599550](https://bugzilla.mozilla.org/show_bug.cgi?id=1599550)

Bug 1599550 - do not require sentry creds to start auth

---

Dockerfile
infrastructure/tooling/src/build/monoimage.js

Bugzilla Bug: [1602464](https://bugzilla.mozilla.org/show_bug.cgi?id=1602464)

Bug 1602464 - fix 'yarn build' now that yarn version is upgraded

---

changelog/issue-217.md
ui/src/components/Dashboard/index.jsx
ui/src/views/Shell/index.jsx
ui/src/views/Tasks/InteractiveConnect/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/217.
Closes https://github.com/taskcluster/taskcluster/pull/2003/files.

[UI] Remove duplicate navigation bars

---

changelog/issue-2155.md
ui/src/components/TaskRunsCard/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/2155.

[UI] Stop showing a different run when clicking on artifact dropdown

---

changelog/UAvfv115RyiP7AWpg2sWkA.md
ui/src/views/Tasks/ViewTask/index.jsx

This was introduced after upgrading to material-ui v4. Issue was raised via slack.

[UI] Fix regression re: custom actions

---

changelog/Df3me_dPRWa8bJPrvRQfNQ.md
services/worker-manager/src/providers/testing.js
services/worker-manager/src/provisioner.js
services/worker-manager/test/provisioner_test.js
services/worker-manager/test/worker_scanner_test.js

Fix provisioning logic

---

changelog/dJzbtsDKTGmH9GcYaCGpuQ.md
ui/src/components/SpeedDial/index.jsx
ui/src/components/SpeedDialAction/index.jsx

* Revert speed dial hover behavior that was introduced in #2076
* Rewrite SpeedDial and SpeedDialActions as functions to make use of React hooks.

[UI] SpeedDial hover behavior

---

changelog/issue-2125.md
services/web-server/src/loaders/artifacts.js
services/web-server/src/loaders/auth.js
services/web-server/src/loaders/clients.js
services/web-server/src/loaders/github.js
services/web-server/src/loaders/hooks.js
services/web-server/src/loaders/provisioners.js
services/web-server/src/loaders/roles.js
services/web-server/src/loaders/scopes.js
services/web-server/src/loaders/secrets.js
services/web-server/src/loaders/taskStatuses.js
services/web-server/src/loaders/tasks.js
services/web-server/src/loaders/workerManager.js
services/web-server/src/loaders/workerTypes.js
services/web-server/src/loaders/workers.js

Github Bug/Issue: Fixes #2125
I wasn't sure if _everything_ in the `promise.all`'s should be wrapped with try catches, so I did just to be safe. Let me know what you think!

[web-server] Replace Promise.all in loaders with try/catch

---

infrastructure/tooling/src/build/monoimage.js
infrastructure/tooling/src/release/tasks.js
infrastructure/tooling/src/utils/command.js
infrastructure/tooling/src/utils/docker.js
infrastructure/tooling/src/utils/npm.js
infrastructure/tooling/src/utils/pypi.js

Bugzilla Bug: [1602985](https://bugzilla.mozilla.org/show_bug.cgi?id=1602985)

Bug 1602985 - better logging from yarn build / yarn release

---

changelog/issue-2166.md
services/web-server/src/graphql/Workers.graphql
services/web-server/src/resolvers/Tasks.js
services/web-server/src/resolvers/Workers.js
ui/src/components/WorkerTable/index.jsx
ui/src/views/Provisioners/ViewWorker/index.jsx
ui/src/views/Tasks/TaskGroup/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/2166.

[UI] Worker view - show tasks with no runs

---

changelog/bug-1603197.md
services/notify/src/irc.js

Bugzilla Bug: [1603197](https://bugzilla.mozilla.org/show_bug.cgi?id=1603197)

Bug 1603197 - improve irc service logging

---

changelog/bug-1537922.md
libraries/testing/README.md
libraries/testing/src/with-pulse.js
services/auth/src/api.js
services/auth/test/client_test.js

Bugzilla Bug: [1537922](https://bugzilla.mozilla.org/show_bug.cgi?id=1537922)
Write a test, find a bug!

Bug 1537922 - test and fix when publishing clientCreated fails

---

README.md
changelog/SXlhNT5cS2exFh0pixJb6A.md
ui/README.md
ui/src/components/CopyToClipboardListItem/README.md
ui/src/components/CopyToClipboardListItem/index.jsx
ui/src/components/TaskDetailsCard/index.jsx
ui/src/components/TaskRunsCard/index.jsx
ui/src/views/Clients/ViewClient/index.jsx

Relates to https://github.com/taskcluster/taskcluster/issues/2127.

[UI] Add CopyToClipboardListItem

---

changelog/VcSRXNgiRZCrJ2DiiBn5Hw.md
services/web-server/src/login/strategies/mozilla-auth0.js
services/web-server/src/servers/oauth2.js

Attempt to understand what's happening in https://bugzilla.mozilla.org/show_bug.cgi?id=1595749#c16.

[web-server] Add logging

---

changelog/bug-1598643.md
ui/src/components/DateDistance/index.jsx
ui/src/utils/isDateWithin.js
ui/test/isDateWithin_test.js

Bugzilla Bug: [1598643](https://bugzilla.mozilla.org/show_bug.cgi?id=1598643)

Bug 1598643 - Fix flaky tests

---

changelog/bug-1604175.md
clients/client-go/tcqueue/types.go
clients/client-go/tcqueueevents/types.go
generated/references.json
services/queue/schemas/constants.yml
services/queue/src/api.js

Bugzilla Bug: [1604175](https://bugzilla.mozilla.org/show_bug.cgi?id=1604175)

Bug 1604175 - allow task deadline to be 10 days in the future

---

changelog/bug-1588083.md
infrastructure/tooling/src/smoketest/checks/role.js

Bug 1588083 - fix bug to clean up after smoketests

---

changelog/bug-1605933.md
ui/package.json
ui/yarn.lock

Bugzilla Bug: [1605933](https://bugzilla.mozilla.org/show_bug.cgi?id=1605933)

[UI] log viewer update

---

ui/yarn.lock
yarn.lock

This is a followon to
https://github.com/taskcluster/taskcluster/pull/2221 where dependabot
didn't quite get the job done.

Actually upgrade handlebars

---

changelog/T17fV4o9TtmXrX2rCwF1Jg.md
infrastructure/tooling/src/generate/index.js

The list has gotten quite long!

Only show active 'yarn generate' tasks

---

.taskcluster.yml
changelog/bug-1598649-1.md
infrastructure/tooling/src/publish/index.js
infrastructure/tooling/src/publish/tasks.js

Bugzilla Bug: [1598649](https://bugzilla.mozilla.org/show_bug.cgi?id=1598649)

Bug 1598649 - run 'yarn release:publish' on tags

---

changelog/J8nE0srbRZCieCQ50eiApg.md
ui/src/components/HookLastFiredTable/index.jsx

Refactor HookLastFiredTable to use CopyToClipboardTableCell

---

changelog/Ju9A8VKGTxGKW2s6VpEEFQ.md
infrastructure/tooling/src/release/tasks.js
infrastructure/tooling/src/utils/git.js

Note that this will preclude doing releases from non-master branches.
We can tackle that issue when we decide to do so!

Check that the repo is up-to-date before releasing

---

changelog/issue-2232
changelog/issue-2232.md
ui/src/components/CopyToClipboardTableCell/index.jsx
ui/src/components/TableCellItem/index.jsx

Making Icon Size Consistent

---

changelog/VPp4Pls-RIuVqZuKQsycMg.md
ui/src/components/ClientForm/index.jsx
ui/src/components/HookForm/index.jsx
ui/src/components/RoleForm/index.jsx
ui/src/components/SecretForm/index.jsx
ui/src/components/WMWorkerPoolEditor/index.jsx

[UI] Enable form save button if logged out

---

changelog/LxaZwb2KSUeF8VU8gaB6EQ.md
ui/src/components/Dashboard/index.jsx
ui/src/views/Quickstart/index.jsx

TItle Formatting for https://firefox-ci-tc.services.mozilla.com/quickstart

Title Formatting

---

changelog/issue-2266.md
clients/client-go/README.md

Fix links in go client to not include vXX

---

changelog/issue-2269.md
ui/src/components/Log/index.jsx

Fixes https://github.com/taskcluster/taskcluster/issues/2269.

[UI] Log viewer autoscroll to correct location

---

changelog/bug1606874.md
services/github/src/handlers.js
services/github/test/handler_test.js
ui/docs/reference/integrations/github/taskcluster-yml-v1.mdx

Bugzilla Bug: [1606874](https://bugzilla.mozilla.org/show_bug.cgi?id=1606874)

Check the head user when checking collaborators in PR

---

changelog/eIfoP84zQomrdYn8SIg1wA.md
ui/src/components/MarkdownTextArea/index.jsx

Remove error in console

---

changelog/YGLWJC2DQgGFmtnMLNYapQ.md
ui/docs/manual/deploying/workers.mdx

Add public ip write to recommended azure permissions

---

changelog/bug-1588083.md
infrastructure/tooling/src/smoketest/checks/builtin.js
infrastructure/tooling/src/smoketest/checks/dependencies.js
infrastructure/tooling/src/smoketest/checks/indexTask.js

Small change per @tomprince's request in https://phabricator.services.mozilla.com/D58272#inline-366030

Bug 1588083 - use scheduler-id:smoketest for smoketests

---

changelog/bug-1611694.md
services/web-server/src/login/scanner.js

Bugzilla Bug: [1611694](https://bugzilla.mozilla.org/show_bug.cgi?id=1611694)

Bug 1611694 - tolerate 404's when disabling workers

---

changelog/issue-1963.md
clients/client-shell/cmds/version/version.go
clients/client-shell/cmds/version/version_test.go

Github Bug/Issue: Fixes #1963 
Based on work by @DantrazTrev, I was unable to update that PR as I'm not a maintainer here so I've submitted this variant. Feel free to adapt/copy back into the original PR if desired.

Client shell update

---

changelog/pr-2293.md
clients/client-py/README.md
clients/client-py/taskcluster/helper.py

Refs https://github.com/mozilla/code-review/issues/439 & https://github.com/mozilla/code-coverage/issues/388
This is a small helper function to upload new artifacts in one call.

Add Python helper function to upload artifacts

---

changelog/bug-1588099.md
infrastructure/tooling/src/smoketest/index.js
libraries/api/src/middleware/auth.js
libraries/scopes/src/index.js
libraries/scopes/test/simplify_test.js

Thanks to @ajinkabeer for getting started on this!
Bugzilla Bug: [1588099](https://bugzilla.mozilla.org/show_bug.cgi?id=1588099)

Bug 1588099 - simplify scope expressions

---

changelog/bug-1537922.md
services/auth/test/client_test.js
services/auth/test/role_test.js
services/hooks/src/api.js
services/hooks/test/api_test.js
services/notify/test/api_test.js
services/worker-manager/test/api_test.js

Bugzilla Bug: [1537922](https://bugzilla.mozilla.org/show_bug.cgi?id=1537922)

Bug 1537922 - add checks for pulse failures to more services, fix hooks

---

.taskcluster.yml
Dockerfile
changelog/bug-1613150.md
dev-docs/development-process.md
netlify.toml
package.json
ui/package.json

Bugzilla Bug: [1613150](https://bugzilla.mozilla.org/show_bug.cgi?id=1613150)

Bug 1613150 - Upgrade to node 12.15.0

---

changelog/bfLNAgLtTg66gJjSUIDUgg.md
services/web-server/src/login/strategies/test.js
services/web-server/test/login_scanner_test.js

This has been sitting in my "bored on a plane" list for a while :)

Remove unused userFromClientId from login strategies

---

changelog/bug-1611266.md
package.json
services/worker-manager/src/providers/azure.js
yarn.lock

Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1611266

Bug 1611266 - azure-provider must ensure adminPassword meets requirements
